### PR TITLE
DBZ-7425 Use adapter-specific offset loaders when copying offsets

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7425

### CODE REVIEW

**Review by jpechane — APPROVED** [review]
@Naros LGTM, thanks. Please feel free to merge yourself if the test failure is unrelated,

**Comment by Naros** [comment]
Test failure is unrelated, being fixed in PR #5202

**Comment by Naros** [comment]
Applied to main (=2.6) and branch 2.5.

**Pull request merged**
