### PR TITLE
DBZ-286 Connection keepAlive support

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @jpechane, it seems something is missing -- where is the code using the new option when establishing the connection?

**Comment by jpechane** [comment]
IMHO options that are prefixed with database. are automatically as URL properties when JDBC connection is created

**Comment by gunnarmorling** [comment]
Could you also file a PR for adding the new option to the docs? Thanks!

**Comment by gunnarmorling** [comment]
Awesome, thanks, @jpechane.

**Pull request merged**
