### PR TITLE
DBZ-3309 Revert to MySQL specific default snapshot fetch size

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3309

### CODE REVIEW

**Comment by jpechane** [comment]
Test failures unrelated

**Comment by gunnarmorling** [comment]
@jpechane, so this LGTM, and we could merge it as-is. Here's an idea though, after reading the [MySQL driver docs](https://dev.mysql.com/doc/connector-j/8.0/en/connector-j-reference-implementation-notes.html):

* We automatically set "useCursorFetch" to true when a snapshot fetch size other than the default of -1 is given (which is needed in that case)
* We actually keep the default fetch size of 2K and set "useCursorFetch" (unless the value has been set to -1 explicitly); I'd expect this to be more efficient than the row-by-row retrieval, and it seems what some folks in the community do anyways; so this may be a nice improvement of the default behavior

WDYT?

**Comment by jpechane** [comment]
@gunnarmorling Then we are circling back to https://issues.redhat.com/browse/DBZ-3238

So you can crreate a Jira issue for that prposel that is blocked by DBZ-3238

**Comment by gunnarmorling** [comment]
Ok, makes sense. So let's explore the cursor fetch approach as part of DBZ-3238.

**Pull request merged**
