### PR TITLE
DBZ-3074 PgOutputMessageDecoder - Fix unordered keys

### PR DESCRIPTION
**Pull request by kppullin**
Fix issue where `PgOutputMessageDecoder` does not define primary key metadata in key-order.

`PgOutputMessageDecoder.getTablePrimaryKeyColumnNamesFromDatabase()` returns a `Set`, leading to unordered
primary keys in the metadata. Switch the logic to call `JdbcConnection.readPrimaryKeyNames()` which
_does_ correctly return an ordered primary key list.

### CODE REVIEW

**Review by gunnarmorling — COMMENTED** [review]
This change looks good, really weird that this didn't show up earlier (well, non-composite surrogate PKs FTW 😃 ). Could you only add a test which would have failed before this fix? If you e.g. take a PK with three or four columns, this should fail reliably enough with the earlier set-based approach.

**Comment by kppullin** [comment]
I added a test case, verified that it does fail with the prior code, and now passes with this fix.

**Comment by gunnarmorling** [comment]
Could you modify the message of the second commit so it begins with "DBZ-3074"? Thx!

**Review by gunnarmorling — APPROVED** [review]
LGTM, thanks a lot!

The remaining test failure is unrelated and tracked via https://issues.redhat.com/browse/DBZ-3083.

**Pull request merged**
