### PR TITLE
DBZ-2307 - Improve logging when primary keys are not defined

### PR DESCRIPTION
**Pull request by jhuiting**
See https://issues.redhat.com/browse/DBZ-2307 / https://gitter.im/debezium/user?at=5efdf769c3362026a90a6618.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, as you logged this, could you take a look? Thx!

**Comment by Naros** [comment]
Hi @jhuiting, I also think we should consider adding some blurb about this in the documentation.  As indicated in the description on the issue, we make reference to expected behavior for tables with primary keys, but we don't explain the expected outcome for tables that are key-less.  Could you add something about this as well?

**Comment by jhuiting** [comment]
@Naros Please check again, I've updated that part as well.

I also noticed in https://debezium.io/documentation/reference/1.2/connectors/postgresql.html that it mentions: `pgoutput plug-in does not emit all the events for tables without primary keys, it only emits inserts`. In my observation, this also applies for `wal2json`on PG 9.6 as `UPDATE` / `DELETE` statements are removed. This might be something can be removed from the documentation?

**Comment by jhuiting** [comment]
@Naros I'll open a different MR, Github didn't take the updating of my fork well 😬

**Pull request closed without merging**
