### PR TITLE
DBZ-5660 Run UI tests when dependenceis have changed

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-5660

@ani-sha can you take a look and see if this solves our UI test visibility concerns?

### CODE REVIEW

**Comment by ani-sha** [comment]
@Naros Apart from the compilation failure, rest changes should work for UI.

**Comment by Naros** [comment]
Thanks for the review @ani-sha, the compilation problem should be addressed by one of the existing PRs in the UI repository once that is merged.  If that's fine, I'll proceed with merging this to `main` on Wednesday so we can at least begin to see this play out with other PR contributions moving forward.

**Comment by rk3rn3r** [comment]
LGTM

**Comment by Naros** [comment]
Applied to `main`.

**Pull request merged**
