### PR TITLE
DBZ-2011 re-do: add examples of .yaml connector configurations

### PR DESCRIPTION
**Pull request by TovaCohen**
@Naros  -  This is a re-do of the PR that was merged. 
In this PR, please fill in the missing information in the .yaml configuration examples for the MongoDB, PostgreSQL, and SQL Server connectors. Those examples are missing the apiVersion specification in their first lines. They might also be missing other data. I used the MySQL .yaml config sample to create the .yaml examples for the other connectors.  I copied the .yaml config example for MySQL from the tutorial so that one should be complete and correct. 

For the AsciiDoc files that contain the connector information, when the .yaml configurations are complete, those files are ready to merge. 

In the r_mysql-connector-configuration-properties.adoc file, please review my update to the sentence that was broken. I was guessing. It be right or wrong now, but what was previously there did not make sense. 

The unnecessary commit so Antora would work is still present. Sorry, I don't know how to revert that. 

After updates are in place and this is merged, I would really appreciate it if you would backport it to 1.0 and 1.1. Thanks!

### CODE REVIEW

**Comment by TovaCohen** [comment]
@Naros Where do we stand with this? Are you waiting for me to do something? I've done more reading, and now I'm thinking that the .yaml file (the custom resource for Kafka Connect) for each Debezium connector should have the following at the beginning: 

```
apiVersion: kafka.strimzi.io/v1alpha1 
   kind: KafkaConnector 
   metadata: 
      name: inventory-connector 
      labels: strimzi.io/cluster: my-connect-cluster
```

Do you think that's right? If yes, I'll make those changes and add a commit to this PR.

**Comment by Naros** [comment]
Hi @TovaCohen, so I too did some reading about the yaml descriptors and overall most of this looks correct.  I will point out that I did find conflicting versions in the documentation for `apiVersion` which included `v1alpha1` and `v1beta1` so I'm not absolutely certain which it should be.  That said, the other aspects look fine.

**Comment by TovaCohen** [comment]
The new commit added to this PR inserts the missing .yaml parameters for the MongoDB, PostgreSQL, and SQL Server connectors. We still need to confirm that v1beta1 is the correct apiVersion, and I'll talk to someone about that on Tuesday. 

Also, in order to be able to build a book that uses this content downstream, I had to remove duplicate anchor IDs from the sqlserver.adoc file. To make the anchor IDs unique, I added "-sqlserver" to the anchor IDs. I searched for references to these IDs, and updated the references as well.

**Comment by TovaCohen** [comment]
@Naros This is now complete. 
We already use `apiVersion: v1beta1` in "Installing Debezium on OpenShift" and also in other Red Hat guides, for example for AMQ Streams. 

So I updated the `.yaml` examples with that specification. 
The conflicts in the three connector files are all because I edited the beginning lines of each connector's `.yaml` configuration example. So in all three cases, we want the content I just committed and not the content in master. I don't know how to actually resolve these conflicts. Can you do that?  I expect that I caused the conflicts because after you merged my first PR to master, I didn't update my clone master from upstream master. I'll do better in the future, promise!

And then can you backport these updates to 1.0 and 1.1?

Not having this content merged to 1.0 and 1.1 is blocking me now. Please let me know if there is anything I can do to speed this along.  Thanks Chris!

**Comment by Naros** [comment]
Hi @TovaCohen, yah the conflicts are most likely from the fact that part of the commits in this PR are indeed part of master.  I'll review the changes and take a look.  If all looks well I'll merge the net changes into master and we'll work to get 1.0 and 1.1 updated thereafter.

**Comment by Naros** [comment]
I went ahead and re-based and added 14f1970 and cc7b34b commits to master which were the delta commits from what had previously been merged.

**Comment by Naros** [comment]
The following backport PRs have been created:

Branch 1.1: https://github.com/debezium/debezium/pull/1474 
Branch 1.0: https://github.com/debezium/debezium/pull/1475

Thanks @TovaCohen, merged and closing.

**Comment by TovaCohen** [comment]
Happy dance!!!!!!!

**Pull request closed without merging**
