### PR TITLE
DBZ-7944 Exclude signal table from data snapshot

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7944

### CODE REVIEW

**Comment by Naros** [comment]
Errors are related to change - looking into a fix.

**Comment by mfvitale** [comment]
@Naros Is this feasible? How we can produce the event without knowing the schema?

**Comment by Naros** [comment]
> @Naros Is this feasible? How we can produce the event without knowing the schema?

I'm only excluding it from the data part of the snapshot, it will still have its schema captured.

**Review by jpechane — CHANGES_REQUESTED** [review]
@Naros I am fine with this PR for removing signalling tbale from snapshots. But in relation to supplemental logging check I disagree. We are currently testing with ALL supplemental check enabled. Either the test needs to be updated or the initial check needs to stay in place.

**Comment by jpechane** [comment]
@Naros Applied, thanks

**Pull request merged**
