### PR TITLE
DBZ-1035 Support PostgreSQL lock-free snapshot using exported snapshots

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1035

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Comment by gunnarmorling** [comment]
Hey @addisonj, thought this PR for leveraging exported snapshots in PG might be interesting to you :) Any chance you give it a try by building master and running it in your env? Thanks!

**Comment by addisonj** [comment]
sorry, was a bit slow on this, mostly been out this week, but  all look sane to me!

**Comment by addisonj** [comment]
oh one bit of feedback, it seems like there might be room for some more code sharing in the Snapshotter, but nothing too critical

**Pull request merged**
