### PR TITLE
DBZ-2212 Fix Debezium Server download link

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2212

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thinking about it, does it actually make sense to have the "distro" part in the name? It seems a bit redundant; wdyt about adjusting the actual name instead and reverting this change here?

**Comment by jpechane** [comment]
It is not only name but path too

**Comment by gunnarmorling** [comment]
Yes, but should we actually rename _that_?

**Comment by gunnarmorling** [comment]
I.e. the current _debezium-server_ to _debezium-server-parent_ and then distro -> _debezium-server_. E.g. there's also no "distro" part in WildFly's distribution artifact name.

**Comment by jpechane** [comment]
Well in fact we need to apply this PR to master and 1.2 branch to fix current docs.
Then I can prepare another PR that will update the links and `server-distribution.xml` to not use artifactId in the name. This would be applied after this one.
So the 1.2 branch will get correct link and new name will be available fro CR2

**Comment by gunnarmorling** [comment]
> Well in fact we need to apply this PR to master and 1.2 branch to fix current docs.

Done and done.

> Then I can prepare another PR that will update the links and server-distribution.xml to not use artifactId in the name. This would be applied after this one.

Deal!

**Pull request merged**
