### PR TITLE
DBZ-1383 Fix PostgreSQL tests that fail intermittently

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1383

This is a first pass at addressing test stability for the PostgreSQL connector.  There are further changes I'm looking into but this at least addresses a few of the known tests so far that fail randomly.

### CODE REVIEW

**Comment by Naros** [comment]
Hi @jpechane @gunnarmorling 

So one problem I've started to see consistently on Travis related to [DBZ-862][1], this seems to pop up randomly but has happened on both commits I've pushed thus far.  The first commit it happened using the decoderbufs plugin, the second with the wal2json plugin.  The same test is the culprit:

https://github.com/debezium/debezium/blob/master/debezium-connector-postgres/src/test/java/io/debezium/connector/postgresql/OutboxEventRouterIT.java#L141

I need to see how I can reproduce this locally, any insight you guys have would be helpful.

**Comment by Naros** [comment]
So I believe I solved the problem I mentioned above in commit https://github.com/debezium/debezium/pull/1027/commits/05c8fa32241259fd7697560980442a62d3b707b9.

**Comment by jpechane** [comment]
@Naros Great job! I tried to execute the tests 5*3 times in a row in Travis and not a single failure!

**Comment by gunnarmorling** [comment]
Woot -- great news! Thanks a lot, Chris!

>

**Pull request merged**
