### PR TITLE
DBZ-8095 Bump Quarkus to 3.8.5 & Apicurio to 2.5.8.Final

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-8095

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Do you want to wait for https://github.com/debezium/debezium/pull/5720 ?

**Comment by Naros** [comment]
That's fine by me @jpechane :heavy_check_mark:

**Comment by jpechane** [comment]
Let's merge this PR after https://github.com/debezium/debezium/pull/5724 to check the compatibility.

Also please provide a PR into container repo with connect-base image updae of apicurio. Also apicurio version in antora config file needs to be updated.

Please feel free to merge the PR (and the one on server) when CI is re-executed against 3.8.0

**Comment by jpechane** [comment]
@Naros Could you please rebase the PR on the latest main? Thanks

**Comment by jpechane** [comment]
@Naros Applied, thanks

**Pull request merged**
