### PR TITLE
DBZ-4318 Modified default type of aggregateid In outbox collection

### PR DESCRIPTION
**Pull request by sgc109**
https://issues.redhat.com/browse/DBZ-4318

---

Modified default type of aggregateid In outbox collection expected by MongoDB Outbox Event Router for both tests and documentation.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Applied, thx!

**Comment by gunnarmorling** [comment]
Hey @hpgrahsl, this might be interesting for you: we do now also have an outbox routing SMT for the MongoDB connector, it is described in the docs [here](https://debezium.io/documentation/reference/nightly/transformations/mongodb-outbox-event-router.html).

It is functionally very similar to the outbox router we already had for relational connectors, in particular it relies on transactions in the source DB to write to "business" collections and outbox collection consistently.

As a follow-up, we also may support for an outbox flavour, where the outbox message is taken from a specific sub-document of a business document, avoiding the need for cross-collection transactions.

**Comment by sgc109** [comment]
@gunnarmorling Actually, I've opened an issue for a follow-up.

https://issues.redhat.com/browse/DBZ-4319

**Comment by hpgrahsl** [comment]
Very nice stuff! THX for bringing it to my attention @gunnarmorling.

**Pull request merged**
