### PR TITLE
DBZ-3320 Build debezium website upon documentation changes

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-3320

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha Can't we justtrigger the build on the doctumentation repo instead doind the build here?

**Comment by ani-sha** [comment]
@jpechane Documentation repo? Does a separate repo deals with docs, I wasn't aware of it.

**Comment by jpechane** [comment]
https://github.com/debezium/debezium.github.io/actions/workflows/gh-pages-deployment.yml
https://github.com/debezium/debezium.github.io/blob/develop/.github/workflows/gh-pages-deployment.yml

**Comment by ani-sha** [comment]
@jpechane Ok, we just trigger the same workflow for any changes here rather than re-building again.

**Comment by jpechane** [comment]
@ani-sha LGTM, thanks. We will test it when the situation happens

**Pull request merged**
