### PR TITLE
DBZ-5973 Support for more types as key in mongodb incremental snapshot implementation

### PR DESCRIPTION
**Pull request by jcechace**
https://issues.redhat.com/browse/DBZ-5973

### CODE REVIEW

**Comment by jcechace** [comment]
Test failures are cause by DECIMAL128 deserialisation... Same as with ObjectId, I need to figure out how to deserialise these

**Comment by jcechace** [comment]
@jpechane  Provided tests pass this can be merged. ObjectId now works as well as Decimal128. Date Time is failing as it seams to lead to empty records -- I wonder if that is because the value of DateTime is in fact a long.... Thus for now I would stick with supporting numeric types and ObjectId.

**Comment by jpechane** [comment]
@jcechace Applied, good job!

**Comment by xinbinhuang** [comment]
@jpechane @jcechace thx for the great work! curious on if it's possible to support string?

**Comment by jpechane** [comment]
@xinbinhuang Thanks for spotting!

@jcechace I completely overlookd - we talked abot string and dates too.

**Comment by jcechace** [comment]
@jpechane  @xinbinhuang  as mentioned in the initial assessment. The keys do need a stable sorting. Strings are problematic as encodings and special characters can lead to unexpected behaviour.  

@jpechane Regarding Date, I think I mentioned this to you... I was unable to make this one work (tests were failing with "Too many empty events"). Internally in BSON this type is implemented as a wrapper around Long (number of seconds from start of the epoch) and getting the value from the BSON type returns this long value. I suspect there were some problems when deserialising the value -- as it was simply interpreted as Long not a Date. I have a note here to create a follow up Jira, however I think that in this case we will have to change the current behaviour so that not only the key itself but also the type is returned by `keyFromRow`

**Comment by xinbinhuang** [comment]
> re: string

@jcechace What would be the potential consequence of these unexpected behavior e.g. data loss? My feeling is that these unexpected behaviours are rare, and certain less critical workload can probably tolerate this type of unexpected behaviour. 

How do you think about allowing `STRING` but call out the limitation in the doc so user can use it with their own risk? Or create a config flag to enforce this contract?

**Comment by jpechane** [comment]
@jcechace Could you please create the follow-up Jira for Date and another for String?

I think it is fine to add support for String as well just with large warning and the link you referred too. IMHO it sounds to me like the guys are hedging against a potential issue - not that there is a real issue.

**Pull request merged**
