### PR TITLE
DBZ-5595 Comment on materialized DDL statement couldn't be parsed

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-5595

### CODE REVIEW

**Comment by harveyyue** [comment]
Upstream pr: https://github.com/antlr/grammars-v4/pull/2806

**Review by Naros — APPROVED** [review]
LGTM @harveyyue, I'll merge this once @jpechane gives us the okay that `main` is open.

**Comment by harveyyue** [comment]
> LGTM @harveyyue, I'll merge this once @jpechane gives us the okay that `main` is open.

Get😀

**Comment by jpechane** [comment]
@harveyyue Applied, thanks!

**Pull request merged**
