### PR TITLE
DBZ-2220 Fix test failure - SqlServerConnectorIT#verifyOffsets

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-2220

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Great catch, I see clearly now where the problem lies. But instead of delaying snapshot would not it be better either to execute the pre-snapshot inserts in a single transaction or instead of waiting fro max lsn wait for the insert of record with `id == 10` to be present in change table by qurying it directly? I think the former should be just enough.

**Comment by Naros** [comment]
@jpechane I tried wrapping the pre-inserts in a transaction but that still wasn't stable; I still hit a race condition where the snapshot began prematurely.  Ideally I think we should wait until we can guarantee that the max lsn is what we expect from all the pre-snapshot inserts; however I'm not clear how to do that.  Do we have an example of this where I can would know that's occurred before I spin up the connector?

**Comment by Naros** [comment]
I reworked the solution to use Awaitility in conjunction with testing the capture tables to verify that the pre-snapshot inserts had been replicated by SQL Server prior to spinning up the connector.  This should solve the issue without any future timing concerns outside of the obvious where SQL Server fails to propagate within 30 seconds.

**Comment by jpechane** [comment]
@Naros Very nice, thanks!

**Pull request merged**
