### PR TITLE
DBZ-3765 Allow dot in database.server.name

### PR DESCRIPTION
**Pull request by pkgonan**
Hi.
Please See this.

1. [Issue](https://issues.redhat.com/browse/DBZ-3765)
2. [related Issue 1](https://github.com/debezium/debezium/pull/2331)
3. [related Issue 2](https://github.com/debezium/debezium/pull/2418)

### CODE REVIEW

**Comment by Naros** [comment]
Hi @pkgonan, would you be willing to add an integration test for each of the other connectors as well to verify that this works with other connectors, similar to the integration tests in the MySQL connector?

**Comment by pkgonan** [comment]
Hi @Naros.
I have no experience with any database other than mysql, so I'm having a hard time writing tests.

When performing mvn clean verify, the integration test is not performed normally due to a docker problem. Do I have to manually create a database account for each database, grant privileges, and connect multiple databases to replication in a local environment for binlog? I was wondering if there is an easy way to test it using docker to perform integration tests locally.

**Comment by Naros** [comment]
For all connectors besides Oracle, you can simply follow these steps below to spin up a database docker instance that you can use when running the tests from within the IDE to verify if they work

```
cd debezium-connector-<specific-connector>
mvn docker:build
mvn docker:run
```

For Oracle, testing is quite a bit more involved and requires a Vagrant box, see https://github.com/debezium/oracle-vagrant-box.  If you're able to provide tests for all but Oracle, I can amend the PR with one specifically for Oracle.  Thanks!

**Comment by pkgonan** [comment]
@Naros 
Thank you. I'll check with your advice.

**Comment by jpechane** [comment]
@pkgonan Hi, will you have any capacity for the integration tests as asked by @Naros ?

Thanks a lot

J.

**Comment by pkgonan** [comment]
@jpechane Hi.
I can't afford to do that right now. 
If it is urgent to solve the current issue, it would be good for someone else to proceed with the work.

**Comment by Naros** [comment]
I'll take a look and add the tests now that I have a few free cycles.

**Comment by gunnarmorling** [comment]
Hey all, I don't think we need integration tests for this, let alone for all the connectors. Expanding `io.debezium.config.ConfigurationTest.testServerNameValidation()`, so to test that a name containing the "." is ok, should be enough. @Naros, I take it you're going to wrap up this one?

@pkgonan, one question for you only: could you rework your commit using an e-mail address linked to your GH account and force-push this PR's branch; there shouldn't be an "octocat" commit in the end. Thx!

**Comment by pkgonan** [comment]
@gunnarmorling Hi.
I changed email address & username on commit. Please check this out.

**Comment by gunnarmorling** [comment]
Thanks a lot, @pkgonan!

**Comment by pkgonan** [comment]
@jpechane @Naros @gunnarmorling 
Hi. If there is no problem, please merge this PR. Thanks :)

**Pull request merged**
