### PR TITLE
DBZ-2497 Add variable to metrics anchor IDs so IDs are unique in each connetor's doc

### PR DESCRIPTION
**Pull request by TovaCohen**
[DBZ-2497](https://issues.redhat.com/browse/DBZ-2497) is for resolving the duplicate ID problem that exists downstream. We cannot re-use content from the master branch and build the downstream user guide until this is resolved. 

In the shared reference files that have the metrics tables, I added "_{context}" to the anchor ID for each table entry. 
In the doc for each connector, I specified a different value for the :context: attribute. 

I also made the MySQL binlog custom metrics clickable. I did not add the {context} variable to those anchor IDs since they are in only the MySQL doc.

### CODE REVIEW

**Comment by jpechane** [comment]
@TovaCohen I see for all the links the same suffix - `_debezium` - regardelss of connector, for example
http://localhost:4242/documentation/reference/connectors/mongodb.html#connectors-snaps-metric-remainingtablecount_debezium
http://localhost:4242/documentation/reference/connectors/mongodb.html#connectors-snaps-metric-remainingtablecount_debezium

Is it intentional?

**Comment by TovaCohen** [comment]
@jpechane No.
Is 
`:context: debezium`
Defined somewhere in a playbook file for building the doc?  If yes, that needs to be removed.

**Comment by jpechane** [comment]
@TovaCohen See https://github.com/debezium/debezium.github.io/blob/develop/playbook.yml#L39

**Comment by TovaCohen** [comment]
@jpechane  Yes, That line needs to be removed. Can you do that?  Let me know if I need to do something.

**Comment by jpechane** [comment]
@Naros Do you know for what the antora attribute `{context}` is used? Is it safe to be removed or the attribute used in naming of metrci has to be renamed?

**Comment by TovaCohen** [comment]
@jpechane @Naros 
The {context} attribute is a standard, downstream attribute that is being used to ensure that each documentation module is unique. Whoever split the original mysql.adoc, monitoring.adoc and logging.adoc files introduced the {context} attribute. I removed the specification of `context: debezium` in my local playbook.yml file and Antora generated the doc with no errors or warnings. I expect that you can safely remove it. Can you test that?  While we could use a differently named attribute to serve the same purpose in distinguishing the metric table entries, it would be better to use {context} because anyone working on downstream doc will immediately know what it is.

**Comment by jpechane** [comment]
@TovaCohen Thanks for the confirmation, it sounds logical. Still I'd wait for @Naros to explain - he is the author of the Debezium docs/antora and I want to make sure we've hev not oversighted anything.
When @Naros confirms this is unrelated I'll remove the attibute from upstream docs and merge this PR right away.

**Comment by Naros** [comment]
Hi @TovaCohen and @jpechane, so removing the `context` from the `playbook.yml` does generate a warning for us upstream with files based on master with this PR, so I'm trying to determine at the moment which file isn't substituting the `context` properly.  It could be a file we use only for upstream and that could be why.

But with that said, we cannot just remove variables from the playbook.  We have to keep in mind that older versions of the docs are built on the assumption that these values are supplied in the playbook as defaults and by removing them we can cause warnings or worse navigation errors for older releases of the docs.

So ultimately the value in the `playbook.yml` needs to remain; however what I'm seeing upstream confirms what @jpechane saw is that some includes are being substituted correctly and others are not.  I'm going to look at upgrading Antora to see if that resolves the issue and if not I may need to consult with them on how to debug why the substitution seems broken.

**Comment by TovaCohen** [comment]
Sorry this is turning out to be not so simple @Naros and thanks for looking into it. 

@roldanbob  - without this update merged, we cannot fetch from upstream master and build the user guide downstream.

**Comment by Naros** [comment]
So it turns out for situations like this where we want to _allow_ override behavior of these values in things such as include files where variables may be defined in a parent context, the variable has to be defined as follows:
```
asciidoc:
  attributes:
    context@: 'debezium'
```
The introduction of the `@` symbol at the end of the variable declaration implies it can be overridden and thus whatever it is set to in the parent context (in our case the connector .adoc files) will be persisted to any include files within that context. I've opened the PR https://github.com/debezium/debezium.github.io/pull/504 to address this need and once that is merged,then the infrastructure is there for this PR.

**Comment by Naros** [comment]
Thanks @TovaCohen, this LGTM and I'm going to merge it.

**Comment by TovaCohen** [comment]
Thanks @Naros ! You're the best!!!!

**Pull request merged**
