### PR TITLE
DBZ-7275 Close connection registerd with bean registry

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-7275

### CODE REVIEW

**Comment by vjuranek** [comment]
In all Oracle tests there is only failure:
```
[INFO] 
[ERROR] Failures: 
[ERROR]   IncrementalSnapshotCaseSensitiveIT>AbstractIncrementalSnapshotTest.insertDeleteWatermarkingStrategy:973->AbstractSnapshotTest.consumeMixedWithIncrementalSnapshot:169->AbstractSnapshotTest.consumeMixedWithIncrementalSnapshot:173->AbstractSnapshotTest.consumeMixedWithIncrementalSnapshot:182->AbstractSnapshotTest.consumeMixedWithIncrementalSnapshot:192->AbstractSnapshotTest.consumeMixedWithIncrementalSnapshot:211 [Too many no data record results, 1000 < 2000] 
Expecting:
 <6>
to be less than or equal to:
 <5> 
[INFO] 
[ERROR] Tests run: 328, Failures: 1, Errors: 0, Skipped: 6
```
and this one should be fixed by PR #5114

**Comment by jpechane** [comment]
@vjuranek Applied, thanks!

**Pull request merged**
