### PR TITLE
DBZ-2224 Using Log4j 2 as logging backend during tests;

### PR DESCRIPTION
**Pull request by gunnarmorling**
By using the Log4j 1 to 2 bridge, this should be a drop-in replacement.
As this is a test-only dependency, we can upgrade it independently from the version used in Kafka itself.

https://issues.redhat.com/browse/DBZ-2224

Also see https://github.com/debezium/debezium-incubator/pull/178 in the incubator repo.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
So *of course* this is more complicated than I thought initially. I wasn't aware of our low-level log interception hack, but this should be sorted out now. There's one problem remaining, though, and this is configuration. I am still using the bridge from log4j to log4j2, for two reasons:

* all other code that uses log4j continues to work (in fact there might not be such code though, e.g. it Kafka Connect runtime and Kafka clients seem to be using the slf4j abstraction)
* our existing test logging configuration can be used as is; here's a problem though: this [requires opt-in](http://logging.apache.org/log4j/2.x/manual/compatibility.html) via a system property, which we'd have to set in Maven (ok) but also when running tests in the IDE (problematic). So it seems we actually will have to convert the configuration files into the log4j2 format

I'm not looking forward to the prospect of having to convert our log4j.properties files from the 1.x to 2.x format, but it seems kinda inevitable. Also Kafka itself still uses 1.x (there are plans to upgrade), this means for a while we'd have to "support" 1.x format files in examples and documentation.

@jpechane, @Naros, any thoughts/preferences around this?

**Comment by Naros** [comment]
Do we have any idea of the timebox around which we'd need to have this dual support?  

From our examples perspective, I don't think I have an issue with those lagging behind in migration or needing to support dual configurations for the short-term.  We already have situations where we have dual configurations for this sink or source setup within a single example, so this just builds on top of that imo.

From the documentation perspective, I believe this might come back full circle to a point I asked @TovaCohen to check on which was if we could leverage tabbed source code block rendering.  More specifically, we have sections in the docs where we have different configuration file formats, e.g. yaml and json.  We currently either elect to render one or the other based on the conditional formatting of up vs down -stream builds and others where we include both formats sequentially on the page.  

Personally I don't care for how we currently render these consecutive source blocks and would rather see them using this tabbed style format where the tab-name reflects the content type, e.g. Properties, YAML, JSON, Log4j1, Log4j2, ...

That said, I'm fine having both formats in the docs, I just think we probably should try and nail down if such a rendering plugin is permissible downstream and if not, at least we'd then know how we need to render such sections to be compatible downstream and perhaps take advantage of such rendering upstream at least.

**Comment by TovaCohen** [comment]
This is the issue I opened to find out if the customer portal can supported tabbed source output:
https://projects.engineering.redhat.com/browse/CCS-3632

I just added a comment asking if they can respond about this.

**Comment by jpechane** [comment]
https://issues.apache.org/jira/browse/KAFKA-9366 and https://github.com/apache/kafka/pull/7898

**Comment by gunnarmorling** [comment]
Ok, so after our discussion I'm going to close this one for the time being; let's revive this effort once Kafka itself has upgraded to Log4j2. Thanks all!

**Pull request closed without merging**
