### PR TITLE
DBZ-4517 Enable correct config opts for retrying

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4517

### CODE REVIEW

**Comment by jpechane** [comment]
This requires additional discussion - in fact it might make sense to keep the prefix and just fix the documentation.

We already have few options prefixed with `database.` that are not pass-through properties.

**Comment by Naros** [comment]
> We already have few options prefixed with database. that are not pass-through properties.

@jpechane @gunnarmorling I wonder if that's worth a review in terms of Debezium 2.0.  Should we have an explicit namespace that isn't tainted by other configurations that are explicitly for pass-thrus only?

**Comment by jpechane** [comment]
@Naros Yes, definitely good idea.

**Comment by Naros** [comment]
Great, I added it to the Debezium 2.0 issue, [DBZ-3899](https://issues.redhat.com/browse/DBZ-3899).

**Comment by gunnarmorling** [comment]
> This requires additional discussion - in fact it might make sense to keep the prefix and just fix the documentation.

So to make sure I get it right; before this change, the behavior is this:

* Docs say it's `slot.max.retries` and `slot.retry.delay.ms`
* To take affect, it must actually be `database.slot.max.retries` and `database.slot.retry.delay.ms`

If so, I prefer the proposed fix of making the code adhere to what's documented.

> We already have few options prefixed with database. that are not pass-through properties.

Yes, and I don't think that was a wise thing to do (and I believe it was more of an oversight rather than a conscious decision). I'd prefer to not further go down this route.

Given we have seen no complaints about the documented options not taking affect, I'd say this stuff is generally not used, and we're fine with just making the code adhere to what's documented.

**Comment by gunnarmorling** [comment]
> Should we have an explicit namespace that isn't tainted by other configurations that are explicitly for pass-thrus only, i.e. database.props.xxxx ?

Not a huge fan of this admittedly; A single prefix/namespace for pass-through is ok, but having sub-names with different semantics just makes it just more complicated to reason about. Let's rather move those non-passthrough which currently are under "database...." into separate namespace altogether for 2.0.

**Comment by jpechane** [comment]
@gunnarmorling ok, the code has beem undrafted.

**Review by gunnarmorling — COMMENTED** [review]
@jpechane, sorry, here's another set of minor comments. Had created those before but forgot to submit the review. Thx!

**Comment by jpechane** [comment]
@gunnarmorling Done

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
And applied; thx, @jpechane!

**Pull request merged**
