### PR TITLE
add `insert into rds_heartbeat2 …` in DDL filter

### PR DESCRIPTION
**Pull request by heisenbergye**
As debezium hard coded `mysql.rds_heartbeat2` in DDL filter, but RDS Mysql MariaDB add new sql  `insert into rds_heartbeat2 ……` these days, so it will be interrupted by this unrecongnized sql. Please help merge a new release to resolve it, thanks.

### CODE REVIEW

**Comment by jpechane** [comment]
@heisenbergye Thank you for the PR. There is already another solution https://github.com/debezium/debezium/pull/5109 - so I am closing this one in favour of it.

**Comment by heisenbergye** [comment]
@jpechane  okay, thank you

**Comment by Park-Seaweed** [comment]
I'm using mysqls version 5.7 right now, so the maximum debezium version I can upload is 1.9, but can the issue be the same?

**Comment by jpechane** [comment]
@Park-Seaweed Yes, you can see the same issue.

**Pull request closed without merging**
