### PR TITLE
DBZ-8181 Drop several deprecated Oracle configuration options

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-8181

### CODE REVIEW

**Review by jpechane — APPROVED** [review]
Can be merged when CI passes

**Comment by Naros** [comment]
Test `OracleSchemaMigrationIT.shouldParseSchemaChangeWithoutErrorOnFilteredTableWithRawDataType` failure is likely unrelated, but I want to double-check the failure with Oracle 21 XStream.  

The failure with Oracle 19 XStream as been addressed in PR #5814 

The Oracle 23 failures are unrelated, too and will be addressed separately.

**Comment by Naros** [comment]
I checked the test schema migration test, unrelated, so merging.

**Pull request merged**
