### PR TITLE
DBZ-7072 Retry Oracle Flashback-based snapshot queries

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7072

### CODE REVIEW

**Comment by Naros** [comment]
The test failures are unrelated.

**Comment by jpechane** [comment]
@Naros Could you please rebase it on the latest main? Thanks

**Comment by Naros** [comment]
@jpechane this is ready, the failure for XStream 19c is because we default to no retries on this failure.

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Pull request merged**
