### PR TITLE
DBZ-4649 Extend modify_table_partition rule

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-4649

### CODE REVIEW

**Comment by ani-sha** [comment]
Hi @Naros, when I started to look into the definition of `alter_table_partitioning` for fixing this issue, I see that some rules are missing and are not defined as it is in the [Oracle 19c documentation](https://docs.oracle.com/en/database/oracle/oracle-database/19/sqlrf/ALTER-TABLE.html#GUID-552E7373-BF93-477D-9DA3-B2C9386F2877). The way in which it is defined in the documentation is pretty easy to understand and locate. What is the reason for this difference? 
As this issue was about fixing the `modify_table_partition` clause I have done whatever was required.

**Comment by Naros** [comment]
Hi @ani-sha, I honestly have no good answer to your question.  I would say depending on your workload we can tackle this one of two ways.  The fix you've provided addresses the user's specific needs so we can go with what we have for now and add a follow-up task to flush this out later or we can take care of this now.  I leave that entirely up to you on which way you'd prefer to go.

**Comment by ani-sha** [comment]
Thanks, @Naros. It will surely take some time, so  I am going to sort it out in a follow-up task. Logged https://issues.redhat.com/browse/DBZ-4717 for the same.

**Comment by gunnarmorling** [comment]
+1, that's the general preferred way, as we're struggling with issues/PRs dragging on for a long time anyways. So always better to handle such additions as a follow-up.

So are we all set with this one then, @ani-sha?

**Comment by gunnarmorling** [comment]
If so, can you merge it yourself (it LGTM) and resolve the issue in Jira? Thx!

**Comment by ani-sha** [comment]
Applied to main(=1.9)

**Pull request merged**
