### PR TITLE
DBZ-3 Implements a Debezium Connector for ingesting Postgresql changes via logical decoding

### PR DESCRIPTION
**Pull request by hchiorean**
## Prerequisites
- PostgreSQL >= 9.4 configured to allow logical replication
- Debezium [postgres-decoderbufs plugin](https://github.com/debezium/postgres-decoderbufs) installed in the server

## Known issues and limitations
- no DDL support - this is a limitation of Postgres' logical decoding feature, which does not provide this information
- no automatic failover support - neither `warm` nor `hot` standby replicas support logical decoding slots. In other words, logical decoding can only be done from the `master` server. In case of a cluster failure, after a new `master` has been promoted, the connector has to be pointed to the new node and restarted
- current implementation has only been tested on `UX` OSes. When dealing with Windows, the plugin has to be(most likely) natively complied on Windows and installed in the Windows Postgres server

## Features and description
To be able to perform logical replication, the connector relies on a feature of the [Postgres JDBC Driver](https://github.com/pgjdbc/pgjdbc/pull/550) *that has not yet been released*. As such, the current PR *incorporates and uses a version of the JDBC driver that has this feature*. Once this is finally released, we'll want to update the connector and use the official driver.

Similar to the MySQL connector, this connector supports both taking snapshots and streaming incoming changes. With the exception of the DDL related parts, the PostgreSQL connector supports pretty much the same configuration options as the MySQL connector. It also generates events using the same structure and topics as the MySQL connector.

One significant difference from the MySQL connector is about how "multiple databases" are handled: in MySQL one can actually have different database instances and the MySQL connector reflects this for example when it comes to filters. In PostgreSQL however, the preferred way of doing this is *using different schemas* within the same server and physical database. As such, this connector reflects this distinction and updates some of the `debezium-core` classes to handle multiple schemas.

Also, since PostgreSQL has different custom datatypes than MySQL, this PR adds some more semantic types to Debezium which are used to represent this information: `io.debezium.data.geometry.Point`, `io.debezium.data.Xml` and `io.debezium.data.Uuid`

The testing and development for this connector has been done using [Debezium's PostgreSQL docker image](https://github.com/debezium/docker-images/tree/master/postgres/9.6) which is a vanilla Postgres 9.6 Debian installation with the previously mentioned plugin installed.

### CODE REVIEW

**Comment by hchiorean** [comment]
@rhauch : Travis fails atm before even getting to the Postgresql connector with:

`[ERROR] Failed to execute goal io.fabric8:docker-maven-plugin:0.18.1:start (start) on project debezium-connector-mysql: I/O Error: Unable to create container for [debezium/mysql-server-test-database]: Conflict. The name "/database" is already in use by container 23791d3d4a129b7054d44c4929f4b40c529ef7234f6fa11565f9d1f91622c421. You have to remove (or rename) that container to be able to reuse that name. (Conflict: 409) -> [Help 1]`

Not sure why that is.....

**Comment by rhauch** [comment]
Yes, that is the same error I was getting when I upgraded the Docker Maven plugin before changing the use of `docker.image` to `docker.filter`. The symptom is the build incorrectly starts all the defined Docker containers used in the assembly profile but without the different ports defined in the assembly configuration. Turns out we were misusing `docker.image` to control which image(s) should be started, which worked only because of a bug in the Maven plugin which was corrected recently.  The correct approach is to instead use `docker.filter` for the purpose we need, so #143 made this change in addition to the plugin upgrade. 

However, if you rebased with latest on `master` then I'm not sure why it fails on this brach but not on `master`.

**Comment by hchiorean** [comment]
yes, the PR is rebased on the latest `master` (i.e. post plugin update) and so the PG connector uses `docker.filter` instead of `docker.image`

**Comment by hchiorean** [comment]
@rhauch: I ran the build locally a number of times and it worked fine. Is there anything else which can be updated in this PR to try avoiding the Docker failure ?

Also, are the names of the containers started by the Maven plugin relevant ? If not, I suspect changing the `<namingStrategy>` to `none` might fix this particular problem. There is also a `<restartPolicy>` which might influence the behavior if a container already exists

**Comment by rhauch** [comment]
@hchiorean No, the names of the containers are not important to the tests, since they simply use the localhost and the correct port. I won't have time to check the semantics of those options until later this afternoon -- any chance you can summarize them or try them locally?

**Comment by hchiorean** [comment]
added an additional commit which updates the build system to only use `alias` naming when required. In other words, `alias` is naming is still used when docker containers reference other containers via `links` elements. In all other cases the Docker Maven plugin will use a random name for each container.

**Comment by hchiorean** [comment]
well...the current failure is `Error starting userland proxy: listen tcp 0.0.0.0:3306: bind: address already in use`

**Comment by rhauch** [comment]
@hchiorean right, which is strange. Actually, the build is first running

    mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V

before it (usually) runs another build with tests, but for some reason this first pass seems to be starting the container. We need to either change this initial run to exclude integration tests, or we should override Travis' default approach of running the build in two passes.

**Comment by rhauch** [comment]
@hchiorean I think I fixed the build issues. Do you want to rebase?

**Comment by hchiorean** [comment]
@rhauch: done

**Comment by hchiorean** [comment]
@rhauch: I've made similar change to the PG connector Maven docker config, but the latest build failure looks like
```
[ERROR] DOCKER> [debezium/mongo-initiator:3.2]: Timeout after 30008 ms while waiting on log out 'Replica set is ready'
[ERROR] DOCKER> Error occurred during container startup, shutting down...
```
at this point Travis is looking more like a hindrance to me....

**Comment by hchiorean** [comment]
amended the commit again, changing the default PG port to `4532` to see if this works (assuming it gets past the MongoDB hang)

**Comment by hchiorean** [comment]
nope, Mongo still fails...

**Comment by rhauch** [comment]
@hchiorean I'll try to fix that, but how about moving the PostgreSQL connector before the MongoDB connector. Be sure that the build is using a different non-standard port for PostgreSQL.

**Comment by hchiorean** [comment]
rebased on latest master and moved the PG connector module before the Mongo module

**Comment by rhauch** [comment]
@hchiorean, do you want to rebase this on `master` and adjust accordingly? I plan to release 0.3.6 on Dec 21, and it'd be great to release 0.4 before the holidays, too. But that'd mean we need documentation for the PostgreSQL connector. Feel free to create a PR on the [website repository](https://github.com/debezium/debezium.github.io) and update the [PostgreSQL Connector page](https://github.com/debezium/debezium.github.io/blob/develop/docs/connectors/postgresql.asciidoc).

BTW, the changes we talked about in our previous conversation (see #142 for details) were more difficult to get working, so I think it's better if we just plan on trying again to refactor the codebase at a later time (perhaps once we've stopped backporting changes to the `0.3.x` branch).

**Comment by hchiorean** [comment]
rebased on latest `master`. 

Added a new commit with a significant change: since the [Postgres JDBC driver](https://github.com/pgjdbc/pgjdbc) does `SNAPSHOT` releases, this commit removes all the local sources for the PG driver replacing them with a `42.0.0-SNAPSHOT` artifact that contains all the streaming changes.

Moving to a released version will be handled once that's available as part of https://issues.jboss.org/browse/DBZ-158

**Comment by hchiorean** [comment]
added a new commit with `README` and `NOTES` files for the postgres-connector module

**Comment by hchiorean** [comment]
rebased on latest `master` and fixed an issue around topic naming

**Pull request merged**
