### PR TITLE
DBZ-1480 Add read_committed snapshot isolation level

### PR DESCRIPTION
**Pull request by grzegorz8**
https://issues.jboss.org/browse/DBZ-1480

### CODE REVIEW

**Comment by grzegorz8** [comment]
How should I update docs now?

**Comment by jpechane** [comment]
Hi,

thanks for the PR! You can update docs directly in this PR by editing https://github.com/debezium/debezium/blob/master/documentation/modules/ROOT/pages/connectors/sqlserver.adoc

To test it locally check author mode from https://github.com/debezium/debezium.github.io/blob/develop/CONTRIBUTING.md#building-locally

**Comment by gunnarmorling** [comment]
LGTM apart from the missing doc update. Out of curiousity: is this something you're actually planning to use? Or more for the sake of completeness? It seems risky and I've a hard time imagining when one would want to use it. You might end up with stale data propagated to consumers.

**Comment by jpechane** [comment]
@gunnarmorling There was a request from another user for the feature - he cannot use stronger locking and at the same time is on managed SQL Server so cannot enable snapshot mode.

**Comment by gunnarmorling** [comment]
Ok, I'm not against adding it, as long as it's not the default (it isn't) and it would be nice to make clear the potential implications in terms of data consistency. Speaking of that: wouldn't this mean we'd see an event caused by a concurrent commit another time during streaming?

**Comment by grzegorz8** [comment]
To be honest it is not that bad. For instance, tools like sqoop use this isolation level.

Of course, data consistency is not provided as we would like to have in Debezium (snapshot and streaming cdc logs combined should constitute a consistent, linear history).

While using read committed isolation level, correct me if I am wrong, a record added/updated can be captured twice - once in the snapshot, once in the streaming phase. Or record deleted might not be captured in the snapshot, but there will be corresponding delete event in the streaming phase. But this seems to be fine in some cases, e.g. mirroring state in another database. There should be no data loss or data corruption.

**Comment by grzegorz8** [comment]
I believe we might want to restructure a bit the description of `snapshot.isolation.mode` property.
Instead of describing each mode separately, we might write a separate paragraph about each aspect: data consistency and locking.

For instance:
```
It is worth documenting that `snapshot`, `read_committed` and `read_uncommitted` modes do not prevent other
transactions from updating table rows during initial snapshot, while `exclusive` and `repeatable_read` do. +

Another aspect is data consistency. Only `exclusive` and `snapshot` mode guarantee full consistency, that is, initial
snapshot and streaming logs constitute a linear history. In case of `repeatable_read` and `read_committed` modes,
it might happen that, for instance, a record added appears twice - once in initial snapshot and once in streaming
phase. For `read_uncommitted` there are no data consistency guarantees at all (some data might be lost or corrupted).
```

**Comment by gunnarmorling** [comment]
@grzegorz8, I'm open for any improvements. I definitely like the gist you suggested above. Can you add it to the PR? In terms of visualizations, it's not strictly needed from my PoV, I think the text is good enough.

**Comment by gunnarmorling** [comment]
@grzegorz8, are you planning to push a commit with the doc update as per the discussion above?

**Comment by gunnarmorling** [comment]
Excellent, thanks a lot, @grzegorz8! Rebased and applied.

**Pull request merged**
