### PR TITLE
DBZ-3843: Add a transformer to unwrap the records with struct-wrapped fields

### PR DESCRIPTION
**Pull request by elakito**
I opened this issue and described the background in the issue ticket. I think adding a separate SMT is the most non-invasive and effective approach to solve this problem. Please have a look.
Thanks

https://issues.redhat.com/browse/DBZ-3843

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @bingqinzhou, do you know why the Cassandra connector generates the struct style in the first place? I believe there's a good reason, but I don't quite remember, unfortunately. Or, @jgao54, if you happen to read this, can you share some insights? Thanks a lot!

**Comment by gunnarmorling** [comment]
@elakito, could you rebase and force-push this one? We're struggling a bit with intermittent test failures atm. and I'm trying to get them sorted out:

* Vitess: should be fixed by now
* Postgres: should be fixed by now
* SQL Server: Still open, trracked via https://issues.redhat.com/browse/DBZ-2398
* Server: : should be fixed by now

**Comment by gunnarmorling** [comment]
Hey @elakito, could you rebase and force-push this PR? Most/all of those test failures above should be addressed by now. Thx!

**Comment by bingqinzhou** [comment]
> Hey @bingqinzhou, do you know why the Cassandra connector generates the struct style in the first place? I believe there's a good reason, but I don't quite remember, unfortunately. Or, @jgao54, if you happen to read this, can you share some insights? Thanks a lot!

From my understanding, the deletion_ts field is used for downstream processing to differentiate if column is just not included in an update operation or is actually deleted. I'm good with the change in this PR as long as it doesn't affect the current use case of Cassandra Connector.

**Comment by elakito** [comment]
yes. I'll rebase this PR.

**Comment by gunnarmorling** [comment]
Hey @elakito, coming back to this one, sorry for the long delay. So my main question/concern is: when using this SMT, how would a downstream consumer tell apart a column whose value wasn't modified from one which was set to null?

**Comment by elakito** [comment]
Hi @gunnarmorling, I had only insertion scenarios and didn't notice Cassandra-connector has a different behavior for the update or delete scenarios and Cassandra-connector is not using `before` and `after` to specify the changes as described in debezium's event structure documentation https://debezium.io/documentation/reference/transformations/event-flattening.html but only using `after` to describe the changes.

In that case, an SMT cannot be used to transform Cassandra-connecto'r records into debezium's current CDC envelope records using SMT. Is Cassandra-connector's record format also supported by other debezium components? Will this format be treated as a valid stable debezium CDC envelope (type 2) in the future? In that case, the downstream consumers can directly consume those records. Could you tell me whether Debezium team is planning to align these formats?

Thanks.
aki

**Comment by elakito** [comment]
Hi @gunnarmorling, have you had time to follow up on my question above? I now tend to think it is good to document the CDC envelope format that Cassandra-connector currently uses and name it a type-2 or something to differentiate from the standard CDC with before/after properties. 

These two formats are not compatible, as converting from the standard debezium CDC format to this type-2 format is possible with a stateless transformation, but converting in the other direction is not. But if the format is documented by Debeizum project, one can develop downstream applications to consume this type-2 format more directly and efficiently. Furthermore, for some data sources, it may be easier to generate this type-2 format and there will be some additional source connectors.  If we can go in this direction, we can close this PR and open an issue to follow up on documenting this type-2 format.

regards, aki

**Comment by gunnarmorling** [comment]
Hey @elakito, the format is already documented in the Cassandra connector docs (section [Events](https://debezium.io/documentation/reference/stable/connectors/cassandra.html#cassandra-events)). The Cassandra connector is the only one which uses this format, and I don't think it'd make too much sense to add support for it to the other connectors. So in that light, is there actually anything to be done here?

> These two formats are not compatible, as converting from the standard debezium CDC format to this type-2 format is possible with a stateless transformation, but converting in the other direction is not.

Thinking about it, you actually can convert from "type-2" to the standard Debezium format. Specifically, the Postgres connector already supports a [special marker value](https://debezium.io/documentation/reference/stable/connectors/postgresql.html#postgresql-property-toasted-value-placeholder) which will be emitted if the value of an unchanged column cannot be retrieved (a corner case for PG TOAST columns). So it should be possible to transform the type-2 format from Cassandra into the regular one, emitting the "__debezium_unavailable_value" value for all unchanged columns.

Would that help your case? If so, would you be willing to update this PR accordingly? I could see value in having such SMT provided by Debezium OOTB. WDYT?

**Comment by elakito** [comment]
@gunnarmorling Thank you for the documentation link to the type-2 format.

But regarding the transformation from type-2 to type-1 (the normal debezium's event format), I don't think it makes much sense. If we use some special marker to represent the missing values, we can only use such a marker for string or bytes based types but not for numeric types.

And if such transformation made sense, Cassandra-connector could have adopted it.
For datasource types like Cassandra, only the type-2 format makes sense and the downstream applications can be programmed to directly consume those type-2 records than to be programmed to consume the corresponding type-1 converted records that include the special markers. 

So, I think we can close this PR and also the issue linked from this PR.

**Comment by gunnarmorling** [comment]
Ok, going to close this PR then. Thanks a lot nevertheless for the good discussion, it also helped me to get clarity about some things. We are also exploring the idea to have a Debezium-specific JDBC sink connector (see [DBZ-3647](https://issues.redhat.com/browse/DBZ-3647)), in which case we may add support for the "type 2" format for a full end-to-end flow.

**Comment by elakito** [comment]
Thank you. It was a good discussion to understand the problem and find a good solution.

**Pull request closed without merging**
