### PR TITLE
DBZ-7489 Correctly parse XML preamble SQL ending with "IS NULL"

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7489

### CODE REVIEW

**Comment by Naros** [comment]
Test failures are all related to the Async Embedded Engine default timeouts.

**Review by jpechane — APPROVED** [review]
@Naros LGTM thanks! Let's wait wit merge till the management timeout issue in testsuite is solved.

**Comment by jpechane** [comment]
@Naros Applied, thanks! I think is safe to go ahead with it.

**Pull request merged**
