### PR TITLE
DBZ-3755 Fix parsing inline Oracle CREATE INDEX constraints

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3755

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM; could you resolve the merge conflict and merge yourself? Thanks, @Naros!

**Comment by gunnarmorling** [comment]
Gasp, so that "resolve merge conflicts" online creates a merge commit, bah. Sorry about that :(

**Comment by Naros** [comment]
No worries, I'll just rework the PR and resolve the conflicts from the master branch.

**Comment by gunnarmorling** [comment]
Thank you so much! I thought I could actually do everything online without
pulling it to my machine, but it seems you'll get a merge commit then :(

>

**Comment by Naros** [comment]
All good, PR fixed.

**Pull request merged**
