### PR TITLE
DBZ-789 Expose more granular snapshot metrics via JMX

### PR DESCRIPTION
**Pull request by pgoranss**
https://issues.jboss.org/browse/DBZ-789

Exposing new snapshot metric:
Map containing tableName -> Rows Scanned

### CODE REVIEW

**Comment by pgoranss** [comment]
@gunnarmorling Sure, I will add a PR for the docs!

**Comment by gunnarmorling** [comment]
Thanks, @pgoranss!

@jpechane I think there's no big risk associated to this change, so I'd vote for merging this now and releasing it as part of the Final, also if we are after CR1 at this point. WDYT?

**Comment by jpechane** [comment]
@gunnarmorling It looks pretty non-invasive so I think it can go in

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks a lot, @pgoranss!

**Pull request merged**
