### PR TITLE
Simple solution

### PR DESCRIPTION
**Pull request by MikkelHJuul**
may have sideeffects, I cannot compile/execute test. I tested in browser (tutorialspoint)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@MikkelHJuul, thanks! In order to move forward with this, can you please add an actual (integration) test obtaining the value from MySQL. There's many examples in the tests of the MySQL connector. Also the commit message needs updating, referencing the issue number. The fix itself seems reasonable to me.

**Comment by gunnarmorling** [comment]
@MikkelHJuul, any news on this one? Are you still planning to wrap this up? Thanks!

**Comment by MikkelHJuul** [comment]
> @MikkelHJuul, any news on this one? Are you still planning to wrap this up? Thanks!

@gunnarmorling I don't really have the time atm, and the Integration testing is a whole world of its own. I still haven't figured how to debug it, so I can create the proper structure of data and test it...

**Comment by gunnarmorling** [comment]
Ok, so I'm going to close this one for now, so to clean the slate a bit. Re integration testing, you could take a look at existing tests, it's not too involved really. You just need to have Docker installed, as the Maven build will run the databases using Docker. Also see CONTRIBUTING.md for the details. Drop by on the chat if you want to discuss anything. Thanks!

**Pull request closed without merging**
