### PR TITLE
DBZ-5455 Fixed debezium parse binlog default value bug in JdbcValueCo…

### PR DESCRIPTION
**Pull request by youyangkou**
issue link: https://issues.redhat.com/browse/DBZ-5455

### CODE REVIEW

**Comment by youyangkou** [comment]
@Naros yesterday，i see your comment on PR3748，it should be be done inside the MySqlDefaultValueConverter class instead theoretically，But this Exception link to JdbcValueConverters class , so i will fix this bug firstly。secondly i will do it in MySqlDefaultValueConverter class after this PR,thanks.

**Comment by Naros** [comment]
Hi @youyangkou so the `MySqlDefaultValueConverter` itself delegates to the `JdbcValueConverter` after it has parsed the default value either from a given DDL statement or from the JDBC metadata.  So if you trim the value inside the default value converter, you should have no reason to trim the value inside the other class, which is shared by all connectors.  Does that make sense?

**Comment by Naros** [comment]
Hi @youyangkou, I took a look and this was already solved as a part of [DBZ-4150](https://issues.redhat.com/browse/DBZ-4150).  While you have opened this against the `main` repository, your Jira issue says this is an issue with 1.6 and I cannot reproduce this on 1.9 nor main.  Can you confirm this is still a problem against `main` rather than just 1.6?

**Comment by youyangkou** [comment]
> 
@Naros Sorry, this is indeed a bug in version 1.6

**Comment by Naros** [comment]
Thanks for confirming, so unfortunately branch 1.6 is no longer maintained.  I would suggest you upgrade to 1.9.5.Final, which is the current latest stable version and this fix would be unnecessary.  I'm afraid since DBZ-4150 fixes this on `main`, this PR is superflous, ergo I am going to close it.

**Pull request closed without merging**
