### PR TITLE
README translate to korean 

### PR DESCRIPTION
**Pull request by giljae**
Translated the README into Korean.

### CODE REVIEW

**Comment by giljae** [comment]
Translated the README into Korean.

**Comment by giljae** [comment]
[docs] README translated to Korean

**Comment by giljae** [comment]
[docs] README translated to Korean

**Comment by giljae** [comment]
README translated to Korean

**Comment by giljae** [comment]
[docs] README translated to Korean

**Comment by jpechane** [comment]
@giljae Hi, is this PR complete? If ye then please squash all the commits into a single one and change the commit message into
`[docs] README translate to korean].
I'll add your name into `COPYRIGHT.txt` during merging process.

**Comment by giljae** [comment]
Hi Jiri,
PR is completed into a single one for Korean README.md.

Thanks for your help :)
Best regards,
*Giljae Joo (주길재)*

*//The Actual is limited, the possibilities immense. - Alphonse de
Lamartine//*


2022년 7월 12일 (화) 오후 5:59, Jiri Pechanec ***@***.***>님이 작성:

**Pull request closed without merging**
