### PR TITLE
DBZ-3608

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-3608

@jpechane, another small clean-up one.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Ok, the test failure looks real, it's a test that wasn't run accidentally on PG 10 before which got revealed by this. Exploring.

**Comment by gunnarmorling** [comment]
Update pushed; the expected value for a `SERIAL` column needed updating due to the recently merged default value PR.

**Review by Naros — APPROVED** [review]
Changes LGTM.

**Comment by gunnarmorling** [comment]
Thx, @Naros! @jpechane, do you want to merge it?

**Pull request merged**
