### PR TITLE
DBZ-1068 Forward port the work by @grzegorz8 to the 1.1 branch

### PR DESCRIPTION
**Pull request by GuyIEX**
This still doesn't address the concern in the comment https://github.com/debezium/debezium/pull/748#issuecomment-492526200 but this does allow for easier work on the 1.1 branch.

I can provide a patch for master too if needed.

### CODE REVIEW

**Comment by GuyIEX** [comment]
Also, this is more than just a rebase as some code had to change for renamed variables, etc.

**Comment by gunnarmorling** [comment]
Hey @GuyIEX, thanks a lot for picking this up. How comes though you rebased this (only) to 1.1? This version isn't maintained any more at this point, so we'd need a PR against the current master branch (=1.3). Also, could you keep original authorship of the commit to @grzegorz8 and either add your own changes in a separate commit or co-author the original commit? In any case, @grzegorz8 original authorship shouldn't get lost. Thanks!

**Comment by GuyIEX** [comment]
Hi @gunnarmorling, no problem. I did this work against 1.1 because I didn't think this version was not maintained anymore since there was a release of 1.1.3.Final less than 30 days ago. Also, my client needs to run 1.1.x in their environment due to another issue, so this version was my first priority.

I'm unsure how to preserve authorship or co-author the original commit. I will look into this. Once I figure that out I'll use that method for a PR against master.

**Comment by gunnarmorling** [comment]
> I did this work against 1.1 because I didn't think this version was not maintained anymore

Gotcha; we did the 1.1.3 release as the basis for a downstream product release, but generally speaking, only the latest version is actively maintained in the upstream community, i.e. the master branch and thus 1.3 at this point. We might backport critical bugfixes, but feature dev would target the next release always. We release quarterly, so you won't have to wait long to get a final version with the changes :)

> I'm unsure how to preserve authorship or co-author the original commit

You can do `git commit --amend --author "<original author as per git log>"` to re-establish the original authorship. See [here](https://medium.com/blackode/creating-co-authored-commits-on-the-command-line-git-305ae2af9f73) for adding yourself as a co-author to the commit then.

**Comment by GuyIEX** [comment]
Ok, you should see @grzegorz8 as the author and myself as a co-author now. I'll work on a PR for master, but it might not hit until tomorrow.

**Comment by jpechane** [comment]
@GuyIEX Hi, this PR can be closed then?

**Comment by GuyIEX** [comment]
@jpechane Yes. We will continue to use the build from my repo and migrate to the next version that contains these fixes. Thanks!

**Pull request closed without merging**
