### PR TITLE
DBZ-5371 Use initial snapshot position if "$natural:-1" is not supported

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-5371

### CODE REVIEW

**Comment by jpechane** [comment]
@denco37 Please refer to the linked Jira, there is still an issue to be solved.

**Comment by Naros** [comment]
@jpechane I've commented on the issue regarding the capped collection problem.  After talking with a user today who has helped test this particular fix and offered their feedback, we concluded that capped collections are a separate problem from what we're trying to solve here.  More specifically, capped collections are circular buffer-like collections that may simply not be compatible with change streams at all, whereas a non-capped collection is.

**Review by Sage-Pierce — APPROVED** [review]
LGTM

**Comment by Sage-Pierce** [comment]
Thanks for such a quick turnaround on this, @Naros!

**Comment by Naros** [comment]
Applied to main (=2.0) and branch 1.9.

**Pull request merged**
