### PR TITLE
DBZ-5623 DDL Parsing Error

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-5623

### CODE REVIEW

**Comment by harveyyue** [comment]
Upstream pr: https://github.com/antlr/grammars-v4/pull/2834

**Comment by Naros** [comment]
Applied to main (=2.0).

**Comment by ruslandanilin** [comment]
@harveyyue thank you!

**Comment by harveyyue** [comment]
> @harveyyue thank you!

@ruslandanilin Welcome😄

**Pull request merged**
