### PR TITLE
DBZ-1381 Introduce permanent metadata connection

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1381

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @addisonj, this addresses a potential perf issue we noticed recently. Any thoughts from you on this PR? Thanks!

**Comment by gunnarmorling** [comment]
Applied; thanks a lot, @jpechane!

@addisonj, still interested in your feedback on this, if you got any.

**Comment by addisonj** [comment]
This make sense, I had wondered about that a bit. I am not working on this as directly but will get it to to guy who is and get it integrated on our end and see how it works out

**Comment by gunnarmorling** [comment]
Awesome; thanks, Addison!

>

**Pull request merged**
