### PR TITLE
DBZ-1868 Validate commit messages in PR

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Not sure what to think about that tbh. It seems overly formalistic, what about quick typo fixes for instance?

**Comment by jpechane** [comment]
@gunnarmorling The recent version supports one of three format

* DBZ-xxx text
* [release] text
* [jenkins-jobs] text

So to alleviate the concern - we can either introduce [docs] tag or in case of fixes we can just ignore the failing sanity check and merge

**Comment by gunnarmorling** [comment]
> just ignore the failing sanity check and merge

Ok, if that's an option for the occasional quick typo fix, that's fine for
me. But introducing [docs] is good, too, for slightly longer doc fixes
still not warranting a JIRA issue.

>

**Comment by jpechane** [comment]
I must admit I'd prefer either one or the other option but not both.

**Comment by gunnarmorling** [comment]
Let's accept the failing check then every now and then, as e.g. external contributors won't know about the [docs] prefix when sending a typo fix.

**Comment by jpechane** [comment]
@gunnarmorling I agree, if you are happy with it please merge and I'll introduce the same action for incubator repo

**Comment by gunnarmorling** [comment]
Done.

**Pull request merged**
