### PR TITLE
DBZ-7780 NO_DATA snapshot mode validation throw DebeziumException on restarts if snapshot is not completed

### PR DESCRIPTION
**Pull request by mfvitale**
closes: https://issues.redhat.com/browse/DBZ-7780

### CODE REVIEW

**Review by jpechane — APPROVED** [review]
@mfvitale LGTM, thanks! Please feel free to merge (and backport) yourself after CI is completed.

**Comment by mfvitale** [comment]
@Naros Seems even 5h is not enough for oracle-21-xs. `whenSnapshotMultipleTablesAndConnectorRestartsThenOnlyNotAlreadyProcessedTableMustBeProcessed` this is taking about 10 min and executed multiple time. I created https://issues.redhat.com/browse/DBZ-7793

If you agree I'll go to merge this.

**Comment by mfvitale** [comment]
Applies to main (2.7) and 2.6

**Pull request merged**
