### PR TITLE
DBZ-2432: Fixing misuse of assertj

### PR DESCRIPTION
**Pull request by marceloavan**
- Some usages of assertj was not calling the actual assert of the DSL, fixing it (e.g. https://github.com/debezium/debezium/pull/4108/files#diff-62d154ab486c83e199be1a9ffab2aa71549f8905512e724b42b80fb8326b901eR104)
- Changing the Assertions to be statically imported

### CODE REVIEW

**Review by jpechane — CHANGES_REQUESTED** [review]
@marceloavan Nice chunk of changes! Could you please rebase against the latest main and build locally to make sure the code is properly formatted? Thanks a lot

**Comment by marceloavan** [comment]
@jpechane 

Fixed, I've missed that.

I'm still getting some errors on the postgres integrated tests, but also on the main branch, so it probably is related to my env.

**Comment by jpechane** [comment]
@marceloavan I am sorry about Postgres - it is a [bug](https://issues.redhat.com/browse/DBZ-5895)

**Comment by jpechane** [comment]
There are still some formatting issues. Please run `mvn -T 5 clean install -DskipTests=true -DskipITs=true -Passembly,oracle-xstream` to get it built and formatted.

**Comment by marceloavan** [comment]
@jpechane 

Yeah, I've also missed that.

Now it seems right, I'm getting another error with the oracle connector to run your command:

```
[ERROR] Failed to execute goal on project debezium-connector-oracle: Could not resolve dependencies for project io.debezium:debezium-connector-oracle:jar:2.1.0-SNAPSHOT: com.oracle.instantclient:xstreams:jar:21.6.0.0 was not found in https://packages.confluent.io/maven/ during a previous attempt. This failure was cached in the local repository and resolution is not reattempted until the update interval of confluent has elapsed or updates are forced
```
All is good with the remaining projects, and this one I adjusted this one manually to fix my improper changes, now it should be right.

**Comment by jpechane** [comment]
@marceloavan Applied, thanks a lot! Could you please provide the same for Db2, Cassandra and Vitess repos?

**Comment by marceloavan** [comment]
@jpechane 

For vitess there was just one occurrence: https://github.com/debezium/debezium-connector-vitess/pull/111

**Comment by marceloavan** [comment]
@jpechane

Also a few occurrences for db2: https://github.com/debezium/debezium-connector-db2/pull/88.

There are no occurrences for cassandra.

**Pull request merged**
