### PR TITLE
DBZ-849 Refact read mysql sytem variables methods to make them more readable

### PR DESCRIPTION
**Pull request by artiship**
1. Removed the unused param sql for the read system variables methods
2. Extract the duplicate block from the two read system variables methods into a reusable method
3. Extract the sql statement to be a field static final variable

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @artiship, thanks a lot! Sorry for the delay with reviewing, we're on summer holiday mode right now :) But I'll get back to this asap. In the meantime, could you reword the commit messages so they begin with the issue key ("DBZ-xyz ...")? Thanks!

**Comment by artiship** [comment]
@gunnarmorling Sorry forget the issue key. I'll figure out how to amend the commit message. 

And these are three little changes, but they are not very related to each other. Should I make them into different PRs?

**Comment by artiship** [comment]
I've removed the other two commits into two separate PRs.

**Comment by jpechane** [comment]
Applied, thanks @artiship !

**Comment by gunnarmorling** [comment]
Hey @artiship, could you give us your name so we can add it to the list of contributors? Thanks!

**Pull request merged**
