### PR TITLE
DBZ-6524 [PostgreSQL] LTree data is not being captured by streaming

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6524

### CODE REVIEW

**Comment by jpechane** [comment]
@harveyyue Thanks for the PR. There are

- `io.debezium.connector.postgresql.RecordsStreamProducerIT.shouldReceiveChangesForInsertsCustomTypes()`
- `io.debezium.connector.postgresql.RecordsSnapshotProducerIT.shouldGenerateSnapshotsForCustomDatatypes()`

We need to have those tests passing without `include.unknown.datatypes` set to `true`

**Comment by mfvitale** [comment]
> @harveyyue Thanks for the PR. There are
> 
> * `io.debezium.connector.postgresql.RecordsStreamProducerIT.shouldReceiveChangesForInsertsCustomTypes()`
> * `io.debezium.connector.postgresql.RecordsSnapshotProducerIT.shouldGenerateSnapshotsForCustomDatatypes()`
> 
> We need to have those tests passing without `include.unknown.datatypes` set to `true`

I am working on the same..

**Comment by mfvitale** [comment]
https://github.com/debezium/debezium/pull/4576

**Comment by harveyyue** [comment]
@mfvitale Thanks for your another pr for this. I don't notice you have taken this ticket, sorry for the inconvenience.

**Comment by jpechane** [comment]
@harveyyue Thanks for the PR. As @mfvitale unfortunately developed another one in parallel and is in more advanced state I opted to merge it and close this one. I am sorry for that. We will try to eliminate such situations in future.

**Pull request closed without merging**
