### PR TITLE
DBZ-4303 Replace md5 sum of connect extension in Dockerfile during release

### PR DESCRIPTION
**Pull request by jcechace**
https://issues.redhat.com/browse/DBZ-4303

Depends on: 
https://github.com/debezium/container-images/pull/308
https://github.com/debezium/debezium/pull/4060

### CODE REVIEW

**Comment by jcechace** [comment]
Will test the release pipeline once https://github.com/debezium/container-images/pull/308#discussion_r1012041754 is resolved

**Review by jpechane — APPROVED** [review]
@jcechace LGTM! Feel free to merge yourself when the pipeline is tested.

**Comment by jcechace** [comment]
@jpechane will do once the PR in debezium/container-images is resolved

**Comment by jcechace** [comment]
Dry release run passed, merged.

**Pull request merged**
