### PR TITLE
DBZ-6655 Document not supported schema change records on JDBC connector

### PR DESCRIPTION
**Pull request by mfvitale**
closes: https://issues.redhat.com/browse/DBZ-6655

### CODE REVIEW

**Review by roldanbob — CHANGES_REQUESTED** [review]
Hi @mfvitale, I made some preliminary suggestions, but I was confused about a couple of things, so before you implement any changes, please take a look at those. After you have a chance to respond I can take take another pass. Thanks!

**Comment by mfvitale** [comment]
> You refer to excluding schema change topics. Do you mean excluding schema change event records? I made a change assuming that you intended to refer to records vs. topics.

No, I mean schema change topic.

> It's not clear what you mean when you refer to configuring JDBC connector properties to exclude schema change topics (or event records). Pending discussion with you, for now I left the reference to JDBC connector properties, but I am not sure that is correct.
The Debezium JDBC connector doc doesn't refer to either of the properties that you mention. If possible, we should provide a link to the properties that you mention, or to another document that describes how to configure these properties.
I know that Debezium provides SMTs that include a topic.regex option (no s) for [topic routing](https://debezium.io/documentation/reference/stable/transformations/topic-routing.html#by-logical-table-router-topic-regex) and [message filtering](https://debezium.io/documentation/reference/stable/transformations/filtering.html#filter-topic-regex), but I don't find a topics.regex or topic property in any of our connector documentation.

The properties are generic and are default for every Kafka sink connector https://debezium.io/documentation/reference/nightly/connectors/jdbc.html#jdbc-connector-properties. The aim of this documentation change is to state that the schema changes topic is not supported by this sink connector and, in case you enabled `include.schema.changes` in the source connector, this topic must not be included in the topics consumed by the JDBC connector. This can be achieved using the `topics` or `topics.regex` properties. 

Let me know if it's more clear.

**Comment by roldanbob** [comment]
> Let me know if it's more clear.

Thanks, @mfvitale! Yes, having the link to the generic Kafka connector properties clarifies things.

**Review by roldanbob — CHANGES_REQUESTED** [review]
@mfvitale OK, I've reworked my suggestions based on your input. Thanks!

**Review by Naros — APPROVED** [review]

**Comment by Naros** [comment]
Applied to main (=2.4) and branch 2.3.

**Pull request merged**
