### PR TITLE
DBZ-8393 ExtractNewRecordState transform: move processing of headers after envelope has been checked

### PR DESCRIPTION
**Pull request by martinvlk**
This is to avoid NPE for non-envelope rerords.

### CODE REVIEW

**Comment by martinvlk** [comment]
@harveyyue @gunnarmorling @jpechane

There seems to be a change in the logic here since version 2.4.0, which causes a NPE when processing headers for non-envelope records.

My fix makes sure the headers get processed only after non-envelope records have been filtered out.

**Comment by martinvlk** [comment]
Strange, a test is failing in ona of the jobs:
`ExtractNewDocumentStateTestIT.shouldFlattenTransformRecordForInsertEvent:1267 NullPointer Cannot invoke "java.util.List.size()" because the return value of "io.debezium.embedded.AbstractConnectorTest$SourceRecords.recordsForTopic(String)" is null`

But it is passing locally in my dev env.. is this some flaky test that might pass if re-run?

**Comment by jpechane** [comment]
@martinvlk I'll re-run it later to make sure.

**Comment by martinvlk** [comment]
Still failing. But honestly, I don't see how my fix could have affected this part of the code.

**Comment by jpechane** [comment]
@martinvlk Could you please rabe on the latest main?

@vjuranek I noticed error in the log
```
2024-11-12T11:48:12.5835586Z java.lang.IllegalStateException: Cannot stop engine while tasks are starting, this may lead to leaked resource. Wait for the tasks to be fully started.
2024-11-12T11:48:12.5837435Z 	at io.debezium.embedded.async.AsyncEmbeddedEngine.close(AsyncEmbeddedEngine.java:246)
2024-11-12T11:48:12.5838968Z 	at io.debezium.embedded.async.TestingAsyncEmbeddedEngine.close(TestingAsyncEmbeddedEngine.java:34)
2024-11-12T11:48:12.5840576Z 	at io.debezium.embedded.AbstractConnectorTest.stopConnector(AbstractConnectorTest.java:167)
2024-11-12T11:48:12.5842108Z 	at io.debezium.embedded.AbstractConnectorTest.stopConnector(AbstractConnectorTest.java:152)
2024-11-12T11:48:12.5843726Z 	at io.debezium.connector.mongodb.AbstractMongoConnectorIT.afterEach(AbstractMongoConnectorIT.java:76)
2024-11-12T11:48:12.5845862Z 	at io.debezium.connector.mongodb.transforms.AbstractExtractNewDocumentStateTestIT.afterEach(AbstractExtractNewDocumentStateTestIT.java:88)
2024-11-12T11:48:12.5848899Z 	at io.debezium.connector.mongodb.transforms.AbstractExtractNewDocumentStateTestIT.restartConnectorWithoutEmittingTombstones(AbstractExtractNewDocumentStateTestIT.java:94)
2024-11-12T11:48:12.5851868Z 	at io.debezium.connector.mongodb.transforms.ExtractNewDocumentStateTestIT.shouldRewriteDeleteMessage(ExtractNewDocumentStateTestIT.java:1004)
```

is it possible that this relates to some of the test issues you fixed recently?

**Comment by martinvlk** [comment]
Merged the latest changes from main, let's see.

**Comment by martinvlk** [comment]
The check seem to be very flaky... can I do anything to help here?

**Comment by vjuranek** [comment]
> @vjuranek I noticed error in the log
> 
> ```
> 2024-11-12T11:48:12.5835586Z java.lang.IllegalStateException: Cannot stop engine while tasks are starting, this may lead to leaked resource. Wait for the tasks to be fully started.
> 2024-11-12T11:48:12.5837435Z 	at io.debezium.embedded.async.AsyncEmbeddedEngine.close(AsyncEmbeddedEngine.java:246)
> 2024-11-12T11:48:12.5838968Z 	at io.debezium.embedded.async.TestingAsyncEmbeddedEngine.close(TestingAsyncEmbeddedEngine.java:34)
> 2024-11-12T11:48:12.5840576Z 	at io.debezium.embedded.AbstractConnectorTest.stopConnector(AbstractConnectorTest.java:167)
> 2024-11-12T11:48:12.5842108Z 	at io.debezium.embedded.AbstractConnectorTest.stopConnector(AbstractConnectorTest.java:152)
> 2024-11-12T11:48:12.5843726Z 	at io.debezium.connector.mongodb.AbstractMongoConnectorIT.afterEach(AbstractMongoConnectorIT.java:76)
> 2024-11-12T11:48:12.5845862Z 	at io.debezium.connector.mongodb.transforms.AbstractExtractNewDocumentStateTestIT.afterEach(AbstractExtractNewDocumentStateTestIT.java:88)
> 2024-11-12T11:48:12.5848899Z 	at io.debezium.connector.mongodb.transforms.AbstractExtractNewDocumentStateTestIT.restartConnectorWithoutEmittingTombstones(AbstractExtractNewDocumentStateTestIT.java:94)
> 2024-11-12T11:48:12.5851868Z 	at io.debezium.connector.mongodb.transforms.ExtractNewDocumentStateTestIT.shouldRewriteDeleteMessage(ExtractNewDocumentStateTestIT.java:1004)
> ```
> 
> is it possible that this relates to some of the test issues you fixed recently?

yes, exactly this issues was fixed in [DBZ-8397](https://issues.redhat.com/browse/DBZ-8397)

**Comment by vjuranek** [comment]
Remaning test failures seem to be random unrelated failures, I re-run the jobs.
@martinvlk unfortunately yes, our testsuite is not that stable as we would like it to be, PRs to improve it would be always welcome:-)

**Comment by martinvlk** [comment]
Excellent, thanks!
Do you want me to do a cherrypick to the  release branch for 2.7.4, or you do that yourselves?
I assume 3.0.2 gets released from master?

**Comment by jpechane** [comment]
@martinvlk And it is merged, thanks a lot! I'll try to apply it to 2.7 and only in case of the need of larger change I'll ask you for another PR.

**Pull request merged**
