### PR TITLE
Dbz 3299 user guide corrections for mysql connector

### PR DESCRIPTION
**Pull request by roldanbob**
Jira: [DBZ-3299](https://issues.redhat.com/browse/DBZ-3299)

This change to the MySQL connector documentation incorporates corrections to the deployment instructions that were made for the PG connector in Q3 2020, along with other changes for consistency with the documentation for other connectors. The changes include restructuring content.

Upstream, the restructuring changes and other minor changes are apparent in some places.

Changes are tested in a local Antora build and in a local downstream documentation build.

If possible, we should backport these changes to 1.4, as the corrections apply there.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Is this one good to go from your PoV, @roldanbob?

**Comment by roldanbob** [comment]
@gunnarmorling Yes, I think this is ready for merging now. :crossed_fingers: :)

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Applied to master (=1.6) and 1.4.

**Comment by gunnarmorling** [comment]
Thx, @roldanbob!

**Pull request merged**
