### PR TITLE
Fix cmd in the kubernetes.adoc

### PR DESCRIPTION
**Pull request by minchowang**
Missing the symbol  "-"

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@vjuranek could you review and apply this one? Note it should not be merged as is, as there's a merge commit part of this PR. Easiest is to use "Squash and merge" above, which will create a single (non-merge) commit. Thanks!

**Review by vjuranek — APPROVED** [review]

**Comment by vjuranek** [comment]
Hi @minchowang , thanks for your contribution! Could you please setup your email to one associated the your account and update the commit to avoid ["octocat" commit](https://docs.github.com/en/account-and-profile/setting-up-and-managing-your-github-profile/managing-contribution-graphs-on-your-profile/why-are-my-contributions-not-showing-up-on-my-profile#your-local-git-commit-email-isnt-connected-to-your-account)? Thanks you!

**Review by vjuranek — CHANGES_REQUESTED** [review]
contains octocat commits

**Comment by minchowang** [comment]
> contains octocat commits

Ok，i resolve it now

**Comment by vjuranek** [comment]
Thanks @minchowang ! Merged.

**Pull request closed without merging**
