### PR TITLE
DBZ-874 Executing Travis builds in parallel

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @jpechane, what's the status of this one? Is it good to go from your POV? I believe you mentioned some more work being required, but I could mix it up with another PR. Thanks!

**Comment by jpechane** [comment]
@gunnarmorling This is already done, I've triggered a new build to verify it works with the build stabilization PRs introduced last week and if yes then it can be merged.

**Comment by jpechane** [comment]
@gunnarmorling And we are good to go...

**Comment by gunnarmorling** [comment]
Excellent; thanks, @jpechane!

**Pull request merged**
