### PR TITLE
DBZ-5200 Accept multiple lob_storage_parameters & tablespace_name as experssion

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-5200

### CODE REVIEW

**Comment by Naros** [comment]
Hi @ani-sha did we open an upstream PR with these changes?

**Comment by ani-sha** [comment]
@Naros Do we do that for Oracle DDL changes?

**Comment by Naros** [comment]
We try to @ani-sha, if possible.

**Comment by ani-sha** [comment]
Upstream PR - https://github.com/antlr/grammars-v4/pull/2645

**Comment by Naros** [comment]
Applied to 1.9 and main (=2.0).

**Pull request merged**
