### PR TITLE
DBZ-6559 Restore backward compatibility for field that stars with a digit

### PR DESCRIPTION
**Pull request by mfvitale**
closes: https://issues.redhat.com/browse/DBZ-6559

### CODE REVIEW

**Comment by jpechane** [comment]
@mfvitale I pushed a commit that handles the keeping of the first char as an exception not as rule.

**Comment by jpechane** [comment]
@mfvitale Could you please doble check the behaviour of the schema names too? If a topic prefix has value `3prefix`, what is and what was the name of the key/value schemas of messages in the topic? Do they start with `_prefix` or with `_3prefix`?

**Comment by mfvitale** [comment]
> @mfvitale Could you please doble check the behaviour of the schema names too? If a topic prefix has value `3prefix`, what is and what was the name of the key/value schemas of messages in the topic? Do they start with `_prefix` or with `_3prefix`?

Tested and the prefix will be `_3prefix` is it correct?

**Comment by jpechane** [comment]
@mfvitale Yes, that's correct - it is consistent

**Comment by mfvitale** [comment]
> @mfvitale Yes, that's correct - it is consistent

Yes. Let me push this other test.

**Comment by jpechane** [comment]
@mfvitale Applied, thanks

**Pull request merged**
