### PR TITLE
DBZ-8202 extended support for mongoDb

### PR DESCRIPTION
**Pull request by ajit97singh**
https://issues.redhat.com/browse/DBZ-8202

### CODE REVIEW

**Comment by ajit97singh** [comment]
Hi @Naros , apologies for the delay I was struggling with changing commit messages. Hope everything is in line , have closed the previous PR.

**Comment by jpechane** [comment]
@ajit97singh Hi, thanks for the PR. Could you please also execute code formatting before push?
Also I'd like to remind you that we officially dropped support for MongoDB 4. I am fine in adding this quite isolated change into the codebase but please bear in mind that you are on your own with aditional changes/bugfixes.
Thanks for understanding

**Comment by ajit97singh** [comment]
@jpechane Thank you for your feedback and for taking the time to review my PR. I've executed the code formatting as requested. I also appreciate the reminder regarding MongoDB 4. I understand the support limitations, and I’ll keep that in mind for any future work or changes related to this.Thanks again for your guidance and support!

**Comment by jpechane** [comment]
@ajit97singh Thanks, merged via https://github.com/debezium/debezium/pull/5839

**Pull request closed without merging**
