### PR TITLE
DBZ-1244 Detect unreplicated purged GTIDs

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1244

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, could you add a short description of the nature of this change? Thanks!

**Comment by jpechane** [comment]
@gunnarmorling The purpose of this change is to provide the same functionality for `when_needed` snapshot for GTID enabled database like for non-GTID. The non-GTID just relies on missing replication log to detect the new snapshot needs to be triggered. This does not work in GTID environment as we need to compare the GTIDs that are available on the server with those we have already processed - stored in the offsets.
If there is a set of GTIDs that were not replicated by Debezium and at the same time have been already purged then we detect the situation and trigger a new snapshot when required.
We thus

1. Take all GTIDs ever processed by the server
2. Filter out GTIDs that were processed by Debezium
3. Compare them with purged GTID set
4. If the interesction is not empty we know we have not replicated transaction that have already been removed from the server

**Comment by gunnarmorling** [comment]
Thanks, that makes sense! I'll add that explanation to the message of your commit. As said before, let's be a bit more thorough in commit messages, so to know what's going on if we get back to our changes next week, month or year :)

**Comment by gunnarmorling** [comment]
Rebased and applied. Altered your commit message as discussed above. Thanks a lot, @jpechane!

**Pull request closed without merging**
