### PR TITLE
DBZ-651 Add Quarkus and Graal SDK licences

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Why is it we need to redistribute Graal SDK to begin with? We're using Quarkus solely in JVM mode after all.

**Comment by jpechane** [comment]
@gunnarmorling  I tried to remove it
```
Exception in thread "main" java.lang.NoClassDefFoundError: Could not initialize class org.jboss.logmanager.LogContext
	at org.jboss.logmanager.LogManager.getLogger(LogManager.java:110)
	at org.jboss.logmanager.LogManager.getLogger(LogManager.java:27)
	at java.logging/java.util.logging.LogManager.demandLogger(LogManager.java:519)
	at java.logging/java.util.logging.LogManager.demandLogger(LogManager.java:515)
	at java.logging/java.util.logging.Logger.demandLogger(Logger.java:654)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:717)
	at java.logging/java.util.logging.Logger.getLogger(Logger.java:701)
	at org.jboss.logging.JDKLogger.<init>(JDKLogger.java:33)
	at org.jboss.logging.JDKLoggerProvider.getLogger(JDKLoggerProvider.java:24)
	at org.jboss.logging.LoggerProviders.logProvider(LoggerProviders.java:156)
	at org.jboss.logging.LoggerProviders.tryJDK(LoggerProviders.java:112)
	at org.jboss.logging.LoggerProviders.findProvider(LoggerProviders.java:107)
	at org.jboss.logging.LoggerProviders.find(LoggerProviders.java:34)
	at org.jboss.logging.LoggerProviders.<clinit>(LoggerProviders.java:31)
	at org.jboss.logging.Logger.getLogger(Logger.java:2465)
	at io.quarkus.runtime.configuration.ConfigUtils.<clinit>(ConfigUtils.java:39)
	at io.quarkus.runtime.generated.Config.<clinit>(Config.zig:16544)
	at io.quarkus.runner.ApplicationImpl.<clinit>(ApplicationImpl.zig:303)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at java.base/java.lang.Class.newInstance(Class.java:584)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:60)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:38)
	at io.quarkus.runtime.Quarkus.run(Quarkus.java:106)
	at io.debezium.server.Main.main(Main.java:15)
```
and IMHo default shutdown hook requires the class from it as well.

**Comment by gunnarmorling** [comment]
Interesting; could you open an issue with Quarkus for that? I feel the
GraalVM dependency shouldn't be mandatory when running on the JVM.

Am Do., 14. Mai 2020 um 16:16 Uhr schrieb Jiri Pechanec <
notifications@github.com>:

**Comment by jpechane** [comment]
@gunnarmorling https://github.com/quarkusio/quarkus/issues/9320

**Pull request merged**
