### PR TITLE
DBZ-6144 Upgrade impsort-maven-plugin from 1.7.0 to 1.8.0

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6144

### CODE REVIEW

**Comment by jpechane** [comment]
@harveyyue Hi, thanks for that. an this be undrafted or is there any other issue?

**Comment by harveyyue** [comment]
@jpechane There is no other issue, just missoperation with draft.

**Review by Naros — APPROVED** [review]

**Comment by Naros** [comment]
Applied to main (=2.2).

**Comment by bpux** [comment]
i have the same issue as https://issues.redhat.com/browse/DBZ-6144
wondering if you find out why?
the 2.1 branch is still using 1.7.0 version

**Comment by Naros** [comment]
Hi @bpux, This was applied to Debezium 2.2 branch; we did not update Debezium 2.1.

**Comment by bpux** [comment]
thanks. i was using mvn 3.9.1. after downgrade it to 3.8.8, the 1.7 version build passed.

**Pull request merged**
