### PR TITLE
DBZ-1882 Restarting after connection losses in SQL Server

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1882

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros LGTM. Code needs reformatting. Have you had a chance to test it manually by using our tutorial and pausing the SQL Server pod to simulate network issues?

**Comment by Naros** [comment]
Hi @jpechane, I attempted to test it as you suggested but I found that using pause didn't cause any type of network connectivity issue but instead the SQL call would block indefinitely on the streaming thread until the container as unpaused and it would then resume.

That said, after unpausing then stopping the container thereafter I was able to see that the handler was invoked and that `SQLServerException: SQL Server did not return a response.  The connection has been closed." was deemed non-retryable.

**Comment by jpechane** [comment]
@Naros +1 to both suggestions - extedning the retriable exception with the timeout scenario and testing with container delete/start. Then it can be merged

**Comment by Naros** [comment]
@jpechane @gunnarmorling Added some additional retry errors based on test suggestions.

**Comment by gunnarmorling** [comment]
Nice improvement; thanks, @Naros!

**Comment by little-tomato** [comment]
Could you help improve the relevant support for MySQL?

**Comment by gunnarmorling** [comment]
Can you bring your question to the mailing list please (https://groups.google.com/g/debezium/); let's not re-use unrelated, long-closed PRs for this. Thx.

**Pull request merged**
