### PR TITLE
DBZ-1712 MySQL connector use default port when database.port option not specified

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1712

### CODE REVIEW

**Comment by Naros** [comment]
From what I saw there was no `database.port` in the initial config and when https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/jdbc/JdbcConnection.java#L164 was called, the substitution was attempting to use https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/jdbc/JdbcConfiguration.java#L50 which has no default, thus no substitution occurred.

**Comment by hashhar** [comment]
I was talking about the MySQLConnectorConfig class (the Kafka Connect configuration).

It has the default specified.
https://github.com/debezium/debezium/blob/master/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlConnectorConfig.java#L556-L563

Then we construct the JdbcConfiguration using it at https://github.com/debezium/debezium/blob/master/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlJdbcContext.java#L53. Why are the defaults lost then?

**Comment by Naros** [comment]
The default isn't really lost, its really more an integration concern.

Whenever you ask the Kafka `Configuration` for a value based on a `Field`, internally the object looks at the configuration keys and if a key exists, it returns the value specified; however, when the value is not specified, it asks the `Field` to return the default-value, which we'd get 3306 in this case.

But the way this bit of code integrates, its a bit different.

In the `MySqlJdbcContext` constructor, we store the `Configuration` object, we then use it to filter out certain keys and then we cache a copy of it with all the `database.` prefixed keys but the stashed copy has the prefix stripped, so all `jdbcConfig` has from your example in the issue would be:

```
user=mysqluser
server.name=mysql
hostname=localhost
password=********
whitelist=debezium_test
```

It uses this list of key/value pairs to perform the substitution inside the call to `patternBasedFactory` and since there is no entry for `port` in the `jdbcConfig`, it's going to use `JdbcConfiguration.PORT`, which has no default value, hence it doesn't get substituted.

By me explicitly forcing `database.port` into the `jdbcConfig` map if it's not supplied by the JSON configuration for the connector, the right `PORT` field reference gets used and therefore a default value is found and substituted.

Does that help?

**Comment by hashhar** [comment]
Yes, figured that out right now after adding some logs. I was under the assumption that the defaults are used to mutate the config object. Rather the defaults are only used when calling one of the `getXXX(Field)` methods.

**Comment by gunnarmorling** [comment]
Thanks for the fix, @Naros and thanks for reviewing/testing, @hashhar 👍

**Pull request merged**
