### PR TITLE
DBZ-2307 - Improve logging when primary keys are missing

### PR DESCRIPTION
**Pull request by jhuiting**
See https://issues.redhat.com/browse/DBZ-2307 / https://gitter.im/debezium/user?at=5efdf769c3362026a90a6618. 

@Naros @gunnarmorling Let's try again with a PR, this supersedes https://github.com/debezium/debezium/pull/1674.

### CODE REVIEW

**Comment by jhuiting** [comment]
@Naros Please check again, I've updated that part as well.

I also noticed in https://debezium.io/documentation/reference/1.2/connectors/postgresql.html that it mentions: pgoutput plug-in does not emit all the events for tables without primary keys, it only emits inserts. In my observation, this also applies for wal2jsonon PG 9.6 as UPDATE / DELETE statements are removed. This might be something can be removed from the documentation?

**Comment by Naros** [comment]
I would say if all 3 decoders behave the same, then its safe to generalize the documentation about key-less tables; however if there is any difference between the decoders, then we need to make sure the documentation clarifies the behavior accordingly to avoid confusion for users using one decoder over another.  I don't recall all the exact semantics of key-less tables between the decoders of my head, so if you have the bandwidth to make sure the documentation aligns properly that's great.  If not, I'll take a quick review later today and if there any further changes I can amend the PR.

**Comment by jhuiting** [comment]
@Naros I've checked, I think the behavior for the user is similar for both wal2json as well as for `pgoutput`. Only difference is that the former outputs an empty update and the later an empty create (with replication identity default). See also the `wal2json` example: https://github.com/eulerto/wal2json/blob/1b0cbac484f4fe5db80445f6721957511b4de7b7/expected/update1.out

It's hard to see what exactly happens in this case with protobuf.

**Comment by Naros** [comment]
LGTM, thanks @jhuiting!

**Pull request merged**
