### PR TITLE
Create mysql-dbz-198i.ddl

### PR DESCRIPTION
**Pull request by sanzzzay**
Added one more test case involving ALTER command

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @sanzzzay, finally getting to this one. Sorry for the delay. Just to confirm, what is the error message / exception you get here?

**Comment by sanzzzay** [comment]
I was getting this:
`ERROR Error parsing DDL statement and updating tables: ALTER TABLE `NextTimeTable`.`TIMETABLE_SUBJECT_GROUP_MAPPING`   
  drop column `SUBJECT_ID`, 
  drop index `FK69atxmt7wrwpb4oekyravsx9l`,
  drop foreign key `FK69atxmt7wrwpb4oekyravsx9l`  (io.debezium.connector.mysql.MySqlSchema:353)
io.debezium.text.ParsingException: No more content but was expecting token ON`

**Comment by gunnarmorling** [comment]
Ok, thanks! Seems the parser is getting into the branch for handling DROP INDEX ON statements instead of remaining within ALTER TABLE and its sub-clause DROP INDEX.

**Comment by sanzzzay** [comment]
Yes, I guess.

**Comment by sanzzzay** [comment]
By mistake. I closed it

**Comment by sanzzzay** [comment]
and I am not able to reopen and comment.

**Comment by sanzzzay** [comment]
Shall I create one more PR with same file changes??

**Comment by gunnarmorling** [comment]
@sanzzzay Yes, please.

@rhauch So this seems to happen when the table subject to `ALTER TABLE` isn't "known" in `parseAlterTable()` yet. Do you have an idea how we could get into this state? Shouldn't there always be a `CREATE TABLE` prior to that in the binlog?

**Comment by sanzzzay** [comment]
@gunnarmorling Yes I have done that.

**Pull request closed without merging**
