### PR TITLE
Regression test for MySQL dates in snapshot being off by one

### PR DESCRIPTION
**Pull request by benesch**
https://issues.redhat.com/browse/DBZ-1667

As per a discussion on Gitter with @jpechane last night. This test properly fails if the custom date-reading logic is removed like so:

```diff
diff --git a/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java b/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
index 499558ae..59632767 100644
--- a/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
+++ b/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/SnapshotReader.java
@@ -151,9 +151,9 @@ protected Object readField(ResultSet rs, int fieldNo, Column actualColumn, Table
         if (actualColumn.jdbcType() == Types.TIME) {
             return readTimeField(rs, fieldNo);
         }
-        else if (actualColumn.jdbcType() == Types.DATE) {
-            return readDateField(rs, fieldNo, actualColumn, actualTable);
-        }
+        // else if (actualColumn.jdbcType() == Types.DATE) {
+        // return readDateField(rs, fieldNo, actualColumn, actualTable);
+        // }
         // This is for DATETIME columns (a logical date + time without time zone)
         // by reading them with a calendar based on the default time zone, we make sure that the value
         // is constructed correctly using the database's (or connection's) time zone

```

In Debezium 0.9, if the timezone of the JVM running Debezium had an
earlier offset than the timezone of the MySQL server, any values of type
DATE read by the snapshot reader would be incorrectly shifted backwards
by one day. This was the result of a known bug/deficiency in MySQL's
JDBC connector [0].

This bug was inadvertently fixed in Debezium 0.10 by #913, which
bypassed the JDBC date retrieval logic to support zero dates, thus also
avoiding the inappropriate timezone shifting logic. However, since the
fix was inadvertent, there was no test to protect against regression.

This commit adds such a regression test. Since the MySQL server used in
tests uses timezone GMT-11, we just need to run a SnapshotReader in
timezone GMT-12 and verify that the dates are computed correctly. This
test fails if added to Debezium 0.9, but passes now thanks to #913.

Humorously, it is likely someone would have noticed this bug long ago
had the test MySQL server used any other timezone; for example, if the
MySQL server used EST as its timezone, anyone running the tests from the
International Date Line to Chicago would have seen the failure.  Bt with
GMT-11 there is only one timezone with a smaller offset, GMT-12, which
is only used by tiny outlying islands of the US.

[0]: https://bugs.mysql.com/bug.php?id=91112

### CODE REVIEW

**Comment by jpechane** [comment]
@benesch Nic work, thanks, I like you've thought about placing the locale restoration into `finally` block. I'd like to ask you form one more step. Could you please create a Jira issue (https://issues.redhat.com/projects/DBZ/) with more or less the same text it is here and then change the commit message into `DBZ-xxx Regression test for MySQL dates in snapshot being off by one`? It helps us to keep things better organized.

**Comment by gunnarmorling** [comment]
> It helps us to keep things better organized.

I can take care of that. Thanks a lot for the thorough analysis, @benesch, and going the extra-mile for providing a regression test for a bug that got inadvertently fixed already. That's definitely a first!

**Comment by gunnarmorling** [comment]
Rebased and applied. Many thanks again, @benesch!

**Comment by gunnarmorling** [comment]
Hey @benesch, btw. I saw you're with Materialize. If you don't mind me being curious, are you using Debezium in that context? If so, I would love to learn more, either here, or via DM on Gitter, Twitter or somewhere else :)

**Pull request closed without merging**
