### PR TITLE
DBZ-2245 Edit conditionals to expose Avro info downstream

### PR DESCRIPTION
**Pull request by roldanbob**
Commented out `product` conditional content and ` community` conditional tags so that the same avro information renders upstream and downstream.

### CODE REVIEW

**Comment by jpechane** [comment]
Why do wee ned to keep commented out instructions, could we remove them completely?

**Comment by roldanbob** [comment]
A fair point, @jpechane . Not being too familiar with the project and because I was stepping in as temporary backup while @TovaCohen was on PTO, I was reluctant to remove them completely. From your comment I'll assume the the extra caution was unnecessary. Shall I go ahead and remove them?

**Comment by TovaCohen** [comment]
Just noting here that, as Jiri suggests, the comments can be removed.

**Comment by Naros** [comment]
Thanks @roldanbob!

**Comment by TovaCohen** [comment]
@Naros  - As we agreed on chat, this needs to be backported to 1.2 since, for the downstream Q3 release, we are fetching content from the upstream 1.2 branch.  Thanks!

**Pull request merged**
