### PR TITLE
DBZ-1722 (TestContainers)

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-1722

Supersedes #1209.

### CODE REVIEW

**Comment by bsideup** [comment]
@gunnarmorling "Testcontainers", no capital "C" ;)

**Comment by gunnarmorling** [comment]
> "Testcontainers", no capital "C" ;)

What, no "Binnenmajuskel"? What are you people, monsters? 😀 

Thanks for pointing it out, fixed 👍 .

**Comment by bsideup** [comment]
@gunnarmorling for the record, I was in the "capital C" camp :D
But there is only one correct name - the one @rnorth gave when he created the project (although [there is an evidence of capital Cs used by Richard](https://github.com/testcontainers/testcontainers-java/commit/a66cfb038f70859ebdf5e728f0e8b21721ca753e#diff-04c6e90faac2675aa89e2176d2eec7d8) 😂 )

Oh well, at least we all agree that there is no singular "Testcontainer" 💀

Thanks for fixing 👍

**Comment by gunnarmorling** [comment]
Haha, yes, I can relate to that very much. You wouldn't believe the many ways of spelling "Red Hat" incorrectly...

**Comment by bsideup** [comment]
@gunnarmorling wait... there is a space? 😂 #kidding

**Comment by gunnarmorling** [comment]
Exactly. A kitten gets sacrificed by the brands team each time the " " is omitted ;)

**Comment by bsideup** [comment]
Yeah... okay, to conclude our beautiful off-topic: "Redhat" and "Test Containers", right? 😂

**Comment by gunnarmorling** [comment]
LOL, right, ahaha ;)

**Comment by gunnarmorling** [comment]
🎉  Applied; thanks again, @lordofthejars and @bsideup!

**Comment by lordofthejars** [comment]
Thanks for make it possible.

**Pull request merged**
