### PR TITLE
DBZ-6388 __source_ts_ms r (read) operation date is set to future for SQL Server

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6388

### CODE REVIEW

**Comment by harveyyue** [comment]
Related pr:
Db2: https://github.com/debezium/debezium-connector-db2/pull/103

**Comment by Naros** [comment]
Hi @harveyyue, could we adjust the commit message as I have for the PR title?  Thanks!

**Comment by harveyyue** [comment]
> Hi @harveyyue, could we adjust the commit message as I have for the PR title? Thanks!

Done.

**Review by Naros — APPROVED** [review]
LGTM, thanks @harveyyue !

**Comment by Naros** [comment]
Applied to main (=2.3).

**Pull request merged**
