### PR TITLE
DBZ-2586 updating ANLTR parser for grants to support mariadb VIA

### PR DESCRIPTION
**Pull request by jhiza**

### CODE REVIEW

**Comment by jpechane** [comment]
Hi, thanks for the PR. It needs few changes though

* `VIA` should be defined as a token
* `VIA` should be inuclded among `keywordsCanBeId`
* a test should be added to confirm that `VIA` is still valid identifier
* should not be `USING/AS` followed with `PASSWORD` function?

**Comment by gunnarmorling** [comment]
@jpechane, can you add a comment please to all rules specific to MariaDB (we've done that before)? That way we can go with the single grammar but at least keep sort of an overview of what's specific.

**Comment by jpechane** [comment]
@gunnarmorling Done

**Comment by gunnarmorling** [comment]
Thx!

**Pull request merged**
