### PR TITLE
DBZ-3824 NoClassDefFoundError for junit platform 

### PR DESCRIPTION
**Pull request by jcechace**
https://issues.redhat.com/browse/DBZ-3824

### CODE REVIEW

**Comment by jcechace** [comment]
Contains also update for junit5 as they did simplify the dependencies lately and surefire/failsafe tend to be sensitive about that.

**Comment by gunnarmorling** [comment]
@jcechace any idea on the test failures?

**Comment by jcechace** [comment]
> @jcechace any idea on the test failures?

We are correctly tying together versions of Surefire and Failsafe. For whatever reason, it looks like Failsafe is unable to load the entire classpath correctly. I will look into it during the day but I didn't find anything in my brief look yesterday.

**Comment by jcechace** [comment]
@gunnarmorling I "lowered" the upgrade to surefire and failsafe M4 which seems to solve both issues locally.

**Comment by jcechace** [comment]
@gunnarmorling  the next set of failures appears to be unrelated to changes.

**Comment by jcechace** [comment]
so the ```RecordsStreamProducerIT.testEmptyChangesProducesHeartbeat``` is failing also locally. However at this point I might use some assistance from somebody who knows these test better

**Comment by gunnarmorling** [comment]
@jcechace, I recommend you get hold of @jpechane on that one :)

**Comment by jpechane** [comment]
@jcechace See https://github.com/debezium/debezium/pull/2590

**Comment by gunnarmorling** [comment]
@jcechace, could you rebase and force-push this one, so to trigger a new build? Thx!

**Comment by jcechace** [comment]
@gunnarmorling  I did so already yesterday after #2590 was merged. However here you go again ;)

**Comment by gunnarmorling** [comment]
@jcechace, ok, thx. So I take it the build failures are not related to this change then? Can you work with @jpechane to make sure they are all tracked in Jira? Typically, you should find existing issues by looking for the name of the failing method in question.

**Comment by gunnarmorling** [comment]
@jpechane, @jcechace, are the last two remaining test failures unrelated and tracked via Jira issues?

**Comment by jpechane** [comment]
https://issues.redhat.com/browse/DBZ-3863

**Comment by jcechace** [comment]
@gunnarmorling  can we merge? I'd like to test if this resolves some test run issues through IntelliJ

**Comment by gunnarmorling** [comment]
Applied, thx!

**Pull request merged**
