### PR TITLE
DBZ-5077 Support DROP FOREIGN KEY IF EXISTS grammar

### PR DESCRIPTION
**Pull request by AlexMiroshnikov**
Please see https://issues.redhat.com/browse/DBZ-5077 for problem details.

### CODE REVIEW

**Comment by Naros** [comment]
Hi @AlexMiroshnikov we take pull requests against `main` and back port those to older branches as needed.  Could you please rebase this against `main` if this also applies to Debezium 2.0 and we'll back port it after its merged to 1.9?

**Comment by AlexMiroshnikov** [comment]
Hi @Naros , sure thing! :+1:  Thank you for letting me know and sorry for confusion :blush:

**Comment by AlexMiroshnikov** [comment]
@Naros In order to avoid extra mess, I'll just create a new PR based on `main`, and I'm closing this one.

**Comment by AlexMiroshnikov** [comment]
Created https://github.com/debezium/debezium/pull/3467 instead.

**Pull request closed without merging**
