### PR TITLE
DBZ-3697 Adding metadata to fields for SQLServerConnector

### PR DESCRIPTION
**Pull request by mdrillin**
Add schema metadata for SqlServer Connector, and test case

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@rk3rn3r can you handle this one? Thx!

**Comment by rk3rn3r** [comment]
Hey @mdrillin! Thx for taking care of this! Can you also look into used fields in the super-classes from SqlServerConnectorConfig? For example HistorizedRelationalDatabaseConnectorConfig and other classes in the class hierarchy add fields which are not in this PR. Or are these fields not used in SQL Server Connector?

**Comment by gunnarmorling** [comment]
Any news here?

**Comment by gunnarmorling** [comment]
@mdrillin, @rk3rn3r, where are we with this one? What's missing to wrap this one up?

**Comment by mdrillin** [comment]
@rk3rn3r when I did the original work, the fields in the super classes were taken into account.  Sorry for not following up with you on this one

**Comment by rk3rn3r** [comment]
Thx a lot @mdrillin.

**Pull request merged**
