### PR TITLE
DBZ-6479 Add missing privileges as per MySQL 8.0.x

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-6479

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha Applied, thanks

**Comment by jpechane** [comment]
Could you please provide an upstream PR? Thanks

**Comment by ani-sha** [comment]
@jpechane The privilege is already present in the upstream antlr grammar.

**Comment by ani-sha** [comment]
Upstream PR - https://github.com/antlr/grammars-v4/pull/3470

**Pull request merged**
