### PR TITLE
DBZ-3095 Propagating socket exceptions

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-3095

@jpechane, this fixes the issue for me locally. It's not quite clear to me why we only see this with 15, but the situation is that the BLC reader thread doesn't propagate the "socket closed" exceptions, remaining in a busy loop trying to read from the log. That's why the change event source thread fails to obtain the lock to disconnect. This happens for multiple tests during the suite, with each BLC reader thread keeping one core busy 100%.

While I'd love to exactly understand why this is happening, I think the fix is sound and can be merged if tests pass on CI, too.

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling Now it is my turn to say it, could you please add a comment to the code to explain it :-)

**Comment by gunnarmorling** [comment]
@jpechane :)

So in that event handler we catch `EventDataDeserializationException`, which may have an `IOException` as a cause, indicating the socket connection was closed. We don't propagate that exception, so the reader keeps running, hitting the closed socket again and again. By propagating the `IOException`, the reader gets properly stopped, abandoning this infinite loop. I don't understand why this doesn't happen with older JDKs, though. Is this where you're looking for an explanation?

**Comment by jpechane** [comment]
@gunnarmorling Thanks, but I'd rather see the explananiton in the code :-)
As it is just a matter of time till those lines will get optimized away :-)

**Comment by gunnarmorling** [comment]
@jpechane, ok, fair point :) Added. I'll also log an issue with the binlog client, I believe there might be some action required there too.

**Comment by gunnarmorling** [comment]
Logged https://github.com/osheroff/mysql-binlog-connector-java/issues/32 upstream.

**Comment by jpechane** [comment]
@gunnarmorling Applied, thanks

**Pull request merged**
