### PR TITLE
Add Quarkus json logging extension

### PR DESCRIPTION
**Pull request by cburch824**
Related jira issue:
https://issues.redhat.com/browse/DBZ-4114

### CODE REVIEW

**Comment by cburch824** [comment]
Simple change overall. It's worth noting that with this extension the logs are JSON formatted by default.

If that's a concern, it can be overridden with the config `quarkus.log.console.json=false`, but I'm unsure where that could be set in the codebase

**Comment by gunnarmorling** [comment]
I think it's fine to change the format to JSON by default, as long as users can set it back. We'll only have to call out the changed default behavior in the release notes. @jpechane, any objections?

**Comment by jpechane** [comment]
Well, I think the default JSON logging can be a little bit annoying, So I propose

* Mention the JSON logging in the docs - and how it can be enabled/disabled
* Add to release notes as proposed
* Add the line that disbales it to `debezium-server/debezium-server-dist/src/main/resources/distro/conf/application.properties.example`

So the new users will have it disabled by default if they start from the example and the old users will be warned and informed how to switch it off.

**Comment by jpechane** [comment]
@gunnarmorling But how would you achieve?
> Then I'd say let's disable JSON based logging by default, avoiding any migration concern

**Comment by cburch824** [comment]
@gunnarmorling @jpechane
Thanks for the clear direction. I think I have this PR at a point where it:
1. Adds the extension
2. Documents the change and how to disable it
3. Disables it in the example file

As for the release notes, is that something I change in my branch? Or is that done on release?

**Comment by gunnarmorling** [comment]
> As for the release notes, is that something I change in my branch? Or is that done on release?

If you have some good wording in mind, could you add it as a comment to the Jira issue. The issue is labeled accordingly, the migration notes are sourced (manually) from all these labeled issues. Thanks!

**Pull request merged**
