### PR TITLE
 DBZ-649 Support for heterogenous arrays

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-649

This PR provides the following functionality
1) Before it encodes arrays it checks whether all elements are of the same type
2) If all elements are of type document it makes a union of all fields of all elements to create the schema valid for all elements. It also checks that the fields of elements do not change types accross elements
3) Introduces a new array encoding that encodes array as struct as is case for BSON - see array in document http://bsonspec.org/spec.html Such encoding is able to handle arbitrary array values.

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling The test is fixed - the schema struct should be optional. Regarding schema assertion - I just expanded what was already present. We can extract the schema assetion code from postgres module and make it shared.
Regarding the removing Envelope suffix, the explanations is here https://github.com/debezium/debezium/pull/505
 > Because we are ripping out part of Envelope - so I think it make sense to name the schema after the collection only.

**Comment by gunnarmorling** [comment]
@jpechane, having some trouble when testing DBZ-649 with Avro:

```
org.apache.avro.SchemaParseException: Illegal initial character: 0
    at org.apache.avro.Schema.validateName(Schema.java:1147)
```

I.e. we'd have to name those indexing fields differently.

**Comment by gunnarmorling** [comment]
@jpechane Any update on this one?

**Comment by jpechane** [comment]
@gunnarmorling According to Avro spec `_<number>` seems to be vali field name so I am prefixing the indices with underscore.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks, @jpechane! IIUC, you said you're working on a doc PR already, right?

Btw. in the course of testing, I ran into one more related issue: [DBZ-710](https://issues.jboss.org/browse/DBZ-710).

**Pull request closed without merging**
