### PR TITLE
DBZ-6908 Print password as stars

### PR DESCRIPTION
**Pull request by eizners**

### CODE REVIEW

**Comment by Naros** [comment]
Hi @eizners is the issue key the right key?  The description doesn't seem to align with the issue report in Jira is why I ask.

**Comment by jpechane** [comment]
I suppose it is for https://issues.redhat.com/projects/DBZ/issues/DBZ-6908

Why is it still draft?

**Comment by eizners** [comment]
The issue is that it prints the password in a clear text. Now it is masked.

**Comment by eizners** [comment]
Apologies. It is a typo. Changed the number now.

**Comment by jpechane** [comment]
@eizners Applied, thanks

**Pull request merged**
