### PR TITLE
DBZ-7831 Fix oracle connector failed to work when the table name contains single quote

### PR DESCRIPTION
**Pull request by leoloel**
https://issues.redhat.com/projects/DBZ/issues/DBZ-7831

### CODE REVIEW

**Comment by leoloel** [comment]
https://issues.redhat.com/projects/DBZ/issues/DBZ-7831?filter=allissues

**Comment by Naros** [comment]
Great catch @leoloel, can you confirm whether you checked if the following 3 methods were affected too in the OracleConenction class: `isTableExists`, `getRowCount`, and `reselectColumns`.

**Comment by Naros** [comment]
HI @leoloel can you please remove the merge commit.

**Comment by Naros** [comment]
I'm sorry @leoloel, could you rebase the work to resolve the conflicts, thanks.

**Pull request closed without merging**
