### PR TITLE
DBZ-501 Avoid race condition in stop of thread executor and task subm…

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-501

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane LGTM and we can do it that way. What about this though: Making `start()` and `stop()` both synchronized and have a check for `isShutdown()` as the first thing in `start()`. It'd avoid even more work to be done in this case, e.g. we'd not do the schema refresh. WDYT?

**Comment by jchipmunk** [comment]
Can you add test for this case? It can be a sequence of `stop()` and `start()` method calls.

**Comment by jpechane** [comment]
Good idea, bot changes included, thanks!

**Comment by gunnarmorling** [comment]
Applied, thanks @jpechane and @jchipmunk for reviewing!

**Pull request merged**
