### PR TITLE
Docs mysql connector modularization

### PR DESCRIPTION
**Pull request by fbolton**
This is a replica of Alex's original documentation PR, but with merge conflicts resolved.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@fbolton, @alex-hat-de-rojo, I'm seeing lots of warnings like this when building this:

    asciidoctor: WARNING: skipping reference to missing attribute: context
    asciidoctor: WARNING: skipping reference to missing attribute: prodname

Where should those be defined?

**Comment by gunnarmorling** [comment]
The previous _connectors/mysql.html_ URL is broken, this should still be working. I think the new mysql-intro.html should be renamed to mysql.html.

**Comment by gunnarmorling** [comment]
Another comment on the URL structure; e.g. I see this now:

    assemblies/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.html

That's a mouth-ful. Can this rather be something like this:

    connectors/mysql/how-it-works.html

**Comment by gunnarmorling** [comment]
The formatting for the "Delete change event value" listing is different than other JSON ones.

**Comment by gunnarmorling** [comment]
So I like the new structure overall, also the menu structure on the left makes sense to me. On the particular labels, I'm a bit torn on the usage of "it", and also we've used title casing in menu captions so far. So I'd suggest this:

* How It Works
* Set-up
* Deployment
* Common Issues

**Comment by gunnarmorling** [comment]
Instead of the intra-page ToC at the top we've moved to a sticky one on the right side for many pages. E.g. see configuration/outbox-event-router.asciidoc for an example. Would be nice to use the same for the MySQL connector page ToCs.

**Comment by gunnarmorling** [comment]
@fbolton, @alex-hat-de-rojo, a few comments inline. Mostly details, overall it looks good. As mentioned before it's hard to impossible to see what actually has changed from the contents PoV, but it looked alright to me by taking a high-level look.

Let me know if any of the comments don't make sense or you need help. Let's get this one merged quickly, so to avoid conflicts with other changes happening in parallel. Thanks!

**Comment by fbolton** [comment]
> @fbolton, @alex-hat-de-rojo, I'm seeing lots of warnings like this when building this:
> 
> ```
> asciidoctor: WARNING: skipping reference to missing attribute: context
> asciidoctor: WARNING: skipping reference to missing attribute: prodname
> ```
> 
> Where should those be defined?

@gunnarmorling The required attributes are defined in the [_attributes.adoc](https://github.com/fbolton/debezium/blob/DOCS-mysqlConnector-modularization/documentation/modules/ROOT/pages/_attributes.adoc) file. This attributes file gets included by the [connectors/mysql-intro.adoc](https://raw.githubusercontent.com/fbolton/debezium/DOCS-mysqlConnector-modularization/documentation/modules/ROOT/pages/connectors/mysql-intro.adoc) file. So, if you build the `connectors/mysql-intro.adoc` file directly, all of the attributes should be properly resolved. On the other hand, if you build a single assembly or module file on it's own, those attributes remain unresolved, because those files do not include the attributes file (this is by design - the attributes file is only included by the file at the top of the include chain, so that it can easily be replaced or changed as needed).

Mind you, I just realized there is one attribute that does *not* get defined in that file. The `context` attribute should actually be defined in the `connector/mysql-intro.adoc` file itself, so I will need to add it there.

**Comment by fbolton** [comment]
> The previous _connectors/mysql.html_ URL is broken, this should still be working. I think the new mysql-intro.html should be renamed to mysql.html.

@gunnarmorling Yes, I don't see any compelling reason why the file needs to be called `mysql-intro.adoc`. I will change it back to `mysql.adoc`.

**Comment by fbolton** [comment]
> Another comment on the URL structure; e.g. I see this now:
> 
> ```
> assemblies/cdc-mysql-connector/as_overview-of-how-the-mysql-connector-works.html
> ```
> 
> That's a mouth-ful. Can this rather be something like this:
> 
> ```
> connectors/mysql/how-it-works.html
> ```

Yes, it is a bit of a mouthful. An even simpler approach would to use anchor IDs for the cross-reference links. Then you can define links like `xref:ANCHOR_ID[]` or even `<<ANCHOR_ID>>` (effectively the same thing in AsciiDoc). I'll see if I can clean these up - unfortunately, there are quite a few of those links to fix :-/.

**Comment by fbolton** [comment]
> The formatting for the "Delete change event value" listing is different than other JSON ones.

Ah, right, yes, it's missing the `[source,json]` formatting. I'll fix that.

**Comment by fbolton** [comment]
> So I like the new structure overall, also the menu structure on the left makes sense to me. On the particular labels, I'm a bit torn on the usage of "it", and also we've used title casing in menu captions so far. So I'd suggest this:
> 
>     * How It Works
> 
>     * Set-up
> 
>     * Deployment
> 
>     * Common Issues

Yes, will do.

**Comment by fbolton** [comment]
> Instead of the intra-page ToC at the top we've moved to a sticky one on the right side for many pages. E.g. see configuration/outbox-event-router.asciidoc for an example. Would be nice to use the same for the MySQL connector page ToCs.

I'm not sure exactly what's required here and there might be some issues of compatibility between the upstream and downstream ways of doing things. So I don't think this question can be resolved quickly.

**Comment by Naros** [comment]
> I'm not sure exactly what's required here and there might be some issues of compatibility between the upstream and downstream ways of doing things. So I don't think this question can be resolved quickly.

Hi @fbolton.

The sticky sidebar that @gunnarmorling described is driven by `toc::[]`.  It seems the upstream way is to use `xref` links and those are simply rendered as a list of HTML anchor links with no form of indicator that we could likely base our sidebar logic upon.

As a small test I did modify the assembly file by adding this at the top:
```
:toc:
:toclevels: 1
:toc-placement: macro
```
And then where you had the `xref` list I simply replaced that with `toc::[]`.  This triggers the rendering of our sidebar logic just fine but as you indicated, this will cause a slight difference in rendering for upstream docs unfortunately.

**Comment by Naros** [comment]
Actually I may have spoken a bit too quickly, looking at all the assemblies the `xref` contents indeed follows a similar pattern of being defined inside `doc > preamble > sectionbody > ulist`.  It might be possible to trigger the custom ToC rendering off this style path as well.  Want me to try @gunnarmorling ?

**Comment by gunnarmorling** [comment]
Yes, that'd be great, @Naros. I'd only suggest to wait a little bit until the dust has settled and @fbolton isn't planning to add any more commits to this PR. Once that's done, you can easily add your change on top of this. We should have the consistent ToC style across all pages.

**Comment by gunnarmorling** [comment]
@fbolton, @Naros, where are we with this one? It needs a rebase for sure, and Chris, you wanted to add some more things as per your last comment above?

**Comment by fbolton** [comment]
@gunnarmorling @Naros I'll do the rebasing today and I will also remove the manual mini-TOCs defined with xrefs (these are not actually required for downstream docs).

**Comment by fbolton** [comment]
Note that some of the changes to `mysql.adoc` ( from 46b87526f6a162ba19c7c9697793fb06620385d6 and cdb16bfa2f3ee378c7d9734f3e847c88a3f26bed) inevitable got lost in this rebase. We will need to revisit those changes after the merge.

**Comment by fbolton** [comment]
Actually, there are no instances of `https://issues.jboss.org` left in this MySQL documentation, so we do not need to worry about 46b87526f6a162ba19c7c9697793fb06620385d6. And cdb16bfa2f3ee378c7d9734f3e847c88a3f26bed is something we probably need to revisit anyway, because rendering of tables in the product docs is very different from the community docs and we probably need to find a way of formatting that is compatible with both.

**Comment by fbolton** [comment]
@Naros I tried out the `toc::[]` macro (as you describe in your comment above) in our product documentation build system and discovered that the effect is completely benign. Our build system just ignores and builds without error.

Therefore, I just added the toc macro to each of the assembly files. This should work fine for the community docs, while not causing any problems for the product docs.

**Comment by fbolton** [comment]
@gunnarmorling @Naros Can we merge this PR now? It's done from my perspective.

**Comment by fbolton** [comment]
@gunnarmorling @Naros 
*Report on latest merge conflict resolution*
Since the last rebase of this PR, there were three commits made to `master` that affect the `documentation` subdirectory: c0dd096e1380b38a44dc307019d9ce65716120de, 7c079ca5e5eba749bf0694f1b20c7c2ce834fae5, and eb4b1dad453a0c60df2c16b05eff7305599438fe. Of these three commits, only the first one, c0dd096e1380b38a44dc307019d9ce65716120de, made a change directly to a file that conflicts with the updates made in this PR. The conflicted file was `_attributes.adoc`. But this conflict seems to have been resolved automatically during the rebase. I checked the current contents of the file in this PR against the changes made in c0dd096e1380b38a44dc307019d9ce65716120de and those change were correctly incorporated into the file. So I believe we now have a clean PR, which is consistent with the latest doc updates on `master`.

**Comment by Naros** [comment]
Thanks for all the work @fbolton and team, I'll start given this one last look over and merge when I'm done.  I'll follow-up after that with a PR to address the table "width" and style-sheet naming convention concerns.

**Comment by gunnarmorling** [comment]
> Thanks for all the work @fbolton and team, I'll start given this one last look over and merge when I'm done. I'll follow-up after that with a PR to address the table width and style-sheet naming convention concerns.

+1 If it renders nicely, let's merge it. Thanks a lot, @fbolton and crew!

**Comment by Naros** [comment]
Coming back to the attribute substitutions, I can for now copy the attributes into our playbook files and that addresses the warnings, but there is one substitution that isn't listed in the `_attributes.adoc` file called `{context}`.  This seems to be part of the anchor ids.  Any guidance on what this should be @fbolton on the community side?  For now I've set it as `debezium` to resolve the build warnings.

**Comment by fbolton** [comment]
Ah, yes, the `{context}` attribute can be used to disambiguate anchor IDs in case a file gets multiply included in the same guide. Setting it to `debezium` should be fine.

**Comment by Naros** [comment]
I'll also update the download link version in our playbooks `1.0.0.Final`.

**Comment by Naros** [comment]
Squashed alex's commits together and merged to master.  Thanks again to everyone involved!.

**Comment by fbolton** [comment]
What a relief! Thanks very much, @Naros !

**Comment by gunnarmorling** [comment]
Ha, yeah, indeed! Very happy to have this one in. Thanks for driving this home, @Naros and @fbolton. Nice early Christmas present 🎄 🎁 ☃️ 🚀

**Comment by Naros** [comment]
As a quick follow-up here, I had some dialog with the Antora guys and they actually have incorporated a new feature coming in 2.3 called component attributes.  Essentially rather than defining your attributes globally in the playbook itself you can define them in the `antora.yml` file.

So a question for you @fbolton is whether or not your build system makes use of the component descriptor file `/documentation/antora.yml`?  

I suspect you guys either override or supply your own since this file also controls URL, version, and naming values that would differ downstream than upstream, but wanted to be sure before I decided to tackle this problem using this approach with Antora 2.3.0 when it becomes available.

**Comment by fbolton** [comment]
@Naros No, we don't use the `antora.yml` file at all. In fact, we use a very different build system downstream. But this is absolutely no problem, because as you guessed, we supply our own attributes file which customizes certain attribute values to be different from upstream. In other words, you can go ahead and use the `antora.yml` file, this will not cause any problems for us.

**Pull request closed without merging**
