### PR TITLE
DBZ-6649 Upgrade gRPC to 1.56.1

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-6649

### CODE REVIEW

**Comment by jpechane** [comment]
It is necessary to bump up Vitess gRPC too to keep them compatible.
@HenryCaiHaiying Any objection on that one?

**Comment by HenryCaiHaiying** [comment]
I just tested grpc-1.56.1 jars with vitess connector, they are running fine.

**Comment by HenryCaiHaiying** [comment]
You can move ahead

**Comment by jpechane** [comment]
@HenryCaiHaiying Thanks for confirmation!

**Pull request merged**
