### PR TITLE
DBZ-1970

### PR DESCRIPTION
**Pull request by gunnarmorling**
@jpechane, here's what I came up with; WDYT?

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling I think it looks good and typesafe. Still I don't like `value().value()` calls. How about moving it one step further - https://github.com/debezium/debezium/pull/1471

**Comment by gunnarmorling** [comment]
@jpechane, this is ready for another review round and merge hopefully; I have:

* implemented your suggested change
* updated docs
* moved the `asType()` method from the builder to a separate factory interface, as they shouldn't be callable on the builder interface

**Comment by gunnarmorling** [comment]
Rebased to latest master and force-pushed.

**Comment by jpechane** [comment]
@gunnarmorling Nice wrap-up, thanks!

**Pull request merged**
