### PR TITLE
DBZ-6547 Declare exactly-once semantic support for Postgres connector

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-6547

### CODE REVIEW

**Comment by jpechane** [comment]
@vjuranek Could you please create a new issue for posgres connector and attribute the PR/commit to it? I don't think we'll declare full EoS support in 2.3. Thanks

**Comment by vjuranek** [comment]
sure @jpechane , updated

**Comment by gunnarmorling** [comment]
Hey @vjuranek, @jpechane, out of curiosity: what will happen in terms of EO in case a connector gets restarted while an (initial or incremental) snapshot is running?

**Comment by vjuranek** [comment]
hi @gunnarmorling , this is EOS support only for streaming. If the initial snapshot is not finished successfully, next time it's started again and therefore would result into duplicates. Probably the only way how to ensure EOS for initial snapshot is to run it in one huge transaction, which doesn't seem to be reasonable. On the other hand, for incremental snapshots sending the snapshot chunks in transaction seems to be doable, but the implementation itself is still TBD. See [this Zulip topic](https://debezium.zulipchat.com/#narrow/stream/302533-dev/topic/exactly.20once.20semantics) for more details. Any suggestions/ideas are welcome!

**Comment by jpechane** [comment]
@vjuranek Applied, thanks for the investigation.

**Pull request merged**
