### PR TITLE
DBZ-395 Temporary table statements are skipped

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-395

### CODE REVIEW

**Comment by pgoranss** [comment]
I don't believe these changes will prevent the DROP TEMPORARY TABLE statements from getting into the dbhistory topic in the first place. That the defect... DROP TEMPORARY TABLE statements are spamming the dbhistory topic.

I believe these needs to be ignored within BinlogReader.handleQueryEvent, before the DDL is applied and dispatched to the dbhistory topic. There are some other ignore examples in there.

**Comment by rhauch** [comment]
@pgoranss, yes you are correct that this change will not affect what is recorded in the database history. The challenge is that right now the `handleQueryEvent` is either passing *all* or *none* of the DDL statements found in the query event. We can't just look for `CREATE TEMPORARY` because it's possible that the query event contains multiple statements, and we might want to ignore only *some* of those statements.

I can't easily think of a way of doing this. Really, we want to somehow parse the DDL into separate statements, and then filter out a subset of those statements before recording them in the database history. But we don't want to parse the DDL and regenerate from our incomplete parsed model, since we'll lose information. The only way I can think of to do this is to have the DDL parser take a function it can call with each non-skipped statement, but this seems risky and complex since we currently skip statements in DDL that we don't need to parse, and this is different than statements that we don't want to record in the database history.

**Comment by gunnarmorling** [comment]
> because it's possible that the query event contains multiple statements

@rhauch, in which case would the event contain multiple statements? We may start simple and simply ignore `CREATE/DROP TEMPORARY` if it is a single statement and let others pass. This should be easy enough and will improve the situation.

**Comment by jpechane** [comment]
Or what if we allow the user set a regex via configuration that when set and matches then we skip writing the [history]?(https://github.com/debezium/debezium/blob/003d8387ecf9cc46a8dfc3f5e9a71198b393a01e/debezium-connector-mysql/src/main/java/io/debezium/connector/mysql/MySqlSchema.java#L393)

**Comment by gunnarmorling** [comment]
I'm not a big fan of adding this sort of config options - the less knobs and buttons, the better.

**Comment by pgoranss** [comment]
@rhauch Hm ok, I wasn't aware query events could contain multiple DDL. In any case, this PR doesn't address the underlying issue in DBZ-395, agreed? (re: my comment added to the ticket)

**Comment by rhauch** [comment]
Agreed. Just ignoring temp table statements in the DDL parser doesn't help
with DBZ-395.

**Comment by gunnarmorling** [comment]
> Just ignoring temp table statements in the DDL parser doesn't help

+1

@rhauch, what about my suggestion though to limit the fix to ignore `CREATE/DROP TEMPORARY TABLE` in the binlog event handler when it detects it is a single statement? That should be implemented easily enough and would the OP and probably most other cases. We could leave the multiple statement case for another time.

This assumes it's easy to spot single statements without fully parsing them. Also, do you know when we'd receive an event with multiple statements? Do you have an example perhaps?

**Comment by jpechane** [comment]
Replaced wih https://github.com/debezium/debezium/pull/314

**Pull request closed without merging**
