### PR TITLE
DBZ-4243 select only columns that are captured by CDC during incremental snapshot

### PR DESCRIPTION
**Pull request by dude0001**
https://issues.redhat.com/browse/DBZ-4243

### CODE REVIEW

**Comment by dude0001** [comment]
I really don't love the existing unit tests but tried to change them as least as possible. I would like to create an integration test with SQL Server for this using the reproduction steps I added to the issue, but I could use some direction for that. If there are existing integration tests that test signal table-based incremental snapshots w/ CDC configured to not capture all columns on the table, I am missing them.

**Comment by Naros** [comment]
Hi @dude0001 the integration tests for each connector are based on `AbstractIncrementalSnapshotTest`.  Each connector has their own integration test that extends this base implementation so that we write the tests once and reuse across all connectors.  

Also I would suggest trying to leverage the column selection logic from some work we did previously for snapshots, see:
`RelationalSnapshotChangeEventSource#getPreparedColumnNames`.  

I think we should try and reuse that somehow so we prepare snapshots column selections in one place.

**Comment by dude0001** [comment]
Oh derp, I was looking under the pipeline namespace not sure how I overlooked that. I will give the tests a swing and look at commonizing the column selection logic, I love that idea.

**Comment by jpechane** [comment]
@dude0001 Thanks a lot, I just want to let you know the PR needs rebasing due to merge of message key columns PR.

**Comment by gunnarmorling** [comment]
> Also I would suggest trying to leverage the column selection logic from some work we did previously for snapshots, see:
> RelationalSnapshotChangeEventSource#getPreparedColumnNames.

Yes, great point! Not sure what'd be the best way for doing so, given incremental snapshot impl and the traditional one don't share a class hierarchy (somewhat surprisingly). We might either change that, or extract that logic into some `SnapshotSelectPreparer` class. Probably the latter?

**Comment by dude0001** [comment]
@jpechane @Naros I totally agree with the sentiment that there should be shared logic for generating snapshot querries and the select columns. It would help with the consistentency of the product. The purpose of this PR is to fix a specific defect in the existing implementation. Getting this in the product would help us continue to develop our solution and test in Debezium with a CDC environment that does not capture all columns and get more feedback to the project. What are your thoughts on addressing the refactor in a seperate issue & PR, and keeping this PR a pure bug fix of the existing implementation?

I truely love the idea. Unless I am missing something, the column selection logic currently in `RelationalSnapshotChangeEventSource` doesn't seem available in `AbstractIncrementalSnapshotChangeEventSource`. It seems like the logic would need refactored out into it's own class that both inherit from or is injected some other way. I'd love to maybe help tackle, but it doesn't seem like a small change or something I could tackle very soon with my level of knowledge of this repo at this point.

Also @jpechane, it is my pleasure. The PR is a very small change, but is fun and rewarding for me to contribute back to a great community that has helped me a lot. Thank you for the heads up on the rebase.

**Comment by gunnarmorling** [comment]
Ha, seems we cross-posted, @dude0001! Do you think that refactoring would be that large actually? Extracting that logic into a separate class you could use then in both snapshotters shouldn't be too much hassle? Perhaps you could give it a try and see how it goes? The reason I'm pushing somewhat for it is that these temporary fixes tend to stay in place longer than anticipated, hence I'd prefer to to have the "right" fix early on.

**Comment by dude0001** [comment]
I'm a .NET developer by profession and a little green on Java, and my Java environment isn't working complete to run all the tests, etc. So it might be a little challenging for me at the moment. Definitely something I could tackle in .NET, what you are saying makes great sense. I can tackle it in this project eventually with a little learning, just not sure I can get it done real quickly with my other responsibilities. Let me see how much progress I can make. Thank you for the great feedback, let me see what I can do.

**Comment by gunnarmorling** [comment]
Sounds good, thank you so much!

**Comment by dude0001** [comment]
Rebased and added integration test. I'm still looking at the `RelationalSnapshotChangeEventSource` refactor.

**Comment by dude0001** [comment]
@Naros @gunnarmorling I am looking at the requested `RelationalSnapshotChangeEventSource` refactor more. From what I can tell we wouldn't need to just reuse the logic in `RelationalSnapshotChangeEventSource#getPreparedColumnNames`, but actually `RelationalSnapshotChangeEventSource#determineSnapshotSelect` seems like the entry point. We are then talking about refactoring out the 6 methods below from `RelationalSnapshotChangeEventSource` to support this. It seems like the simpler solution to make another class here, but I feel like inheritance is the problem like @gunnarmorling alluded to, and breaking this out into a class isn't feeling great.

Am I making this too complicated? If you'd still like to pursue this refactor on this PR, could I get another push in the direction you'd like to see this go? Playing around with this is feeling like a verily large additional change to do the refactor.

These are the methods I see in `RelationalSnapshotChangeEventSource` that have logic related to building the `select` for snapshots.

`additionalColumnFilter`
`determineSnapshotSelect`
`enhanceOverriddenSelect`
`getColumnValue`
`getPreparedColumnNames`
`getSnapshotSelect`

**Comment by Naros** [comment]
I haven't looked at all the methods in detail but a few things to note.

A vast majority of the connector implementations are quite similar, particularly MySQL, SQL Server, and Oracle.  The only nuance with Oracle is that the traditional snapshots use flashback queries, aka the `AS OF SCN` clause and this isn't applicable for the incremental snapshots.

So what I would first do is to extract the common code to one helper class and then change the methods in the snapshot source to where we simply delegate to this common code.  There isn't harm in leaving the existing framework-ish methods in place for the sake of simplicity so that some connectors can override that behavior where needed.

The one place I do see where this may look tricky is with the `additionalColumnFilter` method usage but I believe that can easily be remedied by adjusting the `getPreparedColumnNames` method to accept one additional argument that is a functional interface that defines differing behavior between the traditional snapshot and the incremental snapshot so that on the traditional snapshot side you can interact with the `SqlServerChangeTable` instances and whatever else is needed on the incremental side.

**Comment by Naros** [comment]
I haven't looked at all the methods in detail but a few things to note.

A vast majority of the connector implementations are quite similar, particularly MySQL, SQL Server, and Oracle.  The only nuance with Oracle is that the traditional snapshots use flashback queries, aka the `AS OF SCN` clause and this isn't applicable for the incremental snapshots.

So what I would first do is to extract the common code to one helper class and then change the methods in the snapshot source to where we simply delegate to this common code.  There isn't harm in leaving the existing framework-ish methods in place for the sake of simplicity so that some connectors can override that behavior where needed.

The one place I do see where this may look tricky is with the `additionalColumnFilter` method usage but I believe that can easily be remedied by adjusting the `getPreparedColumnNames` method to accept one additional argument that is a functional interface that defines differing behavior between the traditional snapshot and the incremental snapshot so that on the traditional snapshot side you can interact with the `SqlServerChangeTable` instances and whatever else is needed on the incremental side.

**Comment by dude0001** [comment]
`additionalColumnFilter` is where I started to feel like this was getting big. I would refactor that in .NET by passing as a function from each implementation, and found that this is done as with an interface as you said. So sounds like we are on the same page, thank you again for the feedback.

**Comment by gunnarmorling** [comment]
Pushed two more commits (which should be one, will squash those eventually) to this PR for unifying the snapshot select column selection across the initial and incremental snapshot implementations.

@dude0001, @jpechane, feedback welcome. Thanks!

**Comment by Naros** [comment]
@gunnarmorling Pushed a commit to fix the Oracle compilation error.

**Comment by gunnarmorling** [comment]
Thanks, @Naros. Seems my change wasn't that innocent after all, looking at all the failures. Investigating.

**Comment by dude0001** [comment]
You beat me to it, thank you! With your previous guidance, my implementation of the column selector is very similar. I was trying to figure out how to use DI instead of creating a new instance with `new` inside the `ChangeEventSource` classes. That was alluding to me a little with my Java knowledge right now. I thought I was going to need to update the factories. Looks like I was overthinking it from Gunnar's change. However, that also seems to be where the tests are failing now. When the incremental snapshot is created through the factory it doesn't seem to have the new key mapper that works for tables without PK.

You made a couple of changes that weren't anywhere on my radar but they look correct. Thank you!

**Comment by gunnarmorling** [comment]
> When the incremental snapshot is created through the factory it doesn't seem to have the new key mapper that works for tables without PK.

Indeed, just came to the same conclusion, and I think I have a fix handy.

> On another note. I have pulled down Gunnar's changes. If I wanted to rebase my entire branch on upstream master, is that an issue now that others are working on the branch. Do I need to merge instead?

So we general prefer rebases (for the sake of a linear history), which in this case would mean you'd do the rebase and then a force-push to this branch (which then means I need to be careful when pulling your changes as the branches will have diverged). So instead let me close this PR, squash my changes (including the fix for the issue above) and create a new PR in a bit. Ideally, this will then be good-to-go. If there are still remaining problems, let's discuss them over in that follow-up PR. Thanks, @dude0001!

**Comment by gunnarmorling** [comment]
@dude0001, here's the follow-up PR, based on your original commit: https://github.com/debezium/debezium/pull/2944. Feedback welcome. Thanks!

**Pull request closed without merging**
