### PR TITLE
DBZ-4864 pass sink properties

### PR DESCRIPTION
**Pull request by zalmane**
https://issues.redhat.com/browse/DBZ-4864

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Can we add a test in some way?

**Comment by zalmane** [comment]
good idea. I can add a test to the RedisOffset adapter to verify the
mechanism works.

**Comment by gunnarmorling** [comment]
Still planning to add the test here, @zalmane? Quick heads-up, CR1 is due on Friday.

**Comment by zalmane** [comment]
yes. I am adding it. just wanted to rebase it off dbz 4771 so was waiting
for that. will push today.

**Comment by gunnarmorling** [comment]
@zalmane, the history PR has been merged :)

**Comment by zalmane** [comment]
@gunnarmorling @jpechane Pushed updated with integration test. The change itself is one line, but needed to refactor the tests with additional test configuration.

**Review by jpechane — APPROVED** [review]
@zalmane Thanks a lot, the code is ok. COuld you please just a note to the docs about this new feature? Thanks.

**Comment by zalmane** [comment]
actually it is already documented. it just didn't work as intended because
the properties were not sent in.

**Comment by gunnarmorling** [comment]
LGTM, thanks, @zalmane! @jpechane, do you want to merge it?

**Comment by gunnarmorling** [comment]
Applied, thx!

**Pull request merged**
