### PR TITLE
DBZ-8219 Fix JAXB xml parsing of Ehcache configuration

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-8219

### CODE REVIEW

**Comment by Naros** [comment]
Test failures are unrelated.

**Review by jpechane — APPROVED** [review]
@Naros LGTM! In this case I'd recommend to look into the generated plugin and Debezium Server as well to make sure dependencies are OK and test the connector in thos deployments as well.

**Comment by Naros** [comment]
Hi @jpechane so I've tried to align this in Debezium Server, but despite my best efforts, the `jaxb-runtime` is always pulled in as 4.0.4 rather than 2.3.1, despite what's in this PR.  Any idea what I am missing?  I've tried exclusions in quarkus and others with no success.

**Comment by jpechane** [comment]
@Naros Hi, I pushed one more commit and created https://github.com/debezium/debezium-server/pull/122

Please give it a test ride to doble check that now everything is aligned and the connector and cach works. Thanks.

**Pull request merged**
