### PR TITLE
DBZ-6449 Use debezium/kafka image in zk-less mode

### PR DESCRIPTION
**Pull request by ani-sha**

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha What is missing in our image that we cannot use `withKraft` as defined in https://java.testcontainers.org/modules/kafka/ ?

**Comment by ani-sha** [comment]
@jpechane I haven't tried as it was available in 1.18.0 version, and we are using testcontainers version 1.17.6

**Comment by jpechane** [comment]
@ani-sha OK, could you try to upgrade it and use if it is ok?

**Comment by ani-sha** [comment]
@jpechane using `withKraft` won't be possible with our `debezium/kafka` image, as it explicitly checks for confluent's kafka image version.

**Comment by jpechane** [comment]
@ani-sha Applied, thanks for checking.

**Pull request merged**
