### PR TITLE
DBZ-3712 Support start/change archive.log.only.mode gracefully

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3712

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Naros, what's your take -- should this go into 1.7.0.Final and 1.6.3? Or keep it for 1.8?

**Comment by Naros** [comment]
I would prefer to get it into 1.7 and backported if possible.  I pinged @jornargelo on the Jira issue to give this PR a test drive but afaik I haven't heard back yet.  The changes only impact users who enable the opt-in feature so the risk is super low for users who don't use this at all.

**Comment by gunnarmorling** [comment]
Ok, let's get it in then.

**Comment by gunnarmorling** [comment]
@Naros, so I've merged to master, but it doesn't apply cleanly to 1.6. Could you take care of this perhaps?

**Pull request merged**
