### PR TITLE
DBZ-5470: Remove the dependency of JdbcConnection on DatabaseSchema

### PR DESCRIPTION
**Pull request by morozov**
See [DBZ-5470](https://issues.redhat.com/browse/DBZ-5470).

### CODE REVIEW

**Review by Naros — APPROVED** [review]
LGTM, thanks @morozov.  I'm going to let @jpechane give this look over as well when he returns next week and if he's good with it, then we can merge this into `main`.

**Comment by jpechane** [comment]
@morozov Good from my side. Could you please rebase to the latest main so Ithe PR can be merged? Thanks

**Comment by morozov** [comment]
The Debezium UI test failure looks unrelated:
> PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target

**Comment by jpechane** [comment]
@morozov Applied, thanks

**Pull request merged**
