### PR TITLE
[DBZ-646] io.debezium.text.ParsingException for TokuDB table

### PR DESCRIPTION
**Pull request by maver1ck**
Current MySQLParser has problems with TokuDB compression parameter.
This PR solves this issue.

### CODE REVIEW

**Comment by jpechane** [comment]
@maver1ck Thanks for contribution! Could you please add an example of `CREATE TABLE` (and `ALTER` if releavant) DDL statements into `io.debezium.connector.mysql.MySqlDdlParserTest`?

**Comment by maver1ck** [comment]
Done :)

**Comment by jpechane** [comment]
@maver1ck Thanks!
@gunnarmorling LGTM

**Comment by maver1ck** [comment]
Checking build errors.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks, @maver1ck!

**Pull request closed without merging**
