### PR TITLE
DBZ-2558 Fix the Quarkus datasource configuration

### PR DESCRIPTION
**Pull request by gsmet**
Either we will need a new 1.2 version for Quarkus 1.9 (before October 6th) or a new DBZ release in Quarkus but that means some discussions with the Camel Quarkus team.

Having a new 1.2 ASAP would be very nice if it's not too much work for you. That would secure our CI and the release schedule.

/cc @ppalaga @lburgazzoli

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @gsmet, if the target is Oct 6th, we also could go for Debezium 1.3, which should be final by then (planned for end of month). This would save us doing another 1.2 release, which we otherwise hadn't planned really.

**Comment by gsmet** [comment]
Yeah, the issue is that it will need to be in line with the Camel Quarkus version that will be used.

I have no idea what are the plans of the Camel team, that's why I pinged Peter and Luca.

Could you check with them?

**Comment by gsmet** [comment]
See https://github.com/quarkusio/quarkus-platform/pull/126 for now.

**Comment by gunnarmorling** [comment]
Ok, so we'll do another release of Debezium 1.2, 1.2.5.Final, with this fix then. We aim for tomorrow, latest next week, which still will be long before Oct 6th.

**Comment by gunnarmorling** [comment]
Test failure is unrelated, applying.

**Comment by gunnarmorling** [comment]
Applied to master (1.3) and 1.2. Thanks, @gsmet!

**Comment by gunnarmorling** [comment]
Released this via Debezium 1.2.5.Final.

**Pull request merged**
