### PR TITLE
DBZ-2462 avoid divisive language in incubator docs

### PR DESCRIPTION
**Pull request by rk3rn3r**
:warning: Must only be merged AFTER https://github.com/debezium/debezium-incubator/pull/188

Docs PR for incubator connectors (include/exclude lists) https://issues.redhat.com/browse/DBZ-2462

### CODE REVIEW

**Review by gunnarmorling — APPROVED** [review]
LGTM, will merge once the incubator PR is in.

**Comment by gunnarmorling** [comment]
@rk3rn3r, can you actually rebase this one and force-push, fixing the merge conflict and also the compilation error, I suppose. Thx!

**Comment by rk3rn3r** [comment]
@gunnarmorling rebased. unfortunately my IDE removed all unnecessary trailing whitespaces. but it's easy to identify the changes

**Comment by gunnarmorling** [comment]
Thx!

**Pull request merged**
