### PR TITLE
DBZ-1727 Debezium Postgres connector does not apply keepalive lsn

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by jpechane** [comment]
@igabaydulin Applied, thanks!

**Comment by gunnarmorling** [comment]
Thx!

**Comment by igabaydulin** [comment]
I have checked if Postgres shutdowns properly now [GitHub Action](https://github.com/igabaydulin/debezium-postgres-shutdown/runs/427749528) (spoiler: it does!) if anyone is interested.
@gunnarmorling @jpechane thanks!

**Comment by jpechane** [comment]
@igabaydulin Thanks for your contribution! As you seem to be quite familiar with Github Actions, is there any chance you could take a look at https://issues.redhat.com/browse/DBZ-1720 ?

**Comment by igabaydulin** [comment]
@jpechane yes, I can. Where can I find the list of non-core repos? Or maybe there is one specific repo you are interested in the first place?

**Comment by jpechane** [comment]
@igabaydulin Thanks for the offer, the repos in question are

https://github.com/debezium/debezium.github.io
https://github.com/debezium/debezium-incubator
https://github.com/debezium/docker-images
https://github.com/debezium/postgres-decoderbufs

I've ordered them by preference

**Pull request merged**
