### PR TITLE
DBZ-2697 Optimisation on SQLServer connector for skipped.operations

### PR DESCRIPTION
**Pull request by blcksrx**

### CODE REVIEW

**Comment by blcksrx** [comment]
The test ran successfully on my local, tomorrow I will check it

**Comment by blcksrx** [comment]
@gunnarmorling This time only one Faulire and I think it's not related to this PR, I only ran `SQLServerConnectorIT` on my local and it passed successfully, but I'm going to run it for the whole package to check it.

**Comment by blcksrx** [comment]
there just 1 failure different from this failure.

**Comment by gunnarmorling** [comment]
Yeah, this one should be unrelated.

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Rebased and applied. Thx!

**Pull request closed without merging**
