### PR TITLE
DBZ-7193 Unchanged toasted array columns are substituted with placeholder even if  REPLICA IDENTITY == FULL

### PR DESCRIPTION
**Pull request by Prabhu19**
Jira Issue: https://issues.redhat.com/browse/DBZ-7193
Affected Debezium versions > 2.0

### CODE REVIEW

**Comment by jpechane** [comment]
@Prabhu19 Hi, thanks for the PR. The code LGTM on the first look. Could you lease add a test that would verify the fixed behaviour? ideally one that will fail before fixing and passes after.

**Comment by Prabhu19** [comment]
> @Prabhu19 Hi, thanks for the PR. The code LGTM on the first look. Could you lease add a test that would verify the fixed behaviour? ideally one that will fail before fixing and passes after.

@jpechane I added testcases can you please check it once?

**Comment by Prabhu19** [comment]
> > @Prabhu19 Hi, thanks for the PR. The code LGTM on the first look. Could you lease add a test that would verify the fixed behaviour? ideally one that will fail before fixing and passes after.
> 
> @jpechane I added testcases can you please check it once?

I also verified against the current main branch and all the added testcases fail
Screenshot 2023-11-30 at 12 46 55

**Comment by jpechane** [comment]
@Prabhu19 Applied, thanks a lot!

**Pull request merged**
