### PR TITLE
DBZ-1342 Partitioned table is included in snapshot

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1342

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, how comes the test changed without actual main code changes?

**Comment by jpechane** [comment]
@gunnarmorling Because it changed in JDBC driver. JDBC drive has not reproted partiioned tables in metadata, now it does.

**Comment by gunnarmorling** [comment]
But where's the driver version change then?

**Comment by jpechane** [comment]
Few weeks ago

**Comment by gunnarmorling** [comment]
Ok, got it. So the test was failing on CI actually. Merging. Thanks, @jpechane!

**Pull request merged**
