### PR TITLE
DBZ-1127 Synchronize MySQL grammar with upstream grammar.

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1127

Upstream PR https://github.com/antlr/grammars-v4/pull/1410

### CODE REVIEW

**Comment by Naros** [comment]
There are a few nuances I noticed while comparing the upstream grammar with our own that I wanted to point out and get some direction on before we merge this.

1. https://github.com/debezium/debezium/blob/3bef558c0942ad12d347bc92a559f06286dcbc1a/debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4#L379

As illustrated above, you can see that the `indexColumnNames` is part of the `REFERENCES` clause is indicated to be optional, but I didn't see any scenario where that was actually valid.  Even testing statements against MySQL 5.6, 5.7, and 8.0 the index column names were required.  In the upstream repository, they aren't.

2. https://github.com/debezium/debezium/blob/3bef558c0942ad12d347bc92a559f06286dcbc1a/debezium-ddl-parser/src/main/antlr4/io/debezium/ddl/parser/mysql/generated/MySqlParser.g4#L415

In this particular rule, you'll notice we allow `COMPRESSION` to be identified by either a `STRING_LITERAL` or an `ID`; however it would seem the MySQL 8 documentation clearly states the value for this option must be a quoted string-value which `ID` is not.  

I didn't yet make these changes as I wanted to ask first as they were some of the obvious differences I saw between the upstream grammar and our own that stood out.  

@gunnarmorling @jpechane , either of you have any opinion to how I should address these?  Obviously you both may have ran across some unique scenario in our usage where these may be needed that just isn't obvious by comparing the upstream grammar, the grammar documentation for MySQL, and then actually executing these statements in the MySQL client.

**Comment by jpechane** [comment]
@Naros Hi, think think the best way forward now is to go and try to run the potentially invalid statments via MySQL. I've seen more then once statements that were not acceptable according to MySQL docs to be accpeted and processed by the server. So I'd say, if they are rejected by the server then let's don't support them. If they are accepted then let's make upstream grammar changed.

**Comment by gunnarmorling** [comment]
@Naros, where are we with this one? Are more changes required in your opinion?

> In the upstream repository, they aren't specified as optional.

Would be interesting to see when the two diverged. Perhaps that got changed upstream after we copied the file? If so, we should do the same in our version.

>  however it would seem the MySQL 8 documentation clearly states the value for this option must be a quoted string-value which ID is not.

No strong preference on that one, apart from aiming for consistency with upstream.

In general, it's no problem if the grammar is more lenient than what's described in the MySQL docs. Keep in mind we "only" need it to obtain the table structures, we're not in the business of validating the user's queries. In contrast, we must not be stricter than what MySQL allows as we'd reject events considered valid by the database.

**Comment by Naros** [comment]
@gunnarmorling 

> Would be interesting to see when the two diverged. Perhaps that got changed upstream after we copied the file?

I checked the `referenceDefinition` rule and at no point has the upstream specified `indexColumnNames` to be optional.  We actually accepted the change here, https://github.com/debezium/debezium/commit/07212043b5a3352b096552edb54a2aa1b06ad415#diff-78b0c2a3c7c8cc0c5e6be38453757731R376.  

> No strong preference on that one, apart from aiming for consistency with upstream.
> In general, it's no problem if the grammar is more lenient than what's described in the MySQL docs. 

Perhaps with the `COMPRESSION` table option rule, we err on the side of leniency?  I did find a few places across the net where the table option wasn't single-quoted like the docs indicate.   I'll include the lenient rule upstream and let those guys decide for now I guess.

**Comment by gunnarmorling** [comment]
> We actually accepted the change here...

Ok, so if `indexColumnNames` is mandated by the MySQL parser (i.e. in the CLI), then we should do the same in our grammar, bringing it on par with the upstream Antlr one.

> Perhaps with the COMPRESSION table option rule, we err on the side of leniency?

The deciding question is whether the MySQL parser allows the unquoted form (ID) or not. If it does, we must not reject it. As you say, staying on the lenient side won't do harm.

So it seems making `indexColumnNames` non-optional is the last thing to do for this PR?

**Comment by Naros** [comment]
> So it seems making indexColumnNames non-optional is the last thing to do for this PR?

That's correct, I'm making that change locally and running the tests to verify that it doesn't introduce a regression and will push in a few; then this should be good to go.

**Comment by gunnarmorling** [comment]
Ok, great! One off the list :)

**Pull request merged**
