### PR TITLE
DBZ-1211 Add test case

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1211

@jpechane Created the PR as requested.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM; @jpechane? Is this behavior of using the (first?) unique key as a Kafka message already described as such in the docs, @Naros, or do docs still need updating?

**Review by gunnarmorling — APPROVED** [review]

**Comment by Naros** [comment]
@gunnarmorling It looks like its already described under the "Change event keys" section in the Oracle documentation which states the following:
```
For a given table, the change event's key will have a structure that contains a field for each column in the primary key (or unique key constraint) of the table at the time the event was created.
```

**Comment by gunnarmorling** [comment]
Ok, cool!

**Comment by Naros** [comment]
Added extra assertions as requested by @jpechane in Gitter chat.

**Comment by jpechane** [comment]
@Naros The formatting issue is fixed in https://github.com/debezium/debezium/pull/2505

**Comment by Naros** [comment]
Thanks @jpechane I guess I missed formatting somewhere along the way in another commit.  My apologies.

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Pull request merged**
