### PR TITLE
DBZ-5045 Use correct buffer type value after deprecated `infinispan` …

### PR DESCRIPTION
**Pull request by vjuranek**
…was removed

### CODE REVIEW

**Comment by Naros** [comment]
That's a nice catch @vjuranek, sorry I missed that when we added the new remote flavor.

**Comment by vjuranek** [comment]
No problem @Naros , but we may think about adjusting CI workflows to spot this issue before the merge (I noticed that the tests in `main` fail after the merge by chance). We run different workflows for PRs and different after merge, so CI under the PR was green while it actually caused the failure.

**Comment by jpechane** [comment]
@vjuranek Unfortunately we can't as the image is not public, we need to use secrets and secrets are not allowed on PRs

**Comment by vjuranek** [comment]
Thanks for explanation @jpechane , I thought that there would be probably the reason why they are different but this doesn't come to my mind.

**Pull request merged**
