### PR TITLE
DBZ-1311 Adding method to read structure for each captured tables

### PR DESCRIPTION
**Pull request by jchipmunk**
https://issues.jboss.org/browse/DBZ-1311

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jchipmunk, I definitely see how it speeds up your use case with a single captured table. I'm wondering though how things will behave if capturing more tables, say 1,000 out of those 5K you have? I'm concerned that fetching each single table metadata separately might be a problem them. Which again makes me wonder why the current call is that slow, it's not that the metadata of 5K tables would be a huge amount of data.

**Comment by gunnarmorling** [comment]
Perhaps we should resort to a custom implementation of metadata retrieval, just fetching the things we need? [This SO](https://stackoverflow.com/questions/8792890/jdbc-with-spring-slow-metadata-fetch-oracle) answer (and linked one) has some good info on this. Biggest caveat is that the internal structure of the metadata tables changes across versions; but I think if there's a substantial perf improvement in doing that, we should give it a try. Similar things are done for PG already.

**Comment by gunnarmorling** [comment]
Ah, and one more thought: are all your 5K tables in the same schema? If not, we might do the same "trick" as for SQL Server (see the corresponding class) and only retrieve the metadata for whitelisted schema. Not ideal, but might help to improve things a bit.

**Comment by gunnarmorling** [comment]
Hey @jchipmunk, any thoughts on ^?

**Comment by jchipmunk** [comment]
> Ah, and one more thought: are all your 5K tables in the same schema? If not, we might do the same "trick" as for SQL Server (see the corresponding class) and only retrieve the metadata for whitelisted schema. Not ideal, but might help to improve things a bit.

My tables have the same schema. 

> Perhaps we should resort to a custom implementation of metadata retrieval, just fetching the things we need? [This SO](https://stackoverflow.com/questions/8792890/jdbc-with-spring-slow-metadata-fetch-oracle) answer (and linked one) has some good info on this. Biggest caveat is that the internal structure of the metadata tables changes across versions; but I think if there's a substantial perf improvement in doing that, we should give it a try. Similar things are done for PG already.

Thank you, I will look towards the custom implementationof metadata retrieval in Oracle connector. This PR can be closed.

**Comment by gunnarmorling** [comment]
Going to close this PR as discussed. Thanks for your efforts, @jchipmunk, and looking forward to the alternative implementation in the Oracle connector.

**Pull request closed without merging**
