### PR TITLE
DBZ-7906 Enhancing the threads utility class for broader use

### PR DESCRIPTION
**Pull request by anupriya-singhal**
This PR is to back port the changes which were done in main branch and has been merged.
We are using 2.5.0.Final for our use case, so we need same fix to be there in 2.5 branch as well. Please help in getting it reviewed as soon as possible, as one of our production issue is dependent on it.
https://github.com/debezium/debezium/pull/5584

### CODE REVIEW

**Comment by anupriya-singhal** [comment]
> linked to your GitHub account

Thanks @jpechane for responding.
Can you please clarify is there a way by which we can get a custom release for 2.5.x having these changes? Or we can ourself follow any reference document to get a newer release of 2.5 or we have to create a custom build on our local only?

Also, I have done github config for email account and user name aptly. Still I am getting comment to authorise my commits, can you please highlight what I am missing here?

**Comment by jpechane** [comment]
@anupriya-singhal There are two commits in this PR - one with correct author and one without.

WRT the build - it is just plain Maven process. So you'll execute - https://github.com/debezium/debezium/blob/main/RELEASING.md#update-versions-and-tag to get properly updated version you'll want to use and it will build the core repo. This you'll do for non-core connector and server repositories too.

**Comment by Naros** [comment]
Hi @anupriya-singhal, given Jiri's comments earlier with 2.5 builds, is it okay to close this PR ?

**Comment by jpechane** [comment]
Closing as we don't intend to backport this to 2.5.

**Pull request closed without merging**
