### PR TITLE
DBZ-2880 Add dependency on org.apache.pulsar:pulsar-io-debezium-core …

### PR DESCRIPTION
**Pull request by fransguelinckx**
https://issues.redhat.com/browse/DBZ-2880

### CODE REVIEW

**Comment by jpechane** [comment]
@fransguelinckx Hi, thanks for the contribution! Could you please jsut compare the distro before and after change so we can verify what dependencies were pulled in?

**Comment by fransguelinckx** [comment]
Sure.

<details>
  <summary>
    Before
  </summary>
  activation-1.1.1.jar
animal-sniffer-annotations-1.14.jar
annotations-2.13.75.jar
annotations-4.1.1.4.jar
antlr4-runtime-4.7.2.jar
apache-client-2.13.75.jar
api-common-1.9.0.jar
arc-1.7.1.Final.jar
asyncutil-0.1.0.jar
auth-2.13.75.jar
auto-value-annotations-1.7.jar
aws-cbor-protocol-2.13.75.jar
aws-core-2.13.75.jar
aws-json-protocol-2.13.75.jar
azure-core-1.5.1.jar
azure-core-amqp-1.2.0.jar
azure-messaging-eventhubs-5.1.1.jar
bouncy-castle-bc-shaded-2.5.2.jar
bson-4.1.0.jar
checker-qual-2.5.2.jar
commons-codec-1.14.jar
connect-api-2.6.0.jar
connect-json-2.6.0.jar
connect-runtime-2.6.0.jar
connect-transforms-2.6.0.jar
conscrypt-openjdk-uber-2.2.1.jar
debezium-api-1.4.0-SNAPSHOT.jar
debezium-connector-mongodb-1.4.0-SNAPSHOT.jar
debezium-connector-mysql-1.4.0-SNAPSHOT.jar
debezium-connector-postgres-1.4.0-SNAPSHOT.jar
debezium-connector-sqlserver-1.4.0-SNAPSHOT.jar
debezium-core-1.4.0-SNAPSHOT.jar
debezium-ddl-parser-1.4.0-SNAPSHOT.jar
debezium-embedded-1.4.0-SNAPSHOT.jar
debezium-server-core-1.4.0-SNAPSHOT.jar
debezium-server-eventhubs-1.4.0-SNAPSHOT.jar
debezium-server-kinesis-1.4.0-SNAPSHOT.jar
debezium-server-pubsub-1.4.0-SNAPSHOT.jar
debezium-server-pulsar-1.4.0-SNAPSHOT.jar
error_prone_annotations-2.2.0.jar
eventstream-1.0.1.jar
failureaccess-1.0.1.jar
gax-1.56.0.jar
gax-grpc-1.56.0.jar
google-auth-library-credentials-0.20.0.jar
google-auth-library-oauth2-http-0.20.0.jar
google-cloud-core-1.93.4.jar
google-cloud-pubsub-1.104.1.jar
google-http-client-1.34.0.jar
google-http-client-jackson2-1.34.2.jar
graal-sdk-20.1.0.jar
grpc-alts-1.30.2.jar
grpc-api-1.30.2.jar
grpc-auth-1.30.2.jar
grpc-context-1.30.2.jar
grpc-core-1.30.2.jar
grpc-grpclb-1.30.2.jar
grpc-netty-shaded-1.30.2.jar
grpc-protobuf-1.30.2.jar
grpc-protobuf-lite-1.30.2.jar
grpc-stub-1.30.2.jar
gson-2.8.6.jar
guava-27.0.1-jre.jar
http-client-spi-2.13.75.jar
httpclient-4.5.12.jar
httpcore-4.4.13.jar
j2objc-annotations-1.1.jar
jackson-annotations-2.11.2.jar
jackson-core-2.10.2.jar
jackson-databind-2.10.2.jar
jackson-dataformat-cbor-2.11.2.jar
jackson-dataformat-xml-2.11.2.jar
jackson-datatype-jdk8-2.11.2.jar
jackson-datatype-jsr310-2.10.2.jar
jackson-jaxrs-base-2.11.2.jar
jackson-jaxrs-json-provider-2.11.2.jar
jackson-module-jaxb-annotations-2.11.2.jar
jakarta.activation-1.2.1.jar
jakarta.activation-api-1.2.1.jar
jakarta.annotation-api-1.3.5.jar
jakarta.el-api-3.0.3.jar
jakarta.enterprise.cdi-api-2.0.2.jar
jakarta.inject-api-1.0.jar
jakarta.interceptor-api-1.2.5.jar
jakarta.json-1.1.6.jar
jakarta.transaction-api-1.3.3.jar
jakarta.validation-api-2.0.2.jar
jakarta.xml.bind-api-2.3.2.jar
javassist-3.26.0-GA.jar
javax.activation-1.2.0.jar
javax.activation-api-1.2.0.jar
javax.annotation-api-1.3.2.jar
jaxb-api-2.3.1.jar
jboss-jaxb-api_2.3_spec-2.0.0.Final.jar
jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar
jboss-logging-3.3.2.Final.jar
jboss-logging-annotations-2.1.0.Final.jar
jboss-logmanager-embedded-1.0.4.jar
jboss-threads-3.1.1.Final.jar
jcip-annotations-1.0.jar
jsr305-3.0.2.jar
kafka-clients-2.6.0.jar
kinesis-2.13.13.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
lz4-java-1.5.0.jar
metrics-spi-2.13.75.jar
microprofile-config-api-1.4.jar
microprofile-context-propagation-api-1.0.1.jar
microprofile-health-api-2.2.jar
mongodb-driver-core-4.1.0.jar
mongodb-driver-sync-4.1.1.jar
mssql-jdbc-7.2.2.jre8.jar
mutiny-0.7.0.jar
mysql-binlog-connector-java-0.23.1.jar
mysql-connector-java-8.0.19.jar
netty-buffer-4.1.49.Final.jar
netty-codec-4.1.49.Final.jar
netty-codec-dns-4.1.49.Final.jar
netty-codec-http-4.1.49.Final.jar
netty-codec-http2-4.1.49.Final.jar
netty-codec-socks-4.1.49.Final.jar
netty-common-4.1.49.Final.jar
netty-handler-4.1.49.Final.jar
netty-handler-proxy-4.1.49.Final.jar
netty-nio-client-2.13.75.jar
netty-reactive-streams-2.0.4.jar
netty-reactive-streams-http-2.0.4.jar
netty-resolver-4.1.49.Final.jar
netty-resolver-dns-4.1.49.Final.jar
netty-transport-4.1.49.Final.jar
netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar
netty-transport-native-unix-common-4.1.49.Final.jar
opencensus-api-0.26.0.jar
opencensus-contrib-http-util-0.24.0.jar
perfmark-api-0.19.0.jar
postgresql-42.2.14.jar
profiles-2.13.75.jar
proto-google-cloud-pubsub-v1-1.86.1.jar
proto-google-common-protos-1.17.0.jar
proto-google-iam-v1-0.13.0.jar
protobuf-java-3.8.0.jar
protobuf-java-util-3.11.4.jar
protobuf-shaded-2.1.0-incubating.jar
protocol-core-2.13.75.jar
proton-j-0.33.6.jar
pulsar-client-2.5.2.jar
pulsar-client-api-2.5.2.jar
pulsar-transaction-common-2.5.2.jar
qpid-proton-j-extensions-1.2.3.jar
quarkus-arc-1.7.1.Final.jar
quarkus-bootstrap-runner-1.7.1.Final.jar
quarkus-core-1.7.1.Final.jar
quarkus-development-mode-spi-1.7.1.Final.jar
quarkus-ide-launcher-1.7.1.Final.jar
quarkus-jsonp-1.7.1.Final.jar
quarkus-netty-1.7.1.Final.jar
quarkus-resteasy-1.7.1.Final.jar
quarkus-resteasy-common-1.7.1.Final.jar
quarkus-resteasy-server-common-1.7.1.Final.jar
quarkus-security-1.1.2.Final.jar
quarkus-security-runtime-spi-1.7.1.Final.jar
quarkus-smallrye-health-1.7.1.Final.jar
quarkus-vertx-core-1.7.1.Final.jar
quarkus-vertx-http-1.7.1.Final.jar
reactive-streams-1.0.3.jar
reactor-core-3.3.5.RELEASE.jar
reflections-0.9.12.jar
regions-2.13.75.jar
resteasy-core-4.5.6.Final.jar
resteasy-core-spi-4.5.6.Final.jar
sdk-core-2.13.75.jar
slf4j-api-1.7.30.jar
slf4j-jboss-logging-1.2.0.Final.jar
smallrye-common-annotation-1.1.0.jar
smallrye-common-constraint-1.1.0.jar
smallrye-common-expression-1.1.0.jar
smallrye-common-function-1.1.0.jar
smallrye-config-1.8.5.jar
smallrye-config-common-1.8.5.jar
smallrye-health-2.2.3.jar
smallrye-health-api-2.2.3.jar
smallrye-health-provided-checks-2.2.3.jar
smallrye-health-ui-2.2.3.jar
snappy-java-1.1.1.3.jar
stax2-api-4.2.1.jar
threetenbp-1.4.3.jar
utils-2.13.75.jar
validation-api-1.1.0.Final.jar
vertx-auth-common-3.9.2.jar
vertx-bridge-common-3.9.2.jar
vertx-core-3.9.2.jar
vertx-web-3.9.2.jar
vertx-web-common-3.9.2.jar
wildfly-common-1.5.4.Final-format-001.jar
woodstox-core-6.2.1.jar
zstd-jni-1.3.7-3.jar
</details>

<details>
  <summary>
    After
  </summary>
  activation-1.1.1.jar
animal-sniffer-annotations-1.14.jar
annotations-2.13.75.jar
annotations-4.1.1.4.jar
antlr4-runtime-4.7.2.jar
apache-client-2.13.75.jar
api-common-1.9.0.jar
arc-1.7.1.Final.jar
async-http-client-2.7.0.jar
async-http-client-netty-utils-2.7.0.jar
asyncutil-0.1.0.jar
audience-annotations-0.5.0.jar
auth-2.13.75.jar
auto-value-annotations-1.7.jar
avro-1.10.0.jar
avro-protobuf-1.9.1.jar
aws-cbor-protocol-2.13.75.jar
aws-core-2.13.75.jar
aws-json-protocol-2.13.75.jar
azure-core-1.5.1.jar
azure-core-amqp-1.2.0.jar
azure-messaging-eventhubs-5.1.1.jar
bookkeeper-common-allocator-4.10.0.jar
bouncy-castle-bc-shaded-2.5.2.jar
bson-4.1.0.jar
checker-qual-2.5.2.jar
circe-checksum-4.10.0.jar
commons-codec-1.14.jar
commons-compress-1.20.jar
commons-configuration-1.10.jar
commons-io-2.7.jar
commons-lang-2.6.jar
commons-lang3-3.9.jar
commons-logging-1.1.1.jar
connect-api-2.6.0.jar
connect-json-2.6.0.jar
connect-runtime-2.6.0.jar
connect-transforms-2.6.0.jar
conscrypt-openjdk-uber-2.2.1.jar
debezium-api-1.4.0-SNAPSHOT.jar
debezium-connector-mongodb-1.4.0-SNAPSHOT.jar
debezium-connector-mysql-1.4.0-SNAPSHOT.jar
debezium-connector-postgres-1.4.0-SNAPSHOT.jar
debezium-connector-sqlserver-1.4.0-SNAPSHOT.jar
debezium-core-1.4.0-SNAPSHOT.jar
debezium-ddl-parser-1.4.0-SNAPSHOT.jar
debezium-embedded-1.4.0-SNAPSHOT.jar
debezium-server-core-1.4.0-SNAPSHOT.jar
debezium-server-eventhubs-1.4.0-SNAPSHOT.jar
debezium-server-kinesis-1.4.0-SNAPSHOT.jar
debezium-server-pubsub-1.4.0-SNAPSHOT.jar
debezium-server-pulsar-1.4.0-SNAPSHOT.jar
error_prone_annotations-2.2.0.jar
eventstream-1.0.1.jar
failureaccess-1.0.1.jar
gax-1.56.0.jar
gax-grpc-1.56.0.jar
google-auth-library-credentials-0.20.0.jar
google-auth-library-oauth2-http-0.20.0.jar
google-cloud-core-1.93.4.jar
google-cloud-pubsub-1.104.1.jar
google-http-client-1.34.0.jar
google-http-client-jackson2-1.34.2.jar
graal-sdk-20.1.0.jar
grpc-alts-1.30.2.jar
grpc-api-1.30.2.jar
grpc-auth-1.30.2.jar
grpc-context-1.30.2.jar
grpc-core-1.30.2.jar
grpc-grpclb-1.30.2.jar
grpc-netty-shaded-1.30.2.jar
grpc-protobuf-1.30.2.jar
grpc-protobuf-lite-1.30.2.jar
grpc-stub-1.30.2.jar
gson-2.8.6.jar
guava-27.0.1-jre.jar
http-client-spi-2.13.75.jar
httpclient-4.5.12.jar
httpcore-4.4.13.jar
j2objc-annotations-1.1.jar
jackson-annotations-2.11.2.jar
jackson-core-2.10.2.jar
jackson-databind-2.10.2.jar
jackson-dataformat-cbor-2.11.2.jar
jackson-dataformat-csv-2.11.2.jar
jackson-dataformat-xml-2.11.2.jar
jackson-dataformat-yaml-2.10.2.jar
jackson-datatype-jdk8-2.11.2.jar
jackson-datatype-jsr310-2.10.2.jar
jackson-jaxrs-base-2.11.2.jar
jackson-jaxrs-json-provider-2.11.2.jar
jackson-module-jaxb-annotations-2.11.2.jar
jackson-module-jsonSchema-2.11.2.jar
jackson-module-paranamer-2.11.2.jar
jackson-module-scala_2.11-2.11.2.jar
jakarta.activation-1.2.1.jar
jakarta.activation-api-1.2.1.jar
jakarta.annotation-api-1.3.5.jar
jakarta.el-api-3.0.3.jar
jakarta.enterprise.cdi-api-2.0.2.jar
jakarta.inject-api-1.0.jar
jakarta.interceptor-api-1.2.5.jar
jakarta.json-1.1.6.jar
jakarta.transaction-api-1.3.3.jar
jakarta.validation-api-2.0.2.jar
jakarta.xml.bind-api-2.3.2.jar
javassist-3.26.0-GA.jar
javax.activation-1.2.0.jar
javax.activation-api-1.2.0.jar
javax.annotation-api-1.3.2.jar
jaxb-api-2.3.1.jar
jboss-jaxb-api_2.3_spec-2.0.0.Final.jar
jboss-jaxrs-api_2.1_spec-2.0.1.Final.jar
jboss-logging-3.3.2.Final.jar
jboss-logging-annotations-2.1.0.Final.jar
jboss-logmanager-embedded-1.0.4.jar
jboss-threads-3.1.1.Final.jar
jcip-annotations-1.0.jar
jopt-simple-5.0.4.jar
jsr305-3.0.2.jar
kafka-clients-2.6.0.jar
kafka_2.11-2.3.0.jar
kinesis-2.13.13.jar
listenablefuture-9999.0-empty-to-avoid-conflict-with-guava.jar
lz4-java-1.5.0.jar
memory-0.8.3.jar
metrics-core-2.2.0.jar
metrics-spi-2.13.75.jar
microprofile-config-api-1.4.jar
microprofile-context-propagation-api-1.0.1.jar
microprofile-health-api-2.2.jar
mongodb-driver-core-4.1.0.jar
mongodb-driver-sync-4.1.1.jar
mssql-jdbc-7.2.2.jre8.jar
mutiny-0.7.0.jar
mysql-binlog-connector-java-0.23.1.jar
mysql-connector-java-8.0.19.jar
netty-buffer-4.1.49.Final.jar
netty-codec-4.1.49.Final.jar
netty-codec-dns-4.1.49.Final.jar
netty-codec-http-4.1.49.Final.jar
netty-codec-http2-4.1.49.Final.jar
netty-codec-socks-4.1.49.Final.jar
netty-common-4.1.49.Final.jar
netty-handler-4.1.49.Final.jar
netty-handler-proxy-4.1.49.Final.jar
netty-nio-client-2.13.75.jar
netty-reactive-streams-2.0.4.jar
netty-reactive-streams-http-2.0.4.jar
netty-resolver-4.1.49.Final.jar
netty-resolver-dns-4.1.49.Final.jar
netty-transport-4.1.49.Final.jar
netty-transport-native-epoll-4.1.49.Final-linux-x86_64.jar
netty-transport-native-epoll-4.1.49.Final.jar
netty-transport-native-unix-common-4.1.49.Final-linux-x86_64.jar
netty-transport-native-unix-common-4.1.49.Final.jar
opencensus-api-0.26.0.jar
opencensus-contrib-http-util-0.24.0.jar
paranamer-2.8.jar
perfmark-api-0.19.0.jar
postgresql-42.2.14.jar
profiles-2.13.75.jar
proto-google-cloud-pubsub-v1-1.86.1.jar
proto-google-common-protos-1.17.0.jar
proto-google-iam-v1-0.13.0.jar
protobuf-java-3.8.0.jar
protobuf-java-util-3.11.4.jar
protobuf-shaded-2.1.0-incubating.jar
protocol-core-2.13.75.jar
proton-j-0.33.6.jar
pulsar-client-2.5.2.jar
pulsar-client-api-2.5.2.jar
pulsar-client-original-2.5.2.jar
pulsar-common-2.5.2.jar
pulsar-functions-api-2.5.2.jar
pulsar-io-core-2.5.2.jar
pulsar-io-debezium-core-2.5.2.jar
pulsar-io-kafka-connect-adaptor-2.5.2.jar
pulsar-transaction-common-2.5.2.jar
qpid-proton-j-extensions-1.2.3.jar
quarkus-arc-1.7.1.Final.jar
quarkus-bootstrap-runner-1.7.1.Final.jar
quarkus-core-1.7.1.Final.jar
quarkus-development-mode-spi-1.7.1.Final.jar
quarkus-ide-launcher-1.7.1.Final.jar
quarkus-jsonp-1.7.1.Final.jar
quarkus-netty-1.7.1.Final.jar
quarkus-resteasy-1.7.1.Final.jar
quarkus-resteasy-common-1.7.1.Final.jar
quarkus-resteasy-server-common-1.7.1.Final.jar
quarkus-security-1.1.2.Final.jar
quarkus-security-runtime-spi-1.7.1.Final.jar
quarkus-smallrye-health-1.7.1.Final.jar
quarkus-vertx-core-1.7.1.Final.jar
quarkus-vertx-http-1.7.1.Final.jar
reactive-streams-1.0.3.jar
reactor-core-3.3.5.RELEASE.jar
reflections-0.9.12.jar
regions-2.13.75.jar
resteasy-core-4.5.6.Final.jar
resteasy-core-spi-4.5.6.Final.jar
scala-library-2.12.9.jar
scala-logging_2.11-3.9.0.jar
scala-reflect-2.12.9.jar
sdk-core-2.13.75.jar
sketches-core-0.8.3.jar
slf4j-api-1.7.30.jar
slf4j-jboss-logging-1.2.0.Final.jar
smallrye-common-annotation-1.1.0.jar
smallrye-common-constraint-1.1.0.jar
smallrye-common-expression-1.1.0.jar
smallrye-common-function-1.1.0.jar
smallrye-config-1.8.5.jar
smallrye-config-common-1.8.5.jar
smallrye-health-2.2.3.jar
smallrye-health-api-2.2.3.jar
smallrye-health-provided-checks-2.2.3.jar
smallrye-health-ui-2.2.3.jar
snakeyaml-1.26.jar
snappy-java-1.1.1.3.jar
stax2-api-4.2.1.jar
swagger-annotations-1.6.0.jar
threetenbp-1.4.3.jar
utils-2.13.75.jar
validation-api-1.1.0.Final.jar
vertx-auth-common-3.9.2.jar
vertx-bridge-common-3.9.2.jar
vertx-core-3.9.2.jar
vertx-web-3.9.2.jar
vertx-web-common-3.9.2.jar
wildfly-common-1.5.4.Final-format-001.jar
woodstox-core-6.2.1.jar
zkclient-0.11.jar
zookeeper-3.5.8.jar
zookeeper-jute-3.5.8.jar
zstd-jni-1.3.7-3.jar
</details>

<details>
  <summary>
    Difference
  </summary>
  async-http-client-2.7.0.jar
async-http-client-netty-utils-2.7.0.jar
audience-annotations-0.5.0.jar
avro-1.10.0.jar
avro-protobuf-1.9.1.jar
bookkeeper-common-allocator-4.10.0.jar
circe-checksum-4.10.0.jar
commons-compress-1.20.jar
commons-configuration-1.10.jar
commons-io-2.7.jar
commons-lang-2.6.jar
commons-lang3-3.9.jar
commons-logging-1.1.1.jar
jackson-dataformat-csv-2.11.2.jar
jackson-dataformat-yaml-2.10.2.jar
jackson-module-jsonSchema-2.11.2.jar
jackson-module-paranamer-2.11.2.jar
jackson-module-scala_2.11-2.11.2.jar
</details>

**Comment by gunnarmorling** [comment]
Wow, that's a huge list of things, I don't think we can add all of them. Do we need all those transitive dependencies in fact, or can we limit it to _only_ the Pulsar core artifact?

Taking a step back, is it you want to add this so to be able to use the Pulsar schema history implementation? If so, it may also be worth while to have a discussion with Pulsar folks to extract this into a separate artifact which we could depend on, instead of full Pulsar proper, which we don't really need in Debezium server.

**Comment by fransguelinckx** [comment]
@gunnarmorling You're correct, I want to be able to use the Pulsar schema history implementation.

I understand your concern, so I excluded all transitive dependencies. This reduces the long list to a single extra dependency: pulsar-io-debezium-core-2.5.2.jar.

I haven't tested it yet, but will do so in the next couple of days and post feedback here. Meanwhile, I'll contact the pulsar people and pitch your idea of a separate artefact.

**Comment by gunnarmorling** [comment]
Any news on this one? Can we go with the core artifact solely?

**Comment by fransguelinckx** [comment]
No not yet unfortunately. I didn't manage to configure PulsarDatabaseHistory.java properly yet, for example the `database.history.pulsar.service.url`.

Stacktrace:
```
2021-01-11 09:53:57,817 INFO  [io.deb.ser.ConnectorLifecycle] (pool-3-thread-1) Connector completed: success = 'false', message = 'Unable to initialize and start connector's task class 'io.debezium.connector.mysql.MySqlConnectorTask' with config: {connector.class=io.debezium.connector.mysql.MySqlConnector, transforms.createKey.type=org.apache.kafka.connect.transforms.ValueToKey, transforms=defaultKey,reroute,extract,createKey,extractKey, transforms.reroute.type=io.debezium.transforms.ByLogicalTableRouter, transforms.extractKey.type=org.apache.kafka.connect.transforms.ExtractField$Key, offset.storage.file.filename=data/offsets.dat, transforms.createKey.fields=MESSAGE_KEY, transforms.reroute.topic.regex=(.*)_EVENT_RECORD(.*), database.history.pulsar.topic=history-topic, database.user=debezium, transforms.extractKey.field=MESSAGE_KEY, transforms.reroute.topic.replacement=public/default/integration-events, database.server.name=everesst, transforms.defaultKey.static.value=placeholder_message_key, database.port=3306, offset.flush.interval.ms=0, key.converter.schemas.enable=false, transforms.extract.type=io.debezium.transforms.ExtractNewRecordState, database.hostname=127.0.0.1, transforms.defaultKey.static.field=MESSAGE_KEY, database.password=********, database.history.pulsar.service.url=pulsar://127.0.0.1:6650, value.converter.schemas.enable=false, name=pulsar, transforms.defaultKey.type=org.apache.kafka.connect.transforms.InsertField$Value, table.include.list=.*\..*_EVENT_RECORD, database.history=org.apache.pulsar.io.debezium.PulsarDatabaseHistory}', error = '{}': org.apache.kafka.connect.errors.ConnectException: java.lang.IllegalArgumentException: Param serviceUrl must not be blank.
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:291)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:758)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:171)
	at io.debezium.server.DebeziumServer.lambda$start$1(DebeziumServer.java:142)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.lang.IllegalArgumentException: Param serviceUrl must not be blank.
	at org.apache.pulsar.client.impl.ClientBuilderImpl.serviceUrl(ClientBuilderImpl.java:85)
	at org.apache.pulsar.io.debezium.PulsarDatabaseHistory.setupClientIfNeeded(PulsarDatabaseHistory.java:118)
	at org.apache.pulsar.io.debezium.PulsarDatabaseHistory.setupProducerIfNeeded(PulsarDatabaseHistory.java:128)
	at org.apache.pulsar.io.debezium.PulsarDatabaseHistory.start(PulsarDatabaseHistory.java:147)
	at io.debezium.connector.mysql.MySqlSchema.start(MySqlSchema.java:178)
	at io.debezium.connector.mysql.MySqlTaskContext.start(MySqlTaskContext.java:246)
	at io.debezium.connector.mysql.MySqlConnectorTask.createAndStartTaskContext(MySqlConnectorTask.java:351)
	at io.debezium.connector.mysql.MySqlConnectorTask.start(MySqlConnectorTask.java:143)
	... 7 more
```

I wanted to troubleshoot this, but I'm having some trouble running debezium server from my IDE. Will try to find some time this week.

**Comment by gunnarmorling** [comment]
Ok, thanks for the update.

>

**Comment by gunnarmorling** [comment]
I'm going to close this one for now, so to clean the slate a bit. Feel free to open up a new PR once you deem it ready. Thx!

**Pull request closed without merging**
