### PR TITLE
0.6

### PR DESCRIPTION
**Pull request by rk3rn3r**

### CODE REVIEW

**Comment by rk3rn3r** [comment]
clicked the wrong button. lol. sorry

**Comment by gunnarmorling** [comment]
0.6?! LOL :)

>

**Comment by rk3rn3r** [comment]
I tried to follow 
https://github.com/KirstieJane/STEMMRoleModels/wiki/Syncing-your-fork-to-the-original-repository-via-the-browser
to sync my fork
wanted to cancel but the UI was loading too slow. then there was the create PR button under the cursor, where a sec earlier was cancel. :D

I am trying to write a Redis CDC Connector for DBZ over the weekend (challenge myself). Realized there's a replication log that wants to be captured ;)

**Comment by rk3rn3r** [comment]
I did it on the console afterwards. I guess I'm not that UI guy

**Comment by gunnarmorling** [comment]
> I am trying to write a Redis CDC Connector for DBZ over the weekend
(challenge myself). Realized there's a replication log that wants to be
captured ;)

That's funny, just was thinking about Redis the other day. If you do
something, make sure to take a look at how the SQL Server connector is
implemented (ChangeEventSource et. al) as it's the blueprint for any
connectors going forward (we're trying to unify more and more code across
connectors, but it's still in flux...).

Am Mi., 29. Mai 2019 um 21:43 Uhr schrieb René Kerner <
notifications@github.com>:

**Pull request closed without merging**
