### PR TITLE
DBZ-7257 Fix regression in parsin Oracle 12 version

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-7257

### CODE REVIEW

**Comment by vjuranek** [comment]
Waiting for test farm to be more stable to re-run the tests.

**Comment by vjuranek** [comment]
@jpechane Oracle testsuite is currently broken, the fix is in PR #5113 and PR #5114. This one should be re-run after merging these PRs.

**Comment by jpechane** [comment]
@vjuranek Merged and re-running

**Pull request merged**
