### PR TITLE
Remove duplicate description from mongodb.adoc

### PR DESCRIPTION
**Pull request by Fraznist**
`capture.mode` description has a duplicate paragraph. This PR removes one of the duplicates.

### CODE REVIEW

**Comment by jpechane** [comment]
@Fraznist Thanks for the PR. @roldanbob Could you please check if the removed text is the one to be removed or it should be the other one?

**Review by roldanbob — APPROVED** [review]
LGTM. Thanks, @Fraznist for catching the duplicate.

**Comment by jpechane** [comment]
Merged via https://github.com/debezium/debezium/pull/4785 to apply it to `main` first.

**Comment by Fraznist** [comment]
@roldanbob you're welcome, should I add COPYRIGHT, Aliases and an jira card commit msg so that the checks pass, or will you take it from here?

**Pull request closed without merging**
