### PR TITLE
DBZ-4462 Run formatting check in the same connector/module workflows

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-4462

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, could you review this one?

**Comment by ani-sha** [comment]
@gunnarmorling There is some more pending work to do in this. I will ping for review once done. Thanks.

**Comment by gunnarmorling** [comment]
@ani-sha, oh, ok, I see. In that case it's best to mark it as a "Draft" PR.

**Comment by gunnarmorling** [comment]
@ani-sha, hey, what's needed in order to wrap this one up?

**Comment by ani-sha** [comment]
@gunnarmorling It's ready for review now.

**Review by Naros — APPROVED** [review]
This LGTM @ani-sha, great work!

**Pull request merged**
