### PR TITLE
DBZ-8157 Document VECTOR type

### PR DESCRIPTION
**Pull request by jpechane**
Documentation for https://github.com/debezium/debezium/pull/5784

### CODE REVIEW

**Comment by jpechane** [comment]
This is MySQL specific righ now so I put into MySQL-only docs

**Comment by roldanbob** [comment]
> This is MySQL specific righ now so I put into MySQL-only docs

@jpechane Is this also supported for MariaDB?

**Comment by jpechane** [comment]
No, it is not.

**Comment by roldanbob** [comment]
@jpechane I pushed a change to your branch to update the MariaDB/MySQL shared file.
The product version of the doc now includes `Vector` in the list of MySQL data types at the beginning of the _Data type mappings_ section. The list in the MariaDB version of the doc does not include the `Vector` type.

**Review by roldanbob — APPROVED** [review]
Good from my perspective.

**Comment by jpechane** [comment]
@roldanbob Applied, thanks for the changes!

**Pull request merged**
