### PR TITLE
DBZ-3713 Wrapped client.xadd within Try-Catch in RedisStreamChangeConsumer

### PR DESCRIPTION
**Pull request by ashmeet13**
In case of a failure the entire batch would be skipped and the whole process
crashes. Adding a try catch block similar to other sinks

Issue - https://issues.redhat.com/browse/DBZ-3713

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ani-sha, @Naros, something seems odd with the builds and the checks. If you look above, no PR build has been run as @ashmeet13 (hey there!) is a first-time contributor and a once-off approval of building PRs of them is needed. Still there is the red X next to the commit, indicating some builds have run. Could one of you take a look into why this is happening and how to prevent it? Thx!

**Comment by ani-sha** [comment]
@gunnarmorling I think I figured it out. As we don't have any `branch` specification on the `push/pull_request` step in all workflows, so actions are also triggered in forked repositories and I checked in the forked repository of @ashmeet13, the build that ran against this commit in his repository are reflected here even if this requires `approval and run`. 
I am going to log a Jira and fix this.

**Comment by gunnarmorling** [comment]
Ok, I see. Thanks for analysing and providing a fix, @ani-sha!

**Comment by gunnarmorling** [comment]
So I don't think anything changes here in terms of behavior, an exception will still be raised, just as before. Still, wrapping into a Debezium exception seems a tad nicer.

**Pull request merged**
