### PR TITLE
DBZ-7159 Fail fast during deserialization if a value is not a CloudEvent

### PR DESCRIPTION
**Pull request by rkudryashov**
https://issues.redhat.com/browse/DBZ-7159

A new validator will also be used by [`ConvertCloudEventToSaveableForm`](https://github.com/debezium/debezium-connector-jdbc/blob/main/src/main/java/io/debezium/connector/jdbc/transforms/ConvertCloudEventToSaveableForm.java#L156)

### CODE REVIEW

**Comment by jpechane** [comment]
@rkudryashov Should `baseCheck` and `checkFields` throw an exception in case of not fmet preconditions?

**Comment by jpechane** [comment]
@rkudryashov Yes, I understand but the aforementioned methods can throw an exception which means that `isCloudEvent` can throw an exception too. Is it desirable for your use case?

**Comment by rkudryashov** [comment]
@jpechane the methods throw an exception only if they are called with
serializer type other than json or avro. I think that's ok

**Comment by rkudryashov** [comment]
@jpechane changed to return false

**Comment by rkudryashov** [comment]
Eventually I think an exception should be thrown in case of a serializer type other than JSON or Avro because the validator doesn't know how to check such records

**Pull request merged**
