### PR TITLE
DBZ-1926 Log unexpected exceptions during snapshot

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1926

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Logging *and* re-throwing the exception looks a bit like an anti-pattern; shouldn't it be logged elswhere if it just bubbles up?

**Comment by jpechane** [comment]
@Naros I don't think this is the right place. IMHO to root cause is
- handling in `failed` method
- the main `catch` in `execute` method around line 831, there is `UNLOCK TABLES` command and the `failed` method call later in the handler has lost the original SQL statement as it was overwritten by the unlock

**Comment by Naros** [comment]
Hi @gunnarmorling @jpechane, thanks for pointing those things out.  Let me know if the new changes in the latest commit make more sense?  Based on Jiri's comments I think it should help a bit better.

**Comment by jpechane** [comment]
@Naros LGTM! Can be merged when the typo is fixed

**Comment by gunnarmorling** [comment]
Thanks, @Naros!

**Pull request merged**
