### PR TITLE
 DBZ-630 Unifying common start-up logic across connectors 

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.jboss.org/browse/DBZ-630

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling - thanks, a great improvement again!

Unfortunately I think it also confuses things a little bit - wrt the naming. Partly are the problems inherited from current basecode and partly are new issues introduced. Please let me explain.

Every task has associated `context` of type `SourceTaskContext`. You create a new context calld `ConnectorTaskContext`. This context is associated with task but the naming implies it can be assocatied with connector too. And how do those two types of *TaskContexts* differ? I'd like to see a clear name that would distinct those two types. If possible I'd like to neither use expression Task nor Connector. Maybe the plain `Context` would be enough?

For postgres I see you are using the context in exact way how I think it is envisioned. There is a `PostgresTaskContext` that is associated with task.

For MongoDB it is less ideal. How is a `ConnectionContext` that by name says it is something related to connection derived from task? And where is the link between task and its context?

And MySQL is completely confusing now - the task has _three!_ contexts
 - `SourceTaskContext`
 - `MySQLTaskContext`
 - `MySqlJdbcContext` whose name implies it relates to a db connection but inherits from `...TaskContext`!

Ideally every task will contain reference to
 - `SourceTaskContext`
 - another context derived from renamed `ConnectorTaskContext` and this one will contain an optional reference to a context related to connection

This brings me one more question - a task context has 1:1 relationship between task and context. What are rules that defines what should be defined as attributes in task itself and what should go into the context?

I am sorry for the long comment but I hope you understand why I see there are now separate cross-cutting concerns entnagled together.

**Comment by gunnarmorling** [comment]
Hey @jpechane, lots of good questions, and I fully agree it's not ideal yet. But I hope we're on the right path. I did it the proposed way to not be derailed too much from what I'm actually working on, but I'm happy to revisit this and improve it further. I think the following would be a good structure eventually:

* Every task (`PostgresConnectorTask` etc.) has a reference to a corresponding context class, which contains those objects/metadata scoped to the task lifecycle, i.e. a `Clock`, a `XyzConnectorConfig` etc.)
* These specific context classes should be derived from a common base context which keeps commonalities; that's the `ConnectorTaskContext` from this PR. We can rename it, `SourceTaskContext` might work, but it'll conflict with KC's class of the same name. Perhaps `CdcSourceTaskContext`?
* These specific context classes may optionally have references to other contexts, e.g. the `ConnectionContext`; i.e. there should be a delegation relationship, not an inheritance relationship; this would address your concern for MySQL above; In fact, I had the same concern, I just shied away from doing this right now due to the effort. But it shouldn't be too much, so I guess I'll just do it.

> What are rules that defines what should be defined as attributes in task itself and what should go into the context?

I think it's not black and white, but I'd keep an attribute in the task itself if it's just needed there and I'd add it to the context if it's consumed in multiple places, which gets simplified by adding it to the context which can be passed around.

Does that make sense?

**Comment by jpechane** [comment]
@gunnarmorling +1 on all points, that was exatly on my mind, thanks!

**Comment by gunnarmorling** [comment]
@jpechane Pushed an update as per our discussion and rebased, too.

**Comment by jpechane** [comment]
@gunnarmorling Great work, thanks!

**Pull request merged**
