### PR TITLE
DBZ-5825 Use Java 19 in Java Outreach action

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-5825

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Why is this draft only?

**Comment by jpechane** [comment]
Force pushed with

* update to the latest main
* test for Spanner connector
* Server build in separate repo

**Comment by jpechane** [comment]
@Naros Looking at outrech page we should probably jump directly to Java 20 EA

**Comment by jpechane** [comment]
The Spanner build failure tracked via https://issues.redhat.com/browse/DBZ-6065

**Comment by Naros** [comment]
> @Naros Looking at outrech page we should probably jump directly to Java 20 EA

That's a good point.  I think I created this before my holiday PTO.  I've added this to my list for this week.

**Comment by jpechane** [comment]
@Naros I think we are good to go with this one. Spanner is not working and Cassandra seems to be affected by the Cassandra lib code, so IMHO we can take the results and publish them. Do you know who is the current contact on our side? Still Gunnar?

**Comment by Naros** [comment]
Most likely @jpechane, I'm not aware of there being anyone else.

**Pull request merged**
