### PR TITLE
DBZ-5610 MySQL Connector capture TRUNCATE command as message in table topic

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-5610
The truncate command sample data of table topic as below:
key: null
value:
`
{
    "before": null,
    "after": null,
    "source": {
        "version": "2.0.0-SNAPSHOT",
        "connector": "mysql",
        "name": "test_avro",
        "ts_ms": 1665304468000,
        "snapshot": {
            "string": "false"
        },
        "db": "workdb",
        "sequence": null,
        "table": {
            "string": "dbz5236"
        },
        "server_id": 112233,
        "gtid": null,
        "file": "mysql-bin.000035",
        "pos": 125109,
        "row": 0,
        "thread": null,
        "query": null
    },
    "op": "t",
    "ts_ms": {
        "long": 1665304468970
    },
    "transaction": null
}`

### CODE REVIEW

**Comment by harveyyue** [comment]
I'll update the document later.

**Comment by jpechane** [comment]
@harveyyue Thanks a lot, this will go into 2.1

**Comment by harveyyue** [comment]
> @harveyyue Thanks a lot, this will go into 2.1

Get😊

**Comment by jpechane** [comment]
@harveyyue Applied, thanks!

**Pull request merged**
