### PR TITLE
DBZ-2972: Should parse create procedure statements with labeled body

### PR DESCRIPTION
**Pull request by ramanenka**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could you please change the commit message so it begins with "DBZ-2972 Should parse..."? Thanks!

**Comment by ramanenka** [comment]
@gunnarmorling Done. Please note that this is not the fix. The purpose of this PR is to reproduce the bug.

**Comment by gunnarmorling** [comment]
> The purpose of this PR is to reproduce the bug.

Doh, just realizing this :)

Perhaps you could give it a try to fix it, too? Check out earlier commits in the _debezium-ddl-parser_ module for the general approach, it's pretty much straight-forward.

**Comment by ramanenka** [comment]
Yeah, I thought it's going to be straight-forward too, especially since I've already contributed to _debezium-ddl-parser_  a few times. But it looks like it's a bit more complex this time. The grammar seems to be alright: `(uid ':')? BEGIN`. So it should match `lbl:BEGIN`, but it doesn't. It feels like it can match `BEGIN` only when it's surrounded by whitespaces, but when `BEGIN` is prefixed with `:` it refuses to match. I've already spent a few hours trying to understand why, but no luck so far.

**Comment by jpechane** [comment]
Fixed with https://github.com/debezium/debezium/pull/2074

**Pull request closed without merging**
