### PR TITLE
DBZ-2657: fall back to use 'SHOW SLAVE STATUS' to retrieve position or GTID information when MASTER STATUS is not available

### PR DESCRIPTION
**Pull request by darthnebu**
https://issues.redhat.com/browse/DBZ-2657

DBZ-2657: fall back to use 'SHOW SLAVE STATUS' to retrieve position or GTID information when MASTER STATUS is not available

I have ran unit test but not integration test in my local, because I couldn't figure out how to configure DOCKER_CERT_PATH env var and kept getting "Cannot create docker access object: /Users/<usr>/.docker/key.pem" error. Please let me know if you have any recommendation on configuring that, as well as to the code. Thank you

### CODE REVIEW

**Comment by rk3rn3r** [comment]
hey @darthnebu! Thank you for the PR. I think it would be good to add an integration test for this scenario as well.
About you issue, are you using Docker Toolbox instead of Docker Desktop on Mac? A quick google gave me that result on how to configure that parameter: https://docs.docker.com/docker-for-mac/docker-toolbox/
Maybe that helps?

**Comment by darthnebu** [comment]
@rk3rn3r Thanks for the prompt reply! I agree we can use an integration test for this change, and I appreciate the help on resolving the docker issue. I'm very unfamiliar with docker so bare with me:

I use docker desktop (says: "Docker Desktop is running" on my tool bar), and here's what I have 
```
➜  ~ ls ~/.docker
application-template  config.json  contexts  daemon.json  run
➜  ~ docker --version
Docker version 19.03.12, build 48a66213fe
```

For the environmental var I have:
```
➜  debezium-connector-mysql git:(DBZ-2657) echo $DOCKER_CERT_PATH
/Users/boquan/.docker
➜  debezium-connector-mysql git:(DBZ-2657) echo $DOCKER_HOST
tcp://10.1.2.2:2376
➜  debezium-connector-mysql git:(DBZ-2657) echo $DOCKER_TLS_VERIFY
1
```

Could you shed some light on it? Feel free to ask for more information.

**Comment by jpechane** [comment]
Closing as this can't be done

**Comment by gunnarmorling** [comment]
Could you elaborate a bit on _why_ it cannot be done? Thanks!

>

**Comment by jpechane** [comment]
@gunnarmorling Please see https://issues.redhat.com/browse/DBZ-2657?focusedCommentId=15384921&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15384921

**Comment by gunnarmorling** [comment]
Gotcha, thx!

**Pull request closed without merging**
