### PR TITLE
DBZ-3429 SQL Server properties with spaces

### PR DESCRIPTION
**Pull request by kyleyj**
SQL Server properties issues with spaces.  JIRA Ticket: https://issues.redhat.com/browse/DBZ-3429

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thx, @kyleyj! The change looks good, could you only add a test to one of the connectors, so to spot/avoid any future regressions here. Thanks again!

**Comment by gunnarmorling** [comment]
Thinking a bit more about this, there is `Configuration.getStrings(String, String)`, which should be invoked. And we may even consider adding `Configuration.getTrimmedStrings(String)` which specializes on getting trimmed strings from a comma-separated list value. This method could then be used later on for retrieving all those similar options from the configuration.

**Comment by gunnarmorling** [comment]
Hey @kyleyj, are you planning to do the changes suggested above? No problem if not, just let us know. Thx!

**Comment by gunnarmorling** [comment]
You just can keep pushing further commits to this PR's branch.

**Comment by kyleyj** [comment]
I had some git trouble in pushing the additional commit to this same PR.  Rather than taking more time to figure it out, I'm going to close this PR and open a new one with the latest commit.  New PR is #2320

**Pull request closed without merging**
