### PR TITLE
DBZ-2141 Add a custom MongoDB connector error handler to do retries on connection errors

### PR DESCRIPTION
**Pull request by jgraf50**

### CODE REVIEW

**Comment by Naros** [comment]
Hi @jgraf50, first thanks for the contribution.  

I'm curious if _all_ `MongoSocketException` use cases should trigger connection retries.  At least in other connectors, we've actually done this by checking the message text of the exception.  I haven't yet looked at the mongodb driver source to see if there might be some corner cases, but just thought I'd ask the question in case you had done that research already.

**Comment by jgraf50** [comment]
Thanks, @Naros.  I have not looked at the source but the [documentation](https://mongodb.github.io/mongo-java-driver/3.4/javadoc/com/mongodb/MongoSocketException.html) lists just 5 exceptions:

- MongoSocketClosedException
- MongoSocketOpenException
- MongoSocketReadException
- MongoSocketReadTimeoutException
- MongoSocketWriteException

These all seem reasonable to retry (although we would never see the write exception).  I have been running Debezium with this change in our Staging and Production environments for several weeks and the only case I am seeing is `MongoSocketReadException`.

**Comment by jpechane** [comment]
@jgraf50 Hi, all looks reasonable for me to cover. So IMHO this PR is good to go. Just one question,  what if MongoDB will reject connection due to security reasons or similar. Will not be ane of these exceptions part of such stack trace?

**Comment by Naros** [comment]
@jpechane, looking at the driver source in-depth some this morning, I believe the driver would throw a `MongoSecurityException` in that use case as its literally littered throughout all of the authentication classes.  Additionally in the net code, the only time that these `MongoSocketException` derivatives are thrown seem to be when the underlying Java API throws a net-code related exception like `IOException`, `SocketTimeoutException`, or when some socket state is checked and found that the connection didn't open, was abruptly closed, etc.  

That said, I'm going to go ahead and merge the PR.  Thanks for the contribution @jgraf50.

**Comment by jgraf50** [comment]
Thanks for the detailed review, @Naros !

**Pull request merged**
