### PR TITLE
[DBZ-4809] Add task id and partition to the logging context...

### PR DESCRIPTION
**Pull request by jribera-sugarcrm**
...for multi-partition connectors.

Co-authored-by: Sergei Morozov <morozov@tut.by>

-- Resolves https://issues.redhat.com/browse/DBZ-4809

### CODE REVIEW

**Comment by jribera-sugarcrm** [comment]
@gunnarmorling here's a pr for updating the logging context with task id/partition names.

**Comment by gunnarmorling** [comment]
This LGTM, thanks, @jribera-sugarcrm! @morozov, any thoughts from your side? The test failure should be unrelated, it's the first time I'm seeing it (the test itself was added rather recently), so I'll log an issue in case it shows up again.

**Comment by morozov** [comment]
Looks good to me too.

**Comment by gunnarmorling** [comment]
Merged; thanks a lot, @jribera-sugarcrm!

**Pull request merged**
