### PR TITLE
DBZ-1345 Should not snapshot materialized views

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1345

### CODE REVIEW

**Comment by Naros** [comment]
@jpechane Unless you disagree, I think I probably should add a test for each connector.  While the report was initially for Postgres; the code change is central to all connectors. What's your opinion?

**Comment by gunnarmorling** [comment]
Not sure whether all the DBs support materialized views, but for those that do, yes, having the same test wouldn't be bad. This ties in with a more general thought: should we have some kind of "TCK" that's executed against all the tests? This might be a great way to make sure a test like this is just maintained once. OTOH I'm not sure how feasible it is to do it, given there are some subleties in connector behaviors. Some food for thought.

**Comment by Naros** [comment]
I've added PR for Oracle [here](https://github.com/debezium/debezium-incubator/pull/97).

**Comment by gunnarmorling** [comment]
Applied. Just added the `@FixFor` annotation. Thanks, @Naros!

**Pull request merged**
