### PR TITLE
DBZ-7831 Allow streaming from tables with single-quotes in name

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7831

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Comment by leoloel** [comment]
Hi, why not consider my previous [PR.](https://github.com/debezium/debezium/pull/5531/files) I feel a little disappointed. I spent a lot of time trying to fix that.

**Comment by Naros** [comment]
hi @leoloel honestly that was an oversight on my part, and I apologize.  I didn't see the PR link in the Jira and I took your comment of "no" on the PR status to mean you hadn't had time to work on it.  Sorry for that.

**Pull request merged**
