### PR TITLE
Explain postgresql security nuances

### PR DESCRIPTION
**Pull request by davecramer**
will fix {productname}

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice addition, thanks a lot, @davecramer! I've logged https://issues.redhat.com/browse/DBZ-3138 for this, I'll reword the commit messages to add its key when applying.

@roldanbob, could you do a quick pass on this doc improvement. I suppose it's a bit more colloquial than what we typically have. Ideally, just push another commit with some adjustments to this PR, as you see fit. Thanks!

**Comment by roldanbob** [comment]
@davecramer I've pulled your `pgsecurity` branch and I'm working through some changes, but it's taking me some time as I've had to educate myself about `pgoutput` and publications. I think I understand the scenario now, but I could also be wrongheaded (headed wrong?). When I finish I'll push my commit as @gunnarmorling requests, and then you two can determine if I've gone off the rails too far.

**Comment by gunnarmorling** [comment]
Sounds good, @roldanbob. The change looks very good contents-wise to me. If you push changes, can you please use the [DBZ-3149](https://issues.redhat.com/browse/DBZ-3149) issue which I've logged for this. I'll also reword Dave's commit messages accordingly. Thx all!

**Comment by davecramer** [comment]
Thanks guys, I figured the nuances were important enough to document.

**Comment by gunnarmorling** [comment]
> I figured the nuances were important enough to document.

They definitely are, so thanks a lot for this contribution. Rob will adjust
wording here and there a bit to match the usual style, and then it's good
to go. Thanks again!

**Comment by gunnarmorling** [comment]
@roldanbob, do you think we can get this one wrapped up by tomorrow? Would love to add it to 1.4.2.Final planned for tomorrow. Thx!

**Comment by roldanbob** [comment]
@gunnarmorling @davecramer As I review the current doc for context, I'm realizing that we partially cover the task of creating a replication user for the connector in [Setting up permissions](https://debezium.io/documentation/reference/1.4/connectors/postgresql.html#postgresql-permissions). I think that rather than add the nuances related to `pgoutput` in the _How the connector works_ section, it's better to build it into the existing topic in the [Set up](https://debezium.io/documentation/reference/1.4/connectors/postgresql.html#setting-up-postgresql) section. WDYT?

**Comment by davecramer** [comment]
Looking at that section. Yes it may make more sense to do it there. That section is rather confusing with all the various options for deploying it though. Perhaps break out the creating of the user a bit to make it clearer

**Comment by roldanbob** [comment]
Ok, if you agree, then, to simplify things, rather than following the original directive of pushing another commit against the current PR, perhaps we should close this one and I'll take the information over into a new commit?

**Comment by davecramer** [comment]
Fine by me

**Comment by gunnarmorling** [comment]
Sounds good, @roldanbob!

**Comment by roldanbob** [comment]
@gunnarmorling I notice that the Q3 2020 downstream doc states that _"This release of Debezium supports only the native pgoutput logical replication stream."_ 

But there are some conflicting statements about using pgoutput. For example, _"If you are using one of the supported logical decoding plug-ins, **that is, not `pgoutput`** [emphasis mine], and it has been installed, configure the PostgreSQL server as follows ..."_

Since the downstream doc is specific to the current Q1 release, I think we should conditionalize (or remove?) such statements, no? In the current upstream version, do we need to still refer to support provided by back-level Debezium versions?

**Comment by gunnarmorling** [comment]
> I think we should conditionalize...

Yes, for downstream, only `pgoutput` is supported. Ideally, no notion of other plug-ins should appear in downstream docs. That being said, `pgoutput` also is a logical decoding plug-in (it only is available by default on PG 10 onwards), so that sentence is worded a bit confusingly. It should say the following in this part (for upstream only):

> If you are using a logical decoding plug-ins other than `pgoutput`, after installing it, configure the PostgreSQL server as follows:

WDYM by "back-level" exactly here:

> do we need to still refer to support provided by back-level Debezium versions?

In general, docs should only discuss that current version of Debezium they apply to, any references to earlier versions should be avoided. But I'm not sure whether that's what you're asking?

**Comment by gunnarmorling** [comment]
So as I'm reading that install section again (https://debezium.io/documentation/reference/connectors/postgresql.html#installing-postgresql-output-plugin), this definitely would deserve some overhaul. In general, we should recommend to use `pgoutput` on PG 10+ in a more prescriptive way. The other two plug-ins should primarily be used only on older PG versions. But perhaps we can take that one separately from this permission clarification here?

**Comment by roldanbob** [comment]
> . Ideally, no notion of other plug-ins should appear in downstream docs. That being said, `pgoutput` also is a logical decoding plug-in

@gunnarmorling Yes, you understood me correctly. By back-level, I just mean earlier versions. I wasn't sure whether in the current version of the upstream doc we wanted to maintain backwards-compatibility by continuing to include information that was true in previous versions.

**Comment by roldanbob** [comment]
> But perhaps we can take that one separately from this permission clarification here?

Yes, I agree, let's address cleaning up references to the other plug-ins separately.

**Comment by gunnarmorling** [comment]
>  I wasn't sure whether in the current version of the upstream doc we wanted to maintain backwards-compatibility by continuing to include information that was true in previous versions.

Gotcha, no, we generally don't need/want that. Docs for earlier versions are two clicks away via the drop-down in the Antora docs, so each doc version should be focused on on this one version. There may be a few references to earlier versions remaining, from a time where we had a single set of docs for all versions. After moving to Antora, they should have been removed, but some may still need cleaning up.

**Comment by roldanbob** [comment]
@davecramer I added the content that you contributed via a new PR #2163. I wanted to add you as a reviewer there, but was unable to. Let me know if any changes are required. Thanks for your help! 

Closing this one.

**Comment by roldanbob** [comment]
> The other two plug-ins should primarily be used only on older PG versions.

Ah, I was thinking that we only supported 10+, but I see now that it's 9.6+, so we need to retain that information for the time being.

**Pull request closed without merging**
