### PR TITLE
DBZ-4801 Using JdbcConfiguration over Configuration

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-4801

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, can you take a look at this one?

I'm not 100% happy about the edit-build-adapt cycle in some places, but I think it increased type-safety out-weighs this overall. I believe this could be overcome, but it would require much larger changes to the type hierarchy of config builders, so I shied away from doing that.

**Comment by gunnarmorling** [comment]
I'll push PR for Vitess/Db2 if there's general consencus on this one.

**Comment by jpechane** [comment]
@gunnarmorling LGTM. There is still a conflict to be fixed.

**Comment by gunnarmorling** [comment]
Ok, resolved all the merge issues and will apply. Will send follow-up changes for the other affected connectors, too.

**Pull request merged**
