### PR TITLE
DBZ-1121 Emit ALTER event for updated tables

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1121

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Interesting; don't we have a test which should be adjusted?

**Comment by jpechane** [comment]
@gunnarmorling There is `io.debezium.connector.sqlserver.SqlServerChangeTableSetIT.readHistoryAfterRestart()`. Fisrt it dailed due to NPE and then due to changes I forgot to add to
`io.debezium.connector.sqlserver.SqlServerDatabaseSchema.applySchemaChange(SchemaChangeEvent)`.

**Comment by gunnarmorling** [comment]
I guess my question is this: should we have a test which recovers the history and asserts the correct type for a CREATE TABLE event and ALTER TABLE event?

**Comment by jpechane** [comment]
@gunnarmorling Test added

**Comment by gunnarmorling** [comment]
LGTM, applied. Thanks, @jpechane1

**Pull request merged**
