### PR TITLE
Updated MySQL connector Jenkins job to use custom ports for MySQL

### PR DESCRIPTION
**Pull request by jcechace**
1) Jenkins slaves in http://ci.hibernate.org have a MySQL server already running at port 3306 (probably with root permissions).
2) SourceTaskContext#configs() wasn't present in Kafka API v1.x, thus removing @Override annotation

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane?

**Comment by jpechane** [comment]
@jcechace Fine for me. Please prefix the commit messages with `[jenkins-jobs] ` stirng prefix so we can easily categorise them

**Comment by gunnarmorling** [comment]
Could you merge it then, please? Thanks!

>

**Comment by jcechace** [comment]
@jpechane  done

**Pull request merged**
