### PR TITLE
DBZ-4610 Upgrade to Kafka 3.1.0

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4610

### CODE REVIEW

**Comment by Naros** [comment]
@jpechane one thing I noticed is several warnings from Kafka after we moved to Kafka 3.0 about the usage of:

* `internal.key.converter`
* `internal.value.converter`

These are used inside `EmbeddedEngine` and from what I can tell have been removed from Kafka.  Should we also remove these to avoid the warnings when using Debezium Server or the Embedded engine?

**Comment by gunnarmorling** [comment]
@Naros, yeah, we should. If you're quick, we can still attribute this to https://issues.redhat.com/browse/DBZ-4514, which dealt with that removal in a slightly different context.

**Comment by tooptoop4** [comment]
@jpechane does this mean debezium no longer works with kafka 2.x brokers?

**Comment by rk3rn3r** [comment]
@tooptoop4 no, Kafka brokers always understand older protocol versions and convert older requests. You might have to estimate with some overhead for the conversion though.

**Comment by tooptoop4** [comment]
@rk3rn3r isn't this opposite? newer client but older broker

**Pull request merged**
