### PR TITLE
DBZ-3913 Specify branch name on push/pull_request step

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-3913

### CODE REVIEW

**Comment by ani-sha** [comment]
cc: @gunnarmorling

**Comment by gunnarmorling** [comment]
LGTM, will merge once the currently pending release is done. That said, I could swear we already had those branch names in that config before, did they got lost somehow along the way?

**Review by gunnarmorling — APPROVED** [review]

**Comment by ani-sha** [comment]
@gunnarmorling We have those for connector repositories, but missed it here. Anyway we have it now :)

**Comment by gunnarmorling** [comment]
Gotcha, thanks!

**Pull request merged**
