### PR TITLE
DBZ-4677 Upgrade to Quarkus 2.7.0.Final

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-4677

### CODE REVIEW

**Comment by Naros** [comment]
@jpechane I just noticed the note that this needs to be aligned with apicurio.  Where exactly would I find that for my own benefit since I tend to be the one upgrading Quarkus as I see their releases on the platform list.

**Comment by gunnarmorling** [comment]
> this needs to be aligned with apicurio.

That's interesting, why would that be? Apicurio is its own process, thus any library versions should be independent between the two projects? Or is this about the Apicurio converter dependencies (which shouldn't directly be related to Quarkus, though?

**Comment by Naros** [comment]
That was my understanding @gunnarmorling but since I saw the message I just wanted to affirm there wasn't a problem by me just bumping up Quarkus to 2.7 wrt apicurio.

**Comment by gunnarmorling** [comment]
Tbh. I can't really think of any problem here. Apicurio is a separate process, so whatever dependency versions it has, won't matter for Debezium. The exception would be the converters and their dependencies, but I don't think there'll be a problem here either, in particular given that versions already diverged before, as you mentioned. I'll go ahead and merge this. Thx!

**Pull request merged**
