### PR TITLE
DBZ-1362 Stabilize test executions on CI

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Could we use Awaitility for this kind of logic (if there's no way around it)?

**Comment by jpechane** [comment]
@gunnarmorling Awaitility implementation added. Unfrotunately we need to handle missing https://github.com/awaitility/awaitility/issues/48

**Comment by gunnarmorling** [comment]
Nice. It should have a JIRA issue, though.

**Comment by gunnarmorling** [comment]
Nice, merged. Thanks a lot, @jpechane!

**Pull request merged**
