### PR TITLE
DBZ-7095 The MySqlParser.g4 parser has a priority problem

### PR DESCRIPTION
**Pull request by caicancai**
The MySqlParser.g4 parser has a priority problem, symbols such as */% should not have the same priority as +- symbols

### CODE REVIEW

**Comment by caicancai** [comment]
cc @jpechane

**Comment by caicancai** [comment]
After restoration：
fixed

Before:
屏幕截图 2023-10-31 172227

**Comment by caicancai** [comment]
I have used antlr4 plugin of idea to verify it, but I don't know if it is accurate

**Comment by caicancai** [comment]
https://github.com/antlr/grammars-v4/pull/3804

**Comment by jpechane** [comment]
@caicancai Thanks a lot. Will you please port the changes via this or a new PR when the upstream PR is merged?

**Pull request closed without merging**
