### PR TITLE
DBZ-6070 DDL events not stored in schema history topic for excluded tables

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6070

### CODE REVIEW

**Review by jpechane — CHANGES_REQUESTED** [review]
@harveyyue Thanks for the PR. It looks good for MySQL. Still my question is, does it work in the same way for Oracle/SQL Server/Db2? IMHO the method is exposed but used only by MySQL, not elswhere.

**Comment by harveyyue** [comment]
> @harveyyue Thanks for the PR. It looks good for MySQL. Still my question is, does it work in the same way for Oracle/SQL Server/Db2? IMHO the method is exposed but used only by MySQL, not elswhere.

Yes, you are correct. I'm not sure whether to apply this option to Oracle/SQL Server/Db2 connectors since it will break the current captured schema behavior. This option's default is true means it only captures the tables from specified schema/database. 
Ok, I will apply this option to the others.

**Comment by jpechane** [comment]
@harveyyue It is ok if default value is different for connectors. Please see `io.debezium.connector.db2.Db2ConnectorConfig.QUERY_FETCH_SIZE` as an example. I'd recommend to create the common option that sets the default corresponding to Db2/Oracle/SQL Server and then override it in MySQL.

**Comment by harveyyue** [comment]
@jpechane Got it.

**Comment by harveyyue** [comment]
Related pr:
Db2: https://github.com/debezium/debezium-connector-db2/pull/97

**Comment by Naros** [comment]
Hi @harveyyue did we check whether the `schema.exclude.list` or `table.exclude.list` impacted this behavior similar to the `database.exclude.list`?

**Comment by harveyyue** [comment]
> Hi @harveyyue did we check whether the `schema.exclude.list` or `table.exclude.list` impacted this behavior similar to the `database.exclude.list`?
No, these filters only will work on enabling the property `schema.history.internal.store.only.captured.tables.ddl`, otherwise will capture all non-system table schemas.

**Comment by harveyyue** [comment]
@jpechane I will rebase it.

**Comment by jpechane** [comment]
@harveyyue Applied, thanks!

**Pull request merged**
