### PR TITLE
DBZ-6736 Add support for ALTER TABLE IF EXISTS

### PR DESCRIPTION
**Pull request by joschi**
https://issues.redhat.com/browse/DBZ-6736

MariaDB supports conditionally altering tables with the `IF EXISTS` clause.

Refs
- https://mariadb.com/kb/en/alter-table/
- https://github.com/antlr/grammars-v4/pull/3642

### CODE REVIEW

**Comment by mfvitale** [comment]
@joschi  Seems that you opened 3 PRs for the same. Can you please close the others?

**Review by mfvitale — APPROVED** [review]

**Comment by joschi** [comment]
> @joschi Seems that you opened 3 PRs for the same. Can you please close the others?

@mfvitale The other pull requests were opened against the respective version branches (`2.3` and `2.4`).

Happy to close them. Is the commit from the `main` branch going to be cherry-picked onto the version branches?

**Comment by mfvitale** [comment]
I think you can for sure close the one on 2.4 since it's the current release so the main branch is enough. 

We usually backport only for critical bugs. 
I let @jpechane decide in this case.

**Comment by joschi** [comment]
> We usually backport only for critical bugs.

At least Debezium 2.3.1.Final contains a bunch of these DDL fixes. 😅 
https://debezium.io/blog/2023/07/27/debezium-2-3-1-final-released/

**Pull request merged**
