### PR TITLE
DBZ-414 Binlog reader position can be overwritten when offset exists

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-414

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @jpechane, can you perhaps add a few words on describing the change on a high level? Nothing fancy needed, just to get the picture a bit quicker. Thx!

**Comment by jpechane** [comment]
If you are using Debezium and lose a part of binlog either beacuse of log or Debezium not running for some time you need to re-execute the snapshot. It might be undesirable in some situations.
On use case for this feature is just skip over the gap and continue processing from the first available binlog. Another is to switch to `schema_only` snapshot mode to re-initialize  schema and then continue with processing from end of binlog.
If this setting is enabed then offsets are dis-regarded and force rewind to either start or end of binlog is executed and reading continues from that point on.

**Comment by pgoranss** [comment]
I like the rewind feature as recovery mode option. 

It would be nice to expand the option to rewind to a specific binlog position, assuming an external tool is keeping track of this, rather than just start and end.

**Comment by jpechane** [comment]
It would be pretty easy to do it for file/offset combo but we need to think about how to handle GTIDs.

**Comment by rhauch** [comment]
Once again, we have to be careful about specifying binlog filename and position within the configuration. Connect workers can restart a connector _at any time_, and if the binlog position is specified in the config the connector will jump to that position even if had already done that already. And you can’t rely upon users to update the config in time before the next rebalance since you don’t know when that will be. 

The best way to set the binlog position is via the proposed offset reset tool. (I don’t have ready access to the kip at this time).

**Comment by pgoranss** [comment]
Do you guys think a heartbeat approach might work better for https://issues.jboss.org/browse/DBZ-414? 

Simply commit a heartbeat message to a dummy topic at some pre-defined frequency which is less than the binlog retention period, like once per hour or day. Wouldn't that commit the latest offset to kafka connect even if no messages have been read during the retention period? Just thinking about preventing the scenario from occurring rather than how to workaround it when it does.

**Comment by jpechane** [comment]
The heartbeat will prevent the situation to happen but it does not mean that this is no longer needed - it is still good for recovery.

**Comment by gunnarmorling** [comment]
Agreed that the heartbeat approach would be great for the use case described in DBZ-220.

About the issue here, can't we simply do a new snapshot (just schema) when being in "schema_only" mode and detecting that we can't continue from the previously stored offset? We'll miss data changes after the connector was shut down before, but that's just the nature of that snapshotting mode.

In terms of the discussed offset management tool, there's [KAFKA-4107](https://issues.apache.org/jira/browse/KAFKA-4107) and @rhauch's [KIP-199](https://cwiki.apache.org/confluence/display/KAFKA/KIP-199%3A+Add+Kafka+Connect+offset+tool).

**Comment by jpechane** [comment]
@gunnarmorling It is exactly what you are talking about - just I provide you with either ignoring all that is in binlog or process at least the events that are stored in binlog.

**Comment by pgoranss** [comment]
Can I get an update on this PR's status? It is one recovery option to workaround the KC defect and it could be useful for other situations. If it's going in will definitely impact implementation for https://issues.jboss.org/browse/DBZ-443 which I'm starting to work on shortly

**Comment by gunnarmorling** [comment]
I don't think we should implement this feature in the suggested way, for the reasons descibed by @rhauch above. It seems to big of a risk to process specific binlog sections twice after restarting/rebalancing without the user knowing. Hence I'd prefer to close this PR.

I still think this is a more desirable approach:

> simply do a new snapshot (just schema) when being in "schema_only" mode and detecting that we can't continue from the previously stored offset. We'll miss data changes after the connector was shut down before, but that's just the nature of that snapshotting mode.

**Comment by jpechane** [comment]
Let's close it for know. If there will be more request from community preferring event re-processing to event gaps we can reconsider the decision and approach.

**Pull request closed without merging**
