### PR TITLE
DBZ-8125 Make ORA-00600 errors related to `krvrdGetUID` retriable

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-8125

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Could you please investigate the test failures?

**Comment by Naros** [comment]
As these errors are related to the Apicurio discussion from today's call, I'm going to proceed with merging as the failures are unrelated to the change and tests pass when Apicurio is not used.

**Pull request merged**
