### PR TITLE
DBZ-3572 Binlog metrics were renamed to streaming

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3572

Needs to be backported to 1.5 branch

### CODE REVIEW

**Review by gunnarmorling — APPROVED** [review]
There's a slight compatibility concern here, but I think that's acceptable. Let's just make sure to point it out in the upgrade notes. Btw. what's the name when enabling the legacy impl, the old one?

**Comment by gunnarmorling** [comment]
Applied to master (1.6) and 1.5.

**Comment by jpechane** [comment]
@gunnarmorling Yes, the old one

**Comment by gunnarmorling** [comment]
> Yes, the old one

Ah, ok, that's great. So there's a way for users to mitigate the change
then, when needed. At least until we remove the legacy impl. Thx!

>

**Pull request merged**
