### PR TITLE
DBZ-6758 When using pgoutput in postgres connector, (+/-)Infinity is not supported in decimal values

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6758

### CODE REVIEW

**Comment by jpechane** [comment]
@harveyyue Thanks for the PR. The statement `io.debezium.connector.postgresql.AbstractRecordsProducerTest.INSERT_NUMERIC_TYPES_STMT` was expected to test infinite values and was passing before the change. Could you please check why it was the case? If this scenario is not cevered, could you please add another test?

**Comment by harveyyue** [comment]
@jpechane OK

**Comment by harveyyue** [comment]
@jpechane The IT `AbstractRecordsProducerTest ` not match following properties:
```
plugin.name=pgoutput
decimal.handling.mode=string
```

**Comment by jpechane** [comment]
@harveyyue Makes sense. Apllied, thanks a lot!

**Pull request merged**
