### PR TITLE
DBZ-3676 Use old mining strategy when LOB support is disabled

### PR DESCRIPTION
**Pull request by Naros**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Naros, so should this one still go into 1.6 Final?

**Comment by Naros** [comment]
@gunnarmorling Yes, I've got a small fix related to this that will need to go into 1.6 Final, just waiting on ChapeauClaque to give the code a day or two more in baking to make sure it's working as we expect before doing so.

**Comment by Naros** [comment]
I'll fixup this PR eventually to satisfy https://issues.redhat.com/browse/DBZ-3676

**Comment by gunnarmorling** [comment]
@Naros, anything else needed for this one?

**Comment by gunnarmorling** [comment]
Applied; thx!

**Pull request merged**
