### PR TITLE
DBZ-466 Remove hardcoding of schema version number, leaving it empty …

### PR DESCRIPTION
**Pull request by david-szabo-epam**
…instead

https://issues.jboss.org/browse/DBZ-466

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @david-szabo-epam, thanks a lot!

I was testing this change with a simple SMT, but instead of the schema version from the registry I'm always getting null when calling `record.valueSchema().version()` in that SMT. Can you share the code perhaps which you use to obtain the actual version from the registry?

**Comment by david-szabo-epam** [comment]
Hi @gunnarmorling ,
Our pipeline looks like this: MySQL -> Kafka -> AWS S3

We ended up using the version in a custom partitioner for Confluent's S3SinkConnector:

Here's relevant part of the code (we're using Scala):
```scala
import io.confluent.connect.storage.partitioner.TimeBasedPartitioner
import org.apache.kafka.connect.sink.SinkRecord

class SchemaAndTimeBasedPartitioner[T] extends TimeBasedPartitioner[T] {
...
  override def encodePartition(sinkRecord: SinkRecord): String = {
    val datePath = super.encodePartition(sinkRecord)
    val version = sinkRecord.valueSchema().version()
    ...
  }
```

To be honest I'm not sure, if schema registry version is already available for Debezium source connector's SMTs, but it definitely impacts the version observed on sink side (as did Debezium's hardcoded version that I just removed).

**Comment by gunnarmorling** [comment]
Hey, yeah, just figured, too, that the version likely only will be visible when applying the SMT on the sink side. Which makes sense as the Avro serializer hasn't kicked in when the SMT is applied in the source connector.

**Comment by gunnarmorling** [comment]
Nice, seeing the version as managed by the registry from within an SMT on the sink side, just as expected.

**Comment by gunnarmorling** [comment]
Applied; thanks, @david-szabo-epam!

**Pull request merged**
