### PR TITLE
DBZ-1933 Add anchors to connector properties

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1933

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Wow! I hope you used sed or something similar and didn't add those all by hand :)

**Comment by gunnarmorling** [comment]
@Naros, great work! One tiny nit: when going to one of the anchors, it's slighty scrolled to much down, i.e. the specific item is hidden behind the bread-crumb. At least that's what I'm observing with Firefox. Do you see this, too?

**Comment by Naros** [comment]
@gunnarmorling So what I see is this:

image

Is that what you're seeing?

If that's the case, what we could do is apply a small style change so that these specific anchors have a slight padding amount to the top so that when they scroll they're pushed down slightly so the top of the text does not look like its being cut-off, like this:

image

**Comment by Naros** [comment]
Rebased against latest master.

**Comment by gunnarmorling** [comment]
Yes, it's like that, only that it's even scrolled up a bit further on FF.
I.e. the prop name is literally hidden by the bread-crumb. Interestingly,
this only shows up on FF, and only when directly invoking an anchor URL.
When clicking on one of the props on the page, it is scrolled about right.
So, yes, maybe add a bit of padding if it's possible. How is the behaviour
for you?

>

**Comment by Naros** [comment]
Oh thanks, I can fully reproduce the completely hidden scenario - thanks!  I'll take a look.

**Comment by Naros** [comment]
So this behavior seems to be specific to Firefox and from what I have found, any anchor exhibits this problem, not just for the configuration options.  The solution I've found requires we apply a certain type of style to the anchors to work with the fixed header, but I need to see if I can do this non-intrusively as not to impact the downstream rendering of the docs.

**Comment by Naros** [comment]
So after discussion with the Antora developers, we've concluded this is likely a bug with their default-ui templates and as such I've filed https://gitlab.com/antora/antora-ui-default/-/issues/132

**Comment by gunnarmorling** [comment]
@Naros, ok, thanks for clarifying. WDYT, should we still move forward with this PR and merge it? I think we can, it's not that big of a problem and being able to link to props is a nice improvement.

**Comment by Naros** [comment]
I believe we should; it seems the issue is somewhat of a corner case.  If we find it becomes more of a problem, we can then come back and spend more cycles on trying to find a solution.  I do share the sentiment the Antora guys have that I think this is a Firefox bug based on what Dan mentioned in the associated Antora issue.

**Comment by gunnarmorling** [comment]
Ok, cool. Will apply then. Btw. should we pull in the latest changes from the default theme occassionally? IIRC we have a fork, but perhaps they applied fixes/improvements upstream which would be good to have?

**Pull request merged**
