### PR TITLE
DBZ-7828 Correct filter query in snapshot task to handle SQLServer table quote

### PR DESCRIPTION
**Pull request by mfvitale**
closes: https://issues.redhat.com/browse/DBZ-7828

### CODE REVIEW

**Review by jpechane — COMMENTED** [review]
@mfvitale LGTM, thanks! Please feel free to merge and backport yourself if Oracle failures are unrelated.

**Comment by mfvitale** [comment]
@Naros Seems oracle failures are not related, are you aware of these test failures?

**Pull request merged**
