### PR TITLE
[DBZ-274] Enable Maven caching

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Looks good (apart from the CI failure), @jpechane. Could you log a JIRA issue though and re-word the commit messages to reference the issue key? Thanks!

**Comment by jpechane** [comment]
Closing to trigger a build again

**Comment by jpechane** [comment]
Reopening to trigger a build again

**Comment by gunnarmorling** [comment]
Rebased and applied; thanks, @jpechane!

**Pull request merged**
