### PR TITLE
DBZ-1828 Removing deprecated SMT options

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-1828

### CODE REVIEW

**Comment by Naros** [comment]
I think we need to consider [DBZ-1791](https://issues.redhat.com/browse/DBZ-1791) as well since the removal of the deprecated options I believe is what we wanted to align in this issue, right?

**Comment by gunnarmorling** [comment]
Ah yes, you are right. I wasn't aware that the removed fields are referenced by the MongoDB SMT, too. As DBZ-1791 is assigned to you, perhaps you could take over this branch and add this on top?

**Comment by gunnarmorling** [comment]
@Naros, to be sure, you'll pick up this one, right?

**Comment by Naros** [comment]
@gunnarmorling indeed, its on my list for today.

**Comment by Naros** [comment]
So unless you disagree, I'm going to keep `operation.header` and `add.source.fields` in the MongoDB implementation marking them deprecated and add the `add.headers` and `add.fields` options as the replacements.  That way the migration for `ExtractNewDocumentState` SMT should be seamless for users at least for the next minor release.

**Comment by Naros** [comment]
I'm closing this PR in favor of PR #1492

**Pull request closed without merging**
