### PR TITLE
DBZ-3457 incremental snapshots doc

### PR DESCRIPTION
**Pull request by roldanbob**
[DBZ-3457](https://issues.redhat.com/browse/DBZ-3457)

Updates to signaling, ad hoc and incremental snapshot docs, and docs for SQL-based connectors. 

Supersedes earlier PR #2923 that I closed because it had grown stale and required too much work to rebase.

This change represents a significant update to the existing upstream docs with a good deal of restructuring. I split the ref-connector-incremental-snapshot.adoc file in two to create a separate ad hoc snapshots file (needed to support downstream use), moved content around from the signaling and original incremental snapshots files, and incorporated content from the  [incremental snapshots blog post](https://debezium.io/blog/2021/10/07/incremental-snapshots/) by @jpechane and the 1.6.x release announcements by Jiri and @Naros .  

As you review, please verify that I've included all of the necessary content and that I've correctly captured the sense that was originally intended. Also, let me know whether you think that the extensive background about how incremental snapshots work is too much and should be trimmed back. 

Tested in local Antora build

Please backport to 1.6 and 1.7 branches. 
Do we need to also backport to 1.8?

### CODE REVIEW

**Comment by roldanbob** [comment]
I forgot to remove the WIP from the PR title, so I just did that.

**Comment by gunnarmorling** [comment]
@jcechace, could you take a look at this one?

**Comment by roldanbob** [comment]
Conflicts in `db2.adoc` and `postgresql.adoc` are due to  duplicate entries for `snapshot.chunk.size` and `signal.data.collection` properties. Both of the entries flagged as conflicts should be removed. The entries that should be preserved contain a [product] conditional with a note to indicate that snapshots and signaling are Tech preview features.

**Comment by roldanbob** [comment]
@gunnarmorling  @jcechace Hoping that someone can give this a look-see early this week.

**Comment by gunnarmorling** [comment]
@roldanbob, yes, it's on @jcechace's list for this week. @jpechane, you should take a look as well, please.

@roldanbob, this will need a rebase in any case, so as to resolve those merge conflicts. Thx.

**Comment by jcechace** [comment]
@gunnarmorling  LGTM however my knowledge on this is limited.

**Comment by roldanbob** [comment]
> this will need a rebase in any case, so as to resolve those merge conflicts. Thx.

@gunnarmorling Rebased and force pushed. Pending approval this should now be all set.

**Comment by roldanbob** [comment]
I've run into some problems with the way that the content is building downstream, so I've got to do some pretty broad refactoring to resolve the ID conflicts. I will probably close this to PR and start fresh.

**Pull request closed without merging**
