### PR TITLE
Alwyas shut down records processing thread pool and offset store

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-7661

### CODE REVIEW

**Comment by jpechane** [comment]
@vjuranek Given the amount of failures, can it be related?

**Comment by vjuranek** [comment]
Converting to draft until I do more detail investigation of the failures.

**Comment by vjuranek** [comment]
Indeed was related:-)

**Comment by vjuranek** [comment]
Test failures are unrelated - DBZ server failed again due to Redis [DBZ-7692](https://issues.redhat.com/browse/DBZ-7692), SQL server due to flaky `IncrementalSnapshotWithRecompileIT.stopCurrentIncrementalSnapshotWithAllCollectionsAndTakeNewNewIncrementalSnapshotAfterRestart` and `IncrementalSnapshotWithRecompileIT.stopCurrentIncrementalSnapshotWithoutCollectionsAndTakeNewNewIncrementalSnapshotAfterRestart` (both are now marked as flaky but for some reason not ignored - still haven't figured out why) and finally `SqlServerConnectorIT.shouldStopRetriableRestartsAtConfiguredMaximumDuringSnapshot` failed with `Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Database 'testDB2' is in transition. Try the statement later.` which is probably and issue with the DB, so I'm not marking this tests as flaky.

**Comment by jpechane** [comment]
@vjuranek Applied, thanks!

**Pull request merged**
