### PR TITLE
[DBZ-1389] Added MongoDB 4.2 to test matrix]

### PR DESCRIPTION
**Pull request by jcechace**

### CODE REVIEW

**Comment by jpechane** [comment]
@jcechace Could you please fix the commit comment? The DBZ-... should not be in braces and there is addtional `]` at the end of the messgae. Thanks!

**Comment by jpechane** [comment]
@jcechace MongoDB 4.2 is missing so the test cannot be executed - see https://github.com/debezium/docker-images/tree/master/mongo-initiator

**Comment by gunnarmorling** [comment]
Modified the commit message and applied. Thanks, @jcechace!

**Comment by gunnarmorling** [comment]
@jcechace, can you please always add a link to the JIRA issue when creating a PR. Makes it a bit easier to handle. Thx!

**Pull request closed without merging**
