### PR TITLE
DBZ-2305 fix mysql decimal deminsion issue

### PR DESCRIPTION
**Pull request by michaelwang**
fix mysql decimal deminsion issue
https://issues.redhat.com/browse/DBZ-2305

### CODE REVIEW

**Comment by jpechane** [comment]
@michaelwang LGTM Thanks! Could you just please replace the non-ASCII (chinese) chars in comments and strings with plain ASCII ones? This way it is easier to edit file when needed by international community.
Also it would be great if you could create a PR in upstream project (https://github.com/antlr/grammars-v4) so other projects can benefit from your work too.

**Comment by jpechane** [comment]
@michaelwang I am sorry, I close the PR accidentally, reopening it.

**Comment by gunnarmorling** [comment]
Thanks, @michaelwang! In addition to what Jiri said, could you please also author the commit using a email address linked to your GitHub account? That way it will properly be attributed to you in history and stats. Thanks!

**Comment by gunnarmorling** [comment]
Hey @michaelwang, do you think you might address the review remarks by next week? We're planning to do a release on Wednesday. Thx!

**Comment by michaelwang** [comment]
sorry , I mess up the PR, I will do it again.

**Comment by michaelwang** [comment]
Hi @jpechane  @gunnarmorling  

   I create a new PR https://github.com/debezium/debezium/pull/1693 , 
and did the following : 
1, fix the git commit author info which linked to GITHUB
2. replace the non-ASCII character with ASCII character

addition: I will pull request to https://github.com/antlr/grammars-v4 

Thanks.

**Pull request closed without merging**
