### PR TITLE
DBZ-3748 Build non-core connectors with PR branch of debezium main repo

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-3748

### CODE REVIEW

**Comment by ani-sha** [comment]
Hi @Naros, here is my take on what you requested for GH actions to trigger build based on the PR branch.
FYI, after this gets reviewed there will be incoming changes in respective connector workflows.

**Comment by Naros** [comment]
So if I understand, any change made to the common paths in a PR will result in the sibling repositories being built but only if the sibling repository has a pull request using the same branch name as the core repository's PR.  Since it's a cross-repository dispatch, do we see this sibling's build status in the main repository's pull request actions or only in the sibling repository?  

> incoming changes in respective connector workflows

Sure, what type of changes should we expect there exactly?

**Comment by ani-sha** [comment]
> Since it's a cross-repository dispatch, do we see this sibling's build status in the main repository's pull request actions or only in the sibling repository?

The sibling's build status can be seen in the sibling repository itself, not in the main repository. 

> Sure, what type of changes should we expect there exactly?

I am going to add the changes in db2, which basically would be dispatch workflow that would be triggered by this workflow.

**Comment by ani-sha** [comment]
@Naros Just one question, should we be aiming at a two-way trigger or just one-way? For example, one repository dispatch action from main to siblings, or it should be vice versa too?

**Comment by gunnarmorling** [comment]
Hey @Naros, leaving this one to you to handle. That being said: isn't still likely to happen that the first PR build is going to fail in such situation, as not all PRs will be created at the same time? I.e. some manual re-triggering will be needed one all PRs are there?

**Comment by jpechane** [comment]
Will not it work in this way?

* the developer will create core PR
* the developer will create connector repo PR
* connector jobs on core will fail as connector PRs are not in place yet 
* connector PR job will pass
* connector PR job will trigger core PR build
* core PR build will pass

**Comment by Naros** [comment]
> I.e. some manual re-triggering will be needed one all PRs are there?

@gunnarmorling Yes, I think there will be the need for some re-triggering in the event that PRs get opened in reverse order.  We are assuming that the user creates the core PR first and the connector repo PR afterward as @jpechane describes above, but there is really only so much we can automate and do.

So then @ani-sha based on the latest comments, this is ready from your side?

**Comment by ani-sha** [comment]
> the developer will create core PR
the developer will create connector repo PR
connector jobs on core will fail as connector PRs are not in place yet
connector PR job will pass
 
@jpechane As per your mentioned suggestions, so far these four steps have been achieved. Please see https://github.com/debezium/debezium-connector-db2/pull/29. And please ignore the changes in this PR, consider this as a dummy for testing the builds of db2 repo PR.

> connector PR job will trigger core PR build
core PR build will pass

Can you clarify how these next two would be achieved? I have few questions regarding these steps. 
1. Right now I have created a new workflow in connector PR (Db2), so will that workflow after successful build going to trigger this core PR build? 
2. If yes for (1), Is it possible to trigger this PR build via a dispatch action?

**Pull request closed without merging**
