### PR TITLE
DBZ-6173 Support for upgrading UI build to use Debezium 2.2

### PR DESCRIPTION
**Pull request by jcechace**
There are few things which could still be polished and moved from UI codebase here. 
Just wanted to get it out ASAP so that it can be tested. 

It works-on-my-machine (tm), however I'm running MacOS so it should be tried on linux as well.

### CODE REVIEW

**Review by Naros — APPROVED** [review]

**Review by rk3rn3r — APPROVED** [review]

**Comment by rk3rn3r** [comment]
Nice improvements. Added @ani-sha as reviewer for awareness of the changes.

**Review by ani-sha — APPROVED** [review]
@jcechace Looks good, the TODO in the https://github.com/debezium/debezium-ui/pull/700 should be added to this PR or the done in a follow-up one?

**Comment by ani-sha** [comment]
Also [DBZ-6173](https://issues.redhat.com/browse/DBZ-6173) has been released in CR1, so we need a new Jira for this one. Can you please create a new ticket and change it accordingly @jcechace? Thanks.

**Comment by jcechace** [comment]
@ani-sha  yes, the TODO should be added on tom of these changes. I will create the ticket and finish things here. 

@rk3rn3r  Before I do this, I need somebody to test these change on Linux machine. Just build this locally and try the changes in https://github.com/debezium/debezium-ui/pull/700

**Comment by jcechace** [comment]
Superseded by #4473

**Pull request closed without merging**
