### PR TITLE
DBZ-6714 Set precision of MySQL unsigned bigints in output decimal type

### PR DESCRIPTION
**Pull request by benesch**
When using the "precise" configuration for `bigint.unsigned.handling.mode`, the output decimal types were not specifying a precision. Adjust the code to generate an Avro schema with a decimal precision of 20, which is sufficient to represent all possible unsigned bigints.

**Warning to reviewer:** I couldn't get the tests running locally, so I was only able to test that this compiled, not that the test succeeded.

### CODE REVIEW

**Comment by benesch** [comment]
Thanks very much for the fix!

> Why can't you run the tests?

The MySQL connection fails with a complaint about `unknown_ca`:

```
Caused by: javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca
```
https://gist.github.com/benesch/0568bd207e0d5a76ec3de0db2edc0fcc

I spent 30m trying to this figure out to no avail. I'm running the MySQL server via the Debezium-provided Docker image, so I don't understand what's going wrong!

**Comment by benesch** [comment]
@jpechane the MySQL 5.7 job failed, but it looks unrelated to this PR?

```
2023-07-25T14:55:24.9517716Z [INFO] 
2023-07-25T14:55:24.9524299Z [INFO] Results:
2023-07-25T14:55:24.9524568Z [INFO] 
2023-07-25T14:55:24.9524765Z [ERROR] Failures: 
2023-07-25T14:55:24.9525693Z [ERROR]   SnapshotParallelSourceIT>SnapshotSourceIT.shouldCreateSnapshotOfSingleDatabaseWithoutGlobalLock:111->SnapshotSourceIT.snapshotOfSingleDatabase:187 
2023-07-25T14:55:24.9526908Z Expecting:
2023-07-25T14:55:24.9527283Z  <"customers">
2023-07-25T14:55:24.9527650Z not to be equal to:
2023-07-25T14:55:24.9527868Z  <"customers">
2023-07-25T14:55:24.9527991Z 
2023-07-25T14:55:24.9528072Z [INFO] 
2023-07-25T14:55:24.9528465Z [ERROR] Tests run: 297, Failures: 1, Errors: 0, Skipped: 10
```

**Comment by jpechane** [comment]
@benesch Applied, thanks!

For future reference - if you don't run test from Maven then you need to use `-Ddatabase.ssl.mode=disabled`.

**Comment by benesch** [comment]
Thanks so much for the test fix and quick merge, @jpechane!

FYI, the commands I was running to attempt to test were the following.

First, to start the MySQL docker image:

```
mvn -pl :debezium-connector-mysql docker:build docker:start
```

Second, to actually run the test:

```
mvn test -pl :debezium-connector-mysql -Dtest=MySqlUnsignedIntegerIT#shouldConsumeAllEventsFromDatabaseUsingBinlogAndNoSnapshot 
```

That second command was the one failing with `javax.net.ssl.SSLHandshakeException: Received fatal alert: unknown_ca`.

Indeed, passing `-Ddatabase.ssl.mode=disabled` worked!

```
$ mvn test -pl :debezium-connector-mysql -Dtest=MySqlUnsignedIntegerIT#shouldConsumeAllEventsFromDatabaseUsingBinlogAndNoSnapshot  -Ddatabase.ssl.mode=disabled
...
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 1.446 s - in io.debezium.connector.mysql.MySqlUnsignedIntegerIT
[INFO] 
[INFO] Results:
[INFO] 
[INFO] Tests run: 1, Failures: 0, Errors: 0, Skipped: 0
[INFO] 
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  3.713 s
[INFO] Finished at: 2023-07-25T22:04:30-04:00
[INFO] ------------------------------------------------------------------------
```

I'm not familiar enough with Java to know why this is required—pom.xml seems to be disabling the sslmode?—but I won't question it too deeply.

**Pull request merged**
