### PR TITLE
DBZ-43 Changed form of schema change topic to use schemas

### PR DESCRIPTION
**Pull request by rhauch**

### CODE REVIEW

**Comment by mvj3** [comment]
@rhauch It still doesn't work ...

The reproduce steps are:

### 1. change docker-compose's Kafka Connect shell environment

```yaml
connect_schemaregistry:  # a copy of #connect
  build: $PROJECT_DIR/docker/another_company/connect_schemaregistry
  ports:
    - "8088:8088"
  links:
    - zookeeper
    - kafka
  environment:
    - LOG_LEVEL=INFO

    - GROUP_ID=connect_schemaregistry  # need to be different from #connect's
    - CONFIG_STORAGE_TOPIC=my-connect-schemachange-configs
    - OFFSET_STORAGE_TOPIC=my-connect-schemachange-offsets
    - ADVERTISED_HOST_NAME=$DOCKER_MACHINE_IP

    # overwrite default
    - CONNECT_REST_PORT=8088
    - CONNECT_ADVERTISED_PORT=8088
    - CONNECT_REST_ADVERTISED_PORT=8088
    - REST_PORT=8088
    - ADVERTISED_PORT=8088
    - CONNECT_offset.storage.file.filename=/mnt/connect_schemaregistry.offsets

    # Sink task only accepts schema+payload json form, but not schema-changes.topic.
    # 20160512 Fixed by https://github.com/debezium/debezium/pull/39 DBZ-43 Changed form of schema change topic to use schemas #39
    # - CONNECT_key.converter.schemas.enable=false
    # - CONNECT_value.converter.schemas.enable=false
```

### 2. Use https://github.com/rhauch/debezium/tree/dbz-43 branch to compile jar.

### 3. run my Kafka Sink Connector, which reads schema-change topic. (And debezium mysql source connect). And here's the same error

```java
connect_schemaregistry_1 | 2016-05-12 08:02:48,940 - ERROR [WorkerSinkTask-dp-schemachange-sink-connector-0:ShutdownableThread@84] - Thread WorkerSinkTask-dp-schemachange-sink-connector-0 exiting with uncaught exception: 
connect_schemaregistry_1 | org.apache.kafka.connect.errors.DataException: JsonDeserializer with schemas.enable requires "schema" and "payload" fields and may not contain additional fields
connect_schemaregistry_1 | 	at org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:323)
connect_schemaregistry_1 | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.convertMessages(WorkerSinkTask.java:265)
connect_schemaregistry_1 | 	at org.apache.kafka.connect.runtime.WorkerSinkTask.poll(WorkerSinkTask.java:175)
connect_schemaregistry_1 | 	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.iteration(WorkerSinkTaskThread.java:90)
connect_schemaregistry_1 | 	at org.apache.kafka.connect.runtime.WorkerSinkTaskThread.execute(WorkerSinkTaskThread.java:58)
connect_schemaregistry_1 | 	at org.apache.kafka.connect.util.ShutdownableThread.run(ShutdownableThread.java:82)
```

The error stack shows it happens before Kafka Connect transfer the data to our schema change connector's `put` method, and it throw error at when it read the Kafka message `org.apache.kafka.connect.json.JsonConverter.toConnectData(JsonConverter.java:323)`

### 4. the conclusion
So I suggest maybe we should add `#toConnectData` test which reads a mock Kafka schema-change message data.

**Comment by rhauch** [comment]
@mvj3, I'm not sure that I really corrected the problem you were seeing. The first commit was rebased on top of the latest `master`, while the new second commit adds explicit checking and validation of the key, key schema, value, and value schema for each consumed message, via round-tripping with the `JsonConverter` and `JsonDeserializer`. 

All the tests pass, but I've not had a chance to look into the problem you were seeing. In fact, I'm not convinced I have enough information to even replicate your tests. For example, what is `$PROJECT_DIR/docker/another_company/connect_schemaregistry` in your info above?

**Comment by mvj3** [comment]
@rhauch the same error happens again ...

Our requirement  is very simple, just write a Kafka Sink Connector to consume schema-change topic which generated by Debezium Source Connector. And the messages format here lacks schema+payload  structure.

Anyway, it's a little difficult for you to reproduce the same error, I'll fix it by myself later, and send a PR. Thanks for this additional job here, it helps :)

-------------------------

`$PROJECT_DIR/docker/another_company/connect_schemaregistry ` looks like

```dockerfile
FROM debezium/connect:0.1

EXPOSE 8084

ENV CONNECTOR_JAR_PATH=/kafka/connect/debezium-connector-mysql/

# .. copy some compiled jars to CONNECTOR_JAR_PATH

ENTRYPOINT ["/docker-entrypoint.sh"]
CMD ["start"]
```

**Comment by rhauch** [comment]
@mvj3, thanks. If you don't mind, please create a PR based on my branch for this PR. That way I can merge it into this PR.

**Comment by mvj3** [comment]
@rhauch sure. And I'll fix it in the next few weeks. Right now I'm still working on other issues.

If anyone wants this feature too, then I shall work on it timely.

**Comment by rhauch** [comment]
It would be great to include this change into Debezium 0.2, which I hope to wrap up before May 25.

**Comment by mvj3** [comment]
@rhauch Cool

**Comment by rhauch** [comment]
@mvj3, I'm going to merge this since the schemas created by it are needed for [DBZ-52](https://issues.jboss.org/browse/DBZ-52). Any issues with this?

**Comment by mvj3** [comment]
@rhauch Great. Since this PR doesn't break the test cases.

**Comment by rhauch** [comment]
Rebased the PR on latest 'master' and refactored some of the integration tests to be much more clear and explicit in their assertions. Also, corrected the logic writing records to the change topic to write only those DDL statements that apply to the list of filtered databases.

**Comment by mvj3** [comment]
@rhauch Cool! 👍

**Pull request merged**
