### PR TITLE
[DBZ-1075] ByLogicalTableRouter should support MongoDB

### PR DESCRIPTION
**Pull request by dvfeinblum**
See [this](https://issues.redhat.com/projects/DBZ/issues/DBZ-1075) ticket for more info.

### CODE REVIEW

**Comment by jpechane** [comment]
@dvfeinblum Hi, thanks for the PR but I think there is a misunderstanding in the problem.

1. I recommend you to extend the test {{io.debezium.transforms.ByLogicalTableRouterTest}} with a new test that would set *key* and *value* of the message that is passed to the transformation. Unfrotunately such test is missing and this is definitely pitential quality risk. You'd use three messages - create, update, delete with MySQL schema
2. When the test above will be passing then you'd add another one but for MongoDB format so create/patch/delete
3. If I read code correctly the test above should fail due to missing `before` field
4. If this is the case then you'd modify the code of `io.debezium.transforms.ByLogicalTableRouter<R>` to ensure that ` before` is no longer mandatory

Do you think this is mor einline with DBZ-1075? Thanks for your feedback!

**Comment by gunnarmorling** [comment]
Hey @dvfeinblum, howdy? Anything we should discuss here in order to move forward with it?

**Comment by dvfeinblum** [comment]
Hi @gunnarmorling. Sorry for the lack of activity. Work's been really hectic this week. I have marching orders for this work, just need a spare second to actually get to it. Sorry for the delay!

**Comment by gunnarmorling** [comment]
No worries, just wanted to check in. Take all the time you need. Thanks a
lot!

>

**Comment by gunnarmorling** [comment]
Hey @dvfeinblum, going to reply here to your question via DM, so everyone is on the same page. 

The problem with the existing test (`ByLogicalTableRouterTest`) is that needs to build a `SourceRecord` from scratch which resembles the actual records as produced by Debezium. That's not only tedious work, but also quite error-prone, as their might be differences between the record structure produced by the actual connectors and the "emulated" one created in tests. Funnily, there's even a comment along these lines at the end of this test class.

This is why I think we should take a different route and rely on more integrative tests for that SMT, running the actual connectors, applying the SMT to the produced record(s) and assert the outcome. There already is a similar example: `EventRouter` (an SMT for routing outbox events) with accompanying unit test `EventRouterTest` for some basic testing and `OutboxEventRouterIT` in the Postgres connector module for more advanced testing on the actual record structure. Doing the same for the table router will result in better test fidelity and lesser effort to implement it.

So here's what I suggest:

* Leave `ByLogicalTableRouterTest` as is (well, removing that comment at the bottom perhaps ;)
* Add two new integration tests, one in the PG connector module, one in the MongoDB connector module
* Each test should do an INSERT, UPDATE and DELETE, apply the SMT and assert the resulting records; in particular, it should assert that:
  * the topic of the record has been adjusted to the expected value
  * the schema name of the `Envelope` struct has been adjusted as expected (as it contains the topic name, e.g. "mysql-server-1.inventory.customers.Envelope")
  * the schema name of the `Before` and `After` structs have been adjusted as expected; this applies only to the test in the PG connector module; for MongoDB, which is a schemaless datastore, there is no counterpart to these schemas, as the change event value is a stringified JSON in the `after` and `patch` fields
 * Adjust the `ByLogicalTableRouter` implementation so it no longer stumbles upon MongoDB change events without `Before` and `After` structs

As @jpechane has been saying, the test in the MongoDB connector module will fail until you've adjusted the implementation, whereas the Postgres one should pass already. I think it helps to take a look at the two schemas for Postgres (or any other relational Debezium connector) and MongoDB, too:

* Postgres: https://debezium.io/documentation/reference/connectors/postgresql.html#create-events
* MongoDB: https://debezium.io/documentation/reference/connectors/mongodb.html#mongodb-change-events-value

Note how the topic name surfaces in the names of the `Envelope`, `Before` and `After` schemas for the relational connectors, but only in the `Envelope` schema name for MongoDB.

Does that help? If not, please let me know what needs further clarification. Thanks a lot!

**Comment by gunnarmorling** [comment]
@dvfeinblum, I saw some question of you on this somewhere a few days ago, but can't find it any more. Let's centralize discussion here, that way it's easier to keep track. Thanks!

**Comment by dvfeinblum** [comment]
I'm gonna bravely step back from this work for the time being. Work's getting a bit busy and I don't have time to figure this out at the moment.

**Comment by gunnarmorling** [comment]
Ok, thanks for the update, @dvfeinblum. Whenever you feel like picking up this one (or something else), just get in touch. Don't be a stranger :)

**Pull request closed without merging**
