### PR TITLE
Dbz 713

### PR DESCRIPTION
**Pull request by n3pathi**
https://issues.jboss.org/browse/DBZ-713

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @n3pathi, thanks for opening this PR! I'm a bit unsure now: does this solve the issue for you, or is there still a problem and you need help with it? Thanks!

**Comment by gunnarmorling** [comment]
Could you also share the error/exception you get with and without your PR (ideally add it to the issue in JIRA, please)?

**Comment by gunnarmorling** [comment]
Hey @n3pathi, could you share some more details on this one? Would be good to know whether this PR solves the issue or not. Thanks!

**Comment by n3pathi** [comment]
The error message when the connector user is trying to list collections on a database with no access

30.116:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on <db_name> to execute command { listCollections: 1, cursor: { batchSize: 0 } }", "code" : 13, "codeName" : "Unauthorized" }   [io.debezium.connector.mongodb.Replicator]
connect_1    | com.mongodb.MongoCommandException: Command failed with error 13: 'not authorized on <db_name> to execute command { listCollections: 1, cursor: { batchSize: 0 } }' on server 10.2.130.116:27017. The full response is { "ok" : 0.0, "errmsg" : "not authorized on <db_name> to execute command { listCollections: 1, cursor: { batchSize: 0 } }", "code" : 13, "codeName" : "Unauthorized" }
connect_1    | 	at com.mongodb.connection.ProtocolHelper.getCommandFailureException(ProtocolHelper.java:115)
connect_1    | 	at com.mongodb.connection.CommandProtocol.execute(CommandProtocol.java:114)
connect_1    | 	at com.mongodb.connection.DefaultServer$DefaultServerProtocolExecutor.execute(DefaultServer.java:168)
connect_1    | 	at com.mongodb.connection.DefaultServerConnection.executeProtocol(DefaultServerConnection.java:289)
connect_1    | 	at com.mongodb.connection.DefaultServerConnection.command(DefaultServerConnection.java:176)
connect_1    | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:216)
connect_1    | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:207)
connect_1    | 	at com.mongodb.operation.CommandOperationHelper.executeWrappedCommandProtocol(CommandOperationHelper.java:113)
connect_1    | 	at com.mongodb.operation.ListCollectionsOperation$1.call(ListCollectionsOperation.java:178)
connect_1    | 	at com.mongodb.operation.ListCollectionsOperation$1.call(ListCollectionsOperation.java:173)
connect_1    | 	at com.mongodb.operation.OperationHelper.withConnectionSource(OperationHelper.java:431)
connect_1    | 	at com.mongodb.operation.OperationHelper.withConnection(OperationHelper.java:404)
connect_1    | 	at com.mongodb.operation.ListCollectionsOperation.execute(ListCollectionsOperation.java:173)
connect_1    | 	at com.mongodb.operation.ListCollectionsOperation.execute(ListCollectionsOperation.java:81)
connect_1    | 	at com.mongodb.Mongo.execute(Mongo.java:836)
connect_1    | 	at com.mongodb.Mongo$2.execute(Mongo.java:823)
connect_1    | 	at com.mongodb.OperationIterable.iterator(OperationIterable.java:47)
connect_1    | 	at com.mongodb.ListCollectionsIterableImpl.iterator(ListCollectionsIterableImpl.java:76)
connect_1    | 	at com.mongodb.MappingIterable.iterator(MappingIterable.java:36)
connect_1    | 	at io.debezium.connector.mongodb.MongoUtil.forEach(MongoUtil.java:99)
connect_1    | 	at io.debezium.connector.mongodb.MongoUtil.forEachCollectionNameInDatabase(MongoUtil.java:89)
connect_1    | 	at io.debezium.connector.mongodb.ConnectionContext$MongoPrimary.lambda$null$3(ConnectionContext.java:333)
connect_1    | 	at java.lang.Iterable.forEach(Iterable.java:75)
connect_1    | 	at io.debezium.connector.mongodb.ConnectionContext$MongoPrimary.lambda$collections$4(ConnectionContext.java:332)
connect_1    | 	at io.debezium.connector.mongodb.ConnectionContext$MongoPrimary.execute(ConnectionContext.java:267)
connect_1    | 	at io.debezium.connector.mongodb.ConnectionContext$MongoPrimary.collections(ConnectionContext.java:328)
connect_1    | 	at io.debezium.connector.mongodb.Replicator.performInitialSync(Replicator.java:264)
connect_1    | 	at io.debezium.connector.mongodb.Replicator.run(Replicator.java:147)
connect_1    | 	at io.debezium.connector.mongodb.MongoDbConnectorTask.lambda$null$1(MongoDbConnectorTask.java:127)
connect_1    | 	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
connect_1    | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
connect_1    | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
connect_1    | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
connect_1    | 	at java.lang.Thread.run(Thread.java:748)

**Comment by gunnarmorling** [comment]
Hey @n3pathi, thanks for your patience!

I could reproduce the issue and implemented a fix, which is slightly different from this one here (and also does some clean-up while I was working on it). Hence I'm going to close this PR, the new one is https://github.com/debezium/debezium/pull/566. This will be part of the upcoming Debezium 0.8.0.CR1 release. Thanks again for your efforts, that's much appreciated!

**Pull request closed without merging**
