### PR TITLE
DBZ-3499 Add support for parsing of newer MySQL privileges

### PR DESCRIPTION
**Pull request by tommyk-gears**
Added the privileges listed at https://dev.mysql.com/doc/refman/8.0/en/privileges-provided.html to the MySQL parser (note that Table 6.3 on that page is incomplete, there are privileges not listed in that table but documented further down in the document, e.g. `SERVICE_CONNECTION_ADMIN`)

### CODE REVIEW

**Comment by jpechane** [comment]
@tommyk-gears Hi, thanks for the PR, it looks good!
I'd just propose one change, I'd recommend to add the test statements into debezium-ddl-parser/src/test/resources/mysql/examples/grant.sql instead of the Java code.
When done could you please also prepare a PR to the upstream grammar - https://github.com/antlr/grammars-v4/tree/master/sql/mysql/Positive-Technologies
With the example statements moved to the SQL file you'd be able to prepare it with almost no problem.

**Comment by jpechane** [comment]
@tommyk-gears I am doing a release today so I took a liberty and did the changes, could you please still prepare the usptream PR and link it here?

**Comment by tommyk-gears** [comment]
@jpechane Thanks for quick feedback and for fixing my messy test case!
I created the upstream PR here: https://github.com/antlr/grammars-v4/pull/2184

**Comment by jpechane** [comment]
@tommyk-gears Thanks a lot!

**Pull request merged**
