### PR TITLE
Update CONTRIBUTE.md for CI migration from Travis to GitHub Actions

### PR DESCRIPTION
**Pull request by ani-sha**
Any more quick points to add? 

cc : @gunnarmorling

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha LGTM, applied

**Comment by gunnarmorling** [comment]
Very nice! So now only those modules (and the ones dependent on it) will be rebuilt whose code has changed with a given PR, right? Which is why we don't see any check here for this one besides the formatting and the message check?

**Comment by jpechane** [comment]
@gunnarmorling Exactly

**Comment by gunnarmorling** [comment]
Cool, thx!

>

**Pull request merged**
