### PR TITLE
Update cassandra.adoc

### PR DESCRIPTION
**Pull request by raultov**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, thanks a lot! @bingqinzhou?

**Comment by raultov** [comment]
Hi guys,
maybe you can help me :), debezium-connector-cassandra documentation is not really explicit about how to deploy the connector in a Cassandra node. Do know where I could find further information on how to perform it?
Specifically:
- I do not know how toexecute the jar downloaded from https://mvnrepository.com/artifact/io.debezium/debezium-connector-cassandra/1.0.1.Final It complains about Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Handler
- In case of getting the connector running, how to use this configuration https://debezium.io/documentation/reference/connectors/cassandra.html#example-configuration as input for the connector?

**Comment by Naros** [comment]
Hi @raultov, I would say if there are aspects of the documentation that aren't clear enough, please feel free to open an issue and we'll take a look.  That said, to your specific questions:

> Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.server.Handler

This sounds like you might be missing the `jetty` dependency somehow? 

@bingqinzhou, would it be possible to add a section that describes how to run the connector on the nodes, e.g. what would the classpath/command line look like?

> how to use this configuration

Since the Cassandra connector must run on each node in the cluster, you would run the connector using the configuration file as a command line argument similar to the following:
```
java -cp "<classpath>" io.debezium.connector.cassandra.CassandraConnectorTask <configFile>
```

**Comment by raultov** [comment]
Thanks @Naros for your support, I managed to run it successfully.
Based on my own experience, maybe I can contribute on that section about running the connector on the nodes.

**Comment by gunnarmorling** [comment]
@raultov, sure any improvements to the docs and code are always welcomed. Thanks!

**Comment by gunnarmorling** [comment]
Thanks, @raultov!

**Pull request merged**
