### PR TITLE
Debezium 2.3 Oracle backports

### PR DESCRIPTION
**Pull request by Naros**
Backports for Debezium 2.3 for Oracle missed transaction fixes.

### CODE REVIEW

**Comment by Naros** [comment]
Ok, I'll run the tests locally against Oracle 19 and let you know @jpechane

**Comment by Naros** [comment]
Since this only impacts LogMiner, I just ran those tests: :heavy_check_mark: 
```
[INFO] Debezium Build Aggregator .......................... SUCCESS [  0.450 s]
[INFO] Debezium IDE Formatting Rules ...................... SUCCESS [  0.478 s]
[INFO] Debezium Checkstyle Rules .......................... SUCCESS [  0.856 s]
[INFO] Debezium Revapi Rules .............................. SUCCESS [  0.056 s]
[INFO] Debezium Parent POM ................................ SUCCESS [  0.703 s]
[INFO] Debezium API ....................................... SUCCESS [  6.471 s]
[INFO] Debezium Core ...................................... SUCCESS [01:07 min]
[INFO] Debezium ANTLR DDL parsers ......................... SUCCESS [ 45.575 s]
[INFO] Debezium Assembly Descriptors ...................... SUCCESS [  0.172 s]
[INFO] Debezium Embedded .................................. SUCCESS [05:14 min]
[INFO] Debezium Storage Module ............................ SUCCESS [  0.016 s]
[INFO] Debezium Storage Kafka Module ...................... SUCCESS [  0.316 s]
[INFO] Debezium Storage File Module ....................... SUCCESS [  0.158 s]
[INFO] Debezium Schema Generator .......................... SUCCESS [  0.981 s]
[INFO] Debezium Connector for Oracle ...................... SUCCESS [51:56 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  59:15 min
[INFO] Finished at: 2024-01-08T12:43:05-05:00
[INFO] ------------------------------------------------------------------------
```

**Comment by jpechane** [comment]
@Naros Applied, thanks

**Pull request merged**
