### PR TITLE
DBZ-3873 Extract new top-level menu node for SMTs

### PR DESCRIPTION
**Pull request by uidoyen**

### CODE REVIEW

**Comment by uidoyen** [comment]
@gunnarmorling @rk3rn3r @roldanbob Adding in comment as I am unable to add reviewer.

**Review by Naros — APPROVED** [review]
This LGTM.  Just need confirmation from @roldanbob that the new ToC section is fine for downstream consumption.

**Comment by roldanbob** [comment]
> This LGTM. Just need confirmation from @roldanbob that the new ToC section is fine for downstream consumption.

Yes, @Naros, this works for me. I don't consume the `nav.adoc file directly, so my interest is just informational to enable me to reflect the same changes via the downstream mechanism.

**Comment by gunnarmorling** [comment]
Thx for the change and reviewing, all! Merging.

**Pull request merged**
