### PR TITLE
DBZ-1766 Update lastOffset to commit only after a record is committed

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-1766

Supersedes #1245.

### CODE REVIEW

**Comment by mwinstanley** [comment]
I patched this PR and verified with the same testing as in https://github.com/debezium/debezium/pull/1245 that the problem appears to be fixed (no more missing data on restart).

**Comment by gunnarmorling** [comment]
Thanks for reporting back, @mwinstanley! So the change itself should be good to go, we're just fighting with some (unrelated) issues on CI here...

**Comment by gunnarmorling** [comment]
@jpechane, is the merge commit intended? Way more commits show up here now than expected.

**Comment by gunnarmorling** [comment]
Ok, the remaining test failure is unrelated; merging. Thanks again, @mwinstanley!

**Pull request merged**
