### PR TITLE
DBZ-1688 Fix SQLserver type time(4)...time(7)  lost nanoseconds

### PR DESCRIPTION
**Pull request by liulangwa**
example 

20:50:02.4973002  become 20:50:02.4970000

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks a lot, @liulangwa! Could you please:

* File a JIRA issue and reference its number in the commit message
* Add a test
* Rework the commit to use an email address associated to your GitHub account?

Thanks a lot!

**Comment by liulangwa** [comment]
@gunnarmorling 
https://issues.redhat.com/projects/DBZ/issues/DBZ-1688?filter=allopenissues

**Comment by liulangwa** [comment]
@gunnarmorling 
some checks failed,please restart the job

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks a lot, @liulangwa!

**Pull request closed without merging**
