### PR TITLE
Refactor exporting to CloudEvents: remove RecordParser

### PR DESCRIPTION
**Pull request by rkudryashov**
https://issues.redhat.com/browse/DBZ-7755

I divided what was left in `RecordParser` between `RecordAndMetadata` and `CloudEventsMaker`

As a continuation of the task, [`CloudEventsProvider`](https://github.com/debezium/debezium/blob/main/debezium-core/src/main/java/io/debezium/converters/spi/CloudEventsProvider.java) can also be removed

### CODE REVIEW

**Comment by Naros** [comment]
Hi @rkudryashov can you please follow-up with PRs in the vitess, Informix, and db2 repositories with a branch named `DBZ-7755`, doing so will cause those branches and this one to be built in conjunction to verify that the build works universally across the entire portfolio.  Thanks!.

**Comment by rkudryashov** [comment]
Hi @Naros 

https://github.com/debezium/debezium-connector-vitess/pull/189
https://github.com/debezium/debezium-connector-db2/pull/149
https://github.com/debezium/debezium-connector-informix/pull/40

**Comment by rkudryashov** [comment]
Those new PRs (vitess and informix) was built successfully, but it seems that when building this PR, old versions of those connectors are used, [for example](https://github.com/debezium/debezium/actions/runs/8587080321/job/23530288316?pr=5467):

```
Error:  /home/runner/work/debezium/debezium/informix/src/main/java/io/debezium/connector/informix/converters/InformixRecordParser.java:[23,43] cannot find symbol
```

**Comment by Naros** [comment]
Thanks @rkudryashov, we'll review, thanks for the turn-around on those sibling repo PRs.

**Comment by jpechane** [comment]
@rkudryashov Applied, nice clean-up, thanks!

**Pull request merged**
