### PR TITLE
DBZ-1916 Add tests for datatype.propagate.source.type

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1916

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Added a commit for formatting fixes, rebased and force-pushed.

**Comment by gunnarmorling** [comment]
@Naros, does this option also need addition to docs? Or is it there already?

**Comment by Naros** [comment]
It's already part of the docs, we merely just didn't have the test coverage for the various connectors.

**Comment by gunnarmorling** [comment]
Ok, thanks for clarifying!

**Pull request merged**
