### PR TITLE
DBZ-7020 Use optional schema for Timezone Converter tests

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-7020

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha Could you please add `VerifyRecord` calls to the tests as well so we make sure there is no other issue left?

**Comment by jpechane** [comment]
@ani-sha Could you please add `VerifyRecord` after the transformation too? So the record is verified both befor and after transfromation? Thanks

**Comment by ani-sha** [comment]
@jpechane Could you please give this a final review?

**Comment by jpechane** [comment]
@ani-sha Applied, thanks!

**Pull request merged**
