### PR TITLE
DBZ-5485 Support wait/nowait clause in mariadb

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-5485

### CODE REVIEW

**Comment by harveyyue** [comment]
Same test it failure:
https://github.com/debezium/debezium/pull/3778

2022-08-06T07:04:56.8466097Z [ERROR]   ReadOnlyIncrementalSnapshotIT.lambda$testStopSnapshotKafkaSignal$10:292 expected:<[fals]e> but was:<[tru]e>

**Comment by harveyyue** [comment]
Upstream pr: https://github.com/antlr/grammars-v4/pull/2742

**Review by Naros — APPROVED** [review]
LGTM, thanks @harveyyue

**Comment by Naros** [comment]
Applied to main (=2.0).

**Pull request merged**
