### PR TITLE
DBZ-5052 Don't send tombstones when consumer doesn't support them

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-5052

### CODE REVIEW

**Comment by jpechane** [comment]
@vjuranek LGTM, could you please reformat the code?

**Comment by vjuranek** [comment]
@jpechane should be ready now

**Comment by vjuranek** [comment]
btw: current version adds one more small change in debezium server when embedded engine is constructed (it's a pity GH still haven't any function which would show the diff between PR versions - already reviewed vs. new version)

**Comment by jpechane** [comment]
@vjuranek Applied, thanks!

**Pull request merged**
