### PR TITLE
DBZ-1437 Fix ExportedSnapshotter/InitialOnlySnapshotter to properly determine when to run a snapshot

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1437

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, could you check in the history of `InitialOnlySnapshotter`, and more specifically the implementation of that mode which predates the snapshotter SPI. The reason I'm asking is that this one also always seems to do a snapshot. This seems equally incorrect, but then perhaps this mode has been implemented like that also before the snapshotter SPI was introduced?

**Comment by Naros** [comment]
@gunnarmorling, I checked the prior implementation and you're correct.  We previously only performed the `INITIAL_ONLY` snapshot under the following conditions:

* No prior offsets were found
* A prior snapshot stopped/failed and must be restarted

Otherwise this mode should not invoke a snapshot.  I'll address this as well.

**Comment by Naros** [comment]
The heartbeat failure from the tests seems to be a random failure that locally I cannot reproduce on any frequency and shouldn't be impacted by these changes since it uses `NEVER`.  So if this looks good to you @gunnarmorling, its good by me.

**Comment by gunnarmorling** [comment]
Rebased and applied; thanks, @Naros!

**Pull request merged**
