### PR TITLE
[docs] Clearify incremental snapshot procedure for Oracle

### PR DESCRIPTION
**Pull request by Lucascanna**

### CODE REVIEW

**Review by Naros — APPROVED** [review]
LGTM, @roldanbob this okay with you?

**Review by roldanbob — CHANGES_REQUESTED** [review]
@Lucascanna Thanks for the clarifications. I agree with your suggestions and plan to apply the changes to the other connector docs. I've requested a few changes to remove future tense and replace potentially ambiguous pronoun references (`this`).

**Comment by Lucascanna** [comment]
Thanks @roldanbob I have committed your suggestions

**Comment by Naros** [comment]
Thanks @Lucascanna .

**Pull request merged**
