### PR TITLE
DBZ-2029 Edited the architecture description

### PR DESCRIPTION
**Pull request by TovaCohen**
The title says it all. This is ready to merge unless you notice something that needs to be fixed. 
Please backport this PR to 1.1.
Thanks!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, you wanna take that one?

**Comment by gunnarmorling** [comment]
Applied to master (=1.2) and 1.1. @TovaCohen, I take it you apply the right configuration to have this additional page show up in downstream docs?

**Comment by gunnarmorling** [comment]
Note I did some small adjustment in a follow-up commit, clarifying that Kafka Connect is the _only_ supported approach downstream.

**Comment by TovaCohen** [comment]
@gunnarmorling To answer your question about "apply the right configuration to have the additional page show up in the downstream docs" - Yes. Downstream, I work in a documentation repository topic branch that I create from the master branch for the 2020-Q2 release. In my topic branch, I have attributes set to always fetch updates from only the 1.1 upstream branch. I already updated the downstream Debezium User Guide to have the architecture.adoc content. You can see a preview here: 
https://access.redhat.com/documentation/en-us/red_hat_integration/2020-q2/html-single/debezium_user_guide/index?lb_target=stage#debezium-architecture
With my updates and your update merged to 1.1, now I will go downstream, fetch the updates, and push/merge them to our downstream master for the Q2 release. Hope that wasn't too much detail!
And then I will ask for a QA review of the updated architecture content.

**Pull request merged**
