### PR TITLE
[DBZ-1193] Add support for network type MACADDR and MACADDR8 in PostgreSQL connector

### PR DESCRIPTION
**Pull request by Wang-Yu-Chao**
https://issues.jboss.org/browse/DBZ-1193

Add supoorts for network types `CIDR`, `MACADDR`, `MACADDR8`.

#### Tested on PostgreSQL 9.6, 10 and 11:

DDL (PostgreSQL 9.6): 
```
CREATE TABLE inventory.network (pk SERIAL, i INET, c CIDR, m MACADDR, PRIMARY KEY(pk));
```

DDL (PostgreSQL 10 and 11):
```
CREATE TABLE network_address_table (pk SERIAL, i INET, c CIDR, m MACADDR, m8 MACADDR8, PRIMARY KEY(pk));
```

DML (PostgreSQL 9.6): 
```
INSERT INTO inventory.network VALUES (1001, '192.168.2.0/12', '192.168.100.128/25', '08:00:2b:01:02:03');
```

DDL (PostgreSQL 10 and 11):
```
INSERT INTO network_address_table (i, c, m, m8) VALUES ('192.168.2.0/12', '192.168.100.128/25', '08:00:2b:01:02:03', '08:00:2b:01:02:03:04:05');
```

Before Patch:
```
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "int32",
                "optional": false,
                "field": "pk"
            }
        ],
        "optional": false,
        "name": "servername.inventory.network.Key"
    },
    "payload": {
        "pk": 1001
    }
}	
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "pk"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "i"
                    }
                ],
                "optional": true,
                "name": "servername.inventory.network.Value",
                "field": "before"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "pk"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "i"
                    }
                ],
                "optional": true,
                "name": "servername.inventory.network.Value",
                "field": "after"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "string",
                        "optional": true,
                        "field": "version"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "connector"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "name"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "db"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "ts_usec"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "txId"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "lsn"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "schema"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "table"
                    },
                    {
                        "type": "boolean",
                        "optional": true,
                        "default": false,
                        "field": "snapshot"
                    },
                    {
                        "type": "boolean",
                        "optional": true,
                        "field": "last_snapshot_record"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "xmin"
                    }
                ],
                "optional": false,
                "name": "io.debezium.connector.postgresql.Source",
                "field": "source"
            },
            {
                "type": "string",
                "optional": false,
                "field": "op"
            },
            {
                "type": "int64",
                "optional": true,
                "field": "ts_ms"
            }
        ],
        "optional": false,
        "name": "servername.inventory.network.Envelope"
    },
    "payload": {
        "before": null,
        "after": {
            "pk": 1001,
            "i": null
        },
        "source": {
            "version": "0.9.4-SNAPSHOT",
            "connector": "postgresql",
            "name": "servername",
            "db": "postgres",
            "ts_usec": 1554462087304494,
            "txId": 597,
            "lsn": 24620232,
            "schema": "inventory",
            "table": "network",
            "snapshot": true,
            "last_snapshot_record": true,
            "xmin": null
        },
        "op": "c",
        "ts_ms": 1554462087670
    }
}
```

After Patch (PostgreSQL 10 and 11):
```
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "int32",
                "optional": false,
                "field": "pk"
            }
        ],
        "optional": false,
        "name": "fulfillment.public.network_address_table.Key"
    },
    "payload": {
        "pk": 1
    }
}	
{
    "schema": {
        "type": "struct",
        "fields": [
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "pk"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "i"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "c"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "m"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "m8"
                    }
                ],
                "optional": true,
                "name": "fulfillment.public.network_address_table.Value",
                "field": "before"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "int32",
                        "optional": false,
                        "field": "pk"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "i"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "c"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "m"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "m8"
                    }
                ],
                "optional": true,
                "name": "fulfillment.public.network_address_table.Value",
                "field": "after"
            },
            {
                "type": "struct",
                "fields": [
                    {
                        "type": "string",
                        "optional": true,
                        "field": "version"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "connector"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "name"
                    },
                    {
                        "type": "string",
                        "optional": false,
                        "field": "db"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "ts_usec"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "txId"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "lsn"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "schema"
                    },
                    {
                        "type": "string",
                        "optional": true,
                        "field": "table"
                    },
                    {
                        "type": "boolean",
                        "optional": true,
                        "default": false,
                        "field": "snapshot"
                    },
                    {
                        "type": "boolean",
                        "optional": true,
                        "field": "last_snapshot_record"
                    },
                    {
                        "type": "int64",
                        "optional": true,
                        "field": "xmin"
                    }
                ],
                "optional": false,
                "name": "io.debezium.connector.postgresql.Source",
                "field": "source"
            },
            {
                "type": "string",
                "optional": false,
                "field": "op"
            },
            {
                "type": "int64",
                "optional": true,
                "field": "ts_ms"
            }
        ],
        "optional": false,
        "name": "fulfillment.public.network_address_table.Envelope"
    },
    "payload": {
        "before": null,
        "after": {
            "pk": 1,
            "i": null,
            "c": null,
            "m": null,
            "m8": null
        },
        "source": {
            "version": "0.9.4-SNAPSHOT",
            "connector": "postgresql",
            "name": "fulfillment",
            "db": "postgres",
            "ts_usec": 1554561187637489,
            "txId": 558,
            "lsn": 24516152,
            "schema": "public",
            "table": "network_address_table",
            "snapshot": false,
            "last_snapshot_record": null,
            "xmin": null
        },
        "op": "c",
        "ts_ms": 1554561187750
    }
}
```

### CODE REVIEW

**Comment by ShubhamRwt** [comment]
Hello @Wang-Yu-Chao. I have given the support for cidr network address type in PR #838 so instead of giving support for all the address types please first give support for the macaddr type so it would be beneficial as it would be easy to test and implement plus we would be able to resolve the issue easily.

**Comment by Wang-Yu-Chao** [comment]
Hello @ShubhamRwt. I'm all ok. But in my humble opinion, since these are all network types and basically the code are similar, it might be better to put them together for this single issue. So let's wait for pros' opinions. :)

**Comment by ShubhamRwt** [comment]
Then you can merge my commits into yours :) @Wang-Yu-Chao.

**Comment by Wang-Yu-Chao** [comment]
Docker image for testing postgres connector uses PostgreSQL 9.6 and this version doesn't support `MACADDR8` type, so CI checks fail. Could that be a good idea to change that image version to 10 or 11? @gunnarmorling  @jpechane

**Comment by gunnarmorling** [comment]
> Could that be a good idea to change that image version to 10 or 11?

There's a way to skip specific tests depending on the DB version (see `@SkipWhenDatabaseVersionLessThan`, please). So we can exclude that test when running on 9.6 (we got a matrix test job which tests against all the supported versions).

**Comment by gunnarmorling** [comment]
Thanks a lot, @Wang-Yu-Chao! Unfortunately, there's some overlap with #838 which was filed pretty much at the same time. So my suggestion is that @ShubhamRwt reworks his PR so it's one commit and it references the right JIRA issue in its message. Once that's done, I'll merge it and you rebase your PR here, so it will effectively only add support for the other type types. Doing so, please also change the commit message to reference the right JIRA issue. Thanks!

**Comment by gunnarmorling** [comment]
Hey @Wang-Yu-Chao, so I've merged the PR bringing in cidr support. Could you rebase your PR to the latest master? There are a few conflicts due to that, but they should be resolved easily (as they are the same change essentially). If you need help, let us know. Thanks!

**Comment by Wang-Yu-Chao** [comment]
@gunnarmorling. No problem. I'll deal with it asap.

**Comment by Wang-Yu-Chao** [comment]
Hey @gunnarmorling, I've fixed this issue by separating test code for `MACADDR8` type. Are there any further suggestions? Thank you!

**Comment by gunnarmorling** [comment]
Rebased and applied; thanks, @Wang-Yu-Chao. Could you also push a commit to @ShubhamRwt's PR https://github.com/debezium/debezium.github.io/pull/274 for adding the two new column types to the docs? Thanks!

**Pull request merged**
