### PR TITLE
DBZ-7790 Improve LOB merge when table is keyless

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7790

@leoloel added this as I couldn't push to your original PR.
This supersedes PR #5493

### CODE REVIEW

**Comment by leoloel** [comment]
It is a good idea to use rowid to differentiate rows. I just saw this commit #5524  and suddenly thought of using rowid.

**Review by jpechane — APPROVED** [review]
@Naros LGTM, thanks! PLease feel free to merge yourself if the test failures are only flaky.

**Comment by jpechane** [comment]
@Naros Applied, thanks

**Pull request merged**
