### PR TITLE
DBZ-3896 Enable semicolon in DDL

### PR DESCRIPTION
**Pull request by zouxinyu0328**
https://issues.redhat.com/browse/DBZ-3896

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey, could you please describe a bit more why this is needed? Could you also log a Jira issue and reference its issue number in the commit message? Thx!

**Comment by gunnarmorling** [comment]
CC @Naros

**Comment by zouxinyu0328** [comment]
Hi @gunnarmorling and @Naros , I created a new [Jira](https://issues.redhat.com/browse/DBZ-3896) for the issue. Please check. Thanks!

**Comment by gunnarmorling** [comment]
Hey @zouxinyu0328, could you rebase and squash the commits into a single one, author the commit with an email linked to your GH account (avoiding the "octocat commit") and prefix the commit message with the issue key ("DBZ-3896 Enable..."). Thanks!

**Comment by Naros** [comment]
Hi @zouxinyu0328 could you please follow up on Gunnar's request above?  If I don't see that you have had a chance to in the next few hours I'll proceed with making the commit myself so we can get this included in tomorrow's release.

**Comment by Naros** [comment]
Closing this PR in favor of PR #2623

**Pull request closed without merging**
