### PR TITLE
DBZ-6446 Support shrink clause for Oracle index partition

### PR DESCRIPTION
**Pull request by ddsr-ops**
https://issues.redhat.com/browse/DBZ-6446

### CODE REVIEW

**Comment by jpechane** [comment]
@ddsr-ops Applied, thanks

**Comment by jpechane** [comment]
@ddsr-ops Could you please send a PR to the upstream grammar as well and link it here? Thanks alot

**Comment by ddsr-ops** [comment]
> @ddsr-ops Could you please send a PR to the upstream grammar as well and link it here? Thanks alot

@jpechane Sorry, I can not understand what it means. I have created a PR to main branch, is the main branch not the upstream?
Thank you for your explanation.

**Comment by jpechane** [comment]
@ddsr-ops Please see https://github.com/antlr/grammars-v4/tree/master/sql/plsql

**Pull request merged**
