### PR TITLE
DBZ-4419 Deprecate TruncateHandlingMode, favor skipped.operations

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-4419

### CODE REVIEW

**Comment by jpechane** [comment]
Is the `skipped.operations` based cofig tested somewhere?

**Comment by Naros** [comment]
Hmm, I'll check and add a test if one doesn't exist to cover the use case with PG.

**Comment by Naros** [comment]
So @jpechane I don't think I thought this through unless I am missing something.  So right now the behavior is:

* With no `TruncateHandlingMode` value configured, `TRUNCATE` events are skipped by default.
* Users must opt into `TruncateHandlingMode#INCLUDE` if they want these events emitted.

But `skipped.operations` use inverse semantics where `TRUNCATE` events would be emitted unless opted-out (skipped).

This means that starting with 1.9, users that are on PG11 or higher and using pgoutput will go from not getting `TRUNCATE` events by default to getting them.  Is that a problem?

**Comment by jpechane** [comment]
@Naros Well, we usually follow the procedure to emit warnings in one release and change behaviour in the next one. How about changit the default value of the skipped ops to `t`?

**Comment by gunnarmorling** [comment]
With skipped.ops defaulting to "t", how can a user opt into not skipping truncates (i.e. emitting them)?

**Comment by gunnarmorling** [comment]
Mh, yeah, that feels clunky indeed. So how about that:

* Deprecate truncate.handling.mode, ignore it (logging a warning if it's given)
* Emit truncate events by default
* If the user don't want them, they need to us skipped.ops=t

While it is a behavioral change, I'd say it's probably an acceptable one? In general, I'd expect consumers to be ready to receive events they cannot handle and ignore them, so emitting the events by default shouldn't be a problem, plus there is a mitigation available via skipped.ops. WDYT, @Naros, @jpechane?

**Comment by Naros** [comment]
@gunnarmorling I'm fine with that plan.  On the plus side, it seemed that using a `Type.LIST` field with a default value, our validation of the Configuration definition wasn't exactly right, so at least commit d8c7062 fixes that.  

> don't we have truncate.handling.mode for Oracle, too? Or did we go for skipped.ops there right from the beginning?

We went for skipped ops from the beginning there.  That's what prompted this follow-up Jira for PG.

**Comment by jpechane** [comment]
@gunnarmorling 

> In general, I'd expect consumers to be ready to receive events they cannot handle and ignore them

This sounds like an overly optimistic assumption...

**Comment by Naros** [comment]
Haha, so what's our consensus then here?

**Comment by gunnarmorling** [comment]
So after discussing this some more in the weekly call yesterday, I think we've converged on this:

- Make skipped.ops=t the default for PG for Debezium 1.9
- Add special value "none" to skipped ops enum
- Deprecate truncate.handling.mode, raise a warning if it's given; map it internally to skipped.ops it's set
- Make skipped.ops=t the default for Oracle for Debezium 2.0

@jpechane, @Naros, @rk3rn3r, are you ok with that?

**Comment by jpechane** [comment]
@gunnarmorling +1

**Comment by gunnarmorling** [comment]
@Naros, so does this reflect the described state above, or is more work needed?

**Comment by Naros** [comment]
@gunnarmorling It does now.

**Comment by gunnarmorling** [comment]
Ok, sweet, will take another look then. Could you log a follow-up for 2.0-next for changing the default for the Oracle connector option in the meantime?

**Comment by gunnarmorling** [comment]
This LGTM now, can be merged once CI has passed. Thx, @Naros!

**Review by gunnarmorling — APPROVED** [review]

**Comment by Naros** [comment]
> Ok, sweet, will take another look then. Could you log a follow-up for 2.0-next for changing the default for the Oracle connector option in the meantime?

Yep, already added it as a bullet point on the all-inclusive Debezium 2.0 input JIRA.

**Comment by Naros** [comment]
Logged unrelated error as [DBZ-4592](https://issues.redhat.com/browse/DBZ-4592)

**Review by gunnarmorling — APPROVED** [review]

**Pull request merged**
