### PR TITLE
DBZ-2915  Use Testcontainers to setup Pulsar 

### PR DESCRIPTION
**Pull request by ani-sha**
Use ` mvn clean install -pl debezium-server-pulsar -am -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn` to run.

On commenting out `withCopyFileToContainer` property and running the existing changes produces:
```
Exception in thread "pool-4-thread-1" io.debezium.DebeziumException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.ExecutionException: org.apache.pulsar.client.api.PulsarClientException: java.util.concurrent.CompletionException: org.apache.pulsar.shade.io.netty.channel.AbstractChannel$AnnotatedConnectException: finishConnect(..) failed: Connection refused: localhost/127.0.0.1:6650
        at io.debezium.server.pulsar.PulsarChangeConsumer.createProducer(PulsarChangeConsumer.java:110)
        at io.debezium.server.pulsar.PulsarChangeConsumer.lambda$handleBatch$1(PulsarChangeConsumer.java:121)
        at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1133)
        at io.debezium.server.pulsar.PulsarChangeConsumer.handleBatch(PulsarChangeConsumer.java:121)
        at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:82)
        at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:812)
        at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:171)
        at io.debezium.server.DebeziumServer.lambda$start$1(DebeziumServer.java:142)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
        at java.base/java.lang.Thread.run(Thread.java:834)
```
There are config files under `debezium-server-pulsar/docker/conf/` which have been used in the docker maven plugin as [here](debezium-server-pulsar/docker/conf/). Upon looking into `GenericContainer` methods to do volume mapping using `withClasspathResourceMapping` (for eg [here](https://www.testcontainers.org/features/files/#volume-mapping)) in our case produced:
```
Caused by: java.lang.IllegalArgumentException: Resource with path /docker/conf/ could not be found on any of these classloaders: [jdk.internal.loader.ClassLoaders$AppClassLoader@5bc2b487, QuarkusClassLoader:Quarkus Base Runtime ClassLoader]
```
So certainly unsure of which method to use to map the config files and establish/start the container successfully. 
cc: @gunnarmorling

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ani-sha, with those resources being under _docker/conf_, they were not part of the test classpath and thus not visible to the classloader of the test. I pushed a commit for moving them under _test/resources_ to fix that. With that change and some corresponding adjustment, the test passes for me locally.

**Comment by ani-sha** [comment]
Thanks @gunnarmorling, works for me as well. Marking the PR ready for review.

**Comment by ani-sha** [comment]
https://issues.redhat.com/browse/DBZ-2915

**Comment by gunnarmorling** [comment]
Applied; thx!

**Pull request merged**
