### PR TITLE
DBZ-1315 UNDEFINED field causes exception

### PR DESCRIPTION
**Pull request by ChingTsai**
https://issues.jboss.org/browse/DBZ-1315

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @ChingTsai, thanks a lot! Could you rework the commit so it uses an e-mail associated to your GH account? That way it will [properly be attributed|https://help.github.com/en/articles/why-are-my-contributions-not-showing-up-on-my-profile] in the commit stats/history. Thanks!

**Comment by ChingTsai** [comment]
@gunnarmorling Done!

**Comment by gunnarmorling** [comment]
Thanks, @ChingTsai!

**Comment by gunnarmorling** [comment]
@jpechane, can we still merge it for Alpha2?

**Comment by gunnarmorling** [comment]
Thanks, @ChingTsai! This will be part of 0.10.Beta1 (due in two weeks).

**Pull request merged**
