### PR TITLE
DBZ-1234 Remove deprecated features and configuration options

### PR DESCRIPTION
**Pull request by Naros**
https://issues.jboss.org/browse/DBZ-1234

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, as this is labelled with "WIP", what other things are you planning to add? Could you also rebase this to the current master? Thanks!

**Comment by gunnarmorling** [comment]
@jpechane, here's one more thing I'm considering to drop: the "adaptive_time_microseconds" value for the PG connector's "time.precision.mode"; this was added to keep compatibility with earlier behaviors at some point, but it's prone to value loss for large `TIME` values. So I don't think there's actual value in having it and it wouldn't be there hadn't this (arguably, incorrectly) existed before. WDYT?

**Comment by jpechane** [comment]
@gunnarmorling Agrre. I've went through the docs and it seems to be the only one not completed.

**Comment by gunnarmorling** [comment]
No worries :) Seems we're in agreement of its removal then.

On a related note, I've filed https://github.com/debezium/debezium/pull/884 and the a corresponding doc update for removing a deprecated SMT option.

**Comment by Naros** [comment]
> as this is labelled with "WIP", what other things are you planning to add? Could you also rebase this to the current master? Thanks!

@gunnarmorling I had marked this WIP as I knew the SMT option was still pending, but it looks like you took care of that as a part of PR #884, so at this point all which remains is what @jpechane mentioned which I'll add.

**Comment by gunnarmorling** [comment]
Excellent, thanks!

**Comment by Naros** [comment]
@jpechane @gunnarmorling Let me know if there is anything I missed or that you'd like to see changed with how I handled the adaptive `time.precision.mode` commit.

**Comment by gunnarmorling** [comment]
>  how I handled the adaptive time.precision.mode commit.

I think that's fine. I've just pushed one minor commit to get the enum value via its `parse()` method as this also deals with trimming the value.

**Comment by gunnarmorling** [comment]
@Naros, could you also prepare the wording for the migration notes and add it as a comment to the JIRA issue (I've already done it for the SMT option). Thanks!

**Comment by gunnarmorling** [comment]
Applied. Thanks a lot, @Naros!

**Pull request merged**
