### PR TITLE
DBZ-1392 Applying formatter;

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.jboss.org/projects/DBZ/issues/DBZ-1392

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Naros, here's the updated PR for the formatting. Note I've squashed your commit with the original one, so to avoid the forth and back around the JSON formatting. I've also pushed one more commit to run the formatter as part of the default build pipeline. Unless I've missed something, the validate profile isn't needed any longer, so I've removed this.

Could you review (taking a quick look whether there are any apparent formatting issues like the JSON one) and merge if you think it's good? Thanks!

**Comment by gunnarmorling** [comment]
@Naros, one last thought: is there any update to the contrib guide needed, e.g. on using the same formatting template for the Eclipse IDE (I don't think it can be done 100% with IntelliJ)?

**Comment by gunnarmorling** [comment]
@jpechane, as you're back, could you alternatively take a look? Thx!

**Comment by jpechane** [comment]
Applied, thanks @Naros and @gunnarmorling!
Local test proved there was no need for further reformat after application.

**Comment by Naros** [comment]
Thanks for taking care of reviewing this @jpechane.

**Pull request merged**
