### PR TITLE
DBZ-6825 Add vcs.xml for idea

### PR DESCRIPTION
**Pull request by wuzhenhua01**
https://issues.redhat.com/browse/DBZ-6825

### CODE REVIEW

**Comment by mfvitale** [comment]
Hi @wuzhenhua01 good idea. We have IDE settings in `support/ide-configs` folder. Maybe you can create the `idea` folder and put the `vcs.xml` inside an `options` folder (Same path when you export settings from File->Manage IDE Settings->Export Settings...).

**Comment by jpechane** [comment]
@wuzhenhua01 Would you please be able to follow-up on @mfvitale recomendation?

**Comment by wuzhenhua01** [comment]
@jpechane @mfvitale I am sorry for replying so late, let me see

**Comment by jpechane** [comment]
@wuzhenhua01 Applied, thanks!

**Pull request merged**
