### PR TITLE
DBZ-1233 - MODE as column name

### PR DESCRIPTION
**Pull request by mrozieres**
Add MODE to keywordsCanBeId to fix parse exception on so named columns

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks a lot, @mrozieres! Could you also please add a test (see other DDL parser tests for examples) and also send a PR to the Antlr upstream repo for applying the same change there?

**Comment by mrozieres** [comment]
@gunnarmoling I added a test case and also all the missing keywords i found present in the lexer and missing from the parser.

**Comment by mrozieres** [comment]
@gunnarmorling  Upstream PR done https://github.com/antlr/grammars-v4/pull/1396.

**Comment by gunnarmorling** [comment]
@jpechane, any concerns on your side?

**Comment by jpechane** [comment]
@gunnarmorling Functionally it is great. I'd just prefer spaces around `+` in string concatenation code in the test

**Comment by gunnarmorling** [comment]
Ok, will add and merge.

**Comment by gunnarmorling** [comment]
Rebased, squashed and applied. Thanks a lot, @mrozieres

**Pull request closed without merging**
