### PR TITLE
Dbz 3974 schema change doc updates

### PR DESCRIPTION
**Pull request by roldanbob**
[DBZ-3974](https://issues.redhat.com/browse/DBZ-3974)

This change adds missing information to the MySQL connector doc about the `tableChanges` field in schema change messages and also updates the Db2, Oracle, PostgreSQL, and SQL Server connector docs for consistency.

Changes tested in a local Antora build.

### CODE REVIEW

**Comment by roldanbob** [comment]
I noticed that a bunch of commits had been added to `master` after I submitted the PR, so I rebased my branch. Now I'm seeing the message that there are conflicts. Let me know if I need to adjust anything on my end.

**Comment by gunnarmorling** [comment]
@roldanbob, yeah, there's way too many commits in this PR. Can you rebase this one to the latest master and then force-push to this PR's branch? There should only be commits attributed to DBZ-3974 part of it.

**Comment by gunnarmorling** [comment]
Hey @roldanbob, could you update this PR (or close and create a new one) so it contains the only intended and relevant changes? Thanks 🙏 !

**Comment by roldanbob** [comment]
> Hey @roldanbob, could you update this PR (or close and create a new one) so it contains the only intended and relevant changes? Thanks pray !

Ok, sure. Probably better at this point to close this one and create a new one, so I'll do that. Thanks.

**Pull request closed without merging**
