### PR TITLE
DBZ-7196 Add modify range_partitions to modify_table_partition rule in parsing PL/SQL

### PR DESCRIPTION
**Pull request by ilyasahsan123**
https://issues.redhat.com/browse/DBZ-7196

### CODE REVIEW

**Comment by ilyasahsan123** [comment]
Upstream: https://github.com/antlr/grammars-v4/pull/3834

**Comment by Naros** [comment]
Hi @ilyasahsan123 it would appear the test failures are related, could you take a look?

**Comment by ilyasahsan123** [comment]
Hi, @Naros, I've updated the logic for parsing SQL and ran the tests locally. Could you please review the changes? 
Thanks!

**Comment by Naros** [comment]
Thanks @ilyasahsan123, applied to main (=2.5).

**Pull request merged**
