### PR TITLE
DBZ-6702 Disable jdk-outreach-workflow.yml in forked personal repo

### PR DESCRIPTION
**Pull request by GOODBOY008**
Personal repo should not run by scheduled.

### CODE REVIEW

**Comment by GOODBOY008** [comment]
@jpechane Please code review ,if you are available.

**Review by Naros — CHANGES_REQUESTED** [review]
Hi @GOODBOY008, I'm sorry but I don't believe the commit message aligns with the YAML file that was changed.  I would have expected the `jdk-outreach-workflow.yml` to have been the file modified, no?

**Comment by GOODBOY008** [comment]
@Naros I am so sorry for my mistake.

**Comment by jpechane** [comment]
@Naros Before merging, @ani-sha is checking if there is any other solution that would not require hardocing of repo name into the workflow.

**Review by ani-sha — COMMENTED** [review]
Hi @GOODBOY008, I think it would best if you could disable all/individual workflows within your forked repository. Using `repository: debezium/debezium` restricts the workflows to run exclusively for the main repository, which may not be beneficial for other users, not just for this workflow but for other workflows too. 

To disable this workflow you can check these attachments. 
Screenshot 2023-07-25 at 6 10 16 PM
Screenshot 2023-07-25 at 6 10 31 PM

**Comment by GOODBOY008** [comment]
@ani-sha Thanks for your remind.

**Pull request closed without merging**
