### PR TITLE
Fix unusable array information in Serialization

### PR DESCRIPTION
**Pull request by abergmeier**
According to ErrorProne, (implicitly) calling toString on the array does
not give useful information. Seems like these code paths are not unit
tested?

### CODE REVIEW

**Comment by abergmeier** [comment]
IMO this would need at least one test.

**Comment by abergmeier** [comment]
@gunnarmorling  Can you guys get your CI output in check please - I have a hard time figuring out why the CI failed - it is just way too much.

**Comment by abergmeier** [comment]
Looking into this more I am not sure whether having a Base64 encoding for a byte array makes sense. What is the rationate behind that?

**Comment by gunnarmorling** [comment]
> What is the rationate behind that?

Good question, indeed the Base64 encoding seems a bit dubious. I think just calling `Arrays#toString()` passing the original byte array would be the better thing to do. I suppose this was based on the wrong assumption that `Base64#encode()` would return a String and not another byte array.

**Comment by abergmeier** [comment]
> If you rework the commit as suggested above, could you also prefix its message with "DBZ-759..."? Thanks!

Done.

**Comment by gunnarmorling** [comment]
Nice, rebased and applied. Thanks, @abergmeier!

**Pull request closed without merging**
