### PR TITLE
DBZ-2224 Test logging based on logback

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2224

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling This is not finished yet but I'd like you to have a preliminary look and give your opinion.

At the end I went with logback based implementation. I skipped both JUL and JBoss Logging as both requires in some form a sys propery configuration which is not convenient for test execution purposes.

The replacement is relatively seamless, the only difference is `LogInterceptor`. It is not possible to uses non-parametric constructor of it and instead the concrete logger that emits the message must be used.
The reason is logback's additivity. When you add multiple loggers tuning thresholds then each logger would log the message if the logger matches. So you will see duplicate messages. To prevent this you need to disable additivity. Unfortunately in that case only the concrete logger will get the message we intend to interecept and it will not get into the root logger. Thus it is necessary to provide the exact logger name expected to log the message.

**Comment by gunnarmorling** [comment]
@jpechane, yes, this LGTM. I'd say let's go for it. Not sure what's still missing? @Naros may have some thoughts about it too. Given this is solely test-scoped, I think we're pretty free to do what we want here. Looking forward to getting off of log4j very much.

**Comment by jpechane** [comment]
@gunnarmorling It is completed, including other connector repos.

**Review by gunnarmorling — APPROVED** [review]
LGTM, merging. Thx, @jpechane!

**Pull request merged**
