### PR TITLE
DBZ-3718 Add table option TABLE_TYPE for create table

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-3718

### CODE REVIEW

**Comment by ani-sha** [comment]
Upstream PR - https://github.com/antlr/grammars-v4/pull/2258

**Comment by spingping** [comment]
Hi, @ani-sha After we upgrade our DBZ version from v1.5.4 to v1.9.5. We encounter the following ERRORs.
```
io.debezium.text.ParsingException: DDL statement couldn't be parsed. Please open a Jira issue with the statement 'CREATE TABLE tbl_info_tab (
        id int(8) NULL,
        table_name varchar(128) NULL,
        table_desc varchar(256) NULL,
        table_type tinyint(4) NULL,
)
ENGINE=InnoDB
COLLATE=utf8mb4_unicode_ci'
no viable alternative at input 'CREATE TABLE tbl_info_tab (\n        id int(8) NULL,\n        table_name varchar(128) NULL,\n        table_desc varchar(256) NULL,\n        table_type'

	at io.debezium.antlr.ParsingErrorListener.syntaxError(ParsingErrorListener.java:43)
	at org.antlr.v4.runtime.ProxyErrorListener.syntaxError(ProxyErrorListener.java:41)
	at org.antlr.v4.runtime.Parser.notifyErrorListeners(Parser.java:544)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportNoViableAlternative(DefaultErrorStrategy.java:310)
	at org.antlr.v4.runtime.DefaultErrorStrategy.reportError(DefaultErrorStrategy.java:136)
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1228)
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.root(MySqlParser.java:950)
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:73)
	at io.debezium.connector.mysql.antlr.MySqlAntlrDdlParser.parseTree(MySqlAntlrDdlParser.java:45)
	at io.debezium.antlr.AntlrDdlParser.parse(AntlrDdlParser.java:82)
	at io.debezium.connector.mysql.MySqlAntlrDdlParserTest.test(MySqlAntlrDdlParserTest.java:130)
	......
Caused by: org.antlr.v4.runtime.NoViableAltException
	at org.antlr.v4.runtime.atn.ParserATNSimulator.noViableAlt(ParserATNSimulator.java:2026)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.execATN(ParserATNSimulator.java:467)
	at org.antlr.v4.runtime.atn.ParserATNSimulator.adaptivePredict(ParserATNSimulator.java:393)
	at io.debezium.ddl.parser.mysql.generated.MySqlParser.sqlStatements(MySqlParser.java:1026)
	... 31 more
```
We locate that the root cause is that our table contains a column named `table_type` which is tread as `TABLE OPTION` in new version so the ERROR occurs. Think we should also add `table_type` into `MysqlParser.g4` 's `keywordsCanBeId` list so that we can pass through this.

**Comment by jpechane** [comment]
@spingping Hi, I believe your analysis is spot on, would you be willing to create a Jira issue and provide an associtaed PR?

**Comment by jpechane** [comment]
Created https://issues.redhat.com/browse/DBZ-5643

**Comment by spingping** [comment]
Thank you, I will issue a PR for this.

**Comment by jpechane** [comment]
@spingping Sorry for confusion, PR is already there. I plan to do the release tomorrow and I wanted to make sure it gets in.

**Comment by spingping** [comment]
OK got it., thanks.

**Pull request merged**
