### PR TITLE
DBZ-7618 Implement Versioned interfaces in Transformation and Converter plugins

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-7618

### CODE REVIEW

**Comment by harveyyue** [comment]
jdbc: https://github.com/debezium/debezium-connector-jdbc/pull/65

**Comment by jpechane** [comment]
@harveyyue Thank you very much for the PRs. While it is great to have the support for versioned interfaces I am not really sure about the other change introduced - centralization of the version source. The current implementation is able to detect real version based on the classloader used to load the connector. I think thi should astay as it is now. The SMTs in connectors should use appropriate `Module` class and the core and scripting library should intorduce its own equivalent of `Module` that will provide the version string.

**Comment by harveyyue** [comment]
> @harveyyue Thank you very much for the PRs. While it is great to have the support for versioned interfaces I am not really sure about the other change introduced - centralization of the version source. The current implementation is able to detect real version based on the classloader used to load the connector. I think thi should astay as it is now. The SMTs in connectors should use appropriate `Module` class and the core and scripting library should intorduce its own equivalent of `Module` that will provide the version string.

OK, will do it.

**Comment by jpechane** [comment]
@harveyyue Applied, thanks a lot. Should we do the same for connector classes?

**Comment by jpechane** [comment]
Create a PR for IBMi connector - https://github.com/debezium/debezium-connector-ibmi/pull/6

**Pull request merged**
