### PR TITLE
DBZ-2096 Updates to the architecture image & architecture.adoc files

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-2096

**NOTE**
When back-porting these changes to branches prior to 1.2, be sure to only back-port the commit that updates the image.  The commit that adds the Debezium Server section is specifically to 1.2 only.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice; some suggestions on the new one:

* the icons of the sink systems could be a bit larger, like the source ones
* Could you make it three "documents" for ES again?
* I'd either remove the Camel connector (my preference) or add an arrow + sink system
* The titles are misleading, as Kafka itself isn't part of Kafka Connect; I'd suggest "Kafka Connect with Debezium source connectors", "Apache Kafka", "Kafka Connect with sink connectors"
* The server one isn't quite centered (more white area on the right); also could you add Google Cloud Pub/Sub?

Thanks!

**Comment by Naros** [comment]
> The server one isn't quite centered (more white area on the right);

That was intended because if I cropped the image with equal minimal space on both sides of the server image, the image was scaled up making it appear drastically larger than the other image.  This scaling is because when the browser window is larger than 1600px wide, images get scaled and that might be something we should tweak in hindsight.

In terms of alignment, my goal was that images would be left-aligned in the docs.  Are you preferring that instead they're centered?

**Comment by gunnarmorling** [comment]
Am Di., 9. Juni 2020 um 16:40 Uhr schrieb Chris Cranford <
notifications@github.com>:

> The server one isn't quite centered (more white area on the right);
>
> That was intended because if I cropped the image with equal minimal space
> on both sides of the server image, the image was scaled up making it appear
> drastically larger than the other image. This scaling is because when the
> browser window is larger than 1600px wide, images get scaled and that might
> be something we should tweak in hindsight.
>
Uh, ok. Yeah, so images should never be *up*scaled. Wondering why this is
happening, something CSS-y?


> In terms of alignment, my goal was that images would be left-aligned in
> the docs. Are you preferring that instead they're centered?
>

Yes, I think we went for centered so far.

**Comment by gunnarmorling** [comment]
@Naros, this one still needs closure, right?

**Comment by Naros** [comment]
@gunnarmorling It does, I've rebased this against the latest master to pull in the small change introduced by the docs team for using block style image rendering rather than inline image rendering so that the newly added server architecture image is consistent.  This also includes all the image changes you requested.

**Comment by gunnarmorling** [comment]
@Naros: could you share the original source of the image with me?

Going to merge, test failures are unrelated. Thanks, @Naros.

**Pull request merged**
