### PR TITLE
DBZ-3057 Add some TableId helper methods

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3057

This PR provides changes to Debezium Core needed for https://github.com/debezium/debezium-incubator/pull/252.

### CODE REVIEW

**Comment by Naros** [comment]
The failing tests do not seem related to the change.

**Comment by gunnarmorling** [comment]
LGTM, but how about adding a quick unit test or two?

**Review by gunnarmorling — CHANGES_REQUESTED** [review]
Let's add a unit test or two.

**Comment by Naros** [comment]
@gunnarmorling Tests added.

**Comment by gunnarmorling** [comment]
@Naros, some fix to import ordering is needed.

**Pull request merged**
