### PR TITLE
Tests never completed with the existing wait state

### PR DESCRIPTION
**Pull request by jsight**

### CODE REVIEW

**Comment by rhauch** [comment]
This issue can be fixed by getting rid of the local MongoDB image and pulling the latest. Once you do that, this change is not required, and in fact will break the build.

**Comment by jsight** [comment]
I didn't have a mongo image before, though. The mongo image is pulled by version, so how is that even possibly an issue? Based upon these logs, it seems like the pattern cannot match:

https://paste2.org/At2jY6sC

Maybe you have a parameterized build that behaves differently?

**Comment by jsight** [comment]
Oh, I see the logs from the run on CI: https://travis-ci.org/debezium/debezium/builds/236575382?utm_source=github_status&utm_medium=notification

I'm not sure why it starts twice there, though?

**Comment by rhauch** [comment]
Docker labels can be moved to different images, and that's what happened in the past few months with the MongoDB images. So even though the build pulls by labels, when those labels are updated to new images that change how they start, our build has to adapt.

I think you've run into the same thing that quite a few of us have seen: your local Docker has cached an older image with the label, and for some reason Docker is not recognizing that the label now refers to a different image in Docker Hub. So, remove your local MongoDB image, the rerun the Debezium build.

**Comment by jsight** [comment]
I have removed it and that doesn't help. AFAICT, they haven't updated the tag for 3.2.12 in 25 days. OTOH, I am getting weird errors during the mongo image startup. That makes me think there is something going wrong with fabric8 and my local docker that is causing some of the log entries to be swallowed. It doesn't happen the same way if I run the image manually.

Maybe this will turn into a wiki or something if I can figure out what is going on. :)

**Comment by jsight** [comment]
Ah, its an selinux issue. Now to understand why that happens. :)

**Comment by jsight** [comment]
So, I just added a rule:

echo "type=AVC msg=audit(1495858581.745:9977): avc:  denied  { setattr } for  pid=4993 comm="chown" name="" dev="pipefs" ino=8004590 scontext=system_u:system_r:container_t:s0:c42,c438 tcontext=system_u:system_r:container_runtime_t:s0 tclass=fifo_file permissive=0" | audit2allow -M docker_fifo_access

Then:

semodule -i docker_fifo_access.pp


The rule is pretty simple, and seems like a common requirement: "allow container_t container_runtime_t:fifo_file setattr;"

There are a lot of similar complaints of similar issues. Apparently it can be worked around by specifying "-t", but I don't see an equivalent in fabric8. Oh well.

Thanks!

**Pull request closed without merging**
