### PR TITLE
DBZ-3522 Ensure that there is an active session on the replica set mongo clien…

### PR DESCRIPTION
**Pull request by ccollingwood**
https://issues.redhat.com/browse/DBZ-3522

…t before using clusterDescription and ServerDescriptions to determine primary node.

### CODE REVIEW

**Review by jpechane — APPROVED** [review]
@ccollingwood Thanks a lot. LGTM, waiting for CI to complete and if it passes this can be merged.

**Comment by jpechane** [comment]
@ccollingwood ok, it seems there is an compatibility issue with MongoDB 3.2

**Comment by ccollingwood** [comment]
@jpechane `MongoUtilIT.testGetPrimaryAddress:34 » MongoClient Sessions are not supported`. Looks simple enough of a fix, so I'll try to find some time to resolve the issue. Unfortunately it seems that getting a session was the easiest way to provoke the client into retrieving accurate clusterDescription information. Might have to resort to listing DBs or something similar.

**Comment by jpechane** [comment]
@ccollingwood I am not sure it is really necessary to do anything complex. It is already EOLed so it would be enough - when this error happens for it just to resort to the old method. WDYT?

**Comment by ccollingwood** [comment]
@jpechane I think it's necessary to fix this bc this issue is not simply restricted to 3.2 compatibility. Rather, it revolves around the issue of being session compatible. While 3.2 doesn't have sessions, and therein lies the problem with my original code, it's possible to configure 3.4+ with sessions turned off, thus creating the same issue for more recent versions of mongo. 

Please see my latest code. Instead of creating a session, the code now invokes a function that forces the client to connect to mongo and wait for the results. The code simply requests an arbitrary database name and does nothing with it. Hopefully a relatively lightweight operation.

**Comment by jpechane** [comment]
@ccollingwood Applied, thanks a lot!

**Comment by ccollingwood** [comment]
You're welcome @jpechane . I hopefully can contribute again in the near future.

**Pull request merged**
