### PR TITLE
DBZ-2264 Fix test failure - MongoDbConnectorIT#shouldConsumeTransaction

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-2264

The default lock timeout in MongoDB is `5ms` and apparently this was too short for the environment where this error occurred.  The POM now introduces a new configurable property, `mongo.data.transaction.lock.timeout.ms` which by default I have increased to `1000ms`.  This should likely be sufficient for the Jenkins environment; however if we find it is not we can increase this in the Jenkins job rather than making code changes now.

### CODE REVIEW

**Comment by Naros** [comment]
The test failure is related to the fact that the parameter is applicable to MongoDB 4.0+.  I'll need to rework the PR to account for this on the older MongoDB 3.2 and 3.6 versions.

**Comment by Naros** [comment]
I moved the specification of the lock request timeout to a runtime setting which will get applied on MongoDB 4+ environments.  The setting `mongo.transaction.lock.request.timeout.ms` can be specified on the maven command line and override the default of `1000` ms used by the test suite.

**Comment by gunnarmorling** [comment]
> which will get applied on MongoDB 4+ environments

So does this still take some update to the CI config, or is it good as is?

**Comment by jpechane** [comment]
@Naros The 1 s second seems to be enough right now. We can increase it later more if the issue reappears. Thanks!

**Pull request merged**
