### PR TITLE
DBZ-1668 Documentation Updates [ci skip]

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-1668

* Removed unnecessary roles and options for many adoc tables
* Fixed various typos
* Added consistent incubating note
* Minor tweaks to several code listings to include caption/titles
* Fixed several rendering bugs with bullet lists not being properly rendered
* Added appropriate source code types to source blocks

### CODE REVIEW

**Comment by Naros** [comment]
This PR has a sibling PR in the website repository, https://github.com/debezium/debezium.github.io/pull/409.  This particular PR should be merged prior to apply the website PR to avoid any rendering bugs or issues with style changes, particularly with the new table layouts introduced.

**Comment by gunnarmorling** [comment]
@Naros, can you rebase this one now that #1217 has been merged? Thanks!

**Comment by Naros** [comment]
@gunnarmorling, rebased.

When I hear back from Fintan on the email exchange for table formatting, I should have one more commit to add to this PR to address the final sync-up then we should be able to merge.  The changes I expect to come from the sync-up are:

* Remove `options="header"` and use `|ColA |ColB |ColC` in table layouts instead.
* Change how column widths are defined
* Remove table width attribute

**Comment by gunnarmorling** [comment]
@Naros, saw a few related mails by @fbolton; based on that, can we move forward with this PR? Thanks!

**Comment by Naros** [comment]
> I couldn't build locally, though.

You likely need to fiddle with the `playbook_author.yml` file in the website repository to test the build.  If you change branch entry for `master` to whatever the branch you checked this out to then you should see these changes under the `master` version in the Antora docs.

I'm pretty sure (though this is from memory) that the older versions of the documentation should render as it always has, tables simply having an outer border, a header, and that's it while the tables rendered under `master` should be a bit more decorative with cell borders and striped backgrounds.

> Does the table change make a difference in rendering for upstream?

It should not.  

The goal of the change was to essentially migrate our tables as close to that used by the MySQL changes contributed from downstream.  The old CSS styles we did have likely played a part in the Awestruct rendering used by the website repository but are no longer relevant when we migrated to Antora.

**Comment by gunnarmorling** [comment]
LGTM, merging. Thanks a lot!

> You likely need to fiddle with the playbook_author.yml

Yes, stupid mistake on my end. Got it working eventually, thanks!

**Pull request merged**
