### PR TITLE
DBZ-1076 Postgresql ARRAY support

### PR DESCRIPTION
**Pull request by ShubhamRwt**
DBZ-1076 [Postgresql ARRAY support](https://issues.jboss.org/browse/DBZ-1076?jql=project%20%3D%20DBZ%20AND%20status%20%3D%20Open%20AND%20labels%20%3D%20easy-starter)

### CODE REVIEW

**Comment by ShubhamRwt** [comment]
@gunnarmorling and @jpechane can you help me with bug which leading to build fail in travis. I will be adding the other ranges on the basis of this. I think the changes that I have made are ok so please take a look at this whenever you are free. Thanks

**Comment by ShubhamRwt** [comment]
@gunnarmorling I have added the support for int4range array and int8range array. It is good to merge now and ragrading the isuue I guess most of the types are covered now the only left one in range type  is numrange. I have added some part for numrange too but its commented for now as it was giving me some bugs in travis build.

**Comment by jpechane** [comment]
@gunnarmorling Fine for me, applying. @ShubhamRwt Thanks!

**Comment by gunnarmorling** [comment]
We'd still need the doc update for that; @ShubhamRwt, would you be up for the task? Thanks a lot!

**Comment by ShubhamRwt** [comment]
Yes sure @gunnarmorling. I will do that.

**Comment by gunnarmorling** [comment]
Thanks!

>

**Comment by ShubhamRwt** [comment]
@gunnarmorling should I create a different section/table for the range types or should I add it in the data type table?

**Pull request merged**
