### PR TITLE
DBZ-5888 MariaDB-grammar

### PR DESCRIPTION
**Pull request by uurl**
This PR solves these issues:
-  [DBZ-3575 Implement support for JSON_TABLE in MySQL parser](https://issues.redhat.com/browse/DBZ-3575)
-  [DBZ-3576 Implement window function in MySQL parser](https://issues.redhat.com/browse/DBZ-3576) 
-  [DBZ-5888 Mariadb and Mysql have different syntax](https://issues.redhat.com/browse/DBZ-5888)

Also, updates Debezium's MySQL Parser and Lexer with these:

- https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Positive-Technologies/MySqlParser.g4
- https://github.com/antlr/grammars-v4/blob/master/sql/mysql/Positive-Technologies/MySqlLexer.g4

### CODE REVIEW

**Comment by uurl** [comment]
Hello @jpechane @Naros could you please review my PR?

**Comment by jpechane** [comment]
@uurl Generally LGTM! Could you please split the PR a bit?
There should be one commit for DBZ-3575 and one for DBZ-3576. Introduced grammar features should be tested in `ddl-parser/src/test/resources/mysql/examples/`
For those two commits there will be links to upstream PR(s) providing the same functionality in upstream grammar to make sure tho whole community benefits from it.
Other unrelated changes (like formatting, grammar optimization etc.) will go to a  commit prefixed with DBZ-5888.
Thanks a lot

**Comment by jpechane** [comment]
@uurl Where we stand with this PR now? Thanks

**Comment by uurl** [comment]
Hello @jpechane, yes this PR can be merged now and would close [DBZ-5888 Mariadb and Mysql have different syntax](https://issues.redhat.com/browse/DBZ-5888).

I see it has two aspects to consider:
1. I'm working on the PR to solve [DBZ-3575 Implement support for JSON_TABLE in MySQL parser](https://issues.redhat.com/browse/DBZ-3575), I'll submit the PR in a few hours.
2. I consider the idea is keeping it synchronized with [antlr/grammars-v4](https://github.com/antlr/grammars-v4) I've submitted two PRs for them, one was already approved ([MySQL](https://github.com/antlr/grammars-v4/pull/2942)) and the other is in waiting for approval from their side ([MariaDB](https://github.com/antlr/grammars-v4/pull/2940)).

Thanks 😄

**Comment by jpechane** [comment]
@uurl Thanks for clarification, applied!

**Pull request merged**
