### PR TITLE
1.4

### PR DESCRIPTION
**Pull request by alan-cxh**
Hi, bro：
today I pull your project to my local, and find that lack of a file with suffix '.class' in module of 'debezium-connector-postgres', 
pls check screenshot.  thx.

image

### CODE REVIEW

**Comment by rk3rn3r** [comment]
That's a generated class for the Postgres Protobuf spec. You have to compile the Postgres connector to generate that class. After the first compilation you'll find the generated class.

**Comment by gunnarmorling** [comment]
"Bro", really? Pull requests are for proposing code changes, not enquiring help. @rk3rn3r hinted into the right direction, please use the [forum](https://groups.google.com/forum/#!forum/debezium) for any follow-up questions.

**Comment by alan-cxh** [comment]
I got it, thx

**Comment by alan-cxh** [comment]
Can you provide a complete file of installation steps？

**Comment by alan-cxh** [comment]
Can you provide a complete file of installation steps for more details ？because I can not understand clearly in Readme papper.

**Comment by gunnarmorling** [comment]
https://debezium.io/documentation/reference/1.4/install.html. Let's
continue in the Google group, please.

>

**Comment by alan-cxh** [comment]
I download the file thar url is "https://repo1.maven.org/maven2/io/debezium/debezium-server-dist/1.3.1.Final/debezium-server-dist-1.3.1.Final.tar.gz", and execute  run.sh. but find the under error, below the run log

[root@localhost debezium-server]# sh run.sh 
__  ____  __  _____   ___  __ ____  ______ 
 --/ __ \/ / / / _ | / _ \/ //_/ / / / __/ 
 -/ /_/ / /_/ / __ |/ , _/ ,< / /_/ /\ \   
--\___\_\____/_/ |_/_/|_/_/|_|\____/___/   
2021-01-27 14:47:51,383 INFO  [io.deb.ser.BaseChangeConsumer] (main) Using 'io.debezium.server.BaseChangeConsumer$$Lambda$80/35534346@5d0a1059' stream name mapper
2021-01-27 14:47:53,738 INFO  [io.deb.ser.kin.KinesisChangeConsumer] (main) Using default KinesisClient 'software.amazon.awssdk.services.kinesis.DefaultKinesisClient@68fa0ba8'
2021-01-27 14:47:53,741 INFO  [io.deb.ser.DebeziumServer] (main) Consumer 'io.debezium.server.kinesis.KinesisChangeConsumer' instantiated
2021-01-27 14:47:58,937 INFO  [org.apa.kaf.con.jso.JsonConverterConfig] (main) JsonConverterConfig values: 
	converter.type = key
	decimal.format = BASE64
	schemas.cache.size = 1000
	schemas.enable = true

2021-01-27 14:47:58,970 INFO  [org.apa.kaf.con.jso.JsonConverterConfig] (main) JsonConverterConfig values: 
	converter.type = value
	decimal.format = BASE64
	schemas.cache.size = 1000
	schemas.enable = false

2021-01-27 14:47:59,216 INFO  [io.deb.emb.EmbeddedEngine$EmbeddedConfig] (main) EmbeddedConfig values: 
	access.control.allow.methods = 
	access.control.allow.origin = 
	admin.listeners = null
	bootstrap.servers = [localhost:9092]
	client.dns.lookup = use_all_dns_ips
	config.providers = []
	connector.client.config.override.policy = None
	header.converter = class org.apache.kafka.connect.storage.SimpleHeaderConverter
	internal.key.converter = class org.apache.kafka.connect.json.JsonConverter
	internal.value.converter = class org.apache.kafka.connect.json.JsonConverter
	key.converter = class org.apache.kafka.connect.json.JsonConverter
	listeners = null
	metric.reporters = []
	metrics.num.samples = 2
	metrics.recording.level = INFO
	metrics.sample.window.ms = 30000
	offset.flush.interval.ms = 0
	offset.flush.timeout.ms = 5000
	offset.storage.file.filename = data/offsets.dat
	offset.storage.partitions = null
	offset.storage.replication.factor = null
	offset.storage.topic = 
	plugin.path = null
	response.http.headers.config = 
	rest.advertised.host.name = null
	rest.advertised.listener = null
	rest.advertised.port = null
	rest.extension.classes = []
	rest.host.name = null
	rest.port = 8083
	ssl.cipher.suites = null
	ssl.client.auth = none
	ssl.enabled.protocols = [TLSv1.2]
	ssl.endpoint.identification.algorithm = https
	ssl.engine.factory.class = null
	ssl.key.password = null
	ssl.keymanager.algorithm = SunX509
	ssl.keystore.location = null
	ssl.keystore.password = null
	ssl.keystore.type = JKS
	ssl.protocol = TLSv1.2
	ssl.provider = null
	ssl.secure.random.implementation = null
	ssl.trustmanager.algorithm = PKIX
	ssl.truststore.location = null
	ssl.truststore.password = null
	ssl.truststore.type = JKS
	task.shutdown.graceful.timeout.ms = 5000
	topic.creation.enable = true
	topic.tracking.allow.reset = true
	topic.tracking.enable = true
	value.converter = class org.apache.kafka.connect.json.JsonConverter

2021-01-27 14:47:59,235 INFO  [org.apa.kaf.con.run.WorkerConfig] (main) Worker configuration property 'internal.key.converter' is deprecated and may be removed in an upcoming release. The specified value 'org.apache.kafka.connect.json.JsonConverter' matches the default, so this property can be safely removed from the worker configuration.
2021-01-27 14:47:59,235 INFO  [org.apa.kaf.con.run.WorkerConfig] (main) Worker configuration property 'internal.value.converter' is deprecated and may be removed in an upcoming release. The specified value 'org.apache.kafka.connect.json.JsonConverter' matches the default, so this property can be safely removed from the worker configuration.
2021-01-27 14:47:59,236 WARN  [org.apa.kaf.con.run.WorkerConfig] (main) Variables cannot be used in the 'plugin.path' property, since the property is used by plugin scanning before the config providers that replace the variables are initialized. The raw value 'null' was used for plugin scanning, as opposed to the transformed value 'null', and this may cause unexpected results.
2021-01-27 14:47:59,240 INFO  [org.apa.kaf.con.jso.JsonConverterConfig] (main) JsonConverterConfig values: 
	converter.type = key
	decimal.format = BASE64
	schemas.cache.size = 1000
	schemas.enable = true

2021-01-27 14:47:59,241 INFO  [org.apa.kaf.con.jso.JsonConverterConfig] (main) JsonConverterConfig values: 
	converter.type = value
	decimal.format = BASE64
	schemas.cache.size = 1000
	schemas.enable = true

2021-01-27 14:47:59,270 INFO  [io.deb.ser.DebeziumServer] (main) Engine executor started
2021-01-27 14:47:59,408 INFO  [org.apa.kaf.con.sto.FileOffsetBackingStore] (pool-3-thread-1) Starting FileOffsetBackingStore with file data/offsets.dat
2021-01-27 14:48:02,920 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main]=Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 2440 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.lang.ClassLoader.loadClass(ClassLoader.java:404)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.VertxImpl.createHttpServer(VertxImpl.java:310)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:819)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.DeploymentManager$$Lambda$212/1334405552.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$213/207988207.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2021-01-27 14:48:03,009 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 2464 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.vertx.core.impl.VertxImpl.createHttpServer(VertxImpl.java:310)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:819)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.DeploymentManager$$Lambda$212/1334405552.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$213/207988207.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2021-01-27 14:48:03,754 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
2021-01-27 14:48:03,765 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:03,765 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
2021-01-27 14:48:03,765 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:03,765 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
2021-01-27 14:48:03,765 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:03,766 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
2021-01-27 14:48:03,766 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:03,766 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
2021-01-27 14:48:03,766 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
2021-01-27 14:48:03,766 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
2021-01-27 14:48:03,766 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
2021-01-27 14:48:03,787 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
2021-01-27 14:48:03,787 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
2021-01-27 14:48:03,788 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1) Starting PostgresConnectorTask with configuration:
2021-01-27 14:48:03,789 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    connector.class = io.debezium.connector.postgresql.PostgresConnector
2021-01-27 14:48:03,789 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    offset.flush.interval.ms = 0
2021-01-27 14:48:03,789 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    database.user = root
2021-01-27 14:48:03,789 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    database.dbname = postgres
2021-01-27 14:48:03,789 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    offset.storage.file.filename = data/offsets.dat
2021-01-27 14:48:03,789 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    database.hostname = 192.168.60.128
2021-01-27 14:48:03,790 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    database.password = ********
2021-01-27 14:48:03,790 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    name = kinesis
2021-01-27 14:48:03,790 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    schema.include.list = inventory
2021-01-27 14:48:03,790 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    database.server.name = tutorial
2021-01-27 14:48:03,790 INFO  [io.deb.con.com.BaseSourceTask] (pool-3-thread-1)    database.port = 5432
2021-01-27 14:48:04,579 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
2021-01-27 14:48:04,580 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
2021-01-27 14:48:04,580 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
2021-01-27 14:48:04,588 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:04,954 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-3,5,main]=Thread[vert.x-eventloop-thread-3,5,main] has been blocked for 2046 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:260)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:204)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:879)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:848)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.DeploymentManager$$Lambda$212/1334405552.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$213/207988207.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2021-01-27 14:48:04,958 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-1,5,main]=Thread[vert.x-eventloop-thread-1,5,main] has been blocked for 4486 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:260)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:204)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:879)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:848)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.DeploymentManager$$Lambda$212/1334405552.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$213/207988207.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2021-01-27 14:48:04,964 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-2,5,main]=Thread[vert.x-eventloop-thread-2,5,main] has been blocked for 2046 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at java.util.zip.ZipFile.read(Native Method)
	at java.util.zip.ZipFile.access$1400(ZipFile.java:60)
	at java.util.zip.ZipFile$ZipFileInputStream.read(ZipFile.java:734)
	at java.util.zip.ZipFile$ZipFileInflaterInputStream.fill(ZipFile.java:434)
	at java.util.zip.InflaterInputStream.read(InflaterInputStream.java:158)
	at sun.misc.Resource.getBytes(Resource.java:124)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:462)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:73)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:368)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:362)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:361)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:335)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
	at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
	at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
	at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
	at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
	at io.vertx.core.impl.AddressResolver.resolveHostname(AddressResolver.java:83)
	at io.vertx.core.impl.VertxImpl.resolveAddress(VertxImpl.java:810)
	at io.vertx.core.net.impl.AsyncResolveConnectHelper.doBind(AsyncResolveConnectHelper.java:56)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:289)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:204)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:879)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:848)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.DeploymentManager$$Lambda$212/1334405552.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$213/207988207.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2021-01-27 14:48:04,971 WARNING [io.ver.cor.imp.BlockedThreadChecker] (vertx-blocked-thread-checker) Thread Thread[vert.x-eventloop-thread-0,5,main]=Thread[vert.x-eventloop-thread-0,5,main] has been blocked for 4510 ms, time limit is 2000 ms: io.vertx.core.VertxException: Thread blocked
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:260)
	at io.vertx.core.http.impl.HttpServerImpl.listen(HttpServerImpl.java:204)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.setupTcpHttpServer(VertxHttpRecorder.java:879)
	at io.quarkus.vertx.http.runtime.VertxHttpRecorder$WebDeploymentVerticle.start(VertxHttpRecorder.java:848)
	at io.vertx.core.Verticle.start(Verticle.java:66)
	at io.vertx.core.impl.DeploymentManager.lambda$doDeploy$9(DeploymentManager.java:556)
	at io.vertx.core.impl.DeploymentManager$$Lambda$212/1334405552.handle(Unknown Source)
	at io.vertx.core.impl.ContextImpl.executeTask(ContextImpl.java:366)
	at io.vertx.core.impl.EventLoopContext.lambda$executeAsync$0(EventLoopContext.java:38)
	at io.vertx.core.impl.EventLoopContext$$Lambda$213/207988207.run(Unknown Source)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:164)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:472)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:500)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.lang.Thread.run(Thread.java:748)

2021-01-27 14:48:05,378 INFO  [io.quarkus] (main) debezium-server-dist 1.3.1.Final on JVM (powered by Quarkus 1.7.1.Final) started in 15.023s. Listening on: http://0.0.0.0:8080
2021-01-27 14:48:05,387 INFO  [io.quarkus] (main) Profile prod activated. 
2021-01-27 14:48:05,388 INFO  [io.quarkus] (main) Installed features: [cdi, smallrye-health]
2021-01-27 14:48:07,438 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
2021-01-27 14:48:07,439 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
2021-01-27 14:48:07,439 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
2021-01-27 14:48:07,443 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
2021-01-27 14:48:07,443 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:07,447 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "schema.blacklist" is deprecated and will be removed in future versions. Please use "schema.exclude.list" instead.
2021-01-27 14:48:07,448 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.blacklist" is deprecated and will be removed in future versions. Please use "table.exclude.list" instead.
2021-01-27 14:48:07,448 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "table.whitelist" is deprecated and will be removed in future versions. Please use "table.include.list" instead.
2021-01-27 14:48:07,449 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.whitelist" is deprecated and will be removed in future versions. Please use "column.include.list" instead.
2021-01-27 14:48:07,450 WARN  [io.deb.con.Configuration] (pool-3-thread-1) Using configuration property "column.blacklist" is deprecated and will be removed in future versions. Please use "column.exclude.list" instead.
2021-01-27 14:48:07,542 INFO  [io.deb.con.pos.PostgresConnectorTask] (pool-3-thread-1) user 'root' connected to database 'postgres' on PostgreSQL 10.15 on x86_64-pc-linux-gnu, compiled by gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-39), 64-bit with roles:
	role 'pg_read_all_settings' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: false]
	role 'test_user' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: true]
	role 'lottu1' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: true]
	role 'pg_stat_scan_tables' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: false]
	role 'root' [superuser: true, replication: true, inherit: true, create role: true, create db: true, can log in: true]
	role 'pg_monitor' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: false]
	role 'postgres' [superuser: true, replication: true, inherit: true, create role: true, create db: true, can log in: true]
	role 'pg_read_all_stats' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: false]
	role 'pg_signal_backend' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: false]
	role 'lottu2' [superuser: false, replication: false, inherit: true, create role: false, create db: false, can log in: true]
	role 'lottu3' [superuser: false, replication: false, inherit: true, create role: false, create db: true, can log in: true]
2021-01-27 14:48:07,657 INFO  [io.deb.con.pos.con.PostgresConnection] (pool-3-thread-1) Obtained valid replication slot ReplicationSlot [active=false, latestFlushedLsn=null, catalogXmin=null]
2021-01-27 14:48:07,657 INFO  [io.deb.con.pos.PostgresConnectorTask] (pool-3-thread-1) No previous offset found
2021-01-27 14:48:07,658 INFO  [io.deb.con.pos.sna.InitialSnapshotter] (pool-3-thread-1) Taking initial snapshot for new datasource
2021-01-27 14:48:07,852 INFO  [io.deb.con.pos.con.PostgresReplicationConnection] (pool-3-thread-1) Creating replication slot with command CREATE_REPLICATION_SLOT debezium  LOGICAL decoderbufs
2021-01-27 14:48:07,907 INFO  [org.apa.kaf.con.sto.FileOffsetBackingStore] (pool-3-thread-1) Stopped FileOffsetBackingStore
2021-01-27 14:48:07,909 INFO  [io.deb.ser.ConnectorLifecycle] (pool-3-thread-1) Connector completed: success = 'false', message = 'Unable to initialize and start connector's task class 'io.debezium.connector.postgresql.PostgresConnectorTask' with config: {name=kinesis, connector.class=io.debezium.connector.postgresql.PostgresConnector, database.port=5432, schema.include.list=inventory, database.user=root, offset.storage.file.filename=data/offsets.dat, database.hostname=192.168.60.128, database.password=********, database.server.name=tutorial, offset.flush.interval.ms=0, database.dbname=postgres}', error = '{}': io.debezium.DebeziumException: Creation of replication slot failed
	at io.debezium.connector.postgresql.PostgresConnectorTask.start(PostgresConnectorTask.java:132)
	at io.debezium.connector.common.BaseSourceTask.start(BaseSourceTask.java:106)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:758)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:171)
	at io.debezium.server.DebeziumServer.lambda$start$1(DebeziumServer.java:139)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

**Pull request closed without merging**
