### PR TITLE
DBZ-2677 Columns in ResultSet should be get in order.

### PR DESCRIPTION
**Pull request by pikaaQ**
In some earlier version of oracle-jdbc, a “Stream has already been closed” exception will be throw when get value from ResultSet out-of-order.

### CODE REVIEW

**Review by gunnarmorling — COMMENTED** [review]
Wow, that sounds a bit scary :) Which driver version is this? Is this version supported by Debezium even? That said, nothing speaks against doing this change. Could you only author the commit with an e-mail address associated to your GH account and force-push to this PR? Thx!

**Comment by Naros** [comment]
We recently patched this problem in [DBZ-2624](https://issues.redhat.com/browse/DBZ-2624).  During my analysis, there was not a reason to reorder all columns but specifically to fetch the value of column 13 (the default value) before any other column.  This was because of how the `LONG` / `LONGRAW` data types are read as indicated in the screen shots for DBZ-2677.  

Can you please test with the latest 1.4.0.Alpha1 build of Debezium and see if this problem still occurs?  If it doesn't, I'm inclined to suggest we close this issue as duplicate to DBZ-2624.  If there is still an outstanding issue, then because DBZ-2624 added an overridden variant of the function you modified, could you make the necessary changes against the debezium-incubator oracle connector instead?

**Comment by pikaaQ** [comment]
> Wow, that sounds a bit scary :) Which driver version is this? Is this version supported by Debezium even? That said, nothing speaks against doing this change. Could you only author the commit with an e-mail address associated to your GH account and force-push to this PR? Thx!

@gunnarmorling I’v just traversed the versions of ojdbc8,  and found out the last version with the “Stream has already been closed” exception is ojdbc8-18.3.0.0 (Feb, 2020). As oracle-connector is in incubation state, I don't know which version is the last supported version by Debezium.
I put my experience in the [issue tracker](https://issues.redhat.com/projects/DBZ/issues/DBZ-2677) and thought it's linked by the issue code “DBZ-2677”.  Sorry for zero-comment on GH.

**Comment by pikaaQ** [comment]
> We recently patched this problem in [DBZ-2624](https://issues.redhat.com/browse/DBZ-2624). During my analysis, there was not a reason to reorder all columns but specifically to fetch the value of column 13 (the default value) before any other column. This was because of how the `LONG` / `LONGRAW` data types are read as indicated in the screen shots for DBZ-2677.
> 
> Can you please test with the latest 1.4.0.Alpha1 build of Debezium and see if this problem still occurs? If it doesn't, I'm inclined to suggest we close this issue as duplicate to DBZ-2624. If there is still an outstanding issue, then because DBZ-2624 added an overridden variant of the function you modified, could you make the necessary changes against the debezium-incubator oracle connector instead?

@Naros This issue don't occur in the test with the latest 1.4.0.Alpha1 and I see the overridden variant in io.debezium.connector.oracle.OracleConnection.  It's ok except feeling wired about the order.
As ojdbc8 docs mentioned, "For maximum portability, result set columns within each row should be read in left-to-right order, and each column should be read only once”, I still think it's a better solution(at least a better code style) to make the indexes in order.
But I can feel your concern about stability and this fix may be enough now.  It's OK to merge this issue and close this PR.

**Pull request closed without merging**
