### PR TITLE
DBZ-4364 Fix missing method call

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4364

### CODE REVIEW

**Comment by jpechane** [comment]
The failure is casued by the comparison code - ther is a `BYTES` field that is byte array and after deserialization it is {{HeapBuffer}} - but the content in both cases is the same.

**Comment by gunnarmorling** [comment]
Ok, cool. I was scared a bit, but it seems it's not that bad after all.

**Comment by gunnarmorling** [comment]
@jpechane, so the test failure is unrelated, but it's not the first time I see the same root cause:

```
2021-11-26T07:50:59.0396140Z Caused by: org.postgresql.util.PSQLException: ERROR: could not open relation with OID 18941
2021-11-26T07:50:59.0398007Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2565)
2021-11-26T07:50:59.0400434Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2297)
2021-11-26T07:50:59.0402440Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
2021-11-26T07:50:59.0404207Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
2021-11-26T07:50:59.0405907Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
2021-11-26T07:50:59.0407282Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
2021-11-26T07:50:59.0408934Z 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
2021-11-26T07:50:59.0410425Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
2021-11-26T07:50:59.0411856Z 	at org.postgresql.jdbc.PgStatement.executeQuery(PgStatement.java:236)
2021-11-26T07:50:59.0413591Z 	at org.postgresql.jdbc.PgDatabaseMetaData.getColumns(PgDatabaseMetaData.java:1577)
2021-11-26T07:50:59.0415250Z 	at io.debezium.jdbc.JdbcConnection.getColumnsDetails(JdbcConnection.java:1236)
2021-11-26T07:50:59.0417072Z 	at io.debezium.jdbc.JdbcConnection.readSchema(JdbcConnection.java:1201)
2021-11-26T07:50:59.0419528Z 	at io.debezium.connector.postgresql.PostgresSchema.refresh(PostgresSchema.java:88)
2021-11-26T07:50:59.0422128Z 	at io.debezium.connector.postgresql.PostgresTaskContext.refreshSchema(PostgresTaskContext.java:68)
2021-11-26T07:50:59.0425602Z 	at io.debezium.connector.postgresql.PostgresStreamingChangeEventSource.init(PostgresStreamingChangeEventSource.java:96)
```

The actual problem isn't clear to me, I suppose some odd consistency issue in Postgres and its data catalog. I'm wondering though whether we could and should mitigate it by implementing some kind of local retry logical within `PostgresTaskContext::refreshSchema()`. WDYT?

**Comment by gunnarmorling** [comment]
Hum, happened in the exact same method [here](https://github.com/debezium/debezium/pull/2980) too. That can't be a coincidence?

**Comment by gunnarmorling** [comment]
Pushed an attempt to fix this intermittent issue. This fails many builds now.

**Comment by gunnarmorling** [comment]
@jpechane, so not quite sure whether this fixes the issue 100%, but at least that build is green now. Can you take a look and merge if you think it's ok?

**Pull request merged**
