### PR TITLE
DBZ-1962 Introduce column.whitelist for the MySql connector

### PR DESCRIPTION
**Pull request by jhuiting**
See https://issues.redhat.com/browse/DBZ-1962

Right only the Debezium Postgres connector [supports the column whitelist](https://github.com/debezium/debezium/pull/1407), adding it for MySQL as well.

Todo
- Update documentation for MySQL

### CODE REVIEW

**Comment by rk3rn3r** [comment]
Yes, when this PR was created I was looking already into exactly that. I came to the conclusion that's easier I merge it to my branch when it's done or when it's in master. It's easier for me to solve the conflicts in my t's quite complex change and there'll be duplicates in debezium-core etc. So once this is done, I'll resolve the issues.

**Comment by jhuiting** [comment]
@gunnarmorling @rk3rn3r OK, I'll try to fix the test and add the missing documentation. Not sure what's going on with the test, seems to be failing locally now as well.

**Comment by jhuiting** [comment]
@rk3rn3r @gunnarmorling Please check again, I've added documentation for the property, and fixed the test. Took me a while to realize that the test that I'd use as an example was actually failing for the wrong reason. Fixed that test as well.

**Comment by rk3rn3r** [comment]
Hey @jhuiting! like mentioned before, we are about to remove divisive language from Debezium.

We will merge #1750 soon that tackles the topic. Can you maybe update your PR based on the new naming and only use COLUMN_INCLUDE_LIST (column.include.list)? As soon as the other PR is merged I will notify you so that you can rebase your branch on the updated master.

**Comment by jhuiting** [comment]
@rk3rn3r Fine with me, I'll rebase as soon the other MR is merged.

**Comment by gunnarmorling** [comment]
@rk3rn3r where are we with this one? Is it good to go?

**Comment by jhuiting** [comment]
@rk3rn3r @gunnarmorling For me this PR is still good to go :-)

**Comment by gunnarmorling** [comment]
Thanks for the reminder! LGTM, will merge. Thanks, @jhuiting!

**Comment by gunnarmorling** [comment]
Just realizing that this referenced the original Jira issue that already had been closed a while ago (for Postgres). So I created https://issues.redhat.com/browse/DBZ-2508 just for the purpose of adding this to the change log, but I cannot modify the commit message anymore.

**Pull request merged**
