### PR TITLE
DBZ-5838 Run test against Apicurio registry

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-5838

### CODE REVIEW

**Comment by vjuranek** [comment]
After this change there should be a few failures in Oracle job - this is tracked under [DBZ-5880](https://issues.redhat.com/browse/DBZ-5880). Also there is a failure of `io.debezium.connector.postgresql.LogicalDecodingMessageIT.shouldApplyBinaryHandlingMode` on Postgres 14 and 15 with pgoutpu and randomly failing `io.debezium.connector.postgresql.TablesWithoutPrimaryKeyIT.shouldProcessFromStreamingOld` on Postgres 14 with pgoutput which I'm still investigating.

**Review by obabec — APPROVED** [review]
Looks good to me. I am curious when the Apicurio folks will fix the bugs.

**Comment by vjuranek** [comment]
@jpechane all green now:-)

**Comment by jpechane** [comment]
@vjuranek Applied, thanks a lot!

**Pull request merged**
