### PR TITLE
DBZ-7633 Add Postgres end-to-end JMH test for Debezium engine

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-7633

Example output:

```
Benchmark                                          (eventCount)  Mode  Cnt   Score   Error  Units
PostgresEndToEndPerf.processRecordsAsyncEngine             1000    ss        0.750           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine            10000    ss        1.000           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000    ss        2.248           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000    ss       14.941           s/op
PostgresEndToEndPerf.processRecordsEmbeddedEngine          1000    ss        0.799           s/op
PostgresEndToEndPerf.processRecordsEmbeddedEngine         10000    ss        0.981           s/op
PostgresEndToEndPerf.processRecordsEmbeddedEngine        100000    ss        2.636           s/op
PostgresEndToEndPerf.processRecordsEmbeddedEngine       1000000    ss       19.919           s/op

```

### CODE REVIEW

**Comment by jpechane** [comment]
Should it be tested with different thread counts?

**Comment by vjuranek** [comment]
Good idea @jpechane ! I added in the single run varying number of threads and processing order.

**Comment by vjuranek** [comment]
Example output now:
```
Benchmark                                          (eventCount)  (processingOrder)  (threadCount)  Mode  Cnt   Score   Error  Units
PostgresEndToEndPerf.processRecordsAsyncEngine           100000            ORDERED              1    ss        2.620           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000            ORDERED              2    ss        2.362           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000            ORDERED              4    ss        2.495           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000            ORDERED              8    ss        2.355           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000            ORDERED             16    ss        2.965           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000          UNORDERED              1    ss        2.090           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000          UNORDERED              2    ss        4.157           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000          UNORDERED              4    ss        2.753           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000          UNORDERED              8    ss        2.358           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine           100000          UNORDERED             16    ss        2.977           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000            ORDERED              1    ss       20.142           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000            ORDERED              2    ss       16.904           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000            ORDERED              4    ss       16.446           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000            ORDERED              8    ss       16.285           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000            ORDERED             16    ss       18.261           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000          UNORDERED              1    ss       19.051           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000          UNORDERED              2    ss       18.875           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000          UNORDERED              4    ss       19.196           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000          UNORDERED              8    ss       17.951           s/op
PostgresEndToEndPerf.processRecordsAsyncEngine          1000000          UNORDERED             16    ss       17.004           s/op
PostgresEndToEndPerf.processRecordsEmbeddedEngine        100000                N/A            N/A    ss        2.580           s/op
PostgresEndToEndPerf.processRecordsEmbeddedEngine       1000000                N/A            N/A    ss       22.049           s/op
```

**Review by jpechane — CHANGES_REQUESTED** [review]
@vjuranek LGTM, thanks! Just please use word `engine` in module and package name instead of `embedded`. When done feel free to merge the PR yourself.

**Pull request merged**
