### PR TITLE
DBZ-2870 Enforce Java 11

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2870

### CODE REVIEW

**Comment by rk3rn3r** [comment]
@jpechane will Cassandra work with Java 11? Then maybe you just have to add
```
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
```
to the Cassandra build workflow to make the tests pass?

**Comment by gunnarmorling** [comment]
@rk3rn3r, nope, unfortunately, Cassandra 3.x (which is what we're still relying on), doesn't work with JDK 11, AFAIK. Hence we decided to not go all in with Java 11 just yet. It's required for the build and will be the officially recommended runtime version, but things essentially still will work with 1.8 for the time being.

**Comment by gunnarmorling** [comment]
That being said, yes, the enforcer rule needs overriding, which is done in https://github.com/debezium/debezium-connector-cassandra/pull/27.

**Comment by rk3rn3r** [comment]
Sure, I assumed we generally switch to Java 11 now and also upgrade Cassandra accordingly.

**Comment by gunnarmorling** [comment]
@rk3rn3r, we'd love to, but this turned out to be a bit more work, so it's not done within a minute.

**Review by gunnarmorling — APPROVED** [review]

**Pull request merged**
