### PR TITLE
DBZ-529 Upgrade to MongoDB 3.6, compatibility testing

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-529

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane So are we testing against 3.4 *and* 3.6 on CI?

**Comment by jpechane** [comment]
@gunnarmorling No 3.6 and 3.2 (3.2 was used by default in the past so I kept it)

**Comment by gunnarmorling** [comment]
Ok, that seems reasonable. I'm wondering though why we don't see this issue when testing on 3.6: 

* https://issues.jboss.org/browse/DBZ-624
* WIP PR https://github.com/debezium/debezium/pull/443

Is the SMT not tested against 3.6? Having some more certainty around this one would be desirable. So that at least we can say something like that the SMT won't work with 3.6 for the time being, but we're confident about the actual connector. Or, ideally, make the SMT work with 3.6, too.

**Comment by jpechane** [comment]
@gunnarmorling IMHO the SMT is not tested as an integration test against the MongoDB but only against messages created by `RecordMakers` so the version has no impact on the test execution.

**Comment by gunnarmorling** [comment]
Ah, yes. I think we should add an integration test then. Should be possible
to get a source record from the connector and feed it to the SMT. WDYT?

**Comment by jpechane** [comment]
@gunnarmorling It is definitely good idea. But should it be done as part of this PR? When added the Travis test will be broken. Or If we add it it should be ignored by default and enabled only after DBZ-624 is fixed

**Comment by gunnarmorling** [comment]
Yes, we can handle it separately (as part of DBZ-624 would make sense). I'm
bringing it up though for the purposes of documentation. We should say
somewhere in the docs that the SMT isn't supported for 3.6 for now and also
we should double-check in the connector docs, whether we say anything on
the patch format in emitted messages. Some comment may be in order, stating
that there are differences depending on the version of MongoDB.

**Comment by jpechane** [comment]
@gunnarmorling  I've prepared a docs https://github.com/debezium/debezium.github.io/pull/142 PR

**Comment by gunnarmorling** [comment]
Applied. Thanks, @jpechane!

**Pull request merged**
