### PR TITLE
DBZ-3650 Image for creating KAFKA containers based on RHEL

### PR DESCRIPTION
**Pull request by novotnyJiri**
https://issues.redhat.com/browse/DBZ-3650

### CODE REVIEW

**Review by jcechace — APPROVED** [review]
LGTM. @jpechane  please have a second look.

**Comment by jpechane** [comment]
@novotnyJiri How the shell scripts differe from upstrem ones? If they are the same they might be just download from github during the build time?

**Comment by gunnarmorling** [comment]
@jpechane, can you take care of this one? There's an "octocat" commit btw. which needs sorting out // CC @novotnyJiri

**Comment by jpechane** [comment]
@novotnyJiri Approved, thanks!

**Pull request merged**
