### PR TITLE
Add "table.fields.additional.error.on.missing" config support to Outb…

### PR DESCRIPTION
**Pull request by yinzara**
…ox EventRouter

### CODE REVIEW

**Comment by betmix-matt** [comment]
https://debezium.zulipchat.com/#narrow/stream/348249-community-postgresql/topic/Adding.20a.20new.20field.20to.20outbox.20table

**Review by Naros — APPROVED** [review]

**Comment by jpechane** [comment]
@Naros Is there anything needed before merge?

**Comment by Naros** [comment]
Nope @jpechane, I just failed to merge it.  Sorry about.

**Comment by Naros** [comment]
Applied to main (=2.5).

**Pull request merged**
