### PR TITLE
DBZ-8092: No viable alternative at input "add COLUMN yes"

### PR DESCRIPTION
**Pull request by ramanenka**
https://issues.redhat.com/browse/DBZ-8092

MySQL permits `yes` keyword to be used as an identifier.

### CODE REVIEW

**Comment by ramanenka** [comment]
Also submitted upstream: https://github.com/antlr/grammars-v4/pull/4170.

**Comment by Naros** [comment]
Hi @ramanenka this likely also applies to MariaDB, could you adjust that grammar, too?

**Comment by ramanenka** [comment]
@Naros Adjusted MariaDB's grammar as well.

**Review by Naros — APPROVED** [review]
LGTM @ramanenka, letting all the CI jobs finish before merging.

**Comment by Naros** [comment]
Applied to main (=3.0) and branch 2.7.  Thanks @ramanenka !

**Pull request merged**
