### PR TITLE
DBZ-5544 Support BASE64_URL_SAFE in BinaryHandlingMode

### PR DESCRIPTION
**Pull request by pkgonan**
Background
* For high-volume processing, Relational Databases typically store UUIDs as binary(16) type. This is usually used as a unique identifier and can be exposed in the URL. Therefore, the Base64 Url Safe Encoding method should be user-selectable.
* Debezium JdbcValueConverters.java support BASE64 BinaryHandlingMode. But it is not url safe.

Purpose
* Support BASE64_URL_SAFE in BinaryHandlingMode 

Jira
* https://issues.redhat.com/browse/DBZ-5544

### CODE REVIEW

**Comment by jpechane** [comment]
@pkgonan LGTM, thanks! Could you please also add documentation update?

**Comment by pkgonan** [comment]
@jpechane Hi. Thank you for reviewing PR.

What do you mean by document update? If you have a PR that I can refer to, please let me know.

**Comment by jpechane** [comment]
Please see https://github.com/debezium/debezium/tree/main/documentation/modules/ROOT/pages/connectors

**Comment by pkgonan** [comment]
@jpechane 
Hi. I've updated document.

**Comment by jpechane** [comment]
@pkgonan Applied, thanks!

**Pull request merged**
