### PR TITLE
[DBZ-1869] Bump MongoDB java driver to the latest version 3.12.2

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@oscerd, are you seeing that test failure locally, too? It's a new test just added recently, so it might also be flaky independent of your change, but I'm curious. Thanks.

**Comment by oscerd** [comment]
Hey @gunnarmorling, no locally I don't have that failure. I can investigate btw.

**Comment by gunnarmorling** [comment]
Thanks, that'd be awesome. It's about a new feature for skipping specific event types. Not quite sure right now what could be causing it.

**Comment by oscerd** [comment]
Do you want me to close this and re-open it later?

**Comment by gunnarmorling** [comment]
As you prefer. If you think you'd find the time to look into the test
failure, let's just keep it open for now.

**Comment by oscerd** [comment]
I'll leave it open and I'll investigate a bit

**Comment by jpechane** [comment]
https://issues.redhat.com/browse/DBZ-1867

**Comment by oscerd** [comment]
@jpechane done!

**Comment by oscerd** [comment]
@jpechane done! updated the commit message too

**Comment by jpechane** [comment]
@oscerd Applied, thanks!

**Pull request merged**
