### PR TITLE
DBZ-5592 Allow LIST_VALUE_CLAUSE to use TIMESTAMP LITERAL

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-5592

### CODE REVIEW

**Comment by ani-sha** [comment]
Hi, @Naros are there any other changes required for this Jira? 
After your review, I am going to add changes for the upstream. Thanks.

**Review by Naros — APPROVED** [review]
LGTM @ani-sha, waiting to hear when its safe to merge.  You can proceed with the upstream PR if you haven't already.  Thanks!

**Comment by ani-sha** [comment]
Upstream PR - https://github.com/antlr/grammars-v4/pull/2817

**Comment by jpechane** [comment]
Witholding the merge. @ani-sha it seems that the upstream build has failed. Could you please check what is going on? Is it possible that our grammar is to divereg from the upstream one?

**Review by jpechane — CHANGES_REQUESTED** [review]
Temporarily putting PR on hold to see why upstream is failing

**Comment by ani-sha** [comment]
@jpechane One small change was required for `PARTITION_NAME`. It looks good now. Checks should be passing.

**Comment by jpechane** [comment]
@ani-sha Could you please rebase the PR on the latest main? Thanks

**Comment by jpechane** [comment]
@ani-sha Applied, thanks

**Pull request merged**
