### PR TITLE
DBZ-935 Error while parsing json column type for MySQL

### PR DESCRIPTION
**Pull request by deepakbarr**
https://issues.jboss.org/projects/DBZ/issues/DBZ-935

### CODE REVIEW

**Comment by jpechane** [comment]
@deepakbarr Looks good to me, thanks for the contribution! Could you please drop the colon from the commit message? Also is it possible to add a test case to verify the code?

**Comment by deepakbarr** [comment]
@jpechane  Thanks for the review. I have addressed the review comments and updated the PR. However, I see that the Travis CI build is failing because of a different error. The error I see in the job log is 

"The command "wget https://archive.apache.org/dist/maven/maven-3/3.3.9/binaries/apache-maven-3.3.9-bin.zip" failed and exited with 4 during ."
Seems like some connectivity issue. Is there a way to trigger this again ?

**Comment by jpechane** [comment]
@deepakbarr I've restarted the job

**Comment by jpechane** [comment]
@deepakbarr Perfect! One last plea, could you please squash all the commits into a single one? We would like to remove the merge commits and all those without DBZ prefix. Thanks!

**Comment by jpechane** [comment]
@deepakbarr Applied, thanks for the contribution!

**Pull request merged**
