### PR TITLE
DBZ-576 Internal parameters

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-576

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane I'm a bit confused about that one, didn't we agree on _not_ adding the notion of internal parameters? As that'd mean a change to the name (and thus code using it) when promoting it to a "supported" option?

**Comment by jpechane** [comment]
IIRC we agreed on introducing internal properties but without a formal promotion process. Also the documentation should contain warning about using them. See https://gitter.im/debezium/dev?at=5a69c44d98927d5745345112

**Comment by gunnarmorling** [comment]
@jpechane Ok, makes sense. Thanks for the pointer back to the discussion. This change itself doesn't add much, though. How about using the vehicle for the existing undocumented options. There's the DDL filter one, and I think one more. It seems reasonable to rename those into the new namespace. Then, to the migration notes, we should add a mention of this (while the options had been unsupported, it's a good thing to point out to the name change to any potential users there may be).

**Comment by jpechane** [comment]
@gunnarmorling DDL filter was made internal. Unfortunately I do not recall the other one - is there really more than one?

**Comment by gunnarmorling** [comment]
Merged. Thanks, @jpechane! The one I had been thinking about was `binlog.buffer.size`, but indeed that's mentioned in the docs, just in status "incubating". So `ddl.filter` seems to be the only one.

**Pull request merged**
