### PR TITLE
DBZ-1267 Order capture instances by create date

### PR DESCRIPTION
**Pull request by grzegorz8**

### CODE REVIEW

**Comment by jpechane** [comment]
@grzegorz8 I am not really sure about this change. How the code will behave in case of clock skew? What if NTP client will sync time in such a way that it will go back in time? Will not we receive an incorrecto ordering of the events then?

**Comment by grzegorz8** [comment]
Yes, you are right. I haven't taken that into account.

**Comment by grzegorz8** [comment]
On the other hand, I expect that no-one creates capture instances so frequently for the same table that we should worry about clock issues.

NTP would slow down the clock rather that move backwards. 
https://serverfault.com/questions/94683/will-ntp-drift-the-clock-backwards

**Comment by jpechane** [comment]
@grzegorz8 NTP was just an example, Generally relying on clock for event ordering is very risky. And also this would need to be tested for DST etc.

**Comment by grzegorz8** [comment]
Then none of the fields is perfectly reliable.

- start_lsn - good if we assume that capture instance is deleted relatively quick (in <= N days, where N is log retention period).
- createDate - good if capture instances are not created so frequently that time issues might complicate things.

I  also checked object_id but it is just a random number.

**Comment by jpechane** [comment]
@grzegorz8 I think the option 1 is less risky as it is something that can be controlled way easier than time issues.

**Comment by grzegorz8** [comment]
Ok, so I am closing this PR.

**Pull request closed without merging**
