### PR TITLE
DBZ-3377 Restart Oracle connector on ORA-01291, missing logfile

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3377

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Is restarting going to mitigate this issue actually?

**Comment by Naros** [comment]
The reporter's ORA-01291 error situation is based on the premise that their redo log filenames aren't static.  They embed the log's sequence number in the name, so this means when a redo log rotates to an archive log, the redo log gets a new name.   This creates a problem with LogMiner if its in the middle of mining a given redo log and it gets swapped out to an archive log.  This change is meant to avoid the user needing to have a restart script for themselves and to automatically restart the connector for them.

**Comment by Naros** [comment]
> will the connector be able to continue to run successfully after the restart, or will it fail again due to any missing log files?

In the case of the reporter's problem, it would restart fine and it would process the now archive logs successfully; however when the connector catches up to the current redo log, it's possible due to their high volume of log switches that eventually another ORA-01291 exception will be thrown and the connector would again stop & restart.  

The other alternative here would be to catch this exception at runtime and attempt to retry the mining session ourselves and if a restart of the mining session leads to another ORA-01291 we throw the exception and let the connector stop.  But I think given the environment that the reporter is working within, this is really meant to give them a built-in solution rather than relying on an automated script of their own since there is little which we can do to mitigate against the error in the first place due to the sheer volume of log swaps & naming conventions used.

**Comment by gunnarmorling** [comment]
Applied, thx!

**Pull request merged**
