### PR TITLE
DBZ-4742 change connect config to use WorkerConfig

### PR DESCRIPTION
**Pull request by zalmane**
https://issues.redhat.com/browse/DBZ-4742

This changes the config values passed to the connector to use those that were processed by the WorkerConfig, similar to those sent to the OffsetStore. It then enables any ConfigProviders such as FileConfig to support secrets.
I ran the tests and could not see any side effects. Please review.

### CODE REVIEW

**Comment by zalmane** [comment]
Yes, seems to work fine. The main issue was that the WorkerConfig seems to contain the properties after all interpolations, but the config sent to the Connector was using the original properties map. See the JIRA ticket for the properties I used. I tested it with a FileConfigProvider as described in the Debezium blog post about secrets and seems to function OK. I was not sure if there are any other side effects you can think of. The full tests seemed to run fine.

**Comment by zalmane** [comment]
@gunnarmorling Is there any comments about this PR? What is needed to push this forward?

**Comment by gunnarmorling** [comment]
@zalmane, can we have a test for this in any way?

**Comment by zalmane** [comment]
yes, what is the best place to add the test?

**Comment by gunnarmorling** [comment]
I think ultimately, you'd want to add a test for the feature you describe in DBZ-4742, being able to use config providers, e.g. with secrets. This could go into the Debezium Server module. In that light I'm actually wondering whether the proposed change is enough, because I don't think anywhere in DBZ Server we'd yet try to instantiate and use such config provider, or do we?

**Comment by zalmane** [comment]
I think the WorkerConfig does set up the providers and seems to work OK. I'll add the test and it will verify the functionality is working as intended.

**Comment by gunnarmorling** [comment]
> I think the WorkerConfig does set up the providers and seems to work OK

Ah, yes, I see where you're coming from. Anyways, the test will show how well it works. Thx!

**Comment by spicy-sauce** [comment]
@gunnarmorling  @zalmane I'll try to provide this test today, hopefully we will be able to include this too in 1.9.
Once completed, I'll open a new PR with this change and the test.

**Comment by jpechane** [comment]
@zalmane Applied, thanks a lot!

**Comment by jonapgar-groupby** [comment]
To anyone coming here looking for clues as to why this still may not work. If you're using the quarkus build the `${file:...}` property will be interpreted as a env substitution. You need to use an addition dollar-sign `$${file:...}`

**Pull request merged**
