### PR TITLE
DBZ-1886 Separate storageExists() method to support manual topic creation

### PR DESCRIPTION
**Pull request by ivan-klass**
https://issues.redhat.com/browse/DBZ-1886

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks a lot for the report and the suggested fix. I agree that the connector shouldn't try to create the topic if it actually exists already.

I'm wondering though whether we can get around adding yet another configuration option. Taking a step back, there are two distinct notions involved:

* Does the history *storage* exist?
* Does the *history* exist?

The former should drive the creation of the history topic, the latter should drive initial snapshotting. Currently, we cannot distinguish between the two notions, though. So how about adding a new method `DatabaseHistory#storageExists()` and using this one for answering the first question? Its implementaion would check whether the topic exists or not. WDYT?

**Comment by gunnarmorling** [comment]
Hey @ivan-klass, any news on this one?

**Comment by ivan-klass** [comment]
I like the suggested separation of storage / history. Wondering if we could just set some "not-yet-implemented" default (e.g. return "true" before follow-up issues completed) for non-kafka storages

**Comment by gunnarmorling** [comment]
@ivan-klass, I'm a bit lost, where are we with this one? Does it need more work? Thanks for clarifying.

**Comment by gunnarmorling** [comment]
Ok, took another look, and it still needs updating as per the discussion above about having two methods to differentiate between topic not existing and history within an existing topic not being present.

@ivan-klass, could you let me know whether you're planning to update this PR along these lines? Thanks!

**Comment by ivan-klass** [comment]
@gunnarmorling the `DatabaseHistory` interface is public. I can update PR with discussed suggestion only if we're good to break binary compatibility for any custom history implementations by requiring `storageExists` method on interface. If so, I can implement it for `FileDatabaseHistory` and `MemoryDatabaseHistory` also

**Comment by gunnarmorling** [comment]
@ivan-klass, yes, adding the method to `DatabaseHistory` is fine; we don't consider it public, user-facing contract that'd require any compatability considerations when evolving it. In other words, no external implementations of this are expected.

**Comment by ivan-klass** [comment]
@gunnarmorling thanks, that makes sense, I will follow up when have time this week

**Comment by ivan-klass** [comment]
@gunnarmorling I've updated PR according to suggested implementation, could you please review again?

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks a lot, @ivan-klass!

**Pull request closed without merging**
