### PR TITLE
DBZ-7298 Add service loader manifests for all Connect plugins

### PR DESCRIPTION
**Pull request by mimaison**
Add manifests for source/sink connectors, converters and transformations.

### CODE REVIEW

**Comment by mimaison** [comment]
If you're happy with the changes, I'll also update:
- debezium-connector-vitess
- debezium-connector-informix
- debezium-connector-cassandra
- debezium-connector-db2
- debezium-connector-spanner
- debezium-connector-jdbc
- debezium-connector-ibmi

**Review by mfvitale — APPROVED** [review]

**Comment by jpechane** [comment]
@mimaison LGTM, thanks for taking care of it!

**Comment by mimaison** [comment]
I've opened the following PRs for the incubating connectors:
- https://github.com/debezium/debezium-connector-vitess/pull/176
- https://github.com/debezium/debezium-connector-informix/pull/16
- https://github.com/debezium/debezium-connector-db2/pull/126
- https://github.com/debezium/debezium-connector-jdbc/pull/54
- https://github.com/debezium/debezium-connector-spanner/pull/79
- https://github.com/debezium/debezium-connector-cassandra/pull/117
- https://github.com/debezium/debezium-connector-ibmi/pull/2

Let me know if I've missed a project.

**Comment by jpechane** [comment]
@mimaison Applied, thanks! I backported it to 2.5 branch too as it is basis for the future product release.

**Pull request merged**
