### PR TITLE
DBZ-2465 Obtaining runtime config via dependency injection

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-2465

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @mkouba / @gsmet could one of you take a look at this one? Thx!

**Review by mkouba — APPROVED** [review]
Looks good. Have you tested it with Quarkus yet?

**Comment by gunnarmorling** [comment]
> Have you tested it with Quarkus yet?

Good question. We do have a very basic integration test, but I'm not 100% sure whether it'd capture any regressions here. @Naros, any thoughts?

**Comment by gunnarmorling** [comment]
Ok, added a more complete test for this, too. @Naros, could you please take a look and merge if you think it's good? Once that's done, I'll add my two commits to @gsmet's PR #1772, too.

**Comment by Naros** [comment]
Hi @gunnarmorling and @gsmet, this LGTM.  Merging.

**Pull request merged**
