### PR TITLE
DBZ-961: fetching wrong data types when postgresql domain types…

### PR DESCRIPTION
**Pull request by linux10000**
… are used;

Added suport to some datatypes from postgresql

### CODE REVIEW

**Comment by jpechane** [comment]
@linux10000 Thanks for the PR. This is a good start but the PR needs a little bit of cleaning up.
1) Remove all whitelist changes so only relevant changes are present
2) The postgres specifi files should go into postgres module not to the core
3) I've seen you've changed the SQL query to get metadata. The query needs to be tested (not as a par of testsuite) for case of hundred of thousands types in the database as we have seen such deployments.

**Comment by gunnarmorling** [comment]
So where are we with this one; @linux10000, do you plan to follow up on the review remarks by @jpechane? Thanks!

**Comment by jpechane** [comment]
@gunnarmorling The original contributor no longer whant to continue with this but I believe we can build a new PR based on the analysis already put in the code

**Comment by gunnarmorling** [comment]
Ok, so I'm going to close this one for now, to clear off the slate a bit. It's referenced from the issue in JIRA, so we'll be able to take up the work later on from there. Thanks!

**Pull request closed without merging**
