### PR TITLE
Dbz 175 snapshot refactor

### PR DESCRIPTION
**Pull request by mtagle**
Just the snapshot refactor portion of DBZ 175

move snapshot logic to AbstractSnapshotReader and SnapshotMySQLUtility

modify existing snapshotReader to use refactored functionality, and rename to SnapshotServerReader to distinguish it from the newly added (but as yet unused) SnapshotTableReader.

### CODE REVIEW

**Comment by rhauch** [comment]
And now stepping back a bit to ask about the motives of this refactoring. Yes, the existing code is complex and difficult to follow, but IMO it also is really easy to debug and step through the various logical steps, and it's also easy to look at a log and understand what it was doing. If we break the logic up into lots of smaller methods, we're going to lose that higher-level understanding of the logic.

Why do we want to do the refactoring? IIUC, a significant reason is that we want to perform different kinds of snapshots, and the current code doesn't allow that. This is a good reason to do a refactoring -- are there other goals/reasons? The refactoring has to be guided by the goals.

Regarding that first goal, IMO the biggest problem with the current code is that `SnapshotReader` is doing two things: it's a _asynchronous reader_  and it implements the _snapshot logic_. These two things need to be separated, and IIUC we want to be able to use different snapshot algorithms for different purposes.

So, as a first step I might just try to separate those two behaviors. First, I might create a `SnapshotAlgorithm` interface that just had one `execute()` method, and we could have different implementations of that interface. We might make a first implementation named `DatabaseSnapshotAlgorithm`, and this would snapshot all of the tables. In fact, we might just try to move the current `SnapshotReader.execute()` code into the `DatabaseSnapshotAlgorithm.execute()` method.

Then, we could change `SnapshotReader` to use a `SnapshotAlgorithm` instance, and change the task to instantiate it with `DatabaseSnapshotAlgorithm`. All of this code should work exactly the same as the current code, and all test should pass.

Only then might we try to simplify the `DatabaseSnapshotAlgorithm.execute()` method. Here I think we could go in a couple of different directions. For example, at a really high level we might want the `DatabaseSnapshotAlgorithm.execute()` method to look like this:

```
try {
  db.acquireGlobalLock();
  if (!isRunning) return;

  db.startTransaction();
  db.readBinlogPosition();
  db.readDatabaseNames();
  db.readTableNames();
  if (!isLocked) {
    db.lockTables();
    db.readBinlogPosition();
  }
  db.generateDdlStatements();
  if (minimalLocking && isLocked) {
    ...
} finally {
  // do all the cleanup here, perhaps in a few steps to make sure it's done correctly
}
```

This is pretty darned attractive, but of course there are problems with simplifying this much. The current logic uses a fair number of variables used to track state shared across all of these steps, and my ultra-high-level ideal code neglects almost all of this (e.g., all of the checks to see if the logic was cancelled). We'd have to rectify that, but it's going to make the algorithm less ideal. 

I think the biggest immediate win is to not try to simplify that much and to instead go step-by-step and try to pull out some of the multi-line chunks of code that would definitely be reusable. For example:

                final List<String> databaseNames = new ArrayList<>();
                sql.set("SHOW DATABASES");
                mysql.query(sql.get(), rs -> {
                    while (rs.next()) {
                        databaseNames.add(rs.getString(1));
                    }
                });
 
That could easily be pulled into a separate method, perhaps on the `MySqlJdbcContext`, so that the above could be replaced by:
         
                final List<String> databaseNames = context.readDatabaseNames();

There are a number of non-trivial loops and blocks that could probably be simplified this way without requiring a lot of passing of state. How far can we get while taking this simple approach.

THEN, we could create the `TableSnapshotAlgorithm` class by copying our new semi-simplified logic and then simplifying, not trying to reuse. It's not clear to me what that logic needs to be, so this approach outlines that logic first and only then can we see where the similarities lie.

WDYT? Am I way off base?

**Comment by jpechane** [comment]
@rhauch I think you are not right path but let me propose one other think. We we really need to intemingle logic of anpashotting when globlac lock is not available with logic where it is not? Maybe it should be separated into two algortihm instances and it would clean the code a little bit too.

**Comment by rhauch** [comment]
@jpechane, I would think that we'd have several algorithms, including the one you mentioned. Obviously the algorithms should be simple enough so that this is feasible. My concern is that we abstract it too much, we might make it really difficult to follow what the heck each is actually doing, or we build up too much state in those methods (e.g., locking) to make it difficult to reuse the methods.

Now that I think about it, the locking logic is complex _but stateful_, while most of the other steps actually are not very stateful (e.g., reading the tables in a database, reading the schemas for a list of tables, or copying the content of a list of tables, etc.). What if we were to pull out the locking logic into a reusable, stateful component, separate from the algorithms? Each algorithm could instantiate that, use the various methods as required, and then in the algorithm's finally block call the locking component's cleanup method that would "do the right thing" no matter which locks were obtained. Actually, @mtagle's snapshot utility class is this plus a bunch of the other non-stateful operations.

**Comment by gunnarmorling** [comment]
+1 for beginning with extracting some of the logic of `SnapshotReader#execute()` into separate methods (i.e. things which doesn't require the propagation of state). Then, in a next step, and regarding variables needed for keeping state, a context parameter object may be introduced which is passed around and keeps track of the required variables. Or, this could be extracted into a separate class, e.g. named `SnapshottingRun` which maintains that state as variables.

Taking a step back, one of my goals would be to explore whether these routines can be made re-usable and shared across connectors, as I'd assume that snapshotting logic may look similar for different RDMBS. But that's not something that'd need addressing with the change at bay. Focusing this refactoring onto what's needed in order to reasonably implement DBZ-175 seems like a good idea to me.

**Pull request closed without merging**
