### PR TITLE
DBZ-198 Add another DDL parser test case

### PR DESCRIPTION
**Pull request by rhauch**
Added an additional test that is unable to reproduce the problem reported on April 4. This test passes with no other changes.

### CODE REVIEW

**Comment by rhauch** [comment]
@gunnarmorling please review and merge if approved.

**Comment by gunnarmorling** [comment]
So you added the `CREATE TABLE` statements before the `ALTER`. They were missing in the original patch (which just contained the `ALTER`), causing the parser go into a wrong branch when handling the `DROP INDEX`. So I was wondering how we could arrive at this state (ALTER without previous CREATE event). So you think it was just an issue with the test actually?

**Comment by rhauch** [comment]
I didn't realize that, so let's hold off on this and I'll try to fix on Monday.

**Comment by gunnarmorling** [comment]
Hey @rhauch, any further insights on this one? Is it just an issue with the original test or can it actually happen we get to an `ALTER TABLE` without knowing that table before (in which case we'd have to adjust the parser)?

**Comment by rhauch** [comment]
@gunnarmorling I've updated the test to better handle `ALTER TABLE` statements that apply to tables not yet known by the parser.

**Comment by gunnarmorling** [comment]
Ok, looks good. It's not clear to me when we run into this case, but it seems better to be prepared for it. Thanks, @rhauch!

**Comment by gunnarmorling** [comment]
Rebased and applied.

**Pull request merged**
