### PR TITLE
DBZ-7006 Properly handle escaped CLOB single-quotes

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7006

### CODE REVIEW

**Comment by jpechane** [comment]
@obabec Could you please take a look at the error message? Thanks

**Comment by Naros** [comment]
@jpechane He said the TF could be having infrastructure issues, so I'm going to restart this one to see if it's been resolved.

**Comment by jpechane** [comment]
@Naros Applied, thanks

**Pull request merged**
