### PR TITLE
DBZ-3725 Validate table before start incemental processing

### PR DESCRIPTION
**Pull request by blcksrx**
https://issues.redhat.com/browse/DBZ-3725

### CODE REVIEW

**Comment by blcksrx** [comment]
@gunnarmorling I believe errors are unrelated  but you are the boss

**Comment by gunnarmorling** [comment]
Thanks, that's a great start! Could you only also log the current data collection in [SignalBasedIncrementalSnapshotChangeEventSource.readChunk()](https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/SignalBasedIncrementalSnapshotChangeEventSource.java#L257}}, when catching and re-throwing `SQLException`? You can access it via `context.currentDataCollectionId()`.

**Comment by blcksrx** [comment]
Actually I did it but without context, I'm going to adjust it now

**Comment by blcksrx** [comment]
@gunnarmorling Could you please check it again?

**Review by Naros — APPROVED** [review]
LGTM, thanks @blcksrx !

**Pull request merged**
