### PR TITLE
DBZ-8260 Make Oracle NLS library provided

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-8260

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros I prepared a PR for this issue. Could you please double check if NLS is redistributable or not? Thanks

**Comment by Naros** [comment]
Hi, @jpechane, this is just like the JDBC driver, so we shouldn't distribute it downstream.

**Comment by jpechane** [comment]
And in upstream?

**Comment by Naros** [comment]
So Oracle's FUTC does not allow us to redistribute it either, so it needs to be _provided_ for all contexts it seems.

**Comment by jpechane** [comment]
@Naros So now to clarify, FUTC does not allow us to redistribute only NLS library or the JDBC driver too?

**Comment by Naros** [comment]
As per our offline discussion, we can redistribute both upstream.

**Pull request merged**
