### PR TITLE
DBZ-7273: Introduce mode to query capture tables directly

### PR DESCRIPTION
**Pull request by ramanenka**
https://issues.redhat.com/browse/DBZ-7273

### CODE REVIEW

**Comment by ramanenka** [comment]
@jpechane Would this approach be acceptable, or you'd still prefer to introduce subclasses as you've described it [here](https://issues.redhat.com/browse/DBZ-7273?focusedId=23681667&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-23681667)?

**Comment by jpechane** [comment]
@ramanenka I think it is fine. I rebase the PR against the latest main and triggered the rebuild of PR. If it passes then it will be merged.

**Comment by jpechane** [comment]
@ramanenka Applied, thanks a lot! Could you please create a docs update PR too? Thanks

**Comment by ramanenka** [comment]
@jpechane Thanks for applying! Here is the docs PR: https://github.com/debezium/debezium/pull/5194.

**Pull request merged**
