### PR TITLE
DBZ-2065 Daily CI task to build against OpenJDK 14 and 15.

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-2065

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hard to judge the outcome just from looking at the YAML files. I'd suggest you merge it whenever you think it's ready, sharing a link to the build results afterwards. Thanks a lot, very nice that we're tackling this!

**Comment by Naros** [comment]
Yah I saw there was an issue with the YAML being consumed by GH actions for some odd reason so I moved it back to draft while I test it in my fork and push whatever changes are needed.  I also have some work already on porting the main CI to actions as well; but I shelved that temporarily.

**Comment by Naros** [comment]
So the workflow should now run at 10pm UTC, 5pm ET.  
Once the build has run, I'll provide a link to the build here.

**Comment by gunnarmorling** [comment]
Ok, but for that to work I'll have to merge it to master first, no? I'll just do that, YOLO ;)

**Comment by jpechane** [comment]
@gunnarmorling No, IIRC @Naros wanted to execute it on his repo first

**Comment by Naros** [comment]
https://github.com/Naros/debezium/actions/runs/109647269

**Comment by gunnarmorling** [comment]
Thanks! So quite a few failures -- what to take from them? Can we say DBZ
is green on 14/15, or not?

>

**Comment by jpechane** [comment]
@gunnarmorling Looking at th test results - SQL Server and MySQL failures ar usual suspects.
The rest is problem related to testcontainer inability to download an image from quay.io which I suppose was cuased by the registry itself.
So we can preliminary say DBZ is green but for the final statement I'd wait for outbox module to be executed as it is quarkus dependent where I'd potentially expect some problems.

**Comment by Naros** [comment]
So on the main repository, https://github.com/debezium/debezium/actions/runs/110863877.

So the caveat with cron workflows is that GitHub only performs a workflow sync after a push to the branch for which cron workflows exist.  So if we modify this workflow in anyway, we need to the perform a push against the branch after the workflow change commit in order to force GitHub to resync the workflows, see [thread](https://github.community/t5/GitHub-Actions/Schedule-workflows-missing/m-p/47577#M6889).

**Pull request merged**
