### PR TITLE
DBZ-4800 Fix SchemaGeneratorMojo execution with default values no Windows

### PR DESCRIPTION
**Pull request by rk3rn3r**
closes https://issues.redhat.com/browse/DBZ-4800

### CODE REVIEW

**Comment by Naros** [comment]
Fails on Windows 10 Pro with the following still:
```
[INFO] --- debezium-schema-generator:1.9.0-SNAPSHOT:generate-api-spec (generate-connector-metadata) @ debezium-connector-mysql ---
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=22600, ConflictMarker.markTime=11500, ConflictMarker.nodeCount=37, ConflictIdSorter.graphTime=19200, ConflictIdSorter.topsortTime=12600, ConflictIdSorter.conflictIdCount=26, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=128800, ConflictResolver.conflictItemCount=37, DefaultDependencyCollector.collectTime=767300, DefaultDependencyCollector.transformTime=220700}
[DEBUG] io.debezium:debezium-schema-generator:jar:1.9.0-SNAPSHOT
[DEBUG]    io.debezium:debezium-core:jar:1.9.0-SNAPSHOT:compile
[DEBUG]       io.debezium:debezium-api:jar:1.9.0-SNAPSHOT:compile (version managed from default)
[DEBUG]       com.fasterxml.jackson.core:jackson-core:jar:2.12.3:compile (version managed from default)
[DEBUG]       com.fasterxml.jackson.core:jackson-databind:jar:2.12.3:compile (optional) (version managed from default) (optionality managed from default)
[DEBUG]          com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3:compile (optional)
[DEBUG]       com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.3:compile (optional) (version managed from default) (optionality managed from default)
[DEBUG]       com.google.guava:guava:jar:30.0-jre:compile (version managed from default)
[DEBUG]          com.google.guava:failureaccess:jar:1.0.1:compile
[DEBUG]          com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava:compile
[DEBUG]    org.apache.kafka:kafka-clients:jar:3.1.0:compile
[DEBUG]       com.github.luben:zstd-jni:jar:1.5.0-4:runtime
[DEBUG]       org.lz4:lz4-java:jar:1.8.0:runtime
[DEBUG]       org.xerial.snappy:snappy-java:jar:1.1.8.4:runtime
[DEBUG]       org.slf4j:slf4j-api:jar:1.7.30:compile (version managed from default)
[DEBUG]    org.apache.kafka:connect-api:jar:3.1.0:compile
[DEBUG]       javax.ws.rs:javax.ws.rs-api:jar:2.1.1:runtime
[DEBUG]    io.smallrye:smallrye-open-api-core:jar:2.1.2:compile
[DEBUG]       org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:2.0:compile
[DEBUG]       org.eclipse.microprofile.config:microprofile-config-api:jar:2.0:compile
[DEBUG]       com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.12.3:compile (version managed from default)
[DEBUG]          org.yaml:snakeyaml:jar:1.27:compile
[DEBUG]       org.jboss:jandex:jar:2.2.2.Final:compile
[DEBUG]       org.jboss.logging:jboss-logging:jar:3.4.1.Final:compile
[DEBUG]    org.eclipse.aether:aether-util:jar:1.1.0:compile
[DEBUG]       org.eclipse.aether:aether-api:jar:1.1.0:compile
[DEBUG]    org.codehaus.plexus:plexus-utils:jar:1.1:runtime
[DEBUG] Created new class realm plugin>io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT
[DEBUG] Importing foreign packages into class realm plugin>io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT
[DEBUG]   Imported:  < project>io.debezium:debezium-build-parent:1.9.0-SNAPSHOT
[DEBUG] Populating class realm plugin>io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT
[DEBUG]   Included: io.debezium:debezium-schema-generator:jar:1.9.0-SNAPSHOT
[DEBUG]   Included: io.debezium:debezium-core:jar:1.9.0-SNAPSHOT
[DEBUG]   Included: io.debezium:debezium-api:jar:1.9.0-SNAPSHOT
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-core:jar:2.12.3
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-databind:jar:2.12.3
[DEBUG]   Included: com.fasterxml.jackson.core:jackson-annotations:jar:2.12.3
[DEBUG]   Included: com.fasterxml.jackson.datatype:jackson-datatype-jsr310:jar:2.12.3
[DEBUG]   Included: com.google.guava:guava:jar:30.0-jre
[DEBUG]   Included: com.google.guava:failureaccess:jar:1.0.1
[DEBUG]   Included: com.google.guava:listenablefuture:jar:9999.0-empty-to-avoid-conflict-with-guava
[DEBUG]   Included: org.apache.kafka:kafka-clients:jar:3.1.0
[DEBUG]   Included: com.github.luben:zstd-jni:jar:1.5.0-4
[DEBUG]   Included: org.lz4:lz4-java:jar:1.8.0
[DEBUG]   Included: org.xerial.snappy:snappy-java:jar:1.1.8.4
[DEBUG]   Included: org.apache.kafka:connect-api:jar:3.1.0
[DEBUG]   Included: javax.ws.rs:javax.ws.rs-api:jar:2.1.1
[DEBUG]   Included: io.smallrye:smallrye-open-api-core:jar:2.1.2
[DEBUG]   Included: org.eclipse.microprofile.openapi:microprofile-openapi-api:jar:2.0
[DEBUG]   Included: org.eclipse.microprofile.config:microprofile-config-api:jar:2.0
[DEBUG]   Included: com.fasterxml.jackson.dataformat:jackson-dataformat-yaml:jar:2.12.3
[DEBUG]   Included: org.yaml:snakeyaml:jar:1.27
[DEBUG]   Included: org.jboss:jandex:jar:2.2.2.Final
[DEBUG]   Included: org.jboss.logging:jboss-logging:jar:3.4.1.Final
[DEBUG]   Included: org.eclipse.aether:aether-util:jar:1.1.0
[DEBUG]   Included: org.codehaus.plexus:plexus-utils:jar:1.1
[DEBUG] Configuring mojo io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT:generate-api-spec from plugin realm ClassRealm[plugin>io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT, parent: jdk.internal.loader.ClassLoaders$AppClassLoader@2cdf8d8a]
[DEBUG] Configuring mojo 'io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT:generate-api-spec' with basic configurator -->
[DEBUG]   (f) format = openapi
[DEBUG]   (f) groupDirectoryPerConnector = false
[DEBUG]   (f) outputDirectory = E:\RedHat\GitHub\Naros\debezium\debezium-connector-mysql\target\generated-sources
[DEBUG]   (f) project = MavenProject: io.debezium:debezium-connector-mysql:1.9.0-SNAPSHOT @ E:\RedHat\GitHub\Naros\debezium\debezium-connector-mysql\pom.xml
[DEBUG]   (f) remoteRepos = [confluent (https://packages.confluent.io/maven/, default, releases+snapshots), ossrh (https://s01.oss.sonatype.org//content/groups/public/, default, releases+snapshots), central (https://repo.maven.apache.org/maven2, default, releases)]
[DEBUG]   (f) repoSession = org.eclipse.aether.DefaultRepositorySystemSession@11ec2b2f
[DEBUG]   (f) session = org.apache.maven.execution.MavenSession@29fd8e67
[DEBUG] -- end configuration --
[DEBUG] Skipped remote request for io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT/maven-metadata.xml locally installed metadata up-to-date.
[DEBUG] Skipped remote request for io.debezium:debezium-schema-generator:1.9.0-SNAPSHOT/maven-metadata.xml locally installed metadata up-to-date.
[DEBUG] Dependency collection stats: {ConflictMarker.analyzeTime=18900, ConflictMarker.markTime=14200, ConflictMarker.nodeCount=37, ConflictIdSorter.graphTime=9900, ConflictIdSorter.topsortTime=14300, ConflictIdSorter.conflictIdCount=26, ConflictIdSorter.conflictIdCycleCount=0, ConflictResolver.totalTime=127800, ConflictResolver.conflictItemCount=37, DefaultDependencyCollector.collectTime=11706600, DefaultDependencyCollector.transformTime=201900}
Error: Could not find or load main class io.debezium.schemagenerator.SchemaGenerator
Caused by: java.lang.ClassNotFoundException: io.debezium.schemagenerator.SchemaGenerator
```

**Comment by gunnarmorling** [comment]
Interesting, looks like that's a separate thing though. @Naros, can you push a commit for logging the classpath assembled in `SchemaGeneratorMojo`?

**Comment by rk3rn3r** [comment]
@gunnarmorling is this correct definition for the classpath? 
```
...microprofile-openapi-api-2.0.jar;;file:/C:/Users/nathansm/Desktop/debz_compile_test/debezium/debezium-schema-generator/target/debezium-schema-generator-1.9.0-SNAPSHOT.jar;C:\Users\nathansm\Desktop\debz_compile_test\debezium\debezium-connector-mysql\target\classes
...
```
I think the two `;;` might be okay but  the `file:` prefix is maybe not accepted on Windows?!

**Comment by rk3rn3r** [comment]
@Naros I just pushed a new commit to address cleaning up the classpath string based on my observation in my previous comment. Maybe you can check this commit if it solves the issue?

**Comment by gunnarmorling** [comment]
Yeah, there should be no double separators for sure. Can you still add the logging of the class path on info/debug level?

**Review by Naros — APPROVED** [review]

**Comment by rk3rn3r** [comment]
@gunnarmorling done!
@nathan-smit-1 already reported the changes fix their build issues on Windows. @Naros will confirm later and merge if this solves the issue.

**Review by gunnarmorling — APPROVED** [review]

**Pull request merged**
