### PR TITLE
DBZ-2385 Snapshot refactoring

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-2385

### CODE REVIEW

**Comment by jpechane** [comment]
@harveyyue Hi, thanks for taking the initiative! It is a bit late for 2.0 so I think it make sense to process this after 2.0 is done. In the meantime there is an old PR available - https://github.com/debezium/debezium/pull/2367

It probably makes sense to take a look at that one too?

**Comment by harveyyue** [comment]
@jpechane Adding this feature in 2.1 sounds like a good idea. 
Ok, I will look this pr https://github.com/debezium/debezium/pull/2367.

**Comment by harveyyue** [comment]
There is a postgres it test faiure, should be these changes caused, I will fix it.

**Comment by jpechane** [comment]
Closing as the snapshotting is now refactored and modes unified.

**Pull request closed without merging**
