### PR TITLE
DBZ-5144 Upgrade Kafka to 3.2.0

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-5144

### CODE REVIEW

**Comment by gunnarmorling** [comment]
2.3.0 -> 3.2.0 in the commit message :)

**Comment by jpechane** [comment]
@gunnarmorling You are a nit-picker ;-)

**Comment by gunnarmorling** [comment]
Hehe, yeah, usually I wouldn't mind. But given the version is the key part of the story here, I felt it's worth getting it right :)

**Comment by jpechane** [comment]
The test failures are unrelated.

**Review by Naros — APPROVED** [review]

**Pull request merged**
