### PR TITLE
DBZ-3244 Highlight the need for fully-qualified names

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3244

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Ok, so that's good description of the current state. Can you remind me though again _why_ the behavior is different between table include list and snapshot include list options? Intuitively, one would expect the same pattern.

**Comment by jpechane** [comment]
Because the matching is based on `TableId` which in case of sql server is db+schema+table

**Comment by gunnarmorling** [comment]
Ok, but why don't we change it to make it consistent?

That said, there's a link here to the parallelization work @morozov is doing in DDD-1: if a connector captures multiple databases, fully-qualified schema/table names would have to contain the database name, too. This will be a nice migration concern 🤔 . Perhaps there should be a notion of a "default database" which is used for resolving any filters that don't contain the DB part.

**Comment by jpechane** [comment]
@gunnarmorling That's exactly the problem. The planned work and at the same time the change of current behaviour as we should support bot the current one or backward compatibility and the new for consistency.
In this case I decided against the consiustency for some time and I'd solve the consistency only after we decide how `DDD-1` will look like to make sure we will not end-up in similar mess as with whitlist/includelist compatibility code.

**Comment by gunnarmorling** [comment]
Yeah, I think I'm arriving at the same conclusion; ultimately, we'll need to have the database name as part of these filters, so in that light, the snapshot include list is already doing the right thing. Will merge.

**Review by gunnarmorling — APPROVED** [review]

**Comment by morozov** [comment]
> That said, there's a link here to the parallelization work @morozov is doing in DDD-1: if a connector captures multiple databases, fully-qualified schema/table names would have to contain the database name, too.

Yes, we're making changes to the topic selector and the schema builder to use the source database as part of the fully qualified name (https://github.com/sugarcrm/debezium/pull/30).

Not sure how relevant it is to this case, but the logic introduced in https://github.com/debezium/debezium/pull/739 (use only one of the database and schema, even if both are available) looks inconsistent with the logic of [`TableId#tableId()`](https://github.com/debezium/debezium/blob/09de77cf7da6836d39f414c36dc213da7e058361/debezium-core/src/main/java/io/debezium/relational/TableId.java#L227-L238) (use all available components).

> This will be a nice migration concern 🤔 . Perhaps there should be a notion of a "default database" which is used for resolving any filters that don't contain the DB part.

Not sure I understand the concern. If the filter already requires the database to be part of the expression, how is it different between capturing one database or multiple?

> ultimately, we'll need to have the database name as part of these filters

According to the change in the documentation, it's already the case. Isn't it?

If it's not, the "default database" could be "any database". I.e. If there are too few FQN components, Debezium could add the missing ones: `<schema>.<table>` → `*.<schema>.<table>`. At the same time, the user will be able to provide a more specific filter with enough components (e.g. `<database>.<schema>.<table>`).

**Comment by gunnarmorling** [comment]
> According to the change in the documentation, it's already the case. Isn't it?

That's the thing, we're a bit inconsistent there atm. For snapshot inclusion filters, we require all three components (i.e. in line with what will be required as per your work), but not for regular table include/exclude filters.

>  I.e. If there are too few FQN components, Debezium could add the missing ones

Yes, that should work indeed 👍 .

**Pull request merged**
