### PR TITLE
DBZ-1723 Retrying poll in BaseSourceTask in case of exception.

### PR DESCRIPTION
**Pull request by tomek0021**
https://issues.redhat.com/browse/DBZ-1723

Two new configuration options added: max retry (default 0) and backoff millis (default 3000). Basic idea is to use kafka-connect's error handling abilities added in KIP-298 - in case of exception on poll plugin is required to wrap exception in RetriableException to be retried by the framework. Tested with junit + mockito.

### CODE REVIEW

**Comment by hashhar** [comment]
Looks good to me. But does this depend on a specific version of Kafka Connect?

Also, what happens if the `poll()` method is interrupted during the backoff? Does the framework call the `stop()` method for the Task?

**Comment by tomek0021** [comment]
> Looks good to me. But does this depend on a specific version of Kafka Connect?

https://issues.apache.org/jira/browse/KAFKA-6738 - it was released in 2.0.0 and we're using 2.4.0.

> Also, what happens if the `poll()` method is interrupted during the backoff? Does the framework call the `stop()` method for the Task?

https://github.com/apache/kafka/blob/trunk/connect/runtime/src/main/java/org/apache/kafka/connect/runtime/WorkerSourceTask.java#L243 on poll it just returns from method execute not sure if method stop will be called by the framework afterwards somehow.

**Comment by gunnarmorling** [comment]
Hey @tomek0021, first of all, thanks a lot for this contribution! Supporting retries is up very high on the wish list.

That being said, I'm a little bit confused by the proposed implementation; specifically, it diverges from what you've described in the JIRA issue (which happens to be very much in line with what I was thinking on this topic): why is it that you implement custom options and a new retry loop instead of just raising `RetriableException` at the right places and relying on Kafka Connect to invoke `poll()` again?

**Comment by tomek0021** [comment]
Hi @gunnarmorling you're welcome and to be honest I got paid to do so ;)

I think you probably misslooked 'if' for 'while' in line 78 of BaseSourceTask - right? There's no loop done by me.
As for configuration I think it's good to have it by default working as it was (to prevent conf changes during upgrade) but still possible to easilly turn it on. Also retry count should be configurable IMHO. You were thinking on making it always retrying without any backoff? Kafka-connect on RetriableException just retries again without any backoff.

**Comment by tomek0021** [comment]
Hi @gunnarmorling,

was thinking on it at the beginning but identifying all retriable/non-retriable cases is rather vendor specific and there's no promise it won't change on version update if we will identify by parsing message (no api for specific errors). On the other hand is there need besides connection exception for retrying? Usually DDL-type of errors will be identified during development (hopefully ;)), maybe we can retry on connection + add configuration option to use some regexp for exception type/message matching so user can retry on some more type of errors - what do you think about that?
If you want to identify other retriable cases can you narrow a bit what should I look for?

Another thing is that while I tested it (killed postgres wait a minute and restarted it) retry didn't help - the connection must be recreated as well. I restarted task from within the plugin and it worked but I'm not sure it's the right approach - is restarting from plugin allowed? I can narrow the code for the connection restart but it's almost everything in the start method (at least for the postgres connector).

**Comment by gunnarmorling** [comment]
@tomek0021 I think just handling connection losses would be good enough for now. I don't think the regexp option is needed for now, let's try and get out something basic quickly. We always can expand the set of retriable exceptions later on. You are right, it's connector-specific and it _might_ change between driver versions, although I think the latter is rather unlikely. 

> I restarted task from within the plugin...

Yes, that's a very good point and the most tricky part of this. I think the best would be to restart the current `ChangeEventSource` in this case, i.e. implementing this restart behavior at a lower level than the Connect task. The reason being that we'd like to abstract ourselves from Kafka Connect APIs going forward. The downside is that this would limit this feature to Postgres, SQL Server and Oracle for now, as the other connectors are not yet based on the infrastructure around `ChangeEventSource`. But that'll change (sic! ;) over time. Would that make sense to you?

**Comment by tomek0021** [comment]
Hi @gunnarmorling,
I like idea to decouple from connect - it would be one of possible runtime adapters(?) Is it for code cleanness only or something more? I guess ultimately connect api should be removed outside of core entirely?

I've prepared a sketch of possible solution - I had to decompose postgres/sqlserver task logic to be able to restart it correctly (db connections are spread in too many places to narrow restarting better and in more granular way). I've come up with facade (couldn't find better name) objects that are able to restart + some small refactors around ChangeEventSource approach. Commit isn't clean enough but I think I can squash/rebase it later (no docs, haven't yet removed previous retry code) - I wanted to have more insights if I'm taking the right approach?
Also haven't test it yet with db crash - will do soon.

**Comment by gunnarmorling** [comment]
@tomek0021, hey, circling back to this one. Seems something wrent a bit sideways, there's tons of unrelated commits in this PR now. Can you please rebase this to the current master, so to have a clear picture of the current state of the proposed change (in general we prefer rebases over merge commits for reasons like that)? Thanks!

**Comment by tomek0021** [comment]
I've created new branch from master and cherry picked commit it's now under https://github.com/debezium/debezium/pull/1263

**Comment by gunnarmorling** [comment]
Closing in favour of new PR #1263. Thanks, will comment over there.

**Pull request closed without merging**
