### PR TITLE
DBZ-7871 Change logging level for `Found previous partition offset`

### PR DESCRIPTION
**Pull request by rkudryashov**
https://issues.redhat.com/browse/DBZ-7871

### CODE REVIEW

**Review by mfvitale — APPROVED** [review]

**Comment by jpechane** [comment]
I definitely don't want to remove it globally. The same method is used for initial idnetification of existing offsets by all connectors and it is IMHO important that the message is logged at `INFO` level. I'd be OK with intorducing a flag that will decide whether the logging is at INFO or DEBUG/TRACE level and intorudce a new method that would accept that flag. By default INFO will be used and his instance can override it.

**Comment by mfvitale** [comment]
> I definitely don't want to remove it globally. The same method is used for initial idnetification of existing offsets by all connectors and it is IMHO important that the message is logged at `INFO` level. I'd be OK with intorducing a flag that will decide whether the logging is at INFO or DEBUG/TRACE level and intorudce a new method that would accept that flag. By default INFO will be used and his instance can override it.



> I definitely don't want to remove it globally. The same method is used for initial idnetification of existing offsets by all connectors and it is IMHO important that the message is logged at `INFO` level. I'd be OK with intorducing a flag that will decide whether the logging is at INFO or DEBUG/TRACE level and intorudce a new method that would accept that flag. By default INFO will be used and his instance can override it.



> I definitely don't want to remove it globally. The same method is used for initial idnetification of existing offsets by all connectors and it is IMHO important that the message is logged at `INFO` level. I'd be OK with intorducing a flag that will decide whether the logging is at INFO or DEBUG/TRACE level and intorudce a new method that would accept that flag. By default INFO will be used and his instance can override it.



> I definitely don't want to remove it globally. The same method is used for initial idnetification of existing offsets by all connectors and it is IMHO important that the message is logged at `INFO` level. I'd be OK with intorducing a flag that will decide whether the logging is at INFO or DEBUG/TRACE level and intorudce a new method that would accept that flag. By default INFO will be used and his instance can override it.

What do you think to remove the log `side effect` out of this method and then log it on the task? So any other use of that method will require no previous knowledge.

**Comment by Naros** [comment]
While they do @mfvitale, I can see certain situations where knowing that the offset is per partition could be useful in the case of SQL Server where it stores offsets across partitions, so I wouldn't recommend removing it.  What makes it more complicated as removing the logging would break behavior for MongoDB which has a very different way of logging this phase for users.  

I think the path of least resistance here would be as Jiri mentioned, pass a flag from PG where we do this special call in the commit method to bypass logging like we do for Replica Identity and Schema Refreshes.

**Comment by jpechane** [comment]
@mfvitale WDYT? https://github.com/debezium/debezium/pull/5565/commits/04372acd5ac091e12dc7fd77bbd344e462c91096

**Comment by mfvitale** [comment]
> @mfvitale WDYT? [04372ac](https://github.com/debezium/debezium/commit/04372acd5ac091e12dc7fd77bbd344e462c91096)

Sounds good. Just leaved a nitpick comment.

**Comment by jpechane** [comment]
@mfvitale Comment added

**Pull request merged**
