### PR TITLE
DBZ-491 Failing unit tests when run in EST timezone

### PR DESCRIPTION
**Pull request by pgoranss**
Modifying unit tests to always convert to UTC timezone

https://issues.jboss.org/browse/DBZ-491

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks, @pgoranss. There's test failure on CI, but that seems unrelated. Could you rebase it though and merge everything into a single commit, and prefix the commit message with the issue key (e.g. "DBZ-491 Normalizing date to UTC before asserting"). Thanks!

**Comment by pgoranss** [comment]
@gunnarmorling should be all set now

**Comment by gunnarmorling** [comment]
@pgoranss Thanks, LGTM.

One last thing (sorry for not mentioning it earlier, just noticed): can you use the e-mail associated to your GitHub account as the commit author email. That way your contribution will [show up properly](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/#commits) in the project stats. Thanks!

**Comment by pgoranss** [comment]
@gunnarmorling I updated my Github primary email to that one, and left the old one as secondary, so I think it should be all set. Let me know, thanks.

**Comment by gunnarmorling** [comment]
Yeah, all good now. Rebased and applied. Thanks, @pgoranss!

**Pull request merged**
