### PR TITLE
DBZ-25 Fix build version path

### PR DESCRIPTION
**Pull request by criccomini**

### CODE REVIEW

**Comment by rhauch** [comment]
@criccomini, since these changes are unrelated, I'd prefer to have separate pull requests for these. I'll resurrect #22 and merge that; since it is a trivial change there is no need for an issue. Once I do that, can you rebase and amend the commit that fixes the `build.version` fix to have "DBZ-25" at the beginning of the commit description and the PR title?

Actually, how about resurrecting #22 as-is

**Comment by criccomini** [comment]
Will do

**Comment by criccomini** [comment]
Done.

**Comment by rhauch** [comment]
One more thing ... can you amend the commit and add "DBZ-25 " at the beginning of the commit message? I know it's a nit, but consistency.

**Comment by criccomini** [comment]
Done!

**Pull request merged**
