### PR TITLE
DBZ-4468 Skip non-server tests

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4468

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ani-sha, @Naros, if you look at the output on CI, this job runs long and downloads many dependencies. Should this actually be not the case in the light of the recent changes to caching you did?

**Comment by gunnarmorling** [comment]
The change LGTM, but I'm curious about the build slowness.

**Comment by Naros** [comment]
So specifically regarding the cache, the GH action cache was restored.  We can see this by expanding the "Cache Maven Repository" step in the build workflow [here](https://github.com/debezium/debezium/runs/4818206865?check_suite_focus=true).  Later on during the "Post CAche Maven Repository" step in the build workflow, you can see that changes to the cache were not persisted because the cache key already exists.

What this ultimately means is that throughout the month, we will restore the cache to what it was built as on the first workflow at the start of the month.  Any changes in dependencies that are made to the repository during the month won't get cached and will be downloaded on each job until the following month.  Since we rarely change that many artifacts, this seems acceptable.  We can however set up a cache reset dispatch job if we think we need it to resync the cache manually on an as-needed basis to avoid downloads throughout the month.

In terms of slowness, 6.5 minutes (or 50%) of the build time is allocated to running the format check against the entire repository.  This was something I think @ani-sha added when we decommissioned the separate format check.  Personally, I don't agree with this being a separate part of each workflow because it feels a bit redundant.  

I think it would make more sense to trigger the format validation as part of the single `mvn` run and let Maven only execute the format check on the module and its dependencies that are being compiled/tested; unless someone can point a situation to me where we need to run it across the entire repository.

To make matters worse the two executions of Maven also recompile the code both times, so that seems redundant.

**Comment by gunnarmorling** [comment]
>  Any changes in dependencies that are made to the repository during the month won't get cached and will be downloaded on each job until the following month. Since we rarely change that many artifacts, this seems acceptable.

Oh, I see. Hum, hum, this seems suboptimal. Any Quarkus release update will mean many artifact updates, resulting in longer times for the remainder of the month. Is there a reason we don't update the cache upon each run? When we spoke about that cache key format change, I understood it that way that this would start with a fresh cache at the beginning of each month, but it would be updated from thereon.

> In terms of slowness, 6.5 minutes (or 50%) of the build time is allocated to running the format check against the entire repository.

Ok, so the formatting check should only run against those modules affected by a given workflow. But even when running it against the full repo, there's no way it should take 6.5 min. The downloads are definitely the problem here; locally, with having all dependencies in my local repo, `mvn process-sources` for the entire repo takes ~16 sec.

**Comment by gunnarmorling** [comment]
Ok, I'm going to merge this, as @Naros, is exploring the CI build time issue in a separate PR. Thx!

**Pull request merged**
