### PR TITLE
DBZ-2317 PostgeSQL driver upgrade

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-2317

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane ^^^

**Comment by Naros** [comment]
There seems to be quite a number of errors that repeat this 
```
java.util.NoSuchElementException: No value present
	at java.util.Optional.get(Optional.java:135)
	at io.debezium.connector.postgresql.PostgresValueConverter.numericSchema(PostgresValueConverter.java:300)
	at io.debezium.connector.postgresql.PostgresValueConverter.schemaBuilder(PostgresValueConverter.java:191)
	at io.debezium.relational.TableSchemaBuilder.addField(TableSchemaBuilder.java:367)
	at io.debezium.relational.TableSchemaBuilder.lambda$create$2(TableSchemaBuilder.java:120)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:175)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1380)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.debezium.relational.TableSchemaBuilder.create(TableSchemaBuilder.java:118)
	at io.debezium.relational.RelationalDatabaseSchema.buildAndRegisterSchema(RelationalDatabaseSchema.java:130)
```
I'm curious what ultimately changed in the last 5 bugfix builds of the driver that might cause this?

**Comment by gunnarmorling** [comment]
Gasp, I do remember that actually. There's a rather disruptive change in one of the versions re how metadata like column length is exposed. We fixed that when upgrading back in the day. So we won't get away with simply updating the driver for 1.1 :(

**Comment by gunnarmorling** [comment]
So this needs the changes from DBZ-2027; will update this PR in a bit.

**Comment by gunnarmorling** [comment]
@jpechane, the actual build and tests are green; the failure is about non-conforming commit messages from release commits. I think the message validation needs some fine-tuning, but we can ignore this here in any case.

**Comment by jpechane** [comment]
@gunnarmorling Applied, thanks!

**Pull request merged**
