### PR TITLE
DBZ-4929 Fix Connector NPE when using custom converter

### PR DESCRIPTION
**Pull request by EMsnap**
see also in https://issues.redhat.com/browse/DBZ-4929

### CODE REVIEW

**Comment by EMsnap** [comment]
This is not fair, actually It's me who found this bug lol

**Comment by jpechane** [comment]
@EMsnap Life sucks :-). Please don't be discouraged by this there are many bugs waiting to be treated :-).
Thank you, for the report and PR. As we got multiple PRs solving the same issue I am closing this one as https://github.com/debezium/debezium/pull/3362 was merged.

**Comment by EMsnap** [comment]
yeah it's ok, I'm just joking lol, looking forward for another chance!

**Comment by EMsnap** [comment]
> @EMsnap Life sucks :-). Please don't be discouraged by this there are many bugs waiting to be treated :-). Thank you, for the report and PR. As we got multiple PRs solving the same issue I am closing this one as #3362 was merged.


yeah it's ok, I'm just joking lol, looking forward for another chance!

**Pull request closed without merging**
