### PR TITLE
DBZ-2271 Fix test failure - RecordsStreamProducerIT#testEmptyChangesProducesHeartbeat

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-2271

A race condition still existed where heartbeats might be emitted in a way that would violate the test assertions.  The fix added here is to guarantee that the expected number of heartbeat lsns is always 2.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, still something wrong with "auto-green" ;) That said, this one seems like a connectivity issue which probably is not worth pursuing. Unless we'd want to make this retriable, this could be a good idea.

**Comment by gunnarmorling** [comment]
Any update, @Naros?

**Comment by Naros** [comment]
I think most tests will fail in our suite if some type of unstable connection issue occurs, so I'm not sure its worth changing the test itself to account for this and trying to retry somehow.  If we go down that rabbit hole, I feel we need to do it for all tests.

**Comment by gunnarmorling** [comment]
Agreed, I somehow missed that it was a connection loss. Indeed not worth any effort as you say. Thanks!

**Pull request merged**
