### PR TITLE
DBZ-1515 Add poll pause only after multiple no message attempts

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1515

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, @Naros are you all onboard for merging this for 0.10.0.Final?

**Comment by jpechane** [comment]
@gunnarmorling Half of us is :-)

**Comment by Naros** [comment]
@gunnarmorling +1

**Comment by Naros** [comment]
Applied, thanks @jpechane !

**Comment by davecramer** [comment]
So does this fix the problem?

**Comment by jpechane** [comment]
@davecramer Yes, the test proves it.

**Comment by davecramer** [comment]
@jpechane so here's the deal. pgoutput issues N+2  where N is the number of inserts in the TX messages for this. 
BEGIN;
INSERT
....
INSERT
COMMIT
 wal2json does this in one message.
{"xid":14096,"change":[{"kind":"insert","schema":"public","table":"t0","columnnames":["pk","val3"],"columntypes":["integer","b....


Interesting.

**Comment by jpechane** [comment]
@davecramer protobuf decoder issuses N messages (no BEGIN and COMMIT) and still does not have the same problem.

**Comment by davecramer** [comment]
interesting. I tested the pgoutput decoder and all the messages come out in less than a second with 1000 inserts inside a transaction. I wonder if we truly understand what is going on here ?

**Comment by jpechane** [comment]
@davecramer I think for real understanding we should probably use wirshark to capture what happens on network layer and how it differs betweem pgoutpu and protobuf decoder.
If you compare source code between https://github.com/postgres/postgres/blob/master/src/backend/replication/pgoutput/pgoutput.c and https://github.com/debezium/postgres-decoderbufs/blob/master/src/decoderbufs.c then you'll see that protobuf does not emit anything on begin and commit. SO my theory is that begin/commit arrives as a separate message which means that no data are present which would trigger the poll pause. By introducing poll pause only after multiple empty messages to ahppen we effectivelly solve the problem of empty messages.

**Comment by davecramer** [comment]
@jpechane it was on my list to test yesterday. Somehow it did not make it to the top :( I'll try today

**Comment by davecramer** [comment]
So as mentioned in gitter pgoutput is the only one that sends BEGIN and COMMIT which I guess you consider empty. I now understand that the sink does NOT use this data to wrap the inserts in a transaction due to the way kafka works, thanks

**Pull request merged**
