### PR TITLE
DBZ-1956 This conditionalizes "Schema Change Topic" to be upstream only

### PR DESCRIPTION
**Pull request by TovaCohen**
Please merge and backport to 1.1. 
Thanks!

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Applied to master. Didn't need backporting to 1.1 as that feature was only introduced in 1.2.

**Comment by TovaCohen** [comment]
@gunnarmorling  In the downstream doc repo, I just fetched all the updates in the 1.1 branch.
In the downstream Debezium User Guide, in the doc for SQL Server connector we still have: 

5.3.4. Schema change topic
The user-facing schema change topic is not implemented yet (see {jira-url}/browse/DBZ-1904[DBZ-1904]).

So I think that either this PR needs to be backported to 1.1, or perhaps you can directly edit the sqlserver.adoc file in the 1.1 branch to remove that.

Thanks!

**Comment by gunnarmorling** [comment]
Ok, changed on upstream/1.1 as suggested.

**Comment by TovaCohen** [comment]
Thanks @gunnarmorling!

**Pull request merged**
