### PR TITLE
DBZ-1331 | allow `SET NEW.column=expression` in triggers

### PR DESCRIPTION
**Pull request by szczeles**
https://issues.jboss.org/browse/DBZ-1331

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks a lot, @szczeles! Could you also file a corresponding PR to the Antlr upstream repo (https://github.com/antlr/grammars-v4)? We copy the grammar from there but strive for pushing all fixes back there.

**Comment by szczeles** [comment]
Good idea! Fix is pushed as https://github.com/antlr/grammars-v4/pull/1443

**Comment by gunnarmorling** [comment]
LGTM, merging. Thanks a lot, @szczeles!

**Comment by szczeles** [comment]
Thank you, too @gunnarmorling!

**Pull request merged**
