### PR TITLE
DBZ-8184 Enable snapshot failure retries during Oracle tests

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-8184

### CODE REVIEW

**Review by jpechane — APPROVED** [review]
LGTM, feel free to merge yourself when CI passes.

**Comment by Naros** [comment]
Test failure on Oracle 21 XStream addressed in https://github.com/debezium/debezium/pull/5819

**Comment by Naros** [comment]
The Oracle 23 failures are fixed in #5821

**Pull request merged**
