### PR TITLE
DBZ-8224 allow field name without topic qualifier

### PR DESCRIPTION
**Pull request by msillence**
make filtering match documentation

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros @vjuranek Any comments? If not please feel free to merge.

**Review by Naros — APPROVED** [review]
LGTM from my PoV.

**Review by vjuranek — CHANGES_REQUESTED** [review]
The change LGTM, but when you are in it, could you please add `.strip()` to all `parts`? As you pointed out in the comment in Jira, topics with whitespace before comma are not matched, which I'd say users don't expect. Thanks!

**Comment by Naros** [comment]
As I made the changes suggested by @vjuranek, to avoid creating a new PR since this one is locked, I merged these changes directly into main and backported the change to the 2.7 branch.

**Pull request closed without merging**
