### PR TITLE
DBZ-3542 Use Apicurio 2.0

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3171

Requires debezium/connect:1.6 image built with https://github.com/debezium/docker-images/pull/230

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Looks good, I suppose :)

What's needed to un-draft it, @jpechane?

**Comment by gunnarmorling** [comment]
@jpechane, I've pushed the container image debezium/connect:1.6-devel to Docker Hub. Can you proceed with this PR accordingly?

**Comment by jpechane** [comment]
@gunnarmorling Updated

**Comment by gunnarmorling** [comment]
Thx, @jpechane!

**Pull request merged**
