### PR TITLE
DBZ-6970 Add the new property "truncate.enabled" to jdbc doc

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6970

Sibling PR - https://github.com/debezium/debezium-connector-jdbc/pull/37

### CODE REVIEW

**Review by mfvitale — APPROVED** [review]

**Comment by Naros** [comment]
I added a note in the sibling PR, lets make a note that Db2 utilizes the `ALTER TABLE` syntax this since requires some special permissions beyond `TRUNCATE TABLE`.

**Comment by mfvitale** [comment]
> I added a note in the sibling PR, lets make a note that Db2 utilizes the `ALTER TABLE` syntax this since requires some special permissions beyond `TRUNCATE TABLE`. @mfvitale @harveyyue

@harveyyue  can you please add the note on the doc? Then I think we are ready to apply it.

**Comment by harveyyue** [comment]
> > I added a note in the sibling PR, lets make a note that Db2 utilizes the `ALTER TABLE` syntax this since requires some special permissions beyond `TRUNCATE TABLE`. @mfvitale @harveyyue
> 
> @harveyyue can you please add the note on the doc? Then I think we are ready to apply it.

Done.

**Comment by mfvitale** [comment]
@harveyyue  Applied (2.4 and 2.5), thanks.

**Pull request merged**
