### PR TITLE
DBZ-40 Pulling up some common code to HistorizedRelationalDatabaseSchema

### PR DESCRIPTION
**Pull request by gunnarmorling**
@jpechane I thought you could find this useful for the SQL Server work.

### CODE REVIEW

**Comment by jpechane** [comment]
@gunnarmorling Oracle fails with NPE at line https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java#L87
The `context` is set later at line https://github.com/debezium/debezium/blob/master/debezium-core/src/main/java/io/debezium/relational/HistorizedRelationalSnapshotChangeEventSource.java#L107

**Comment by gunnarmorling** [comment]
Ugh, that's embarrasing :( I'll adjust.

**Comment by gunnarmorling** [comment]
@jpechane Pushed one more commit which should fix that one.

**Comment by jpechane** [comment]
@gunnarmorling Applied, thanks!

**Pull request merged**
