### PR TITLE
DBZ-2689 Parallel Snapshotting Broken for MySql Connector

### PR DESCRIPTION
**Pull request by scornella**
Reproducing bug https://issues.redhat.com/browse/DBZ-2689

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @mtagle, here's a fix related to parallel snapshotting. Do you think you could take a look into the proposed change? Thanks a lot!

**Comment by mtagle** [comment]
this is on my radar and I'll take a look. I have to admit I don't totally understand what the error is, but hopefully I'll get a better sense after I look at the code.

**Comment by gunnarmorling** [comment]
Hey @mtagle, did you ever have a chance to look into this one?

**Comment by mtagle** [comment]
Hey, I took a look but it fell off my radar.  Honestly I'm still a little lost but I'm going to do my best to understand what's going on here. It's been a while since I've touched this so hopefully my memory here isn't totally incorrect.

It looks like this actually deals w/ two issues.  1. unified binlog reader attempts to have 2 uponCompletion runnables, which fails,  and 2. unsetting the filter info when snashot.new.tables is off is causing issues.

with regards to 1: looking at the code, it does look like the unifiedBinLogReader tries to get both a .uponShutdown callback from being part of a chained reader and also explicitly from the code that creates the chain (which tries to tell it to shutdown the unifiedTaskContext.) This does look like it would fail. I think the better way to do this is actually the way it looks like it's handled in the non parallel snapshotting code where shutting down the context is handled by the "chainedReader" rather than an individual reader in the chain. Maybe there is some reason we shouldn't do that though? We are actually already (attempting to anyway) shutting down some context in the chained reader but I assume it is a more limited context (not concerning all the tables we have newly snapshot, presumably)

for 2. I'm not totally sure I agree. It seems to me like you can turn parallel snapshotting on, without adding any new tables, let the connector write some offets (which will contain the filters in the offsets) and then turn add some new tables, and parallel snapshotting should happen. I'm not sure what steps they are taking where they do not see parallel snapshotting taking place when they would expect it to.

**Comment by mtagle** [comment]
I wanted to circle back to this because at the moment we area also seeing parallel snapshotting not "activating" when we add a new table to the configs (we are on DBZ 1.4.0) This seems to be in line with issue (2). We've been able to parallel snapshot before, and I'm not sure what change caused this, but it does look like we are setting the offsets early and then trying to see if there is a difference between the offset and the config to determine if we should do a parallel snapshot. Since we already set the offsets based on the config the result is always false.

**Comment by scornella** [comment]
Right, that lines up with what I saw when I created the issue. One thing that I may have miscommunicated is that I didn't intend for the PR to be the official fix for the bug, rather I just wanted to demonstrate the issue. 

We are still in need of a solution for parallel snapshotting but I am not sure where this falls on your priority list given that a lot of the mysql connector is being re-written for 1.5.

**Comment by gunnarmorling** [comment]
Hey, thanks a lot for your efforts, @scornella and @mtagle! As you say, there's a new MySQL connector implementation in place since Debezium 1.5, and 1.6 adds a new notion of incremental snapshotting (currently Beta). Based on that I'm going to close this one, as we're planning to phase out the existing connector implementation soon, so any large scale fixes to it seem rather unlikely at this point. Thanks again, and I hope the new incremental snapshotting proves useful to you.

**Pull request closed without merging**
