### PR TITLE
DBZ-4654 Oracle DDL parser failure & relax SnapshotType case sensitivity 

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-4654

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, in the commit message, could you reference https://issues.redhat.com/browse/DBZ-4648 for the casing issue? It got reported there two. And then update the title of DBZ-4654 to be focussed on the parsing issue. Thx!

**Comment by Naros** [comment]
Updated the case-sensitivity commit message issue key to DBZ-4648 & the Jira issue title for DBZ-4654.

**Comment by gunnarmorling** [comment]
Thx for splitting this up, this LGTM now. Agreed re the test failure, seems like a network glitch maybe. No need to react to it right now IMO. Will merge.

**Comment by gunnarmorling** [comment]
@Naros, doh, sorry, realizing now I've merged that to upstream/1.8 instead of the candidate branch :/

**Pull request merged**
