### PR TITLE
Bump Mongo Java Driver to version 3.12.1

### PR DESCRIPTION
**Pull request by oscerd**

### CODE REVIEW

**Comment by jpechane** [comment]
@oscerd Hi, thanks for the PR. Could you please create a Jira issue so it gets tracked and is included in release notes and reword the commit message to be like `DBZ-xxx Bump Mongo Java Driver to version 3.12.1`.

**Comment by oscerd** [comment]
Yes, sure

**Comment by oscerd** [comment]
@jpechane done

**Comment by jpechane** [comment]
@oscerd Applied, thanks!

**Pull request merged**
