### PR TITLE
DBZ-7657 Use SQL Server 2022 instead of 2019

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7657

As a result of the discussion about Linux kernel compatibility: https://github.com/microsoft/mssql-docker/issues/868

### CODE REVIEW

**Comment by Naros** [comment]
Failures are our usual SQL Server suspects :(

**Comment by jpechane** [comment]
@Naros Could you please take a look at https://github.com/microsoft/mssql-docker/issues/868#issuecomment-2003214916 ?

**Comment by Naros** [comment]
> @Naros Could you please take a look at [microsoft/mssql-docker#868 (comment)](https://github.com/microsoft/mssql-docker/issues/868#issuecomment-2003214916) ?

I think his issue was the fact he didn't clear the image cache before trying :grin: 
It works fine on Fedora 39 for me using Linux fedora 6.7.5-200.fc39.x86_64.

**Comment by jpechane** [comment]
@Naros Applied, thanks :-)

**Pull request merged**
