### PR TITLE
DBZ-4577 Provide custom error message handling

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4577

Please review - if approved the changes the extra connectors will be added.

### CODE REVIEW

**Review by Naros — APPROVED** [review]

**Comment by jpechane** [comment]
PRs war DB2 and Vitess submitted

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
LGTM, applying. Thx!

**Comment by gunnarmorling** [comment]
@jpechane, are you still planning to submit a PR for adjusting the PG error handler for that report which triggered this?

**Comment by jpechane** [comment]
@gunnarmorling Yes, later today.

**Pull request merged**
