### PR TITLE
DBZ-4569 Upgrade Apicurio and Confluent to the latest version

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4569

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, test failure seems related.

**Comment by gunnarmorling** [comment]
```
2022-01-21 14:00:50,309 INFO  [io.deb.ser.ConnectorLifecycle] (pool-10-thread-1) Connector completed: success = 'false', message = 'Stopping connector after error in the application's handler method: com/google/type/DateTimeProto', error = '{}': java.lang.NoClassDefFoundError: com/google/type/DateTimeProto
	at io.confluent.kafka.schemaregistry.protobuf.ProtobufSchema.<clinit>(ProtobufSchema.java:212)
	at io.confluent.connect.protobuf.ProtobufData.fromConnectSchema(ProtobufData.java:614)
	at io.confluent.connect.protobuf.ProtobufData.fromConnectData(ProtobufData.java:321)
	at io.confluent.connect.protobuf.ProtobufConverter.fromConnectData(ProtobufConverter.java:85)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$build$4(ConvertingEngineBuilder.java:171)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$1(ConvertingEngineBuilder.java:84)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1625)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:682)
	at io.debezium.embedded.ConvertingEngineBuilder.lambda$notifying$2(ConvertingEngineBuilder.java:85)
	at io.debezium.embedded.EmbeddedEngine.run(EmbeddedEngine.java:821)
	at io.debezium.embedded.ConvertingEngineBuilder$2.run(ConvertingEngineBuilder.java:192)
	at io.debezium.server.DebeziumServer.lambda$start$1(DebeziumServer.java:147)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.ClassNotFoundException: com.google.type.DateTimeProto
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:641)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:188)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:455)
	at io.quarkus.bootstrap.classloading.QuarkusClassLoader.loadClass(QuarkusClassLoader.java:405)
	... 20 more

Error:  Tests run: 3, Failures: 0, Errors: 1, Skipped: 2, Time elapsed: 66.748 s <<< FAILURE! - in io.debezium.server.DebeziumServerWithSchemaRegistryIT
Error:  io.debezium.server.DebeziumServerWithSchemaRegistryIT.testPostgresWithProtobuf  Time elapsed: 1.255 s  <<< ERROR!
java.lang.ClassCastException: class java.lang.NoClassDefFoundError cannot be cast to class java.lang.Exception (java.lang.NoClassDefFoundError and java.lang.Exception are in module java.base of loader 'bootstrap')
```

**Comment by jpechane** [comment]
@gunnarmorling Yes there is a conflict in https://mvnrepository.com/artifact/com.google.api.grpc/proto-google-common-protos
I am trying to resolve it

**Comment by gunnarmorling** [comment]
Test failure tracked in https://issues.redhat.com/browse/DBZ-4592

**Comment by gunnarmorling** [comment]
@jpechane, so is this to say the Vitess connector could not be used with ProtoBuf serialization through the Confluent converter?

**Comment by jpechane** [comment]
Test failure is https://issues.redhat.com/browse/DBZ-4592

**Comment by jpechane** [comment]
@gunnarmorling Most probably yes. Otherwise we would need to go through the full loop of trying to upgrade grpc itself and test if it works correctly with vitess.

**Review by gunnarmorling — APPROVED** [review]

**Pull request merged**
