### PR TITLE
DBZ-7570/#133: started to add workaround using SO_LINGER with 0 timeout

### PR DESCRIPTION
**Pull request by acristu**
…ut if use.nongraceful.disconnect=true

### CODE REVIEW

**Comment by acristu** [comment]
@jpechane rebase done ...

Just to mention it here too, workaround from this PR inspired by this https://bugs.openjdk.org/browse/JDK-8241239?focusedId=14646711&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-14646711

Related PR in binlog client https://github.com/osheroff/mysql-binlog-connector-java/pull/142, the "Update Dependencies" job is failing since `com.zendesk:mysql-binlog-connector-java:jar:0.29.2` has not been released yet

**Review by Naros — APPROVED** [review]
Hi @acristu, overall the changes LGTM.  I left one adminstrative comment on the binlog client PR and once that is done, we can coordinate with Ben on the upstream client release and merging here.

**Comment by acristu** [comment]
@Naros updated binlog client PR

**Comment by Naros** [comment]
Superseded by #5517 as this needed a rebase.  Lets continue there.

**Pull request closed without merging**
