### PR TITLE
DBZ-7847 Support in query filter mode with 1000+ tables

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7847

### CODE REVIEW

**Comment by Naros** [comment]
These failures are apicurio related.  Running the tests locally with apicurio 2.4.3.Final they pass, anything with 2.4.4.Final or later fail.

**Comment by jpechane** [comment]
@Naros Should we override Apicurio version for Oracle test execution then?

**Comment by Naros** [comment]
I spoke with the Apicurio team, and I think we have a way forward.  Let's discuss this offline.

**Comment by Naros** [comment]
So only the Oracle fix needs to be backported to 2.6, the apicurio version in 2.6 is still based on 2.4.3.Final which isn't broken.

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Pull request merged**
