### PR TITLE
DBZ-20 (Initial drop of XStream-based Oracle connector)

### PR DESCRIPTION
**Pull request by gunnarmorling**
This supersedes #460, by also pulling in latest changes by @jpechane.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
That said, I'll push one more commit for removing the the _oracle_ module itself, leaving just the changes in core in place, and will file another PR against the incubator repo.

**Comment by gunnarmorling** [comment]
Rebased and moved _debezium-connector-oracle_ module to incubator repo.

**Comment by gunnarmorling** [comment]
To be reviewed together with https://github.com/debezium/debezium-incubator/pull/1.

**Comment by jpechane** [comment]
@gunnarmorling A huge piece of work, thanks!

**Pull request merged**
