### PR TITLE
DBZ-2798 GH Action to add JIRA issue links to pull requests

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-2798

This action fetches `DBZ-xxx` issue numbers and references with its respective JIRA link. Works for multiple issue references as well. On successful review of this PR, I would be adding similar ones in other repos as well.

cc: @gunnarmorling @jpechane

### CODE REVIEW

**Comment by ani-sha** [comment]
Does this failing check imply anything relating to `write access` for the repo? :thinking:

**Comment by jpechane** [comment]
@ani-sha It is probably not going to be that easy. here is the explanation https://github.com/marketplace/actions/add-pr-comment#proxy-for-fork-based-prs

**Comment by gunnarmorling** [comment]
Hum, ok, so it seems it's not feasibly doable atm. then? Setting up some external service is not worth the hassle for this, IMO.

**Comment by ani-sha** [comment]
@gunnarmorling I think we can drop this for now, until we find any better alt. :confused:

**Pull request closed without merging**
