### PR TITLE
DBZ-5478: Restart SQL Server task on "Socket closed" exception

### PR DESCRIPTION
**Pull request by morozov**
https://issues.redhat.com/browse/DBZ-5478

### CODE REVIEW

**Comment by Naros** [comment]
Hi @morozov did you intend for this to remain a draft?

**Comment by morozov** [comment]
No, it’s ready for review.

**Review by Naros — APPROVED** [review]
Great, LGTM, thanks!

**Comment by Naros** [comment]
Applied to main (=2.0) and branch 1.9.

**Pull request merged**
