### PR TITLE
DBZ-1746 Gracefully handle unknown protobuf messages

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-1746

### CODE REVIEW

**Comment by jpechane** [comment]
Tests are running locally with new protobuf format, I'll let know when they pass

**Comment by jpechane** [comment]
@gunnarmorling Local build passed - simplified the process on protobuf side and included it into https://github.com/debezium/postgres-decoderbufs/pull/24/commits/f46bd030d5d2fd75c3abce2a0fcad7e60f19385c

**Comment by gunnarmorling** [comment]
Applied; thanks, @jpechane! Are you taking care of the backport to 1.0 right now? Or one concerted activity for all of them later on?

**Comment by jpechane** [comment]
@gunnarmorling I'd prefer to apply all in one batch, otherwise it is way easier to lose track and froget to include a commit or two

**Comment by gunnarmorling** [comment]
Ok, cool. The DBZ issue is assigned to 1.0-Backlog, so it's in the right
bucket.

>

**Pull request merged**
