### PR TITLE
DBZ-3595 Null key should not be converted

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3595

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, Pulsar-related test failure seems worth exploring.

**Comment by jpechane** [comment]
@gunnarmorling Another by-product of Quarkus 2 :-(

**Comment by gunnarmorling** [comment]
Raaah...

**Comment by jpechane** [comment]
@gunnarmorling Fixed

**Comment by gunnarmorling** [comment]
Applied, thx!

**Pull request merged**
