### PR TITLE
DBZ-2870 Using --release instead of --source/--target

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-2870

### CODE REVIEW

**Comment by rk3rn3r** [comment]
Shouldn't that trigger a build workflow for all modules?

**Comment by jpechane** [comment]
The main `pom.xml` is not among `paths` of module worflows.

**Comment by rk3rn3r** [comment]
Like God above everything? 😅
Do we act on it?

**Comment by jpechane** [comment]
I'll create a Jira issue and push a commit to this PR so it is tested as well

**Comment by jpechane** [comment]
@gunnarmorling I believe the `--release` works only for JDK 9+ compilers so probably `jdk11` profile should be introduced back and the property set in it.

**Comment by gunnarmorling** [comment]
> @gunnarmorling I believe the --release works only for JDK 9+ compilers so probably jdk11 profile should be introduced back and the property set in it.

How about we simply mandate JDK 11+ to be used for the build? Seems that's happening anyways as per the error report by the user on chat triggering this?

**Comment by jpechane** [comment]
@gunnarmorling No, we are not. I've received the same error report independently and after further investigation I've found that it was Confluent's build

**Comment by gunnarmorling** [comment]
Ok, thanks for checking! So in that light, let's keep that change for 1.5.

**Comment by gunnarmorling** [comment]
Closing for now, as we'll defer that upgrade. We still build with JDK 8 for the time being.

**Pull request closed without merging**
