### PR TITLE
DBZ-4429 Improve caching for formatter job

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-4429

### CODE REVIEW

**Comment by gunnarmorling** [comment]
That's interesting; a bit counter-intuitive at first, as this seems to limit the scope of caching (which is a good idea), whereas we didn't seem to do _enough_ caching before. Can you elaborate a bit on the fix? And I suppose similar changes may be in order for other workflows?

**Comment by Naros** [comment]
@ani-sha so I'm a bit confused by this because I agree that it should work.  

Looking at the post-action for the cache action I noticed that it said the cache-key hit was found so it didn't update anything on the run that you linked in Zulip.  Is it possible to go back and check the initial run for this when you first changed the cache key?   I'm curious if the post-action did things correctly or if perhaps there might have been a failure.  What I'm thinking is maybe the cache key exists but not all artifacts got stored?

If you need, you could re-test that by adjusting the cache-key again to just test a branch new cache-key with some random prefix/suffix values temporarily.

**Comment by ani-sha** [comment]
Works now! Should be good to go. Any other suggestions @Naros?

**Comment by Naros** [comment]
Nope, going to merge this.  Again great work @ani-sha !

**Pull request merged**
