### PR TITLE
DBZ-4286 (Debezium 1.6)

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-4286

Sending this PR, as I'm not sure whether the update from 8.0.21 to 8.0.27 will go without any other accomodating changes.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @ani-sha, shouldn't this PR against upstream/1.6 trigger a build?

**Comment by ani-sha** [comment]
@gunnarmorling That's strange. It should trigger all workflow builds. Can you try force pushing again?

**Comment by gunnarmorling** [comment]
Interesting. Force-pushed and now builds were kicked off. The one thing coming to mind is that I changed the base PR of this PR from main to 1.6, as I had originally sent it against the wrong branch. Anyways, all looking good now. Thx, @ani-sha!

**Comment by gunnarmorling** [comment]
Ok, so this also required the changes done for DBZ-3833 (upgrade to 8.0.26). Pulled those in and force-pushed.

**Comment by jpechane** [comment]
@gunnarmorling LGTM, applied, thanks!

**Pull request merged**
