### PR TITLE
DBZ-7645 Revert removal of LogMiner continuous mining

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-7645

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros It seems it aleast Oracle 23 failures are related

**Comment by Naros** [comment]
I am going to re-run the Oracle 23 test @jpechane as it does not fail locally.

**Comment by Naros** [comment]
Looks to have been a fluke with the environment @jpechane, so I think this is good.

**Pull request merged**
