### PR TITLE
DBZ-974 Update MongoDB Driver and Server

### PR DESCRIPTION
**Pull request by renatomefi**
- [x] Update Driver to 3.9.0
- [x] Solve possible deprecation (One per commit for easy rollback and trace-ability)
- [x] Create jobs for testing multiple MongoDB server versions (Moved to a new PR https://github.com/debezium/debezium/pull/675)
- [x] Have mongo-initiator based on the servers version - Depends on https://github.com/debezium/docker-images/pull/105 and https://github.com/debezium/docker-images/pull/107
- [x] Add job for mongo 4.1 (This still doesn't work, is it worth to add it? can we put it in failure "allowed"?)
Edit: I think it's better not, 4.1 dev is still early stages, the previous commits allows us to test it locally but we can wait until 4.2 beta is available

If you try to run locally:
```console
$ mvn docker:build docker:run -pl debezium-connector-mongodb -Dversion.mongo.server=4.1
```

```log
[INFO] DOCKER> [mongo:4.1] "mongo1": Waited on log out '.*waiting for connections on port 27017' 1008 ms
[INFO] DOCKER> [debezium/mongo-initiator:3.2]: Start container 7a72764bd86b
21:43:28.047 mongo-initTesting connection to MongoDB primary node at 172.17.0.2:27017 ...
21:43:28.081 mongo12018-11-13T20:43:28.081+0000 I NETWORK  [listener] connection accepted from 172.17.0.3:54008 #1 (1 connection now open)
21:43:28.082 mongo12018-11-13T20:43:28.082+0000 E -        [conn1] Assertion: Location34348: cannot translate opcode 2010 src/mongo/rpc/message.h 121
21:43:28.082 mongo12018-11-13T20:43:28.082+0000 I NETWORK  [conn1] DBException handling request, closing client connection: Location34348: cannot translate opcode 2010
21:43:28.082 mongo12018-11-13T20:43:28.082+0000 I NETWORK  [conn1] end connection 172.17.0.3:54008 (0 connections now open)
Testing connection to MongoDB primary node at 172.17.0.2:27017 ...
exception: connect failed
7a7276Testing connection to MongoDB primary node at 172.17.0.2:27017 ...
7a7276exception: connect failed
[ERROR] DOCKER> [debezium/mongo-initiator:3.2]: Container stopped with exit code 1 unexpectedly after 507 ms while waiting on exit code 0
[ERROR] DOCKER> Error occurred during container startup, shutting down...
[INFO] DOCKER> [debezium/mongo-initiator:3.2]: Stop and removed container 7a72764bd86b after 0 ms
```

You'll see that the mongo-initiator will fail due to not being able to connect with the server, by having the initiator with a client with the same version as the server makes it work

### CODE REVIEW

**Comment by jpechane** [comment]
@renatomefi Hi, thanks for the contribution! Could you please separate the Jenkins jobs update to a separate PR? Looking at the amount of jobs we might be now better served with matrix builds instead of job per version strategy but this needs further investigation.

Thanks!

**Comment by jpechane** [comment]
@renatomefi I've tried to execut build locally for 3.6 and 4.0 and got a failuer in both cases. I see this in the log
```
14:47:42.415 mongo-init
Testing connection to MongoDB primary node at 172.17.0.2:27017 ...
Using MongoDB primary node to initiate replica set "rs0" with:
- primary node:   172.17.0.2:27017
MongoDB shell version v3.6.8
connecting to: mongodb://172.17.0.2:27017/
MongoDB server version: 3.6.8
{
	"ok" : 0,
	"errmsg" : "Expected type of members.0 to be Object, but found undefined",
	"code" : 93,
	"codeName" : "InvalidReplicaSetConfig"
}

Replica set is ready
```
Could you please double check it?

Thanks

**Comment by renatomefi** [comment]
@jpechane fixed in debezium/docker-images#107

After it's merged and images pushed this should be fixed!

**Comment by renatomefi** [comment]
@gunnarmorling that sounds nice!

I only got to know it in the gitter chat, I'll add where to look for builds in the docs!

**Pull request closed without merging**
