### PR TITLE
DBZ-2375 Hyperlink entries in the mysql metrics tables to facilitate sharing.

### PR DESCRIPTION
**Pull request by roldanbob**
DBZ-2375 Add links to entries in the mySQL metrics tables so that developers can share the anchor urls when responding to questions about the various metrics.

### CODE REVIEW

**Comment by rk3rn3r** [comment]
This looks like a nice addition. Thank you for the PR @roldanbob!

**Comment by roldanbob** [comment]
@rk3rn3r I think it's all set now. Let me know if everything looks ok.

**Comment by Naros** [comment]
Merged, thanks @roldanbob.

**Comment by TovaCohen** [comment]
@Naros Do you plan to backport this to 1.2?

**Pull request merged**
