### PR TITLE
DBZ-1153 Support for special char names

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1153

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, this still is waiting for more feedback from the original issue reporter, correct?

**Comment by jpechane** [comment]
@gunnarmorling If there will be no reactin till tomorrow I think we can merge it. The test proves the special chars are no longer an issue so the case ont reproduced yet might have different root cause.

**Comment by jpechane** [comment]
@gunnarmorling We are good to go, the reporter is testing on older SQL Server version which is probably source of the last problem.

**Comment by gunnarmorling** [comment]
Applied; thanks, @jpechane!

**Pull request merged**
