### PR TITLE
DBZ-2206 Upgrade apicurio to 1.2.2.Final

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2206

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, semi-related: there's an unresolved Apicurio version placeholder in the Avro docs. Could you push a fix for this to this PR? Thx!

**Comment by jpechane** [comment]
@gunnarmorling Done

**Comment by gunnarmorling** [comment]
@jpechane, is that failure for SQL Server tracked already?

**Comment by jpechane** [comment]
Logged in detail for reference - https://issues.redhat.com/browse/DBZ-2211

Was originally part of larger test failure tracking issue

**Comment by gunnarmorling** [comment]
Applied. Also backported the doc part to 1.1. Thanks!

**Pull request merged**
