### PR TITLE
DBZ-1944 updating links to mysql documentation

### PR DESCRIPTION
**Pull request by ahus1**
... to point to large page instead of the assemblies
cc: @gunnarmorling

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Uff, good catch.

@bhardesty, any objections?

**Comment by gunnarmorling** [comment]
@ahus1 btw. do you have a link to that tool you're using for spotting these?

**Comment by bhardesty** [comment]
This looks good to me.

@gunnarmorling I think I'll need to adjust some of the xrefs in any of the .adoc files that are reused in the downstream. This is because antora has its own unique internal linking scheme that is incompatible with downstream doc publication (or any other doc site generator). However, this does not affect the upstream doc at all, so IMO you can go ahead and merge this PR. I can follow up with a separate PR to adjust the xref syntax in a way that will allow the xrefs to be valid in the downstream docs.

**Comment by gunnarmorling** [comment]
Merged. Thanks a lot @ahus1 and @bhardesty!

**Comment by gunnarmorling** [comment]
Merged the PRs for 1.0 and 1.1, too.

To shed some lights on why those branches are maintained: both upstream and downstream are released on a quarterly basis, with the latter lagging behind by one quarter. I.e. this quarter's downstream 1.0 release is based on the December 1.0 upstream release. Current upstream development is done for 1.2 (master), 1.0 is the basis for the current "active" downstream release, and 1.1 the basis for the next downstream release.

@ahus1, is there any way for including your link checker into a CI build somehow?

**Comment by ahus1** [comment]
@gunnarmorling - as you ask for tools: 

There is the **AsciiDoc plugin for IntelliJ**. https://plugins.jetbrains.com/plugin/7391-asciidoc
It allows you to run "Analyze | Inspect Code...". This is how I found these issues. I set up a profile with only the AsciiDoc inspections. 
It validates xrefs and links including their anchors. Will run on both the ultimate and community edition.
Full disclosure: I'm the current maintainer of the plugin. Validation will evolve over time. Please raise GitHub issues for missing validations or false positives.

There is **xref-validator** https://gitlab.com/antora/xref-validator 
It will check if an xref points to a page. This doesn't check includes and anchors AFAIK. This could be part of a build.

For a fully generated site w/ HTML (or a partially generated site), you can **run a link checker** like https://www.npmjs.com/package/broken-link-checker.
It is quite old, but does its job. It checks only if the page exists, not the anchor AFAIK. This can be part of a build like in this script: https://github.com/vuejsfrankfurt/vuejsfrankfurt.de/blob/master/build.sh

**Comment by ahus1** [comment]
@gunnarmorling - almost forgot about this one: https://github.com/aim42/htmlSanityCheck
Runs as Gradle plugin and standalone. In some of my projects at work I wrapped the gradle task as a maven plugin.

**Pull request merged**
