### PR TITLE
DBZ-4023 Check if author names are present in COPYRIGHT.txt

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-4023

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha Could you please create a branch on your repo with yourself being removed from copyright.txt and then use this file as the URL se we can test the PR works even for that case?

**Comment by ani-sha** [comment]
@jpechane Tried and tested, it works - https://github.com/ani-sha/debezium/pull/6

**Comment by jpechane** [comment]
@ani-sha Nice, so could we complicate it a little bit more yet? :-) There is also a mapping file https://github.com/debezium/debezium/blob/master/jenkins-jobs/scripts/config/Aliases.txt#L56 that transaltes a subset of usernames to the real name. Would it be possible to add a support for it too?

**Comment by ani-sha** [comment]
A checking clause to find out if the PR's author name is an `alias name` or not. 
If the name isn't found in `COPYRIGHT.txt`, then check if it is present in `Aliases.txt` or not? 
- If it is present. Do nothing, no comments. 
- If not then add a comment for adding the name into `Aliases.txt` or `COPYRIGHT.txt`.

@jpechane Is that what you mean?

**Comment by jpechane** [comment]
Exactly

**Comment by ani-sha** [comment]
@jpechane It works as expected. Tried in the above PR.

**Comment by jpechane** [comment]
@ani-sha Great job, thanks!

**Pull request merged**
