### PR TITLE
DBZ-4341 log batchSize in BaseSourceTask

### PR DESCRIPTION
**Pull request by tooptoop4**
https://issues.redhat.com/browse/DBZ-4341

DBZ-4341 log batchSize in BaseSourceTask

### CODE REVIEW

**Comment by Naros** [comment]
Hi @tooptoop4, batch size doesn't necessarily mean the number of records changed though.  I don't think any of us are opposed to logging the batch size this way but I want to be clear that if your batch size is 10,000 and 225,000 rows are emitted over the output interval that line will indicate `Batch size: 10000. 225000 record sent in previous ...".  Is that really helpful though?

**Comment by gunnarmorling** [comment]
Good point, @Naros. In fact, the message didn't make much sense before already, because we logged the _total number_ of emitted since task start (`recordCounter`) together with the duration of the last polling interval. So we should simply change this to log `batchSize` together with that duration and otherwise keep the message as-is. The total number of emitted records is already exposed via JMX metrics.

That being said, on the issue itself we spoke about breaking down event count metrics per event type, but that's not what you've implemented here, @tooptoop4. So that's no longer important to you then?

**Comment by tooptoop4** [comment]
recordCounter didn't make sense so batch size is a quick win. the breakdown would be good but I imagine higher effort

**Comment by gunnarmorling** [comment]
Closing in favour of https://github.com/debezium/debezium/pull/3018/. Will leave the metrics change for another time then, tbh. I don't think it'd add super-much value.

**Pull request closed without merging**
