### PR TITLE
DBZ-4672 GH action build trigger adjustments

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-4672

- [x] Fail commit missing Jira prefix check
- [x] Build dependent connectors when schema generator is modified
- [x] Fix file changes check when a change to workflow in `main` is pushed with open PRs.

### CODE REVIEW

**Comment by Naros** [comment]
The commit check should now fail rather than always pass:
image
Navigating to the details:
image

**Comment by Naros** [comment]
Hi @ani-sha, could you take a look at these changes thus far and give me your opinion.  We still need to discuss the final open issue regarding the situation where the scenario is:

- PR 1 - Changes to debezium-workflow.yml is submitted
- PR 2 - Changes to some other code is submitted (here workflow runs as we expect)
- PR 1 - Merged to `main`, so `main` now has the updated workflow
- PR 2 - Another commit is pushed, file changes detection fails

**Comment by Naros** [comment]
So it just occurred to me why that scenario happens and I wonder if that's actually intended behavior.

So @ani-sha @gunnarmorling, each file changes check examinse whether `debezium-workflow.yml` has changed.  In the case of PR #3191 the issue is that at first the changes check only sees the files changed in the PR itself.  But later on after we push the change to the `debeizum-workflow.yml` to `main`, it would appear that the diff actually reports that there is a difference in the workflow on the PR vs the version in `main` and this must be what triggers the case where all modules get built despite the PR actually only targetting things within a specific connector module.

I'll reach out to the action author & review the docs for it to see if there is perhaps a toggle we need to use to avoid this.

**Comment by Naros** [comment]
And looking at the logs from the PR that @gunnarmorling had referenced in the Jira issue, my theory is confirmed:
```
  Added files: 
  Copied files: 
  Deleted files: 
  Modified files: .github/workflows/debezium-workflow.yml
  Renamed files: 
  Type Changed files: 
  Unmerged files: 
  Unknown files: 
  All changed and modified files: .github/workflows/debezium-workflow.yml
  All changed files: .github/workflows/debezium-workflow.yml
  All modified files: .github/workflows/debezium-workflow.yml
```
I reached out to the author, perhaps I am using the wrong toggle with his action; so I'll update this when I know more.

**Comment by Naros** [comment]
So the author confirmed our approach in our workflow is correct but recommended we upgrade to see if the bug has been fixed.  I'll apply the upgrade here and we can merge this and see if the weird triggering of jobs due to miscalculating of the changed files still persists.

**Comment by Naros** [comment]
I examined the output from the "Detect repository changes" stage from the latest commit and it has been fixed.  So from my perspective this is ready to be merged.

**Comment by gunnarmorling** [comment]
Ok, will merge it, thanks! Could you add the green check mark to those items from the issue which are fixed by this?

Btw. this discussion made me realize there's a general "gap" in the system, in the case where a PR gets created, and then further commits are pushed to main while the PR is open. The PR will be built "as-is", whereas when it gets applied to main later on, it will be rebased. In theory, this may cause regressions which went unnoticed by the PR built. So ideally, each PR would have to be rebased to main, then built and only then be merged. As things are, only the next build against the main branch would detect such issues. But I reckon it's rarely a problem in reality, and thus not worth spending effort on preventing it. After all, any regressions _will_ show up after the merge, and in the worst case we could back out a PR again if needed.

**Pull request merged**
