### PR TITLE
DBZ-1492 - MySQL Connector Fails while parsing AWS RDS internal events

### PR DESCRIPTION
**Pull request by pushpavanthar**
Added RDS specific statements(`mysql.rds_sysinfo`) into `internal.database.history.ddl.filter` default value.

### CODE REVIEW

**Comment by pushpavanthar** [comment]
https://issues.jboss.org/browse/DBZ-1492
@jpechane could you please review this PR?

**Comment by gunnarmorling** [comment]
@pushpavanthar, have you tested this with MySQL on RDS? Can you confirm it addresses your original issue? It's really weird btw. that those events come in in "statement" format if the log is set to "row"...

**Comment by jpechane** [comment]
@gunnarmorling We'd similiar cases in the past, see other statements in the filter

**Comment by gunnarmorling** [comment]
Ok, weird nevertheless :)

**Comment by gunnarmorling** [comment]
Btw. I've marked this with a new label "0.10.1-candidate ", which we should use to tag PRs to be backported into a potential 0.10.1 release. Whether or not to do it should be a decision later on, based on number and severity of candidate issues.

**Comment by pushpavanthar** [comment]
@gunnarmorling I've tested this on RDS as well. Right now we are passing this regex pattern as part of config as a workaround in production. 
It appears that, RDS MySQL by default marks such internal `database.tables ` to be ignored by the slave. They appear under the property `Replicate_Ignore_Table` in MySQL. If I'm not wrong the right approach would be to ignore all statements involving tables mentioned in this attribute.
Below is the default tables I got in the RDS i have provisioned.
`Replicate_Ignore_Table: mysql.plugin,mysql.rds_monitor,mysql.rds_sysinfo,innodb_memcache.cache_policies,mysql.rds_history,innodb_memcache.config_options,mysql.rds_configuration,mysql.rds_replication_status`

**Comment by gunnarmorling** [comment]
Ah, that's interesting. So perhaps we can read the value from `Replicate_Ignore_Table` and exclude all those tables? Not necessarily as part of this PR, but as a further improvement going forward.

**Comment by pushpavanthar** [comment]
That's what I was thinking. I need confirmation from people who have used other MySQL providers about the behaviour of Replicate_Ignore_Table property. I would love to take this change in another PR.

**Comment by jpechane** [comment]
@gunnarmorling Don't forget this is a DML, so to do it we would need to parse the DML and decide if it should be replicated or not.

**Comment by gunnarmorling** [comment]
> Don't forget this is a DML, so to do it we would need to parse the DML and decide if it should be replicated or not.

Are you sure? I was thinking of adding a DDL filter such as `(INSERT|DELETE).*mysql.rds_sysinfo` when seeing the table `mysql.rds_sysinfo` in that config property, and similarly for each other one. No need to parse the DML statement then.

**Comment by gunnarmorling** [comment]
Logged this separate ideas as https://issues.jboss.org/browse/DBZ-1521.

**Comment by gunnarmorling** [comment]
Applied; thanks a lot, @pushpavanthar!

**Pull request merged**
