### PR TITLE
DBZ-4444 

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-4444

This is a WIP; I've simply replaced all references of `log4j` with `log4j-jboss-logmanager`.

### CODE REVIEW

**Comment by Naros** [comment]
So besides the dependency on the rest extension, there is also another concern about:
```
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ccranfor/.m2/repository/org/slf4j/slf4j-log4j12/1.7.30/slf4j-log4j12-1.7.30.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ccranfor/.m2/repository/org/jboss/slf4j/slf4j-jboss-logmanager/1.1.0.Final/slf4j-jboss-logmanager-1.1.0.Final.jar!/org/slf4j/impl/StaticLoggerBinder.class]
```
This needs addressing with these changes as well.

**Comment by gunnarmorling** [comment]
Hey @Naros, thanks a lot for looking into this. Two new changes/insights have come up in the meantime:

* We remove the problematic `JMSAppender` class from the container images (see pending announcement here: https://github.com/debezium/debezium.github.io/pull/768)
* We've learned that Kafka Connect Runtime actually does _not_ directly invoke log4j 1.x, but in fact uses slf4j, like Debezium does (it still is required as a runtime component, backing the slf4j API)

In that light, I think the mitigation we have in the container image (removal of `JMSAppender`) may be good enough for the time being. But at the same time, we actually may git rid of log4j in our build completely by using another implementation for slf4j during testing (I'd suggest logback). i.e. we could remove log4j from all our POMs and use logback instead (which will require to update the log config used in tests though). WDYT, could you rework this PR accordingly?

**Comment by gunnarmorling** [comment]
@Naros, so thinking more about it, we probably could close DBZ-4444 (the exploration has been conducted, and we conclude that we will not replace log4j 1.x for the time being in the container images we ship), and attribute this change to https://issues.redhat.com/browse/DBZ-2224, which is about upgrading the logger impl used during testing. WDYT?

**Comment by Naros** [comment]
Agreed

**Pull request closed without merging**
