### PR TITLE
DBZ-6316 Fix unparseable DDL statements for MySQL/MariaDB

### PR DESCRIPTION
**Pull request by joschi**
https://issues.redhat.com/browse/DBZ-6316

### CODE REVIEW

**Comment by jpechane** [comment]
@ani-sha Could you please review the PR and merge when ready?
Also backport to 2.1 would be good. Thanks!

**Comment by joschi** [comment]
The build failure in [Build Debezium / MySQL](https://github.com/debezium/debezium/actions/runs/4619698235/jobs/8185036314?pr=4437) looks unrelated.

```
2023-04-06T10:58:26.4571985Z [INFO] Debezium ANTLR DDL parsers ......................... SUCCESS [ 58.961 s]
```
The changed module builds successfully.

The actual error:
```
2023-04-06T10:04:12.9965461Z Caused by: org.testcontainers.containers.ContainerFetchException: Can't get Docker image: RemoteDockerImage(imageName=debezium/example-mysql:2.1.4.Final, imagePullPolicy=DefaultPullPolicy(), imageNameSubstitutor=org.testcontainers.utility.ImageNameSubstitutor$LogWrappedImageNameSubstitutor@4317a4a8)
2023-04-06T10:04:12.9966762Z 	at org.testcontainers.containers.GenericContainer.getDockerImageName(GenericContainer.java:1371)
2023-04-06T10:04:12.9967525Z 	at org.testcontainers.containers.GenericContainer.logger(GenericContainer.java:651)
2023-04-06T10:04:12.9968201Z 	at org.testcontainers.containers.GenericContainer.doStart(GenericContainer.java:331)
2023-04-06T10:04:12.9968576Z 	... 33 more
2023-04-06T10:04:12.9969369Z Caused by: com.github.dockerjava.api.exception.NotFoundException: Status 404: {"message":"manifest for debezium/example-mysql:2.1.4.Final not found: manifest unknown: manifest unknown"}
2023-04-06T10:04:12.9969879Z 
2023-04-06T10:04:12.9970405Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.execute(DefaultInvocationBuilder.java:241)
2023-04-06T10:04:12.9971378Z 	at org.testcontainers.shaded.com.github.dockerjava.core.DefaultInvocationBuilder.lambda$executeAndStream$1(DefaultInvocationBuilder.java:269)
2023-04-06T10:04:12.9972091Z 	at java.base/java.lang.Thread.run(Thread.java:833)
2023-04-06T10:04:12.9972283Z 
2023-04-06T10:04:12.9972871Z [ERROR] io.debezium.connector.mysql.MySqlParserIT.parseTableWithInVisibleColumns  Time elapsed: 0.239 s  <<< ERROR!
2023-04-06T10:04:12.9973477Z java.lang.NullPointerException
2023-04-06T10:04:12.9973889Z 	at java.base/java.util.concurrent.ConcurrentHashMap.putVal(ConcurrentHashMap.java:1011)
2023-04-06T10:04:12.9974588Z 	at java.base/java.util.concurrent.ConcurrentHashMap.put(ConcurrentHashMap.java:1006)
2023-04-06T10:04:12.9975153Z 	at java.base/java.util.Properties.put(Properties.java:1301)
2023-04-06T10:04:12.9975641Z 	at java.base/java.util.Properties.setProperty(Properties.java:229)
2023-04-06T10:04:12.9976041Z 	at java.base/java.lang.System.setProperty(System.java:999)
2023-04-06T10:04:12.9976585Z 	at io.debezium.connector.mysql.MySqlParserIT.afterEach(MySqlParserIT.java:73)
```

And that's correct because the reference image `debezium/example-mysql:2.1.4.Final` doesn't exist:
```
# crane ls debezium/example-mysql | grep ^2.1
2.1
2.1.0.Alpha1
2.1.0.Alpha2
2.1.0.Beta1
2.1.0.Final
2.1.1.Final
2.1.2.Final
2.1.3.Final
```

**Comment by joschi** [comment]
See https://github.com/debezium/debezium/pull/4439 for a potential fix for the container image issues in the MySQL and PostgreSQL tests.

**Comment by jpechane** [comment]
@joschi Thanks a lot, I rebased to the latest main and if CI passes I'm going to merge it to make sure it gets into next 2.2 release. Could you please prepare a follw-up PR if this will be already merged that will comment all MariaDB specific constructs/privileges as such? Thanks

**Comment by jpechane** [comment]
@joschi Applied, thanks! Just please see the coment above.

**Comment by joschi** [comment]
> Could you please prepare a follw-up PR if this will be already merged that will comment all MariaDB specific constructs/privileges as such?

@jpechane I see that "Add source connector making MariaDB a first-class source within Debezium" moved to Debezium 2.4 (September 2023) in the [Debezium Roadmap](https://debezium.io/roadmap/) document.

Would it make sense to pull it into Debezium 2.3 again (maybe as a preview/alpha feature) and use the already split upstream grammars for this?
- https://github.com/antlr/grammars-v4/tree/master/sql/mariadb
- https://github.com/antlr/grammars-v4/tree/master/sql/mysql

Maybe even let the Debezium build use these grammars directly instead of importing/copying them into this repository could make sense. The changes to either grammar should be applied to both repositories anyway to avoid further sprawl.

Would be happy to help there a little bit since we are currently using MariaDB at work.

**Comment by jpechane** [comment]
@joschi Unfortunately it is not only grammar but binlog differences as well. @novotnyJiri is going to work on it as part of his aster thesis so I am trying to align the plans with his schedule.

**Pull request merged**
