### PR TITLE
DBZ-7908 Add subpartition into allowed expressions when altering table

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-7908

### CODE REVIEW

**Comment by vjuranek** [comment]
Do we keep in sync with upstream grammar? I haven't sent upstream PR yet, as the code base seems to me diverge quite a lot.

**Comment by Naros** [comment]
> Do we keep in sync with upstream grammar? I haven't sent upstream PR yet, as the code base seems to me diverge quite a lot.

I generally do @vjuranek.  Someone rewrote the grammar upstream in recent months and I've been concerned about bringing that down just yet.  What I typically do is add the failure SQL to the upstream test suite and if it passes, I do nothing.  If it fails, I adjust the upstream grammar as necessary, trying to stay as close to our solution here as possible.

**Comment by vjuranek** [comment]
thanks @Naros , make sense. Upstream PR: https://github.com/antlr/grammars-v4/pull/4123

**Comment by vjuranek** [comment]
2.6 backport PR: #5588 5588

**Comment by jpechane** [comment]
@vjuranek Applied thanks

**Pull request merged**
