### PR TITLE
DBZ-1464: fixed NPE when op is not u/i/d

### PR DESCRIPTION
**Pull request by levzem**
if the received event from mongoDB has anything but `op=i`, `op=u`, or `op=d`, it can result in a NPE for example with `op=n` (no op).

https://issues.jboss.org/browse/DBZ-1464

an alternative fix would be to change `recordEvent()`in `RecordMaker` to return 0 if `op` is not found in `operationLiterals`

Can we backport this to `0.9` and release a patch on that branch?

Signed-off-by: Lev Zemlyanov <lev@confluent.io>

### CODE REVIEW

**Comment by levzem** [comment]
@gunnarmorling and @jpechane could you have a look please?

**Comment by gunnarmorling** [comment]
Thanks a lot, @levzem! Squashed, rebased and applied.

Note I've merged this into master, i.e. it'll be part of the 0.10.0.CR1 release next week. We don't have any further 0.9.x releases planned at this point.

**Comment by gunnarmorling** [comment]
And thanks for reviewing, @patilharshal16!

**Comment by renatomefi** [comment]
Hello,

By curiosity, when do you see a noop in mongo oplog? Like, what's the scenario?

Thanks!

**Comment by levzem** [comment]
@renatomefi - I am not sure. This issue was raised by a customer. 

according to [here](https://www.compose.com/articles/the-mongodb-oplog-and-node-js/), `"n" for "no-ops", used for changes in the database or collections which don't result in a change in the stored data`

**Pull request closed without merging**
