### PR TITLE
DBZ-4345 Document snapshot.include.collection.list property for Db2

### PR DESCRIPTION
**Pull request by roldanbob**
[DBZ-4345](https://issues.redhat.com/browse/DBZ-4345)

Adds entry for `snapshot.include.collection.list` to the Db2 connector properties table.

Tested in local Antora build and local downstream build

### CODE REVIEW

**Comment by Naros** [comment]
Did you get a chance to test this in the local downstream build, @roldanbob ?

**Comment by roldanbob** [comment]
> Did you get a chance to test this in the local downstream build, @roldanbob ?

Ugh. No. I ran into some problems with Nebel not converting links properly for the downstream build, so ATM, I'm at a standstill. I have no reason to think that this change should cause any issues downstream, but I can't verify yet. I hope to have a resolution today. I'll keep you posted.

**Comment by roldanbob** [comment]
@Naros For now, to expedite this, I've manually added the content to a downstream file and verified that the new content is built. I'll continue to investigate the tooling problem, but I'll handle that separately for now.

**Review by Naros — APPROVED** [review]

**Comment by Naros** [comment]
Applied to main (=2.0) and branch 1.9.

**Pull request merged**
