### PR TITLE
DBZ-4720 Validate Debezium Server configuration properties

### PR DESCRIPTION
**Pull request by jeremy-l-ford**
Valication connector before attempting to initialize

### CODE REVIEW

**Comment by spicy-sauce** [comment]
@ggaborg, please review this PR (this issue was opened by me at the time).

**Review by ggaborg — APPROVED** [review]

**Review by ggaborg — COMMENTED** [review]
I think there should be some tests for each connector

**Comment by ggaborg** [comment]
Also, this change only touches the validation for the connector properties, not other configuration dependent components like offset storages, schema history, etc.

**Comment by jeremy-l-ford** [comment]
For SchemaHistory, each implementation is already validating itself in the configuration method.

For the OffsetBackingStore, perhaps as part of DBZ-1971, validation support could be added.

In terms of tests for each connector, are you thinking that MySqlConnectorConfig as an example needs to be unit tested?

**Comment by ggaborg** [comment]
@jeremy-l-ford, hi
1. "For SchemaHistory, each implementation is already validating itself in the configuration method." - this only validates required properties and is not similar with the connector validation.
2. "For the OffsetBackingStore, perhaps as part of DBZ-1971, validation support could be added." - I was thinking about a unified mechanism to validate configuration, see 1.
3. "In terms of tests for each connector, are you thinking that MySqlConnectorConfig as an example needs to be unit tested?" yes

**Pull request closed without merging**
