### PR TITLE
DBZ-2766 Remove Guava dependency

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2766

### CODE REVIEW

**Comment by jpechane** [comment]
@kgalieva Hi, could you please take a look at this PR? We want to get indendpendent of Guava but there is a code in read-only snapshotting that depends on it. Would it be possible to refactor it so it is no longer dependent? Thanks a lot

**Comment by kgalieva** [comment]
I've open the PR https://github.com/jpechane/debezium/pull/4

**Comment by kgalieva** [comment]
I've found a bug in my change. I'll fix it tomorrow

**Comment by kgalieva** [comment]
Added the fix https://github.com/jpechane/debezium/pull/5

**Comment by jpechane** [comment]
@Naros I've updated the PR and provided an additional one on https://github.com/debezium/debezium-connector-cassandra/pull/68

**Pull request merged**
