### PR TITLE
DBZ-4423 Simplified method duration.

### PR DESCRIPTION
**Pull request by wfouche**
Old implementation, 1 million iterations took 4291 milliseconds.
New implementation, 1 million iterations took 2111 milliseconds.

### CODE REVIEW

**Comment by helpermethod** [comment]
Especially in older Java versions `String.format` is notoriously slow. I would expect plain old string concatenation to be much faster.

**Comment by wfouche** [comment]
> DBZ-4423 Simplified method duration.

I did prefix the commit with the JIRA issue key.

**Comment by JanecekPetr** [comment]
I found this via Twitter, am not an actual reviewer.

First of all, this PR changes the behaviour a little, but there are no updated tests. This tells me there are actually no tests and some need to be added, especially since we're rewriting this.

Second of all, the presented solution is very readable, but far from being fast. Resolving the template string on every call costs a lot. I created a JMH benchmark here: https://gitlab.com/janecekpetr/benchmarks/-/blob/master/src/main/java/com/gitlab/janecekpetr/benchmark/DurationFormatBenchmark.java (Beware, it's currently using random durations!)

Here are the results from my MacBook Pro 16" (read as "probably very noisy and unreliable"):
- `original` is the original bad code
- `originalWithStaticFormats` is the same, but reuses the `DecimalFormat` objects
- `originalSimplified` still uses the same logic, but does it mostly with longs and reused DecimalFormats
- `stringFormat` is the code of this PR
- `stringBuilder` uses a `StringBuilder`

```
Java 8
Benchmark                                    Mode  Cnt     Score    Error  Units
DurationBenchmark.original                   avgt    5  2296.563 ± 46.786  ns/op
DurationBenchmark.originalWithStaticFormats  avgt    5  1233.087 ± 44.023  ns/op
DurationBenchmark.originalSimplified         avgt    5   329.826 ±  5.223  ns/op
DurationBenchmark.stringFormat               avgt    5  1510.239 ± 33.353  ns/op
DurationBenchmark.stringBuilder              avgt    5    53.533 ±  0.608  ns/op

Java 11
Benchmark                                    Mode  Cnt     Score     Error  Units
DurationBenchmark.original                   avgt    5  2072.693 ± 386.719  ns/op
DurationBenchmark.originalWithStaticFormats  avgt    5  1308.815 ±  22.901  ns/op
DurationBenchmark.originalSimplified         avgt    5   328.450 ±   5.081  ns/op
DurationBenchmark.stringFormat               avgt    5  1219.312 ± 333.448  ns/op
DurationBenchmark.stringBuilder              avgt    5    46.681 ±   5.322  ns/op

Java 17
Benchmark                                    Mode  Cnt     Score     Error  Units
DurationBenchmark.original                   avgt    5  2701.159 ±  32.189  ns/op
DurationBenchmark.originalWithStaticFormats  avgt    5  1643.343 ± 310.077  ns/op
DurationBenchmark.originalSimplified         avgt    5   808.525 ± 107.112  ns/op
DurationBenchmark.stringFormat               avgt    5  1251.860 ±  35.582  ns/op
DurationBenchmark.stringBuilder              avgt    5    42.865 ±   0.709  ns/op
```

While I agree the version in this PR is the most readable by far, it's "only" twice as fast as the original and actually just as fast as the original with reused DecimalFormats. Once we a little further, we can get another 5* or even 30* speedup.

One interesting thing is the regression of all `original*` variants on Java 17. I reran it multiple times to make sure it's actually there, it is. I did not look further, did not have the time yet, it's worth a look and maybe a bug report.

**Comment by gunnarmorling** [comment]
Wow, thanks a lot for chiming in, @JanecekPetr! Indeed this PR is changing the behavior, and I don't think we should do that. So I've added a test and also provided another implementation using a string builder in https://github.com/debezium/debezium/pull/3027. These are the numbers I get:

```
Benchmark                       (value)  Mode  Cnt     Score     Error  Units
DurationToStringPerf.original   3750520  avgt    5  3155,963 ± 149,810  ns/op
DurationToStringPerf.reworked1  3750520  avgt    5  1450,303 ± 151,518  ns/op
DurationToStringPerf.reworked2  3750520  avgt    5    38,933 ±   4,301  ns/op
```

Does this resemble your implementation, @JanecekPetr? I'm sure there's more that could be done, but I am more than happy with that improvement. It didn't matter to begin with, but the original implementation was just itching me :) Feedback on the linked PR very welcome. Thanks a lot for your efforts, @wfouche, @JanecekPetr!

**Comment by JanecekPetr** [comment]
Yup, that's essentially the same implementation except for the trailing 0s handling and using `'0'` vs `"0"` in `append()` :). Nice improvement, I've been nerdsniped as well.

**Comment by gunnarmorling** [comment]
> Nice improvement, I've been nerdsniped as well.

🤓  Haha, yeah, some things just _need_ to be done.

**Comment by gunnarmorling** [comment]
Thanks a lot all, I am going to close this PR in favor of https://github.com/debezium/debezium/pull/3027 then.

**Pull request closed without merging**
