### PR TITLE
DBZ-3449 Moving QA releated plug-ins to separate profile, so to avoid…

### PR DESCRIPTION
**Pull request by gunnarmorling**
… loading them at all

https://issues.redhat.com/browse/DBZ-3449

@jpechane, this should take care of your earlier concerns.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, is that what you had in mind?

**Comment by jpechane** [comment]
@gunnarmorling Looks good thanks! There is just one potential speedup left but it is debatable. You can disable code generation for protobuf and DDL parser modules. I keep this at your discretion.

**Comment by gunnarmorling** [comment]
> You can disable code generation for protobuf and DDL parser modules.

@jpechane, I don't think you can, as there's code compiled against the generated types, right?

**Comment by jpechane** [comment]
@gunnarmorling Right, my bad. I mixed it with protobuf decoder where we commit gerenated sources to the repository. This is not the case with rest of Debezium.

**Comment by gunnarmorling** [comment]
Ok, cool. I've sent PRs for all the other repos, too.

**Pull request merged**
