### PR TITLE
WIP: 1.0.3 cherry pick

### PR DESCRIPTION
**Pull request by jpechane**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, it says WIP, are you planning to add more?

**Comment by jpechane** [comment]
You've also scheduled DBZ-1849 so wehn confirmed the fix is in place after today morning PR it will be added too

**Comment by gunnarmorling** [comment]
@jpechane, ok, let me know then when DBZ-1849 has been added, or just merge this PR yourself afterwards. Thanks!

**Comment by jpechane** [comment]
@gunnarmorling Added, but I intend to merger the PR just before the release

**Comment by gunnarmorling** [comment]
Ok, fine for me. I'd like to get started with the doc backports. I'll push
to this PR then.

>

**Pull request merged**
