### PR TITLE
DBZ-8238 Fix metrics after blocking snapshot

### PR DESCRIPTION
**Pull request by jpechane**
Replaces https://github.com/debezium/debezium/pull/5860

https://issues.redhat.com/browse/DBZ-8238

### CODE REVIEW

**Comment by jpechane** [comment]
@m8719-github Test failures are related to the change.

**Comment by m8719-github** [comment]
taking a look.

**Comment by m8719-github** [comment]
@jpechane I am thinking of making this a MS-SQL specific test, it works there and there is no value in running this test * number of connectors.

**Comment by m8719-github** [comment]
@jpechane I fixed broken tests and pushed to my fork. I couldn't verify DB2 test because DB2 container does not run on my setup.

**Comment by m8719-github** [comment]
opened [WIP PR](https://github.com/debezium/debezium/pull/5871) need CI to run DB2 IT suite.

**Comment by jpechane** [comment]
Merged via https://github.com/debezium/debezium/pull/5871

**Pull request closed without merging**
