### PR TITLE
DBZ-2618 Deploy snapshots for Vitess connector

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-2618

### CODE REVIEW

**Comment by gunnarmorling** [comment]
LGTM, one question though: what about the licenses of the Vitess connector dependencies? Can we distribute them all as part of the archive?

**Comment by jpechane** [comment]
@gunnarmorling You type comments faster than I do :-) https://issues.redhat.com/browse/DBZ-2618?focusedCommentId=15220646&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-15220646

**Comment by jpechane** [comment]
@gunnarmorling According to the latest Jira comment I believe we are goog to go.

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Yes, we are. All dependency licenses are liberal once (Apache v2, 3 clause BSD, MIT). Thanks!

**Pull request merged**
