### PR TITLE
DBZ-4294 Awaiting PURGE has happened

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-4294

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @ani-sha, @Naros, so something still is wrong with the build checks. This PR only changes a single test for MySQL, this should not trigger all the other checks for all the other connectors 🤔 .

**Comment by Naros** [comment]
So I had something like this happen once before and the only common denominator between your occurrence and that time is that a change was merged to the main branch for the `debezium-workflow.yml` file.  So I think there may be a bug on GitHub where there is some type of reconciliation problem with the file changes action.  The way I fixed it on my other PR was to do a rebase and force push of the PR and it worked once the PR had the most up-to-date workflow.

I'm guessing what the default GitHub "paths" logic does differs from what the `tj-actions/changed-files` action does.  You have any suggestions @ani-sha ?

**Comment by gunnarmorling** [comment]
Logged https://issues.redhat.com/browse/DBZ-4672 for the CI trigger issue

**Review by Naros — APPROVED** [review]
LGTM, applied to main (=1.9)

**Pull request merged**
