### PR TITLE
DBZ-4850 Add several retriable SQL error codes

### PR DESCRIPTION
**Pull request by EthanZ328**
(ORA-00310,ORA-01343,ORA-01371)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hey @Naros, could you review and merge this one? Thx!

**Comment by Naros** [comment]
Hi @EthanZ328 so I'm not really comfortable adding these as "retriable" errors because really we should never face these if we are managing logs properly.  So before, I took a look at your log snippets and I saw something quite interesting in the snippet related to the data dictioanry:

```
Missing log file(s) for thread 2, sequence(s) 64055 to 64056
```

So I noticed we did add `64055` and `64056` to the LogMiner session, but these were only for Thread 1 and not Thread 2 is likely why these errors happened in the first place.  The logs that were added for Thread 1 were specifically ONLINE redo logs while the others were ARCHIVE logs.  This leads me to think there may be an issue with the redo log gathering query when multiple threads are in-play.  I'll take a look.

**Comment by EthanZ328** [comment]
@Naros - I found that when we check if log switch occurs, we may misunderstand the sequence when there're more than one threads. It may cause many unnecessary logminer behaviors. I updated code accordingly. But I'm not sure if it is root cause of the Exception yet. Please check.

**Comment by Naros** [comment]
Hi @EthanZ328 so yes I agree that the comparison check can be faulty in an Oracle RAC situation where you have multiple redo threads unlike in a standalone environment.  I think a better solution however would be to adjust the actual underlying SQL inside `SqlUtils#currentRedoLogSequenceQuery`.  There instead you would apply something like `ORDER BY SEQUENCE#` and we can avoid the `Collections.sort()` call.  What do you think?

**Comment by EthanZ328** [comment]
@Naros - Make sense.

**Review by Naros — APPROVED** [review]
LGTM, thanks @EthanZ328

**Pull request merged**
