### PR TITLE
DBZ-1642 Support SQL Server Alwayson node

### PR DESCRIPTION
**Pull request by cobolbaby**
Ref: https://issues.redhat.com/browse/DBZ-1642

Perform a commit operation for compatibility with SQL Server read-only nodes

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Hi, thanks a lot, @cobolbaby! I'm a bit wary about any kind of commit, as the connectors should never _write_ anything, but only _read_ from the database. Could you give some background on why this is needed?  Thanks!

**Comment by jpechane** [comment]
@gunnarmorling It seems that when reading from read only replica the CDC metadata (max LSN) are not updated - only at point of starting the transaction. When I manage to setup a cluster I'll do deeper investigation - this is more of proff to verify the problem is solved.

**Comment by jpechane** [comment]
@gunnarmorling I've got SQL Server read-only running and I can confirm that the LSN is not updated without commits. I've found that reading from replaica always applies snapshot isolation which means that unless comit is executed Debezium sees the same values.

At the same time I am not a fan of unnecessary commits applied. @cobolbaby Could you please confirm whether you needed to set `database.applicationIntent=ReadOnly`? If yes then I propose to execute commits only when this config option is set. WDYT?

@cobolbaby Also could you please introduce method `commit` into `JdbcConnection` and call it?

**Comment by cobolbaby** [comment]
@jpechane In the master-slave mode, the slave database is usually read-only to ensure that the data will not be inconsistent due to user misoperation. So I'm pretty sure I need the configuration item.

**Comment by cobolbaby** [comment]
@jpechane 

> Also could you please introduce method commit into JdbcConnection and call it?

If I modify the code as follows, is that ok?

```JdbcConnection
public <T> T queryAndMap(String query, StatementFactory statementFactory, ResultSetMapper<T> mapper) throws SQLException {
        Objects.requireNonNull(mapper, "Mapper must be provided");
        Connection conn = connection();
        if (!conn.getAutoCommit()) {
            conn.commit();
        }
        try (Statement statement = statementFactory.createStatement(conn);) {
            if (LOGGER.isTraceEnabled()) {
                LOGGER.trace("running '{}'", query);
            }
            try (ResultSet resultSet = statement.executeQuery(query);) {
                return mapper.apply(resultSet);
            }
        }
    }
```

**Comment by jpechane** [comment]
@cobolbaby I am sorry for the confusion. I meant please create method called `commit()` in `JdbcConnection` class that will call commit on database connection so the call will look like `dataConnection.commit();`. It is probably about time to do it as we call commit this way in multiple places

**Comment by cobolbaby** [comment]
Please review the changes.

**Comment by gunnarmorling** [comment]
Is there a way we could mark this transaction as read-only?

**Comment by jpechane** [comment]
@gunnarmorling That's `database.applicationIntent=ReadOnly`. Without that the read-only replica will refuse to execute any commands.

**Comment by gunnarmorling** [comment]
@jpechane, ah, that's interesting. So can we somehow detect that we are connected to a secondary and then either

* pass that option automatically or
* fail if the user has not set it?

Also, commit() should be implemented as no-op then if ReadOnly is set?

**Comment by jpechane** [comment]
@gunnarmorling Please take a look at https://github.com/debezium/debezium/pull/1167#issuecomment-564521420

**Comment by gunnarmorling** [comment]
> Could you please confirm whether you needed to set database.applicationIntent=ReadOnly? If yes then I propose to execute commits only when this config option is set. WDYT?

Ok, that sounds good. So I'd suggest then to override `commit()` on `SqlServerConnection` so it's a no-op when that option is set.

Ideally, we set the option ourselves when detecting we're connected to a secondary. If that's not possible, it should be highlighted in the docs clearly, that this option must be set in this case.

@jpechane, @cobolbaby, does that make sense?

**Comment by jpechane** [comment]
Superseded with https://github.com/debezium/debezium/pull/1176

**Comment by gunnarmorling** [comment]
Closing in favour of #1176. Thanks, @cobolbaby!

**Pull request closed without merging**
