### PR TITLE
DBZ-3100 Vitess Connector supports Vitess 9.0.0

### PR DESCRIPTION
**Pull request by keweishang**
https://issues.redhat.com/browse/DBZ-3100

Related PRs:

- Vitess tutorial: https://github.com/debezium/debezium-examples/pull/156
- Compatibility matrix on the website: https://github.com/debezium/debezium.github.io/pull/639

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@keweishang, thx! Could you ping me here on the website PR once you deem it's good-to-go? Thx!

**Comment by keweishang** [comment]
@gunnarmorling sure, I'll ping you here once it's ready to be reviewed.

**Comment by keweishang** [comment]
The rendered page of the new section:
image

**Comment by keweishang** [comment]
@gunnarmorling it's ready to be reviewed.

**Review by gunnarmorling — APPROVED** [review]

**Pull request merged**
