### PR TITLE
DBZ-3157 Add event_serial_no to CloudEvent Id

### PR DESCRIPTION
**Pull request by vaosinbi**
https://issues.redhat.com/browse/DBZ-3157

Added `event_serial_no` to CloudEvents `Id` field for SQLServer to make it unique in case of the key field update of the source table.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, any objections?

**Comment by jpechane** [comment]
@vaosinbi LGTM, thanks! May I ask you for a test in the sql server module that will veiry the issue is solved?

**Comment by gunnarmorling** [comment]
@vaosinbi, could you add the suggested test? Thanks!

**Comment by gunnarmorling** [comment]
I've actually pushed a test myself, so to wrap up this one.

**Comment by gunnarmorling** [comment]
Rebased and applied. Thx, @vaosinbi!

**Comment by vaosinbi** [comment]
Thanks, @gunnarmorling

**Pull request closed without merging**
