### PR TITLE
DBZ-4245: Handle SQL Server connection errors during database state transition

### PR DESCRIPTION
**Pull request by morozov**
See [DBZ-4245](https://issues.redhat.com/browse/DBZ-4245).

Automated testing of this scenario is non-trivial but should be possible. Hence, marking this as a draft.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
I'm not too hung up on automating testing for this. If you could verify manually that the retry works in these failure situations, it's ok from my PoV. There is low (no?) risk in case this code change does not what it is supposed to do really.

**Comment by gunnarmorling** [comment]
Known intermittent test failure tracked via https://issues.redhat.com/browse/DBZ-3306

**Comment by morozov** [comment]
Yes, with this patch, it works as expected in both cases.

1. Default mode:
   ```
   org.apache.kafka.connect.errors.RetriableException: An exception occurred in the change event producer. This connector will be restarted.
   	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:38)
   	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:292)
   	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:59)
   	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:166)
   	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:127)
   	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
   	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   	at java.base/java.lang.Thread.run(Thread.java:829)
   Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Cannot open database "testDB" requested by the login. The login failed. ClientConnectionId:4e3f36ed-0e56-49f3-9640-e01a6636c686
   ```
2. Multi-partition mode:
   ```
   org.apache.kafka.connect.errors.RetriableException: An exception occurred in the change event producer. This connector will be restarted.
   	at io.debezium.pipeline.ErrorHandler.setProducerThrowable(ErrorHandler.java:38)
   	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:325)
   	at io.debezium.connector.sqlserver.SqlServerStreamingChangeEventSource.execute(SqlServerStreamingChangeEventSource.java:59)
   	at io.debezium.pipeline.ChangeEventSourceCoordinator.streamEvents(ChangeEventSourceCoordinator.java:216)
   	at io.debezium.pipeline.ChangeEventSourceCoordinator.lambda$start$0(ChangeEventSourceCoordinator.java:157)
   	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
   	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   	at java.base/java.lang.Thread.run(Thread.java:829)
   Caused by: com.microsoft.sqlserver.jdbc.SQLServerException: Database 'testDB' is in transition. Try the statement later.
   ```

**Comment by gunnarmorling** [comment]
Cool, thx. Applied.

**Pull request merged**
