### PR TITLE
DBZ-7508 Exit from readChunk after createDataEventsForTable if snapshot is not running anymore

### PR DESCRIPTION
**Pull request by mfvitale**
closes: https://issues.redhat.com/browse/DBZ-7508

### CODE REVIEW

**Comment by mfvitale** [comment]
Postgres test failures is not related. Fixed with https://github.com/debezium/debezium/pull/5303

**Comment by mfvitale** [comment]
All DB2 test are already marked as `flaky` but dunno why is still reported. @Naros Any idea?

**Comment by jpechane** [comment]
It seems that the workflow in core do not have flag `-Dfail.flaky.tests=false` set.

Also I completely forgot, the default value for Flaky test reattempt is just `1`. Maybe we should change it?

**Comment by jpechane** [comment]
@mfvitale Yes, please see `io.debezium.junit.ConditionalFail.ignoreFlakyFailure(Statement, Description, Flaky)`

**Review by rk3rn3r — APPROVED** [review]

**Comment by rk3rn3r** [comment]
Thx @mfvitale for the PR. I just hit the same error and found 3 issues (one of those is this DBZ-7508) in Jira and linked them and closed the duplicate. Thx for the fix.

**Comment by Naros** [comment]
Applied to main (=2.6).

**Pull request merged**
