### PR TITLE
DBZ-3822 Revert back pull_request_target changes

### PR DESCRIPTION
**Pull request by ani-sha**

### CODE REVIEW

**Comment by ani-sha** [comment]
@gunnarmorling I realized without the `checkout` action even the commit message check won't work. I didn't look inside the check step which was failing but showed success.
So we cannot have any comment action in any workflows which has a `checkout action`. Apologies for the unwanted noise. :disappointed:

**Comment by ani-sha** [comment]
@jpechane Do you happen to know the reason for this current failure?
```
fatal: ambiguous argument 'refs/remotes/origin/master..': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
```

**Comment by jpechane** [comment]
@ani-sha Maybe you run it on a rpeository with `main` not `master` branch?

**Comment by ani-sha** [comment]
@jpechane Well, this error message is from the commit message check workflow of this PR (https://github.com/debezium/debezium/runs/3617427167?check_suite_focus=true). I reverted the changes back to it as it was, as we won't be using `pull_request_target` rather trigger the action on normal `pull_request`.

**Comment by gunnarmorling** [comment]
@ani-sha, sorry, I had'nt paid enough attention when merging this. Couldn't you get the commits and their messages via REST and apply the check on them? As you do for the Octocat check?

**Comment by ani-sha** [comment]
@gunnarmorling This should work. Btw `DBZ-3822` was released yesterday, should I create another Jira issue for this?

**Comment by jpechane** [comment]
@ani-sha Where we stand with this PR now?

**Comment by ani-sha** [comment]
> @ani-sha Where we stand with this PR now?

@jpechane The work is done for the PR. Just a question re the issue key DBZ-3822 which already got released. So do I create a new issue for this?

**Comment by jpechane** [comment]
@ani-sha No need for new issue, albeit it was fromally released this is just CI stuff so the project itself is not affected. Thanks a lot!

**Pull request merged**
