### PR TITLE
Fixes some more tests around date handling in the MySQL connector

### PR DESCRIPTION
**Pull request by hchiorean**

### CODE REVIEW

**Comment by rhauch** [comment]
See my [discussion on Gitter](https://gitter.im/debezium/dev?at=579b4726ac80b5ea3f1636bf). I'm not convinced that what the connector is doing and what the test case is doing is correct.

**Comment by hchiorean** [comment]
ok I wasn't aware of the "actual" intent of the connector. 
However, IMO:
* if a connector can avoid dealing with TZs (meaning never send back `Date` objects but timestamps) it should do so
* the fact that dates are stored atm. in the DB using the servers TZ and always unmarshalled back in UTC is weird (to say the least) for the consumers

**Comment by rhauch** [comment]
> the fact that dates are stored atm. in the DB using the servers TZ

@hchiorean does MySQL server store the dates in the local time zone? That's not how I understand the SQL types that have no TZ information -- they're instants in time, so clients are responsible for interpreting them properly.

**Comment by hchiorean** [comment]
i've read the [MySQL docs](http://dev.mysql.com/doc/refman/5.7/en/time-zone-support.html) on this topic a couple of times and it's still a bit confusing to me. Still:
> The current session time zone setting affects display and storage of time values that are zone-sensitive. This includes the values displayed by functions such as NOW() or CURTIME(), and values stored in and retrieved from TIMESTAMP columns. Values for TIMESTAMP columns are converted from the current time zone to UTC for storage, and from UTC to the current time zone for retrieval.

>The current time zone setting does not affect values displayed by functions such as UTC_TIMESTAMP() or values in DATE, TIME, or DATETIME columns. Nor are values in those data types stored in UTC; the time zone applies for them only when converting from TIMESTAMP values. If you want locale-specific arithmetic for DATE, TIME, or DATETIME values, convert them to UTC, perform the arithmetic, and then convert back. 

So my understanding is that:
* `TIMESTAMP ` are stored in UTC but retrieved back in the current (JVM default TZ)
* `DATE`, `TIME`,  `DATETIME` are stored by the server "as-is", without any conversion which means that the JDBC driver when reading them back as `Date` instances will use the JVM default TZ

**Comment by rhauch** [comment]
@hchiorean hmm, okay. But let's not conflate what MySQL does versus what the MySQL binlog client does with the values it sees in the binlog.

**Comment by hchiorean** [comment]
that's a fair point, but from debugging this particular IT test, I can pretty safely say that the binlog connector gives back the `java.sql.Date` objects in the local TZ (with the value stored in the DB from the sql script).

So in the case of the test failure on my machine:
* the test stores `2014-09-08` as a `DATE` in the DB
* the binlog connector will read back a `java.sql.Date` instance with the above value, in my TZ which is UTC+3 at 00:00:00
* the DBZ TZ adapter converts this to UTC which is `2014-09-07-21:00:00` and truncates it to `2014-09-07-00:00:00`

This final value is obviously different than what the test expects (the original values). If instead of this TZ conversion the DBZ connector would always essentially convert whatever the binlog connector gives it to `Instant` instances, it would be far simpler IMO.

**Comment by rhauch** [comment]
Should we still merge this then, given [DBZ-91](https://issues.jboss.org/browse/DBZ-91). I guess we should merge this so that the build works, though I still want to run the test on my local machine just to make sure it still works for my TZ. If you're okay with it, I'll do that on Monday.

**Comment by hchiorean** [comment]
merging this will make the build pass with the current logic of the `TimeZoneAdapter`.
Whether we want a different behavior for `0.3` or just later on is another thing IMO and will require more extensive changes. So IMO it depends on what your plans are for `0.3`:
* if you want to do the rls now (soon) I'd say merge this and rls `0.3` with the same behavior OR
* don't merge this and `0.3` can be delayed until the entire behavior has changed

Also, I'm not sure how changing the schema from `Dates` to `longs` (or `Instant`) will affect backwards compatibility.

**Pull request merged**
