### PR TITLE
DBZ-3634 Enable DDL events to be filtered by include/exclude lists

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3634

So at the core this PR allows `DatabaseHistory.STORE_ONLY_CAPTURED_TABLES_DDL` to influence where the DDL predicate is placed in the LogMiner query.  If the setting is false, the behavior remains unchanged from the way the connector behaves now.  If the setting is true, the DDL events are predicated against the schema and table include/exclude lists.

In conjunction with this change, I took the opportunity to do a small refactor:

* All methods that relate to building the LogMiner query were moved to LogMinerQueryBuilder & removed from SqlUtils
* All tests related to LogMiner queries were moved to LogMinerQueryBuilderTest & removed from SqlUtilsTest
* The query was reworked have a slightly better SQL explain plan than before
*

### CODE REVIEW

**Comment by gunnarmorling** [comment]
> I took the opportunity to do a small refactor

Cool, thanks! Only one suggestion for next time: if possible, do a refactoring in a separate commit than the actual code change, making it a bit easier to view :)

**Review by gunnarmorling — COMMENTED** [review]
@Naros, could you point me to the place where the filtering actually happens? And the newly supported option needs adding to the connectors docs, too. Thx!

**Comment by Naros** [comment]
> Cool, thanks! Only one suggestion for next time: if possible, do a refactoring in a separate commit than the actual code change, making it a bit easier to view :) 

Fair enough, that's a good point.

> could you point me to the place where the filtering actually happens?

I'm assuming you mean [this](https://github.com/debezium/debezium/pull/2481/files#diff-6cff30eeb91eeda9a4d26441289fdef4a75e39e200dbcd43e7443a57232aa135R70-R82).

> And the newly supported option needs adding to the connectors docs, too. Thx!

Ah, yes, I'll add a commit this momentarily.

**Review by gunnarmorling — APPROVED** [review]

**Comment by gunnarmorling** [comment]
Applied. Thanks for the thorough explanation of the change over chat, @Naros 🙏 !

**Pull request merged**
