### PR TITLE
DBZ-3632 Pulling up getJdbcConfig() to RelationalDatabaseConnectorConfig

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-3632

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, @jpechane, could either one of you review and merge this PR? It's a prerequisite for https://github.com/debezium/debezium-connector-db2/pull/25. Thx!

**Comment by jpechane** [comment]
@gunnarmorling There are some formatting issues.

**Review by jpechane — APPROVED** [review]
@gunnarmorling Feel free to merge it yourself after fixing the formatting issues

**Comment by gunnarmorling** [comment]
Reworked, merging. Thx, @jpechane!

**Pull request merged**
