### PR TITLE
DBZ-2456 Selective Snapshot mechanism for Postgres

### PR DESCRIPTION
**Pull request by KaushikIyer16**
https://issues.redhat.com/browse/DBZ-2456

Allow for a selective snapshot mechanism to better manage connectors and their life-cycle. I am proposing a snapshot mechanism that is **SELECTIVE** in nature. The tables to be snapshotted are specified in the config with the key:

    "snapshot.selective.tables": "public.tableA,public.tableB"

and the snapshot.mode to be set to **selective**. So Effectively only the subset of tables specified in the above configuration are considered for snapshots and are locked, post which streaming resumes.

### CODE REVIEW

**Comment by KaushikIyer16** [comment]
HI @jpechane and @gunnarmorling, just wanted to comment here to get your opinion on this feature request. would love to hear your feedback. Do let me know if there is a better way to achieve this.

**Comment by jpechane** [comment]
@KaushikIyer16 Hi, the functionality looks good for me. I'd let @gunnarmorling to decide if he is fine with adding another option.
If yes then I'd recommend to add it to the `io.debezium.pipeline.source.AbstractSnapshotChangeEventSource` so all connectors would benefit from it.

**Comment by gunnarmorling** [comment]
Hey @KaushikIyer16, thanks for this contribution!

In general, I'm positive about adding the capability to snapshot only a subset of tables in the include list. I think it should be implemented somewhat differently, though. In particular, I don't think a new snapshot mode is needed. Rather, any existing snapshot mode should honour that new "snapshot.tables" setting. Indeed `AbstractSnapshotChangeEventSource` would then be the right place for implementing this (or perhaps `RelationalSnapshotChangeEventSource.determineCapturedTables()`).

Not we plan to rework the entire snapshotting routine more holistically later this year, but I think a change as described above wouldn't be in conflict with that. Do you think you could update this PR along these lines?

**Comment by KaushikIyer16** [comment]
Hi @gunnarmorling , @jpechane. Thank you so much for the feedback. Yes, sure I will update the PR along these lines and update here.

**Pull request closed without merging**
