### PR TITLE
Move DB name logging support from SQL Server into core

### PR DESCRIPTION
**Pull request by vjuranek**
https://issues.redhat.com/browse/DBZ-5042

### CODE REVIEW

**Comment by Naros** [comment]
@vjuranek is this one ready for review or is there anymore work needed here?

**Comment by vjuranek** [comment]
@Naros it should be ready.

**Comment by vjuranek** [comment]
Thanks for noticing it @Naros ! I completely missed it. 

Now I found out that oracle connector is by default not included and one has to activate `oracle` profile, otherwise Idea ignores whole module in class search.

**Comment by Naros** [comment]
Hi, @vjuranek that's correct, it's still an opt-in connector.  We should probably consider changing that in 2.0; I'll add a todo for that.

**Comment by Naros** [comment]
Hi @vjuranek I pushed one small commit to favor PDB name when set rather than the CDB name.  When CI passes, I'll merge.

**Review by Naros — APPROVED** [review]

**Pull request merged**
