### PR TITLE
DBZ-6236 Reset ErrorHandler retry counter on successful poll

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-6236

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros The test failures are related to the change.

**Review by jpechane — APPROVED** [review]
@Naros LGTM, thanks! Please feel free to merge yourself when CI is finished.

**Comment by Naros** [comment]
Test failures:
MariaDB - Unrelated
PostgeSQL - Unrelated, failures fixed in other PRs
SQL Server - Needs a re-run, may or may not be related
Db2 - Unrelated, failures fixed in Db2
Informix - Unrelated

**Comment by Naros** [comment]
Going to rebase against `main` once more and test out @mfvitale fix for https://github.com/debezium/debezium/pull/5310 as I seem to hit this problem repeatedly.

**Pull request merged**
