### PR TITLE
Updated tutorial.adoc

### PR DESCRIPTION
**Pull request by navdeep710**
Changed name of the terminal output to check out kafka connect service output.

### CODE REVIEW

**Comment by Naros** [comment]
@navdeep710 That's for the PR.

@gunnarmorling @jpechane I propose before merging this we define a 0.10 branch so that we can also align that release stream's documentation the same way.  The development_docs branch will be used for 1.0 after this week's release.

I also believe we need to cherry-pick https://github.com/debezium/debezium/commit/3e57d8e15f9998fd1b30c7d90d33ec44ac86303f back to the 0.9 and soon to be 0.10 branches so that we don't run into Travis CI problems since they've migrated us to Xenial.

**Comment by gunnarmorling** [comment]
> @gunnarmorling @jpechane I propose before merging this we define a 0.10 branch so that we can also align that release stream's documentation the same way.

+1. Go for it.

**Comment by jpechane** [comment]
@Naros I must admit I am little bit confused now. What's difference between his file and https://github.com/debezium/debezium.github.io/blob/develop/docs/tutorial.asciidoc ?

**Comment by Naros** [comment]
@jpechane First and foremost, the contents in the `debezium.github.io` repository under `/docs/` are pages which will be removed as a part of [DBZ-1466](https://issues.jboss.org/browse/DBZ-1466).  The tutorial was migrated to Antora and now resides in the `debezium` repository where we maintain it per version.

**Comment by gunnarmorling** [comment]
> First and foremost, the contents in the debezium.github.io repository under /docs/ are pages which will be removed as a part of DBZ-1466.

@Naros, could we do this right now? I was suprised to see the files still there, and it seems confusing. WDYT?

> That said the user has submitted a PR for only one of the 3 versions of the tutorial. This change should really be applied to all IMO.

I wouldn't bother updating 0.9 at this point. What we might consider is backporting the fix to 0.10 as it's the current stable release. Also the 0.9 version should be hidden by default on the releases and documentation pages (similar to Hibernate, where you can do "Show older versions").

Could you do this, @Naros?

**Comment by Naros** [comment]
@gunnarmorling Yep, I'll take care of this now.  I believe the cherry-pick maintains the author so I'll just cherry-pick this to 0.10 and master and close this.

**Comment by gunnarmorling** [comment]
+1 Sounds good!

>

**Comment by Naros** [comment]
Thanks for the PR @navdeep710.  I applied this to the `0.10` and `master` branches.

**Pull request closed without merging**
