### PR TITLE
DBZ-3371: Adjust scale of fallback BigDecimal values to match column schema

### PR DESCRIPTION
**Pull request by C0urante**
https://issues.redhat.com/browse/DBZ-3371

### CODE REVIEW

**Comment by C0urante** [comment]
@jpechane does this look alright to you?

**Comment by gunnarmorling** [comment]
Test failures are unrelated, the change LGTM. It'd be nice if we could do the scale adjustment _only_ if the fallback value actually is needed, but that'd require some larger re-work. Leaving it to @jpechane to take another look and merge. Thanks, @C0urante!

**Review by gunnarmorling — APPROVED** [review]

**Comment by jpechane** [comment]
Applied, thanks @C0urante !

**Comment by C0urante** [comment]
Thanks guys!

**Pull request merged**
