### PR TITLE
DBZ-2415 Added support for MySql dynamic privileges

### PR DESCRIPTION
**Pull request by rgibaiev**
Dynamic privileges + CREATE ROLE / DROP ROLE static privileges

https://issues.jboss.org/browse/DBZ-2413
https://issues.jboss.org/browse/DBZ-2415

### CODE REVIEW

**Comment by keweishang** [comment]
LGTM 👍

**Comment by gunnarmorling** [comment]
Thanks for reviewing, @keweishang!

**Comment by jpechane** [comment]
@rgibaiev Hi, I think this is mostly correct. I see one problem though and that's `ROLE`. I've just verified that `ROLE` can be used as column name even in MySQL 8. Please check `keywordsCanBeId` parser rule to solve this sitution.
It also necessary to verify if the same needs to be done for the privileges names intorduced.

**Comment by rgibaiev** [comment]
@jpechane, please review now

**Comment by jpechane** [comment]
@rgibaiev Applied, thanks!

**Comment by jpechane** [comment]
@rgibaiev Would it now be possible for you to prepare a PR for the upstream project?

**Pull request merged**
