### PR TITLE
DBZ-1034 Support tsrange column type on Postgres

### PR DESCRIPTION
**Pull request by sciamp-dev**
https://issues.jboss.org/browse/DBZ-1034

### CODE REVIEW

**Comment by jpechane** [comment]
@sciamp-dev Hi, thanks a lot, it looks good! I'd like to ask for two changes if possible.

Add test for tsrange array - it is missing even for tstzrange so if you could add both it would be great.
Extaend the scope of PR and add support for `daterange` too. Thus we would have all time related ranges supported and can create a follow up issue the would cover number rnages.

**Comment by sciamp-dev** [comment]
Hi @jpechane , sure no problem. I'll add it asap.

**Comment by gunnarmorling** [comment]
Hey @sciamp-dev, are you still planning to add the support/test for the array types as discussed above?

**Comment by sciamp-dev** [comment]
@gunnarmorling yes! I should finish by tomorrow

**Comment by gunnarmorling** [comment]
Hey @sciamp-dev, LGTM overall. Can you just rebase it one more time (there are conflicts with master atm.), squash everything into one commit and prefix its message with "DBZ-1034..."? Then it should be good to go. Thanks a lot!

**Comment by sciamp-dev** [comment]
I had some problems while rebasing, but it should be good now @gunnarmorling .
Sure, I'll prepare a PR for the docs repo

**Comment by gunnarmorling** [comment]
Rebased once more and applied. Thanks a lot, @sciamp-dev!

**Pull request closed without merging**
