### PR TITLE
DBZ-3067 Add OR REPLACE condition for create index

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-3067

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, any idea why the log on CI would be truncated?

**Comment by gunnarmorling** [comment]
Test failure is unrelated.

**Review by gunnarmorling — APPROVED** [review]
LGTM, merging.

**Comment by gunnarmorling** [comment]
@jpechane, do we push MariaDB fixes back upstream to Antlr, too?

**Comment by jpechane** [comment]
@gunnarmorling Usually no

**Pull request merged**
