### PR TITLE
Fix Value

### PR DESCRIPTION
**Pull request by abergmeier**
Fix all errors reported by ErrorProne.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Nice findings, thanks.

Could you please file an issue in our [JIRA tracker](https://issues.jboss.org/browse/DBZ) and reference its number in the commit message? And could you also add the commit author's e-mail to your GitHub account, so your commits will be [properly linked](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) to your user? Thanks again!

**Comment by abergmeier** [comment]
> And could you also add the commit author's e-mail to your GitHub account, so your commits will be properly linked to your user?

Done.

**Comment by abergmeier** [comment]
> Could you please file an issue in our JIRA tracker and reference its number in the commit message?

Done and Done

**Comment by abergmeier** [comment]
IMO these need tests.

**Comment by gunnarmorling** [comment]
Applied, also added a unit test for the two affected methods. Thanks!

**Pull request closed without merging**
