### PR TITLE
Remove deprecated connector config fields

### PR DESCRIPTION
**Pull request by vjuranek**
The first part of https://issues.redhat.com/browse/DBZ-5045

### CODE REVIEW

**Comment by vjuranek** [comment]
DB2 tests should work once [debezium-connector-db2 PR #55](https://github.com/debezium/debezium-connector-db2/pull/55) is merged.

**Comment by jpechane** [comment]
@vjuranek LGTM. The `grep -ir` of string `deprecated` found few more instances in the code and docs. Could you please doublecheck it?

**Comment by vjuranek** [comment]
Thanks for the review @jpechane , you are right, found two more options in Mongo DB (removed), one obsolete option value and one more deprecated value in Oracle DB (not removed yet, not sure if it can be removed - discussing it with @Naros first).

Rest of the deprecated code are mostly methods - should they be removed as well as part of this issue?
Another part is deprecated JXM metrics - these are handled in PR #3571.

Fix for DB2 is [here](https://github.com/debezium/debezium-connector-db2/pull/55), for Cassandra [here](https://github.com/debezium/debezium-connector-cassandra/pull/58). I didn't find any other deprecated config options.

**Comment by jpechane** [comment]
@vjuranek Nice cleanup!

**Pull request merged**
