### PR TITLE
DBZ-4077 Configurable TX topic name prefix

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-4077

Supersedes #2764.

@jpechane, amended the original PR (which was ok overall); can you take another look and merge?

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, reworked as discussed. Can you take a look and hopefully merge?

@abhishekkh, we discussed this some more and realized that instead of solely giving a prefix, the full name should be customizeable. The placeholder `${database.server.name}` can be used for referring to the connector's logical name, with the default value for the new option being `${database.server.name}.transaction`, i.e. the default value is the same as it was before. We'll apply similar changes to other special topic names (heartbeats, etc.) for Debezium 2.0.

**Comment by gunnarmorling** [comment]
Hum, hum; for some reason this does build the Cassandra repo from the main branch and not DBZ-4077, as it should. Will log an issue for this.

**Comment by gunnarmorling** [comment]
@jpechane, this should be good now. The build issue is tracked via https://issues.redhat.com/browse/DBZ-4228.

**Comment by jpechane** [comment]
@gunnarmorling @abhishekkh Applied, thanks!

**Pull request merged**
