### PR TITLE
Initial Bazel compilation

### PR DESCRIPTION
**Pull request by abergmeier**
For now only compiles debezium-core.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Interesting; how would I run this then to reproduce the reports you came up with? And is there something like the Gradle/Maven wrapper, or would I have to install Bazel separately.

We're quite happy with Maven as is, but nevertheless that's an interesting experiment, esp. I'm curious about build times with Bazel. So I'd be interested to try this out myself.

**Comment by abergmeier** [comment]
> Interesting; how would I run this then to reproduce the reports you came up with?

`bazel test //... --test_output=errors`

> And is there something like the Gradle/Maven wrapper, or would I have to install Bazel separately.

You have to install the bazel binary.

> I'm curious about build times with Bazel.

Since Bazel supports multiple layers of caching you can crank down build times to an absolute minimum if you want. Am happy to tell you all about that 😀 .

**Comment by jpechane** [comment]
ErrorProne supports Maven - see https://errorprone.info/docs/installation maybe it is our best bet for the integration.
Also we might put it into persepctive together with https://issues.jboss.org/browse/DBZ-358

**Comment by gunnarmorling** [comment]
Ah, very nice with the Maven support. Agreeing with @jpechane that it's this we should pursue for now (personally, I'm quite interested in Bazel but it's not something we should change easily, so let's keep that for another time).

So perhaps you could send another PR for adding a Maven profile which adds the ErrorProne plug-in and attribute it to [DBZ-358](https://issues.jboss.org/browse/DBZ-358)? We also can add FindBugs in that profile, if we still see the need for it in addition to ErrorProne.

Thanks!

**Comment by abergmeier** [comment]
> So perhaps you could send another PR for adding a Maven profile which adds the ErrorProne plug-in and attribute it to DBZ-358?

Sorry, I am not a Maven expert. I think this should be done by someone who actually knows what to do and why.

Do you nevertheless want to pull Bazel support (in parallel to Maven) or should I keep that in my fork?

**Comment by gunnarmorling** [comment]
> I think this should be done by someone who actually knows what to do and
why.

Sure, no problem.

> Do you nevertheless want to pull Bazel support (in parallel to Maven) or
should I keep that in my fork?

For the time being I'd prefer to not add any Bazel configuration to
Debezium itself.

**Pull request closed without merging**
