### PR TITLE
DBZ-4060 Update PgJDBC to 42.2.22 to fix cloud provider connection issues

### PR DESCRIPTION
**Pull request by judahrand**
See #2743 for initial implementation which went all the way to 42.2.24

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ani-sha, so something still seems off with the alias check. The change has been done as part of the PR (see last commit), still the bot appended that message 🤔 .

**Comment by gunnarmorling** [comment]
@judahrand, ok, I think this looks good from what I've understood about that issue so far. Let's see whether CI likes it too :)

**Comment by judahrand** [comment]
> @judahrand, ok, I think this looks good from what I've understood about that issue so far. Let's see whether CI likes it too :)

I'm really hoping! 🤣 Coding without running code is hard! Need to get my setup sorted out. I think there's something in the Postgres x86 Docker image which doesn't like running on an M1 Mac using emulation. It just... sort of hangs - not only with Debezium.

**Comment by ani-sha** [comment]
> so something still seems off with the alias check. The change has been done as part of the PR (see last commit), still the bot appended that message thinking.

@gunnarmorling So, the action was triggered when the PR was `opened`. And the comparison is done for `COPYRIGHT.txt` and `Aliases.txt` with `debezium@master`, not this PR branch. Hence this bot comment popped up. And we decided the reviewers would be adding the names.

**Comment by gunnarmorling** [comment]
@ani-sha, ah yes, I see. And we need to compare with master due to the trigger permission issue, right. Ok, I think that's fine then, as most of the times folks wouldn't do the required changes (unlike at the PR at hand, where @judahrand was aware of this due to the earlier way of how that messages was phrased). Thanks for clarifying, that all makes sense!

**Comment by judahrand** [comment]
Anyone familiar with this error?
```
2021-10-01T08:04:47.3063249Z 08:04:47.304 postgres2021-10-01 08:04:47.304 GMT [3828] STATEMENT:  DROP PUBLICATION dbz_publication
2021-10-01T08:04:47.3066455Z 2021-10-01 08:04:47,305 INFO   PostgresConnectorIT||test  Connection gracefully closed   [io.debezium.jdbc.JdbcConnection]
2021-10-01T08:04:47.3299795Z 2021-10-01 08:04:47,306 DEBUG  PostgresConnectorIT||test  Error while dropping publication: 'dbz_publication'   [io.debezium.connector.postgresql.TestHelper]
2021-10-01T08:04:47.3301846Z java.lang.RuntimeException: org.postgresql.util.PSQLException: ERROR: publication "dbz_publication" does not exist
2021-10-01T08:04:47.3303564Z 	at io.debezium.connector.postgresql.TestHelper.execute(TestHelper.java:169)
2021-10-01T08:04:47.3305442Z 	at io.debezium.connector.postgresql.TestHelper.dropPublication(TestHelper.java:311)
2021-10-01T08:04:47.3307290Z 	at io.debezium.connector.postgresql.TestHelper.dropPublication(TestHelper.java:305)
2021-10-01T08:04:47.3309175Z 	at io.debezium.connector.postgresql.PostgresConnectorIT.after(PostgresConnectorIT.java:133)
2021-10-01T08:04:47.3311321Z 	at jdk.internal.reflect.GeneratedMethodAccessor11.invoke(Unknown Source)
2021-10-01T08:04:47.3313545Z 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
2021-10-01T08:04:47.3315657Z 	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
2021-10-01T08:04:47.3316989Z 	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:59)
2021-10-01T08:04:47.3318749Z 	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
2021-10-01T08:04:47.3323482Z 	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:56)
2021-10-01T08:04:47.3325428Z 	at org.junit.internal.runners.statements.RunAfters.invokeMethod(RunAfters.java:46)
2021-10-01T08:04:47.3327566Z 	at org.junit.internal.runners.statements.RunAfters.evaluate(RunAfters.java:33)
2021-10-01T08:04:47.3328820Z 	at org.junit.rules.TestWatcher$1.evaluate(TestWatcher.java:61)
2021-10-01T08:04:47.3329731Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-10-01T08:04:47.3330903Z 	at org.junit.runners.BlockJUnit4ClassRunner$1.evaluate(BlockJUnit4ClassRunner.java:100)
2021-10-01T08:04:47.3332355Z 	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:366)
2021-10-01T08:04:47.3333905Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:103)
2021-10-01T08:04:47.3335599Z 	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:63)
2021-10-01T08:04:47.3336890Z 	at org.junit.runners.ParentRunner$4.run(ParentRunner.java:331)
2021-10-01T08:04:47.3338187Z 	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:79)
2021-10-01T08:04:47.3339314Z 	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:329)
2021-10-01T08:04:47.3340478Z 	at org.junit.runners.ParentRunner.access$100(ParentRunner.java:66)
2021-10-01T08:04:47.3341532Z 	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:293)
2021-10-01T08:04:47.3343094Z 	at org.junit.internal.runners.statements.RunBefores.evaluate(RunBefores.java:26)
2021-10-01T08:04:47.3345183Z 	at org.junit.runners.ParentRunner$3.evaluate(ParentRunner.java:306)
2021-10-01T08:04:47.3346277Z 	at org.junit.runners.ParentRunner.run(ParentRunner.java:413)
2021-10-01T08:04:47.3348251Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:365)
2021-10-01T08:04:47.3350598Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:273)
2021-10-01T08:04:47.3352760Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
2021-10-01T08:04:47.3354919Z 	at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:159)
2021-10-01T08:04:47.3358069Z 	at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:377)
2021-10-01T08:04:47.3360607Z 	at org.apache.maven.surefire.booter.ForkedBooter.execute(ForkedBooter.java:138)
2021-10-01T08:04:47.3362901Z 	at org.apache.maven.surefire.booter.ForkedBooter.run(ForkedBooter.java:465)
2021-10-01T08:04:47.3364565Z 	at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:451)
2021-10-01T08:04:47.3365886Z Caused by: org.postgresql.util.PSQLException: ERROR: publication "dbz_publication" does not exist
2021-10-01T08:04:47.3367668Z 	at org.postgresql.core.v3.QueryExecutorImpl.receiveErrorResponse(QueryExecutorImpl.java:2552)
2021-10-01T08:04:47.3370722Z 	at org.postgresql.core.v3.QueryExecutorImpl.processResults(QueryExecutorImpl.java:2284)
2021-10-01T08:04:47.3373251Z 	at org.postgresql.core.v3.QueryExecutorImpl.execute(QueryExecutorImpl.java:322)
2021-10-01T08:04:47.3375025Z 	at org.postgresql.jdbc.PgStatement.executeInternal(PgStatement.java:481)
2021-10-01T08:04:47.3376372Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:401)
2021-10-01T08:04:47.3377703Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:322)
2021-10-01T08:04:47.3379582Z 	at org.postgresql.jdbc.PgStatement.executeCachedSql(PgStatement.java:308)
2021-10-01T08:04:47.3381092Z 	at org.postgresql.jdbc.PgStatement.executeWithFlags(PgStatement.java:284)
2021-10-01T08:04:47.3382918Z 	at org.postgresql.jdbc.PgStatement.execute(PgStatement.java:279)
2021-10-01T08:04:47.3384571Z 	at io.debezium.jdbc.JdbcConnection.executeWithoutCommitting(JdbcConnection.java:1392)
2021-10-01T08:04:47.3386571Z 	at io.debezium.connector.postgresql.TestHelper.execute(TestHelper.java:156)
2021-10-01T08:04:47.3387480Z 	... 33 more
2021-10-01T08:04:47.3388927Z 2021-10-01 08:04:47,306 INFO   PostgresConnectorIT||test  Stopping the connector   [io.debezium.connector.postgresql.PostgresConnectorIT]
2021-10-01T08:04:47.3395235Z 2021-10-01 08:04:47,307 INFO   PostgresConnectorIT||test  Test io.debezium.connector.postgresql.PostgresConnectorIT#shouldNotStartWithInvalidConfiguration succeeded   [io.debezium.connector.postgresql.PostgresConnectorIT]
2021-10-01T08:04:47.3398765Z [ERROR] Tests run: 66, Failures: 1, Errors: 0, Skipped: 2, Time elapsed: 136.176 s <<< FAILURE! - in io.debezium.connector.postgresql.PostgresConnectorIT
2021-10-01T08:04:47.3402859Z [ERROR] io.debezium.connector.postgresql.PostgresConnectorIT.shouldCreatePublicationWhenReplicationSlotExists  Time elapsed: 1.876 s  <<< FAILURE!
2021-10-01T08:04:47.3405863Z java.lang.AssertionError
2021-10-01T08:04:47.3408729Z 	at io.debezium.connector.postgresql.PostgresConnectorIT.shouldCreatePublicationWhenReplicationSlotExists(PostgresConnectorIT.java:2314)
```

**Comment by gunnarmorling** [comment]
> Anyone familiar with this error?

I saw it yesterday actually. Not sure whether it's a flaky test or also related to that upgrade. @jpechane, does it ring a bell for you?

**Comment by jpechane** [comment]
I've just checked the code. This is obvious timing issue. The JMX streaming flag is set before the publication is created and test runs in parallel so it can happen that the publication is not created at time of checking.

**Comment by jpechane** [comment]
Will push a commit a in couple of mins.

**Comment by judahrand** [comment]
Thank you! Looks like this might be the one!

**Comment by jpechane** [comment]
@judahrand And applied, great job. Thanks a lot for all the effort!

**Comment by gunnarmorling** [comment]
Woot, woot! Thanks a lot, @judahrand for the quick turn-around, great collaboration!

**Pull request merged**
