### PR TITLE
DBZ-1122 Fixed a NPE in FileDatabaseHistory.

### PR DESCRIPTION
**Pull request by tomazlemos**
Guarding against a NPE that has happened to me. As it´s my first PR (in life, actually...), please feel free to let me know about anything that I may have done wrong, or not in the appropriate way.

Thanks for the awesome work!

### CODE REVIEW

**Comment by jpechane** [comment]
@tomazlemos I've restarted the CI and build has passed.

**Comment by tomazlemos** [comment]
@jpechane, great! Thanks, hope it’s a helpful albeit tiny PR :-) If I come across anything else I’ll let you know, and thanks again for the awesome work!

**Comment by gunnarmorling** [comment]
Thanks a lot, @tomazlemos! Could you only rework the commit to use an email which is linked to your Github account? That way it will be [properly attributed](https://help.github.com/articles/why-are-my-contributions-not-showing-up-on-my-profile/) to you in the history. Thanks again!

**Comment by gunnarmorling** [comment]
Rebased and applied. Thanks a lot, @tomazlemos!

**Comment by tomazlemos** [comment]
Thanks @gunnarmorling! I couldn’t answer yesterday, it’s probably too late to rework the commit? Either way I’m very happy I could contribute a little bit to this awesome project!

**Comment by gunnarmorling** [comment]
Hi, yeah, no worries, I went ahead and merged it. All is good, this will be
part of the upcoming 0.9.1 release. Thanks a lot again!

>

**Pull request closed without merging**
