### PR TITLE
DBZ-3566: Refactor test-support code to be more extendable

### PR DESCRIPTION
**Pull request by jcechace**
https://issues.redhat.com/browse/DBZ-3566

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, can we get this one in for CR1?

**Comment by jcechace** [comment]
> @jpechane, can we get this one in for CR1?

It's not necessary to have this in CR1... tests are taken from the community (usually master branch) anyway regardless of what is in the build.

**Comment by gunnarmorling** [comment]
@jcechace, yes, understood. Would still be nice to get merged what we can get merged :)

**Comment by jpechane** [comment]
@jcechace Applied, thanks.

**Pull request merged**
