### PR TITLE
Fix Quarkus extension in the 1.2 branch

### PR DESCRIPTION
**Pull request by gsmet**
I confirm that just backporting these 2 commits fixes the issue we have with Quarkus master + the Debezium Outbox extension.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Thanks a lot for doing the backport, @gsmet!

Hey @jpechane, WDYT about spinning another 1.2.x release with this fix? Quarkus folks could use this to address an issue around the outbox extension. I'd suggest we do it together with 1.3.0.Beta2 next week, maybe some more bug fixes relevant for downstream pile up until then. Effort should be minimal, no announcement etc. for 1.2.x needed.

**Comment by jpechane** [comment]
@gunnarmorling Fine for me. @gsmet I am sorry for not doing it myself, I totally forgot about Quarkus having dependency on stable Debezium :-(

**Comment by gsmet** [comment]
No worries, we just spotted the config issue very recently and that's what triggered the backport!

Considering our schedule, we would need the release before September 10th to be on the safe side so I think it works with your schedule.

**Comment by gunnarmorling** [comment]
>  we would need the release before September 10th

Ok, cool. We aim for a release early next week, so this should work. I'm just going to add a true end-to-end test while we're at this, then this should be good to go.

**Comment by gsmet** [comment]
@Naros just a heads up that this one will need some merging too before the 1.2 release :).

**Comment by gunnarmorling** [comment]
Cherry-picked the two additional commits for more extensive testing.

@jpechane, something is wrong with the commit message check, it picks up unrelated release commits which don't conform to the expected pattern. Logged https://issues.redhat.com/browse/DBZ-2479 for that.

Will merge this PR, things build and tests pass locally.

**Comment by gunnarmorling** [comment]
Thanks for the backport, @gsmet! I see it's your first contribution to DBZ, yeah. Looking forward to more :)

**Comment by gsmet** [comment]
Don't hold your breath :).

Thanks all for being so supportive on this one. Please ping me when 1.2.3.Final is released, I'll deal with the Quarkus update!

**Pull request merged**
