### PR TITLE
DBZ-4663 Remove option for specifying driver class from MySQL Connector

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-4663

### CODE REVIEW

**Review by Naros — APPROVED** [review]
I do not see that `database.jdbc.driver` is referenced in the documentation anywhere, so this LGTM.  Thanks @harveyyue!

**Comment by Naros** [comment]
Applied to `main` (=2.2).

**Comment by rk3rn3r** [comment]
Awesome! Thx a lot @harveyyue!

**Review by som-design — COMMENTED** [review]
debezium-connector-mysql/src/test/java/io/debezium/connector/mysql/MySqlConnectorTest.java

**Comment by gnought** [comment]
@Naros @harveyyue could we revert the change to keep the `database.jdbc.driver` option or provide another way to let users specify other JDBC drivers?
We are using v1.6.4 in production that requires a AWS JDBC driver https://github.com/awslabs/aws-mysql-jdbc for IAM authentication connection.

**Comment by jpechane** [comment]
@gnought Thanks for raising this up! We need to revert it ifn that case.

One question, do you know if the same functionality might be needed for other connectors?

**Comment by jpechane** [comment]
@gnought Reverting via https://github.com/debezium/debezium/pull/4247

**Comment by gnought** [comment]
@jpechane perfect! Thanks.

**Pull request merged**
