### PR TITLE
DBZ-1452 New and deprecated options on event flattening SMT

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-1452

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Supersedes #1231.

**Comment by gunnarmorling** [comment]
@Naros, @jpechane, could either of you review and merge this one, so we can include it in tomorrow's Beta2 release? Thanks!

**Comment by Naros** [comment]
Other than the nit-pick typo I saw, this LGTM.  Once it passes CI again I'll merge.

**Comment by gunnarmorling** [comment]
The unrelated test failure has already been addressed on master.

**Comment by Naros** [comment]
@gunnarmorling, awesome merging then.

**Pull request merged**
