### PR TITLE
DBZ-5327 Smart Backfills

### PR DESCRIPTION
**Pull request by vivekwassan**
https://issues.redhat.com/browse/DBZ-5327

### CODE REVIEW

**Comment by vivekwassan** [comment]
@jpechane I have done the changes from my end. I am unsure why integration test is failing 👇 just for DB2 (I do not have working experience with DB2 😇 )

Screen Shot 2022-07-11 at 6 18 29 PM

I have tried multiple times on local, it passes 👇 

Screen Shot 2022-07-11 at 6 17 50 PM

😕 Could you help?

**Comment by jpechane** [comment]
@vivekwassan It is probably only a timing issue. The PR looks good to me, thanks! Could you please just add the new feature to the docs?

**Comment by vivekwassan** [comment]
> @vivekwassan It is probably only a timing issue. The PR looks good to me, thanks! Could you please just add the new feature to the docs?

@jpechane 👋 Added documentation [here](https://github.com/debezium/debezium/pull/3699/commits/d849d11f4e99321e0c8e36044c9fd9d622916754).

**Comment by vivekwassan** [comment]
@jpechane FYI I am testing an edge case there are multiple consecutive backfill signals. I believe there has to be a 1:1 mapping between `additional-condition` and `data-collection`, else `additional-condition` may leak.
I am basically talking about [additional-condition is being stored in connector offsets atm](https://github.com/debezium/debezium/blob/4b9da5e2790b1959e2a04156ab314ae10e7b61ab/debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java#L165) (may have to change the implementation a bit).
I'll update once I complete the testing.

**Comment by vivekwassan** [comment]
> @vivekwassan Thanks fro head-up, I'll wait with merge then.

@jpechane 👋 Hello again! 😄

#### Updates:
-  Added a 1:1 mapping between the `data-collection` and `additional-condition` [here](https://github.com/debezium/debezium/pull/3699/commits/7e15a79ee27136a386fe9c7d2eb1eebc28de35b4). Tested it successfully with consecutive incremental snapshots, no leakage. 

- The above change introduces a breaking change, as it changes how `incremental_snapshot_collections` is [now stored in the connector offsets](https://github.com/debezium/debezium/blob/c3b036d0dd4456ec01e266749e6e56de3ccb6e97/debezium-core/src/main/java/io/debezium/pipeline/source/snapshot/incremental/AbstractIncrementalSnapshotContext.java#L158-L175). 

- The breaking change should not be an issue if debezium upgrade is done after any running incremental snapshot finishes. I wanted to add this information to the release notes. As the [original issue](https://issues.redhat.com/browse/DBZ-5327) is tagged with `2.0.0.Beta1`, I could not found any CHANGELOG for this release (although I was able to found CHANGELOG page for [2.0.0.Alpha3](https://github.com/debezium/debezium/blob/main/CHANGELOG.md#200alpha3)). If you could please point me to the correct place, I'll add this information there. 

- Since the `dataCollectionsToSnapshot` also affects the stop snapshot signal, made required changes [here](https://github.com/debezium/debezium/pull/3699/commits/c3b036d0dd4456ec01e266749e6e56de3ccb6e97). 
One thing I'd like to highlight here, I didn't add `additional-condition` to the stop signal. So, in case there are multiple incremental snapshots with different `additional-condition`s, the stop signal for a specific `data-collection` will kill all the incremental snapshots signals for that `data-collection`.

**Comment by Naros** [comment]
Hi @vivekwassan can you rebase this against the latest changes from `main`?

**Comment by vivekwassan** [comment]
> Hi @vivekwassan can you rebase this against the latest changes from `main`?

Rebase from `main` done.

Regarding the CI failures, the individual tests do pass on local 😕 

**Mongo**: 

Error:  Failures: 
Error:    IncrementalSnapshotIT.updates:435->consumeMixedWithIncrementalSnapshot:322->consumeMixedWithIncrementalSnapshot:270->consumeMixedWithIncrementalSnapshot:289 [Too many no data record results, 1000 < 1000] actual value:<4> should be less than or equal to:<3>
Error:    IncrementalSnapshotIT.updatesLargeChunk:490->consumeMixedWithIncrementalSnapshot:322->consumeMixedWithIncrementalSnapshot:270->consumeMixedWithIncrementalSnapshot:289 [Too many no data record results, 1000 < 1000] actual value:<4> should be less than or equal to:<3>

Screen Shot 2022-07-29 at 2 40 21 PM

Also, CI passes for Mongo 4.0.

**Mysql**:

2022-07-29T19:17:19.3752206Z [ERROR] Failures: 
2022-07-29T19:17:19.3754804Z [ERROR]   IncrementalSnapshotIT.updates:230->AbstractIncrementalSnapshotTest.consumeRecordsMixedWithIncrementalSnapshot:234->AbstractIncrementalSnapshotTest.consumeMixedWithIncrementalSnapshot:176->AbstractIncrementalSnapshotTest.consumeMixedWithIncrementalSnapshot:194 [Too many no data record results, 1000 < 1000] actual value:<6> should be less than or equal to:<5>

Screen Shot 2022-07-29 at 3 23 38 PM

**Comment by vivekwassan** [comment]
@jpechane @Naros 👋 A few tests were sometimes passing/failing on local, so I did a bit of digging. Apparently there was a bug in the PR and I fixed it. Now CI is passing.
I also rebased it with `main` again. 
Could you review the PR?

**Comment by Naros** [comment]
Absolutely @vivekwassan, can you give it one last rebase? Thanks.

**Comment by vivekwassan** [comment]
> Absolutely @vivekwassan, can you give it one last rebase? Thanks.

@Naros Rebase done. Thanks!

**Comment by Naros** [comment]
So @gunnarmorling @jpechane, playing devil's advocate here, do we have any concern regarding SQL injection here?  

The data collections array gets sanitized against the list of `TableId` entries in the relational model, so there is some guard in place for that user-provided bit but in this case for these additional conditions, they're effectively direct pass-thru without any validation or sanitization.

I'm wondering whether something like JSQLParser or some equivalent would be ideal here to at least try and guard against malformed or otherwise malicious SQL bits that could be passed.  What's your thoughts?

**Comment by vivekwassan** [comment]
> So @gunnarmorling @jpechane, playing devil's advocate here, do we have any concern regarding SQL injection here?
> 
> The data collections array gets sanitized against the list of `TableId` entries in the relational model, so there is some guard in place for that user-provided bit but in this case for these additional conditions, they're effectively direct pass-thru without any validation or sanitization.
> 
> I'm wondering whether something like JSQLParser or some equivalent would be ideal here to at least try and guard against malformed or otherwise malicious SQL bits that could be passed. What's your thoughts?

Chipping in my 2 cents, before working on the PR, I referred to existing [snapshot.select.statement.overrides](https://debezium.io/documentation/reference/stable/connectors/mysql.html#mysql-property-snapshot-select-statement-overrides) configuration.

**Comment by vivekwassan** [comment]
> Yes, I don't think this is an issue. As was mentioned we already do it elswhere. Also CDC configuration requires big level of trust anyway. @vivekwassan Where do we stand with this PR now? I saw you did last commit 2 days ago? Can we consider the work complete?

@jpechane PR is complete from my end 🚢 . It was just a rebase from `main`.

**Comment by jpechane** [comment]
@vivekwassan Applied, thanks a lot for the great work!

**Comment by m8719-github** [comment]
Just came across this feature and this is very important for my org and is currently a blocker. We are currently on Maxwell CDC and would like to standardize on Debezium across the entire org but this is a major feature gap between Maxwell and Debezium.
Any chance of this being backported into v1?

**Pull request merged**
