### PR TITLE
DBZ-8023 check PDB field against both null and blank

### PR DESCRIPTION
**Pull request by andreas-ibm**
Fixes https://issues.redhat.com/browse/DBZ-8023

### CODE REVIEW

**Comment by andreas-ibm** [comment]
@Naros This is the fix I mentioned on Zulip

**Comment by andreas-ibm** [comment]
Those tests above seem to have failed due to:
```
13:16:31,405 [INFO] --- maven-enforcer-plugin:3.0.0-M2:enforce (enforce-java-version) @ debezium-build-parent ---
13:16:33,015 [WARNING] Rule 1: org.apache.maven.plugins.enforcer.RequireJavaVersion failed with message:
To build this project JDK 21 (or greater) is required. Please install it.
```
I'm claiming that's not my fault! ;-)

**Comment by andreas-ibm** [comment]
What would I need to do to backport to the 2.7 stream if I needed it?

**Comment by jpechane** [comment]
@andreas-ibm Thanks for the report, @obabec Is working on TF issue.

**Comment by jpechane** [comment]
@andreas-ibm WRT backport, I'll do it after the merge into main.

**Comment by Naros** [comment]
@jpechane since TF is still not operational, I tested the following scenarios:

* Complete LogMiner run with changes - :heavy_check_mark: 
* Streaming/Snapshot Data Type ITs for XStream - :heavy_check_mark: 
* Manually tested running LogMiner in non-CDB mode (Streaming/Snapshot Data Type ITs) - :heavy_check_mark: 
* Manually tested running XStream in non-CDB mode (Streaming/Snapshot Data Type ITs) - :heavy_check_mark: 

I believe that's a reasonable cursory check for these changes.

**Review by Naros — APPROVED** [review]

**Comment by jpechane** [comment]
@Naros I agree
@andreas-ibm Applied, thanks!

**Pull request merged**
