### PR TITLE
[DBZ-3375] SQL Server connector produces the same record during snapshot and streaming (reproducer)

### PR DESCRIPTION
**Pull request by morozov**
https://issues.redhat.com/browse/DBZ-3375

The following tests consistently pass on the `master` branch but they start inconsistently failing if more assertions are added:
1. `SQLServerConnectorIT#testTableExcludeList`
2. `SQLServerConnectorIT#testBlacklistTable`

Please see the reproduction details in the patch.

One of the newly added assertions [fails](https://github.com/debezium/debezium/pull/2280/checks?check_run_id=2257294874#step:4:16335) with the following error:
> SqlServerConnectorIT.testBlacklistTable:961 expected:<1[0]> but was:<1[]>
> SqlServerConnectorIT.testTableExcludeList:1005 expected:<1[0]> but was:<1[]>

The tests above should stream 5 rows of id's 10-14 but occasionally record with id 1 is seen twice: once in the snapshot record returned and again in the streaming records.

This issue is reproduced inconsistently likely to a race condition.

### CODE REVIEW

**Comment by gunnarmorling** [comment]
> they start inconsistently failing if more assertions are added:

LOL, reminds me of that joke, where someone goes to the doctor and says "If I touch here, it hurts", and the doctor replies "Then don't touch there" ;)

More seriously, we're going to take a look.

**Comment by morozov** [comment]
> they start inconsistently failing if more assertions are added:
> […]
> "Then don't touch there" ;)

Oh yeah, we tried to do some extreme sports and found out that it hurts just when we touch there.

**Comment by gunnarmorling** [comment]
@jpechane, could you please add a comment with your findings here? Thx!

**Comment by gunnarmorling** [comment]
@morozov, @jpechane, how should we continue with this one?

**Comment by morozov** [comment]
> @jpechane, could you please add a comment with your findings here? Thx!

I was hoping you guys could verify the issue on your end as you're better familiar with all the internals and the test suite. At this point, it's not clear whether it's a bug or a test suite issue.

If that doesn't work, we as SugarCRM will work on it as part of contributing the [DBZ-2975](https://issues.redhat.com/browse/DBZ-2975) changes back upstream (this is where it's a blocker).

**Comment by gunnarmorling** [comment]
Hey @morozov, please see the latest discussion on the linked issue. It's a general issue, not limited to test code only.

**Comment by morozov** [comment]
Thanks for the research, @gunnarmorling, @jpechane! As I shared with Jiri yesterday, I'm good with whatever decision you make (fix or not fix) as long as the issue doesn't have a practical impact (which doesn't seem to be the case so far). In my understanding, making the test suite resilient to the issue will stabilize the DDD-1 test suite as well. Until then, we'll keep the unstable tests disabled.

I'm closing the pull request since its sole purpose was to reproduce the issue.

**Pull request closed without merging**
