### PR TITLE
DBZ-4029 Heartbeat action queries for MySQL

### PR DESCRIPTION
**Pull request by gunnarmorling**
https://issues.redhat.com/browse/DBZ-4029

### CODE REVIEW

**Comment by gunnarmorling** [comment]
Supersedes https://github.com/debezium/debezium/pull/2763.

**Comment by gunnarmorling** [comment]
Hum, never seen that PG failure before. Don't get it locally either, so I think we should not spend time on it for now.

**Comment by gunnarmorling** [comment]
@jpechane, any thoughts?

**Comment by jpechane** [comment]
@abhishekkh @gunnarmorling Applied, thanks!

**Pull request merged**
