### PR TITLE
[DBZ-1193] Add support for cidr network address type in PostgreSQL connector.

### PR DESCRIPTION
**Pull request by ShubhamRwt**

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@ShubhamRwt Can you please squash the commits into one and prefix the commit message with the corresponding JIRA issue id? Thanks!

**Comment by ShubhamRwt** [comment]
@gunnarmorling squashed the commits into one and rebased it so its good to merge now.

**Comment by gunnarmorling** [comment]
Applied, thanks a lot, @ShubhamRwt! Note I've altered the commit message to reference the issue key. Could you also send a PR for the docs repo (updating [this file](https://github.com/debezium/debezium.github.io/blob/develop/docs/connectors/postgresql.asciidoc)) to add the newly supported column type? Thanks again!

**Comment by ShubhamRwt** [comment]
Yes sure @gunnarmorling, I will do that .

**Pull request merged**
