### PR TITLE
DBZ-3235 Do not fail parsing Oracle LogMiner SQL without a WHERE-clause

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-3235

### CODE REVIEW

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Comment by gunnarmorling** [comment]
Hum, is this desirable, though? I don't think this event would have a key, would it? What's the value of such event to a consumer then?

**Comment by jpechane** [comment]
@gunnarmorling Yes, it is desirable. You can then route such event into a dead-letter topic and act upon the arrival which you'd monitor and act upon the arrival.

**Comment by gunnarmorling** [comment]
How about we promote _all_ columns to the key for such event, as we do for PK-less tables, IIRC?

**Comment by jpechane** [comment]
@gunnarmorling Are you sure? IMHO this was proposed and rejected. Our docs says

> If the table does not have a primary or unique key, then the change event’s key is null. This makes sense since the rows in a table without a primary or unique key constraint cannot be uniquely identified.

**Comment by jpechane** [comment]
@gunnarmorling THere is always elephant in the room - schema registry and schema evolution rules...

**Pull request merged**
