### PR TITLE
DBZ-2592 Add script to list contributors of a release

### PR DESCRIPTION
**Pull request by ani-sha**
https://issues.redhat.com/browse/DBZ-2592

### CODE REVIEW

**Comment by ani-sha** [comment]
This might be a little noob approach, especially when multiple repos were a concern. :sweat_smile: 
Any suggestions @gunnarmorling?

**Comment by Naros** [comment]
Hi @ani-sha, I think the approach looks good but what I believe is still missing is taking the output you've gathered from the git history and converting that into markdown syntax.  I assume that's still a todo?

**Comment by ani-sha** [comment]
@Naros could you give an example of how the names should be aligned in the markdown file?

**Comment by gunnarmorling** [comment]
@Naros, I'm going to leave this to discuss and merge to you and @ani-sha, if that's ok? In the end just let me know how to run the thing for the next announcement post :)

**Comment by gunnarmorling** [comment]
@Naros, @ani-sha, any news here? Would love to use this script for the next announcement, if possible :)

**Comment by ani-sha** [comment]
@gunnarmorling, waiting for @Naros to have a quick look and confirm how the names would be laid in the MD file :)

**Comment by Naros** [comment]
My apologies @gunnarmorling and @ani-sha, I must have missed the GH notification for this one somehow.  The format you're wanting to try and mimic is the following:
```
https://github.com/<github-username>[Real name]
```
I would suggest depending on what you can resolve from the GH commit, you could use the username on the commit and resolve it against the rows in `jenkins-jobs/scripts/config/Aliases.txt`.  If you get a hit, then you should use the real name defined there.  If you get no hit, you could for now just use the account name as the real name.  It's at least a good starting point and we can then take that as an opportunity that if we have some that don't resolve, to update the Aliases file accordingly.

**Comment by ani-sha** [comment]
Hey, @Naros Thanks for the suggestion. If I am not wrong the commit-msg provides the `Author Name`/`Real Name` (and some users have their `username` as `author name`), I was actually struggling to get the username.

**Comment by Naros** [comment]
Yep, in that case I think `Aliases.txt` will come in handy for you :).

**Comment by ani-sha** [comment]
@gunnarmorling @Naros And it's done! :)  I used GitHub API for the same. 
For running the script you have to set three vars ie 

- `TAG1 (from which release)` eg `v1.5.0.Alpha1`
- `TAG2 (to which release)` eg `v1.5.0.Beta1`
- `AUTH_TOKEN (Presonal Access Token)`

**Comment by gunnarmorling** [comment]
Ah, this is really cool! A few suggestions:

* Auth token shouldn't be needed actually for this operation; I just could run the curl command without the header
* Let's make tag1 and tag2 parameters for the script instead of env vars, and validate their presence (i.e. abort if they are not both given)
* Can we then have a GH Actions workflow, which makes this invokeable from the GH Actions UI, requiring the two tags as input parameters (see [here|https://stackoverflow.com/questions/62736315/invoke-github-actions-workflow-manually-and-pass-parameters])

I'm also getting this error locally, I reckon it's due to some difference between Linux (which I suppose you're using) and macOS:

```
parse error: Invalid numeric literal at line 1, column 3
sort: No such file or directory
```

**Comment by ani-sha** [comment]
> parse error: Invalid numeric literal at line 1, column 3
sort: No such file or directory

@gunnarmorling If you reverse the tags that would throw this error, I am not sure why exactly.

**Comment by gunnarmorling** [comment]
@ani-sha, yeah, so in my case it was caused by the fact that `&>>` isn't supported by zsh apparently (default shell on macOS). Could you use the alternative syntax described [here|https://unix.stackexchange.com/questions/170572/what-is-in-a-shell-script] instead? Then it runs 🎉 .

**Comment by gunnarmorling** [comment]
That said, here's the output for v1.5.0.Beta1...v1.5.0.Beta2:

```
[Andrew Garrett],martper2
[Andrew Garrett],mengqiu
https://github.com/AndreyIg[Andrew Garrett],AndreyIg
https://github.com/AndreyIg[Andrey Ignatenko],
https://github.com/Naros[Andrew Garrett],Chris Cranford
https://github.com/Naros[Chris Cranford],
https://github.com/ani-sha[Andrew Garrett],Anisha Mohanty
https://github.com/ani-sha[Andrew Garrett],ani-sha
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/ant0nk[Andrew Garrett],Anton Kondratev
https://github.com/ant0nk[Anton Kondratev],
https://github.com/bingqinzhou[Andrew Garrett],Bingqin Zhou
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/ddseapy[Andrew Garrett],David Seapy
https://github.com/ddseapy[David Seapy],
https://github.com/debezium-builder[Andrew Garrett],Debezium Builder
https://github.com/denisprog[Andrew Garrett],DLiseichykau
https://github.com/denisprog[Victar Malinouski],
https://github.com/fuxiao224[Andrew Garrett],fuxiao224
https://github.com/fuxiao224[fuxiao224],
https://github.com/gunnarmorling[Andrew Garrett],Gunnar Morling
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/jpechane[Andrew Garrett],Jiri Pechanec
https://github.com/jpechane[Jiri Pechanec],
https://github.com/keweishang[Andrew Garrett],Kewei Shang
https://github.com/keweishang[Kewei Shang],
https://github.com/lga-zurich[Andrew Garrett],Luis Garcés-Erice
https://github.com/lga-zurich[Luis Garcés-Erice],
https://github.com/mpermar[Andrew Garrett],mpermar
https://github.com/mpermar[Martín Pérez],
https://github.com/roldanbob[Andrew Garrett],Bob Roldan
https://github.com/roldanbob[Andrew Garrett],roldanbob
https://github.com/roldanbob[Bob Roldan],
https://github.com/roldanbob[Robert Roldan],
https://github.com/vanhoale[Andrew Garrett],Hoa Le
https://github.com/vanhoale[Hoa Le],
https://github.com/vaosinbi[Andrew Garrett],Vladimir Osin
https://github.com/vaosinbi[Vladimir Osin],
https://github.com/zrlurb[Andrew Garrett],Peter Urbanetz
https://github.com/zrlurb[Peter Urbanetz],
```

A few observations:

* Duplications should be removed (e.g. via piping through `uniq`)
* Extra names (besides the actual links) should be removed
* Some names which need resolving against the alias file it seems: martper2, mengqiu
* Icing on the cake would be to remove the trailing comma and replace the last one with ", and"; I know, I'm greedy :-)

**Comment by gunnarmorling** [comment]
Btw. the parse error was caused by this:

* Something wrong with the API invocation (e.g. tags reversed, empty auth header as in my case, etc.)
* the jq in the loop will write an error message to the file
* the second jq cannot parse that, as it's not JSON

That's why it's a best practice to aboard a script early on in case of any error.

**Comment by ani-sha** [comment]
@gunnarmorling yes exactly, that's strange, I am looking into that. 
What are the results for `v1.5.0.Alpha1...v1.5.0.Beta1` ? Can you share it?

**Comment by gunnarmorling** [comment]
Yes, that's what I'm getting for Beta1:

```
https://github.com/Cyril-Engels[Yilong Chang],
https://github.com/Naros[Chris Cranford],
https://github.com/adhaamehab[Adham],
https://github.com/ahmedjami[ahmed],
https://github.com/ani-sha[Anisha Mohanty],
https://github.com/bingqinzhou[Bingqin Zhou],
https://github.com/fahimfarookme[Fahim Farook],
https://github.com/gunnarmorling[Gunnar Morling],
https://github.com/harveyyue[Harvey Yue],
https://github.com/jcechace[Jakub Cechacek],
https://github.com/jpechane[Jiri Pechanec],
https://github.com/keweishang[Kewei Shang],
https://github.com/kppullin[Kevin Pullin],
https://github.com/michaelcizmar[Michael Cizmar],
https://github.com/mrshanepaul[Shane Paul],
https://github.com/nitin1891[Nitin Agarwal],
https://github.com/nitin456[Nitin Agarwal],
https://github.com/r-ballard[unknown],
https://github.com/rgannu[Ganesh Ramasubramanian],
https://github.com/rk3rn3r[René Kerner],
https://github.com/roldanbob[Bob Roldan],
https://github.com/tprelle[Thomas Prelle],
https://github.com/twthorn[Thomas Thornton],
```

**Comment by ani-sha** [comment]
Wow, this worked fine, something messed up for Beta2 :astonished:, scripts need extra care :)

**Comment by gunnarmorling** [comment]
I suppose this is caused some missing alias entries, e.g. for "martper2".

@jpechane, e.g. we have this commit by Martín Pérez, but using a different author name than usual ("martper2"): https://github.com/debezium/debezium/commit/3727273d9e5fa167fe7e8a7e00570cffb6a2e531#diff-15cdf214087b7f2f5dfff4133cbd436157df20e599e6cfc24f4d62088c553e1b. How comes the script that checks for alias completeness didn't catch this (of course the commit should not have been merged to begin with, we don't want any "Octocat" commits, // CC @Naros)?

Also, ideally, this script here actually shouldn't yield that contribution for Beta2, as it it was done before. It's caused though by the recent Oracle connector merge, it seems the tag1...tag2 syntax brings in all the commits which got merged from the Oracle branch. Not a problem though, as it's a one-time issue, and we quickly can remove those additional names which actually didn't commit during the Beta2 frame manually.

**Comment by gunnarmorling** [comment]
@ani-sha, I've pushed a commit which adds the missing alias. With this one, the Beta2 output looks much better now.

**Comment by gunnarmorling** [comment]
@ani-sha, so the problem are the commits by mengqiu and martper2. They return null for the GitHub URL (that's what I'm referring to by "Octocat commits", these commits are done with an e-mail that's not linked to any GH account, thus no profile image is shown next to them in the history; as said, we shouldn't have those to begin with, but these slipped through). So the script needs to be tolerant to that, and in this case just show the name (resolved against the alias file still), but without link.

**Comment by Naros** [comment]
> How comes the script that checks for alias completeness didn't catch this (of course the commit should not have been merged to begin with, we don't want any "Octocat" commits,

I'll look into this @gunnarmorling, I'm surprised it didn't.

@ani-sha, here are my suggestions:

First, change the `jq` line where you find the name/github_url to the following:
```
jq -r 'if .github_url then (.github_url + " " + .name) else ("https://github.com/" + " " + .name) end' $CONTRIBUTORS_LIST_JSON > $CONTRIBUTORS_NAMES
```

What this does is if there is no `.github_url` for the user, it'll be written as:
```
https://github.com/ person's name
```

This should allow the formatting to work as desired and we'll simply need to look for these in the markdown output formatted as:
```
https://github.com/[Person's name]
```
and update these lines accordingly.

One last nit-pick, add `--silent` to the curl call to suppress the progress bar text so the only output should then be what comes from the sort/uniq at the very end.

**Comment by Naros** [comment]
@gunnarmorling I looked into the `martper2` alias issue, it seems we simply added `martper2` to the `COPYRIGHT.txt` directly and that is what allowed the `check-contributors` script to not inform us about the commit.  With adding the alias as you've done in this PR, what we should then do is add `Martín Pérez` to the `COPYRIGHT.txt`.  Could you do that @ani-sha in a follow-up commit in this PR once the script logic is complete?

**Comment by gunnarmorling** [comment]
Ah, great catch, Thx! "martper2" should then also be removed from
COPYRIGHT.txt.

>

**Comment by ani-sha** [comment]
@gunnarmorling Few minor things remaining to address. Will try to wrap it by tomorrow.

**Comment by gunnarmorling** [comment]
Sounds good. But no need to work overtime, Monday is fine :)

>

**Comment by gunnarmorling** [comment]
Ah, I noticed one more thing: for Beta1, there's one entry in the result list where the name is null (GH URL is present, though).

**Comment by ani-sha** [comment]
> Ah, I noticed one more thing: for Beta1, there's one entry in the result list where the name is null (GH URL is present, though).

@gunnarmorling Are you referring to the username `fuxiao224` ?

**Comment by gunnarmorling** [comment]
Applied, thanks a lot, @ani-sha. I've captured a list with a few small follow-up improvements at https://issues.redhat.com/browse/DBZ-2592.

**Pull request merged**
