### PR TITLE
DBZ-4467 Skip unsupported test for Db2

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-4467

### CODE REVIEW

**Comment by jpechane** [comment]
When built locally, the test is duly skipped.

**Comment by gunnarmorling** [comment]
@jpechane, embedded may have to be built as part of other repo builds too (i.e. the change I just pushed for Vitess)?

**Comment by ani-sha** [comment]
@jpechane Yes, I see the test is being skipped when running locally.

**Comment by gunnarmorling** [comment]
@jpechane, any idea bout the Postgres failure?

**Comment by jpechane** [comment]
@gunnarmorling - https://issues.redhat.com/browse/DBZ-2923 maybe time was not enough in this instance

**Comment by jpechane** [comment]
@gunnarmorling Hopld-on, it is a different problem, pleas ewait for a fix

**Comment by gunnarmorling** [comment]
@jpechane, could you rebase this one, so we clearly see which problems remain?

**Comment by jpechane** [comment]
@gunnarmorling So only the build issue remains.

**Comment by gunnarmorling** [comment]
Ok, so I have pushed one commit for adjusting the Db2 job definition to actually build _all_ components from _debezium/debezium_ before building the db2 repository. Not sure whether this helps with this issue at hand, but it's something which should be done anyways.

@ani-sha, can you apply the same change for the other cross-repo workflows, and also the corresponding workflows in the downstream repos? As a guideline, each downstream repo should be buildable in offline mode (mvn ... -o) after the main repo has been built. That's how I tested the change to this workflow definition. I.e. all the main repo components should be installed into the local Maven repo of the build environment before executing that particular downstream repo build. We cannot actually build in offline mode though (as nice as it would be for validation), as the job may need to fetch new driver versions and other external dependencies.

**Comment by gunnarmorling** [comment]
@jpechane, ok, so the Db2 skip seems to work now? But the SQL Server failure is new? Can you log it in Jira?

**Comment by ani-sha** [comment]
@gunnarmorling sure, I can have them added in the #3058 PR. Would be great if we can get this one merged, @jpechane can you merge it?

**Comment by ani-sha** [comment]
Logged https://issues.redhat.com/browse/DBZ-4475 for SQL Server failure.

**Pull request merged**
