### PR TITLE
DBZ-1083 Use include-unchanged-toast only optionally

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.jboss.org/browse/DBZ-1083

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@jpechane, LGTM overall, but can you check out the test failure on Travis? Is it related? One other thought: how about _not_ having an option but trying to establish the connection twice: first with the option set, and if that fails due to a recognizeable exception, try again without it? That way we'd avoid this rather technical and not very meaningful connector option.

**Comment by jpechane** [comment]
@gunnarmorling As usual, it works locally so it'll take some time to investigate :-(. Reagrding double connection - I'd agree if we would be able to detect why the connection failed - but I am not a fan blind retry as one never now what potential side effect it can bring. Maybe we should put the option to `internal` namespace?

**Comment by gunnarmorling** [comment]
I don't think "internal" helps that much, we still want a good OOTB
experience in all environments.

> potential side effect it can bring

wal2json fails early on upon the unsupported option, so I think it's safe
to do.

>

**Comment by jpechane** [comment]
Here is the problem - I tested it with https://github.com/debezium/docker-images/pull/113

**Comment by gunnarmorling** [comment]
> Here is the problem

Can you elaborate? Which problem DYM?

**Pull request merged**
