### PR TITLE
DBZ-5170 Mysql Commit Timestamp

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-5170
I will update to all connectors doc later.

### CODE REVIEW

**Comment by jingtaozhang18** [comment]
Hi @harveyyue. Here is some information I found in binlog that maybe help you. The timestamps in Xid events have difference between auto-commit is enabled and disabled. Here is an example. If I execute SQLs as shown below.

ex7_1

Then binlog file is as show below.

ex7_2

So , the timestamps of transaction's Xid events maybe not ordered.

**Comment by jingtaozhang18** [comment]
Hi @harveyyue, the example you showed above is exactly what I was trying to say. And I think the timestamp of session 2 can't relfect the tranasaction commit time. The transaction commit time I understand is when the change of the transaction can be seen. Do you have any good idea to solve this problem?

**Comment by harveyyue** [comment]
> Hi @harveyyue, the example you showed above is exactly what I was trying to say. And I think the timestamp of session 2 can't relfect the tranasaction commit time. The transaction commit time I understand is when the change of the transaction can be seen. Do you have any good idea to solve this problem?

Regarding the binlog event data which I have posted, the session2 transaction commit time is 1654101009000, the session1 is 1654101018000, I think we just to consume the binlog data without any data changes.

**Comment by jpechane** [comment]
@harveyyue @jingtaozhang18 Hi guys, when do we stand on this PR then? Does it provide the expected data albeit they might be a bit difficult to correctl interpret?

**Comment by jpechane** [comment]
@harveyyue Applied, thanks a lot!

**Pull request merged**
