### PR TITLE
DBZ-5648 Move LogMiner RegEx handling into Java

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-5648

### CODE REVIEW

**Comment by Naros** [comment]
Currently running the tests against the internal Jenkins CI across all database versions/configs.  I've also asked the user to give this PR a test drive to see whether it yields any better performance.

**Comment by Naros** [comment]
There were two errors on the internal CI:
* `shouldIgnoreAllTablesInExcludedSchemas` - this is just a timing issue, CI didn't perform 10 iterations in 3 minutes likely due to being overloaded on PSI with multiple Oracle test matrix executions
* `shouldSnapshotAndStreamAllRecordsThatSpanAcrossSnapshotStreamingBoundaryLargeTrxs` - this is a known issue and one that I should have a fix for in another Jira related to Oracle RAC before the Final.

Looking at the test suite, I didn't notice any major change in execution time with our setup, so it would be interesting if we could hear back from Ronaldo on whether this helps with their performance or not.  @rlanhellas, can you give this a test drive?

**Comment by rlanhellas** [comment]
Hi @Naros , sure I will download your branch make some tests with our data and give you some feedback.

**Comment by Naros** [comment]
Hi @rlanhellas any update?

**Comment by Naros** [comment]
Hi @jpechane let's proceed with merging this into 2.1.0.Alpha1 and looking to backport this to 2.0 in the future weeks?

**Comment by rlanhellas** [comment]
> Hi @rlanhellas any update?

Sorry for the delay in answering you, but this month was crazy here and I didn't have time to validate this. I will do it by the end of this week and return here with the results.

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Comment by jpechane** [comment]
@Naros Applied, could you please prepare 1.9/2.0 PR(s) that would be merged later? This PR does not apply cleanly and also we want to have this tested a bit. Thanks

**Pull request merged**
