### PR TITLE
DBZ-3482 Use date format model that does not depend on client NLS settings in integration tests

### PR DESCRIPTION
**Pull request by TAregger**
See https://issues.redhat.com/browse/DBZ-3482

I intentionally did not change date literals in tests that don't do any inserts on the database (e.g. OracleDmlParserTest and LogMinerDmlParserTest)

### CODE REVIEW

**Comment by gunnarmorling** [comment]
@Naros, you wanna take this one?

**Comment by gunnarmorling** [comment]
Thx, @TAregger! This LGTM, leaving it to @Naros to take another look and merge.

**Comment by Naros** [comment]
Hi @TAregger, I would assume then that the format `TIMESTAMP_AM_PM_SHORT_FORMATTER` in the value converter works without any issues then?  We had to add these given how values are deserialized from the LogMiner SQL strings and I just want to be sure there isn't any issue there with the use of `MMM`.

**Comment by Naros** [comment]
I don't recall specifically off the top of my head.  I'll check the test-suite and report back later today.

**Comment by TAregger** [comment]
Hi @Naros 

I just had test failures in `OracleDmlParserTest` that are related to `TIMESTAMP_AM_PM_SHORT_FORMATTER`.

They can be easily reproduced by running the tests with a different language settings than `en`:
```
export MAVEN_OPTS="-Duser.language=de"
mvn test -Dtest=OracleDmlParserTest#shouldParseTimestampFormats -DforkCount=0
```

```
...
Caused by: java.time.format.DateTimeParseException: Text '22-SEP-20 12.09.37 AM' could not be parsed at index 3
	at java.base/java.time.format.DateTimeFormatter.parseResolved0(DateTimeFormatter.java:2046)
...
```

Strangely I did not get these failures before.

Nevertheless I think the fix should be straightforward, see diff below. Please let me know whether I should add these changes to this PR or I should create a new issue and send a separate PR.

```
diff --git a/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java b/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
index 7ca4e3ce7..8eb6c053e 100644
--- a/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
+++ b/debezium-connector-oracle/src/main/java/io/debezium/connector/oracle/OracleValueConverters.java
@@ -20,6 +20,7 @@
 import java.time.format.DateTimeFormatter;
 import java.time.format.DateTimeFormatterBuilder;
 import java.time.temporal.ChronoField;
+import java.util.Locale;
 import java.util.regex.Matcher;
 import java.util.regex.Pattern;

@@ -76,7 +77,7 @@
             .appendFraction(ChronoField.NANO_OF_SECOND, 0, 9, false)
             .optionalEnd()
             .appendPattern(" a")
-            .toFormatter();
+            .toFormatter(Locale.ENGLISH);

     private static final DateTimeFormatter TIMESTAMP_TZ_FORMATTER = new DateTimeFormatterBuilder()
             .parseCaseInsensitive()
```

**Comment by Naros** [comment]
@TAregger, its fine to add that change to this PR.  It makes sense we do all the work at once needed for this if possible.

**Comment by TAregger** [comment]
@Naros, thanks. I added the changes to this PR.

**Review by gunnarmorling — APPROVED** [review]
Thanks a lot, @TAregger. This LGTM. @Naros, can you double-check and merge if you think it's fine, too? Thx!

**Review by Naros — APPROVED** [review]
Ran the tests with a few other locales and they passed, LGTM.

**Pull request merged**
