### PR TITLE
Issue [DBZ-1039] Ensure no brace-less if() blocks are used in the code base.

### PR DESCRIPTION
**Pull request by ShubhamRwt**

### CODE REVIEW

**Comment by jpechane** [comment]
@ShubhamRwt Looking at the code there is missing space between right parenthesis and left curly brace in `if` statement.

**Comment by ShubhamRwt** [comment]
Ok I will resolve it .

**Comment by renatomefi** [comment]
Hello, thanks for the work! I want to leave some thoughts here!
this might cause a lot of conflicts with the WIP PRs, to try to reduce it I'd suggest to squash this into one commit (so rebase is easier) and maybe wait until the big PRs are merged.
@ShubhamRwt @jpechane What do you think?

**Comment by gunnarmorling** [comment]
Yes, good point about conflicts. I just merged https://github.com/debezium/debezium/pull/796, and this one here definitely needs a rebase. Then we should get it in quickly, so to avoid further conflicts piling up. Do you think of any specific PR, @renatomefi? The outbox one should be fine as it's mostly new sources, I think.

**Comment by gunnarmorling** [comment]
@ShubhamRwt, so could you rebase it place and squash into one commit, as suggested by @renatomefi?

**Comment by renatomefi** [comment]
> The outbox one should be fine as it's mostly new sources, I think.

Sure I think so too!

About the future of these changes, is there anything enforcing this style?

**Comment by gunnarmorling** [comment]
>  is there anything enforcing this style?

I have to admit, I didn't check out the PR in detail yet; I was hoping there'd be a Checkstyle config to ensure it (this was the original idea of the issue).

**Comment by ShubhamRwt** [comment]
Hello @gunnarmorling and @renatomefi . I have rebased this plus i have added the space between the parenthesis and the left curly brace as @jpechane said. I am sending another pull request regarding the same as this branch is having merge conflicts . So I will be closing this pull request and send a new one in a couple of minutes.

**Comment by gunnarmorling** [comment]
Closing this one, as it's superseded by #818. Thanks, @ShubhamRwt!

**Pull request closed without merging**
