### PR TITLE
DBZ-6002 Run PostgresConnectorIT.shouldReceiveChangesForChangeColumnDefault() failed

### PR DESCRIPTION
**Pull request by harveyyue**
https://issues.redhat.com/browse/DBZ-6002

### CODE REVIEW

**Comment by harveyyue** [comment]
I deleted the the branch DBZ-6002 by mistake, so had to create back and re-submit this pr, sorry for the inconvenience.
https://github.com/debezium/debezium/pull/4190

**Comment by harveyyue** [comment]
@jpechane @Naros  Guys, could you please take a look this pr, it will help to fix Postgres IT failed issue.

**Comment by jpechane** [comment]
@harveyyue I pushed a commit fixing the MySQL failure - it is a small compatibility break that will be documented in release notes.

**Comment by jpechane** [comment]
@harveyyue Applied, thanks

**Pull request merged**
