### PR TITLE
DBZ-8362 Use quay.io images

### PR DESCRIPTION
**Pull request by Naros**
https://issues.redhat.com/browse/DBZ-8362

Sibling PR - https://github.com/debezium/debezium-connector-spanner/pull/98

### CODE REVIEW

**Comment by Naros** [comment]
@jpechane the maven build error for checkstyle seems superfluous, it doesn't happen locally and I honestly have no idea why this happens on CI.

**Comment by rk3rn3r** [comment]
@Naros `Plugin net.revelc.code.formatter:formatter-maven-plugin:2.20.0 or one of its dependencies could not be resolved:` Could it be an issue with the dependency cache which was missing the plugin or a connection problem downloading that plugin?

**Comment by Naros** [comment]
Thanks @rk3rn3r and @jpechane, appreciate the help.

**Comment by jpechane** [comment]
@Naros Applied, thanks!

**Pull request merged**
