### PR TITLE
DBZ-3833 Updated mysql-connector-java dependency to 8.0.26

### PR DESCRIPTION
**Pull request by sirscratchalot**
[Link to issue](https://issues.redhat.com/browse/DBZ-3833)

Work on upgrading to the latest version of mysql-connector-java.

### CODE REVIEW

**Comment by sirscratchalot** [comment]
Please hold of on review, I am doing an initial run through the debezium CD integrations and draft PRs do not trigger the pipelines.

**Comment by sirscratchalot** [comment]
There seems to be a date regression linked to updating the connector to 8.0.26, I'm placing this as ready for review to allow someone with more experience to have a look. 

For the tests: 
```
[ERROR]   MySqlConnectorRegressionIT.shouldConsumeAllEventsFromDatabaseUsingSnapshot:618->lambda$shouldConsumeAllEventsFromDatabaseUsingSnapshot$2:697 expected:<[9]> but was:<[8]>
[ERROR]   MySqlConnectorRegressionIT.shouldConsumeDatesCorrectlyWhenClientTimezonePrecedesServerTimezoneUsingSnapshot:872->lambda$shouldConsumeDatesCorrectlyWhenClientTimezonePrecedesServerTimezoneUsingSnapshot$3:916->assertTimestamp:1057 expected:<1[6]> but was:<1[7]>
```
The two assertion statements are off by one errors for getHours and getDayOfMonth respectively:
` assertThat(c4DateTime.getHour()).isEqualTo(expectedTimestamp.getHour());`
` assertThat(c4DateTime.getDayOfMonth()).isEqualTo(9);`

**Comment by jpechane** [comment]
I'll take a look

**Comment by jpechane** [comment]
@gunnarmorling Please review the PR

**Comment by gunnarmorling** [comment]
@jpechane, pushed one more commit for making sure the new prop takes precedence if both old and new are given. Can you take another look and merge? Thx!

**Comment by jpechane** [comment]
@gunnarmorling Thanks!

**Pull request merged**
