### PR TITLE
DBZ-3621 JDBC storage

### PR DESCRIPTION
**Pull request by jpechane**
https://issues.redhat.com/browse/DBZ-3621

- DBZ-3621 adding JdbcDatabaseHistory, JdbcOffsetBackingStore implementations
- DBZ-3621 adding JdbcDatabaseHistory, JdbcOffsetBackingStore implementations
- DBZ-3621 Updated maven to include profiles, offset table is now configurable.
- DBZ-3621 Fixed JdbcOffsetBackingStoreTest and fixed warnings
- DBZ-3621 Added integration test for JDBC offset storage.
- DBZ-3621 Added integration test for JDBC offset storage.
- DBZ-3621 Added README.md
- DBZ-3621 Add database history integration test

### CODE REVIEW

**Comment by jpechane** [comment]
@subkanthi @ismailsimsek I added a new test for the schema history `io.debezium.storage.jdbc.history.JdbcSchemaHistoryIT`.
It seems there is a bug that misses the last record in history after restart, please see `shouldStreamChangesAfterRestart()`

**Comment by subkanthi** [comment]
> @subkanthi @ismailsimsek I added a new test for the schema history `io.debezium.storage.jdbc.history.JdbcSchemaHistoryIT`. It seems there is a bug that misses the last record in history after restart, please see `shouldStreamChangesAfterRestart()`

Will investigate bug in the other branch. Thanks

**Comment by subkanthi** [comment]
Looks like the actual problem is with stopping and starting the connector. Trying to fix it.
Screenshot from 2023-02-24 12-20-32

**Comment by subkanthi** [comment]
> @subkanthi @ismailsimsek I added a new test for the schema history `io.debezium.storage.jdbc.history.JdbcSchemaHistoryIT`. It seems there is a bug that misses the last record in history after restart, please see `shouldStreamChangesAfterRestart()`

@jpechane found the bug, I don't have write access to your fork, I removed the logic of comparing the previous history Id, I think that was added to make sure it does not include duplicates.
```
    @Override
    protected synchronized void recoverRecords(Consumer<HistoryRecord> records) {
        lock.write(() -> {
            try {
                if (exists()) {
                    Statement stmt = conn.createStatement();
                    ResultSet rs = stmt.executeQuery(DATABASE_HISTORY_TABLE_SELECT);

                    while (rs.next()) {
                        String historyData = rs.getString("history_data");
                        if (historyData.isEmpty() == false) {
                            records.accept(new HistoryRecord(reader.read(historyData)));
                        }
                    }
                }
            }
            catch (IOException | SQLException e) {
                throw new SchemaHistoryException("Failed to recover records", e);
            }
        });
    }
```

**Comment by jpechane** [comment]
@subkanthi Thanks a lot. I am afraid this gets a bit messy right now.
I propose to close both

* https://github.com/debezium/debezium/pull/4212
* https://github.com/debezium/debezium/pull/4312

You'll create a new PR based of the lastest main and cherry-pick all the relevant commits to get back to  a manageable state.

Would it be feasible for you?

**Comment by subkanthi** [comment]
> @subkanthi Thanks a lot. I am afraid this gets a bit messy right now.
> I propose to close both
> 
> * https://github.com/debezium/debezium/pull/4212
> * https://github.com/debezium/debezium/pull/4312
> 
> You'll create a new PR based of the lastest main and cherry-pick all the relevant commits to get back to  a manageable state.
> 
> Would it be feasible for you?

Thanks @jpechane , sure will do that.

**Comment by jpechane** [comment]
Closing as a new PR with cherry-picked commits was agreed on.

**Pull request closed without merging**
